#if 0
* abbr0s.c
* abbreviations for {-F[2, {1}], F[2, {1}]} -> {-F[3, {3, Col3}], F[3, {3, Col4}]}
* generated by FormCalc 8.2 on 11-Apr-2013 11:35
#endif

#include "vars.h"
#include "inline.h"


void abbr0s() {

#include "vars.h"

#include "inline.h"

  MatSUN(1,1) = 3;

}
