#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.1 on 6-Apr-2013 23:49
#endif
#undef Sub2276 
#define Sub2276 CtoV2(var1s.C[0])
#undef Sub1358 
#define Sub1358 CtoV2(var1s.C[1])
#undef Sub4020 
#define Sub4020 CtoV2(var1s.C[2])
#undef Sub2247 
#define Sub2247 CtoV2(var1s.C[3])
#undef Sub847 
#define Sub847 CtoV2(var1s.C[4])
#undef Sub4082 
#define Sub4082 CtoV2(var1s.C[5])
#undef Sub2616 
#define Sub2616 CtoV2(var1s.C[6])
#undef Sub1255 
#define Sub1255 CtoV2(var1s.C[7])
#undef Sub2249 
#define Sub2249 CtoV2(var1s.C[8])
#undef Sub978 
#define Sub978 CtoV2(var1s.C[9])
#undef Sub13032 
#define Sub13032 CtoV2(var1s.C[10])
#undef Sub12577 
#define Sub12577 CtoV2(var1s.C[11])
#undef Sub4056 
#define Sub4056 CtoV2(var1s.C[12])
#undef Sub4058 
#define Sub4058 CtoV2(var1s.C[13])
#undef Sub4063 
#define Sub4063 CtoV2(var1s.C[14])
#undef Sub4062 
#define Sub4062 CtoV2(var1s.C[15])
#undef Sub4065 
#define Sub4065 CtoV2(var1s.C[16])
#undef Sub1138 
#define Sub1138 CtoV2(var1s.C[17])
#undef Sub4035 
#define Sub4035 CtoV2(var1s.C[18])
#undef Sub848 
#define Sub848 CtoV2(var1s.C[19])
#undef Sub918 
#define Sub918 CtoV2(var1s.C[20])
#undef Sub90 
#define Sub90 CtoV2(var1s.C[21])
#undef Sub121 
#define Sub121 CtoV2(var1s.C[22])
#undef Sub77 
#define Sub77 CtoV2(var1s.C[23])
#undef Sub82 
#define Sub82 CtoV2(var1s.C[24])
#undef Sub85 
#define Sub85 CtoV2(var1s.C[25])
#undef Sub131 
#define Sub131 CtoV2(var1s.C[26])
#undef Sub879 
#define Sub879 CtoV2(var1s.C[27])
#undef Sub3972 
#define Sub3972 CtoV2(var1s.C[28])
#undef Sub3986 
#define Sub3986 CtoV2(var1s.C[29])
#undef Sub853 
#define Sub853 CtoV2(var1s.C[30])
#undef Sub804 
#define Sub804 CtoV2(var1s.C[31])
#undef Sub803 
#define Sub803 CtoV2(var1s.C[32])
#undef Sub1360 
#define Sub1360 CtoV2(var1s.C[33])
#undef Sub3938 
#define Sub3938 CtoV2(var1s.C[34])
#undef Sub6592 
#define Sub6592 CtoV2(var1s.C[35])
#undef Sub3982 
#define Sub3982 CtoV2(var1s.C[36])
#undef Sub4529 
#define Sub4529 CtoV2(var1s.C[37])
#undef Sub779 
#define Sub779 CtoV2(var1s.C[38])
#undef Sub1486 
#define Sub1486 CtoV2(var1s.C[39])
#undef Sub668 
#define Sub668 CtoV2(var1s.C[40])
#undef Sub778 
#define Sub778 CtoV2(var1s.C[41])
#undef Sub10883 
#define Sub10883 CtoV2(var1s.C[42])
#undef Sub9737 
#define Sub9737 CtoV2(var1s.C[43])
#undef Sub3983 
#define Sub3983 CtoV2(var1s.C[44])
#undef Sub3949 
#define Sub3949 CtoV2(var1s.C[45])
#undef Sub813 
#define Sub813 CtoV2(var1s.C[46])
#undef Sub4000 
#define Sub4000 CtoV2(var1s.C[47])
#undef Sub4001 
#define Sub4001 CtoV2(var1s.C[48])
#undef Sub4011 
#define Sub4011 CtoV2(var1s.C[49])
#undef Sub4013 
#define Sub4013 CtoV2(var1s.C[50])
#undef Sub814 
#define Sub814 CtoV2(var1s.C[51])
#undef Sub4014 
#define Sub4014 CtoV2(var1s.C[52])
#undef Sub904 
#define Sub904 CtoV2(var1s.C[53])
#undef Sub882 
#define Sub882 CtoV2(var1s.C[54])
#undef Sub3996 
#define Sub3996 CtoV2(var1s.C[55])
#undef Sub3981 
#define Sub3981 CtoV2(var1s.C[56])
#undef Sub866 
#define Sub866 CtoV2(var1s.C[57])
#undef Sub867 
#define Sub867 CtoV2(var1s.C[58])
#undef Sub902 
#define Sub902 CtoV2(var1s.C[59])
#undef Sub903 
#define Sub903 CtoV2(var1s.C[60])
#undef Sub3988 
#define Sub3988 CtoV2(var1s.C[61])
#undef Sub4018 
#define Sub4018 CtoV2(var1s.C[62])
#undef Sub905 
#define Sub905 CtoV2(var1s.C[63])
#undef Sub3905 
#define Sub3905 CtoV2(var1s.C[64])
#undef Sub894 
#define Sub894 CtoV2(var1s.C[65])
#undef Sub812 
#define Sub812 CtoV2(var1s.C[66])
#undef Sub4016 
#define Sub4016 CtoV2(var1s.C[67])
#undef Sub3948 
#define Sub3948 CtoV2(var1s.C[68])
#undef Sub3947 
#define Sub3947 CtoV2(var1s.C[69])
#undef Sub3915 
#define Sub3915 CtoV2(var1s.C[70])
#undef Sub3916 
#define Sub3916 CtoV2(var1s.C[71])
#undef Sub4030 
#define Sub4030 CtoV2(var1s.C[72])
#undef Sub886 
#define Sub886 CtoV2(var1s.C[73])
#undef Sub3920 
#define Sub3920 CtoV2(var1s.C[74])
#undef Sub887 
#define Sub887 CtoV2(var1s.C[75])
#undef Sub3918 
#define Sub3918 CtoV2(var1s.C[76])
#undef Sub3922 
#define Sub3922 CtoV2(var1s.C[77])
#undef Sub3923 
#define Sub3923 CtoV2(var1s.C[78])
#undef Sub880 
#define Sub880 CtoV2(var1s.C[79])
#undef Sub831 
#define Sub831 CtoV2(var1s.C[80])
#undef Sub3911 
#define Sub3911 CtoV2(var1s.C[81])
#undef Sub3912 
#define Sub3912 CtoV2(var1s.C[82])
#undef Sub4028 
#define Sub4028 CtoV2(var1s.C[83])
#undef Sub3914 
#define Sub3914 CtoV2(var1s.C[84])
#undef Sub3919 
#define Sub3919 CtoV2(var1s.C[85])
#undef Sub3917 
#define Sub3917 CtoV2(var1s.C[86])
#undef Sub806 
#define Sub806 CtoV2(var1s.C[87])
#undef Sub3941 
#define Sub3941 CtoV2(var1s.C[88])
#undef Sub3942 
#define Sub3942 CtoV2(var1s.C[89])
#undef Sub3943 
#define Sub3943 CtoV2(var1s.C[90])
#undef Sub4034 
#define Sub4034 CtoV2(var1s.C[91])
#undef Sub3953 
#define Sub3953 CtoV2(var1s.C[92])
#undef Sub3952 
#define Sub3952 CtoV2(var1s.C[93])
#undef Sub4042 
#define Sub4042 CtoV2(var1s.C[94])
#undef Sub3956 
#define Sub3956 CtoV2(var1s.C[95])
#undef Sub3990 
#define Sub3990 CtoV2(var1s.C[96])
#undef Sub4021 
#define Sub4021 CtoV2(var1s.C[97])
#undef Sub769 
#define Sub769 CtoV2(var1s.C[98])
#undef Sub126 
#define Sub126 CtoV2(var1s.C[99])
#undef Sub99 
#define Sub99 CtoV2(var1s.C[100])
#undef Sub917 
#define Sub917 CtoV2(var1s.C[101])
#undef Sub4054 
#define Sub4054 CtoV2(var1s.C[102])
#undef Sub4088 
#define Sub4088 CtoV2(var1s.C[103])
#undef Sub802 
#define Sub802 CtoV2(var1s.C[104])
#undef Sub3930 
#define Sub3930 CtoV2(var1s.C[105])
#undef Sub834 
#define Sub834 CtoV2(var1s.C[106])
#undef Sub4010 
#define Sub4010 CtoV2(var1s.C[107])
#undef Sub895 
#define Sub895 CtoV2(var1s.C[108])
#undef Sub884 
#define Sub884 CtoV2(var1s.C[109])
#undef Sub4051 
#define Sub4051 CtoV2(var1s.C[110])
#undef Sub39 
#define Sub39 CtoV2(var1s.C[111])
#undef Sub4087 
#define Sub4087 CtoV2(var1s.C[112])
#undef Sub4069 
#define Sub4069 CtoV2(var1s.C[113])
#undef Sub4086 
#define Sub4086 CtoV2(var1s.C[114])
#undef Sub4072 
#define Sub4072 CtoV2(var1s.C[115])
#undef Sub4071 
#define Sub4071 CtoV2(var1s.C[116])
#undef Sub4067 
#define Sub4067 CtoV2(var1s.C[117])
#undef Sub4068 
#define Sub4068 CtoV2(var1s.C[118])
#undef Sub4070 
#define Sub4070 CtoV2(var1s.C[119])
#undef Sub912 
#define Sub912 CtoV2(var1s.C[120])
#undef Sub4074 
#define Sub4074 CtoV2(var1s.C[121])
#undef Sub4073 
#define Sub4073 CtoV2(var1s.C[122])
#undef Sub75 
#define Sub75 CtoV2(var1s.C[123])
#undef Sub88 
#define Sub88 CtoV2(var1s.C[124])
#undef Sub3924 
#define Sub3924 CtoV2(var1s.C[125])
#undef Sub51 
#define Sub51 CtoV2(var1s.C[126])
#undef Sub3935 
#define Sub3935 CtoV2(var1s.C[127])
#undef Sub4031 
#define Sub4031 CtoV2(var1s.C[128])
#undef Sub3932 
#define Sub3932 CtoV2(var1s.C[129])
#undef Sub3962 
#define Sub3962 CtoV2(var1s.C[130])
#undef Sub3967 
#define Sub3967 CtoV2(var1s.C[131])
#undef Sub3951 
#define Sub3951 CtoV2(var1s.C[132])
#undef Sub3964 
#define Sub3964 CtoV2(var1s.C[133])
#undef Sub4036 
#define Sub4036 CtoV2(var1s.C[134])
#undef Sub4043 
#define Sub4043 CtoV2(var1s.C[135])
#undef Sub159 
#define Sub159 CtoV2(var1s.C[136])
#undef Sub7126 
#define Sub7126 CtoV2(var1s.C[137])
#undef Sub720 
#define Sub720 CtoV2(var1s.C[138])
#undef Sub3921 
#define Sub3921 CtoV2(var1s.C[139])
#undef Sub1334 
#define Sub1334 CtoV2(var1s.C[140])
#undef Sub229 
#define Sub229 CtoV2(var1s.C[141])
#undef Sub9469 
#define Sub9469 CtoV2(var1s.C[142])
#undef Sub1605 
#define Sub1605 CtoV2(var1s.C[143])
#undef Sub173 
#define Sub173 CtoV2(var1s.C[144])
#undef Sub865 
#define Sub865 CtoV2(var1s.C[145])
#undef Sub3980 
#define Sub3980 CtoV2(var1s.C[146])
#undef Sub856 
#define Sub856 CtoV2(var1s.C[147])
#undef Sub3997 
#define Sub3997 CtoV2(var1s.C[148])
#undef Sub4017 
#define Sub4017 CtoV2(var1s.C[149])
#undef Sub3991 
#define Sub3991 CtoV2(var1s.C[150])
#undef Sub3992 
#define Sub3992 CtoV2(var1s.C[151])
#undef Sub3937 
#define Sub3937 CtoV2(var1s.C[152])
#undef Sub4037 
#define Sub4037 CtoV2(var1s.C[153])
#undef Sub4005 
#define Sub4005 CtoV2(var1s.C[154])
#undef Sub4002 
#define Sub4002 CtoV2(var1s.C[155])
#undef Sub861 
#define Sub861 CtoV2(var1s.C[156])
#undef Sub3976 
#define Sub3976 CtoV2(var1s.C[157])
#undef Sub4004 
#define Sub4004 CtoV2(var1s.C[158])
#undef Sub4003 
#define Sub4003 CtoV2(var1s.C[159])
#undef Sub3994 
#define Sub3994 CtoV2(var1s.C[160])
#undef Sub3995 
#define Sub3995 CtoV2(var1s.C[161])
#undef Sub3979 
#define Sub3979 CtoV2(var1s.C[162])
#undef Sub113 
#define Sub113 CtoV2(var1s.C[163])
#undef Sub105 
#define Sub105 CtoV2(var1s.C[164])
#undef Sub4038 
#define Sub4038 CtoV2(var1s.C[165])
#undef Sub112 
#define Sub112 CtoV2(var1s.C[166])
#undef Sub3998 
#define Sub3998 CtoV2(var1s.C[167])
#undef Sub107 
#define Sub107 CtoV2(var1s.C[168])
#undef Sub128 
#define Sub128 CtoV2(var1s.C[169])
#undef Sub66 
#define Sub66 CtoV2(var1s.C[170])
#undef Sub3987 
#define Sub3987 CtoV2(var1s.C[171])
#undef Sub3985 
#define Sub3985 CtoV2(var1s.C[172])
#undef Sub901 
#define Sub901 CtoV2(var1s.C[173])
#undef Sub4019 
#define Sub4019 CtoV2(var1s.C[174])
#undef Sub3978 
#define Sub3978 CtoV2(var1s.C[175])
#undef Sub910 
#define Sub910 CtoV2(var1s.C[176])
#undef Sub844 
#define Sub844 CtoV2(var1s.C[177])
#undef Sub3927 
#define Sub3927 CtoV2(var1s.C[178])
#undef Sub4033 
#define Sub4033 CtoV2(var1s.C[179])
#undef Sub835 
#define Sub835 CtoV2(var1s.C[180])
#undef Sub3950 
#define Sub3950 CtoV2(var1s.C[181])
#undef Sub843 
#define Sub843 CtoV2(var1s.C[182])
#undef Sub4040 
#define Sub4040 CtoV2(var1s.C[183])
#undef Sub3965 
#define Sub3965 CtoV2(var1s.C[184])
#undef Sub871 
#define Sub871 CtoV2(var1s.C[185])
#undef Sub850 
#define Sub850 CtoV2(var1s.C[186])
#undef Sub883 
#define Sub883 CtoV2(var1s.C[187])
#undef Sub3929 
#define Sub3929 CtoV2(var1s.C[188])
#undef Sub3934 
#define Sub3934 CtoV2(var1s.C[189])
#undef Sub4032 
#define Sub4032 CtoV2(var1s.C[190])
#undef Sub3933 
#define Sub3933 CtoV2(var1s.C[191])
#undef Sub3939 
#define Sub3939 CtoV2(var1s.C[192])
#undef Sub65 
#define Sub65 CtoV2(var1s.C[193])
#undef Sub3960 
#define Sub3960 CtoV2(var1s.C[194])
#undef Sub863 
#define Sub863 CtoV2(var1s.C[195])
#undef Sub3984 
#define Sub3984 CtoV2(var1s.C[196])
#undef Sub3958 
#define Sub3958 CtoV2(var1s.C[197])
#undef Sub857 
#define Sub857 CtoV2(var1s.C[198])
#undef Sub3910 
#define Sub3910 CtoV2(var1s.C[199])
#undef Sub96 
#define Sub96 CtoV2(var1s.C[200])
#undef Sub118 
#define Sub118 CtoV2(var1s.C[201])
#undef Sub67 
#define Sub67 CtoV2(var1s.C[202])
#undef Sub827 
#define Sub827 CtoV2(var1s.C[203])
#undef Sub4015 
#define Sub4015 CtoV2(var1s.C[204])
#undef Sub830 
#define Sub830 CtoV2(var1s.C[205])
#undef Sub845 
#define Sub845 CtoV2(var1s.C[206])
#undef Sub897 
#define Sub897 CtoV2(var1s.C[207])
#undef Sub878 
#define Sub878 CtoV2(var1s.C[208])
#undef Sub877 
#define Sub877 CtoV2(var1s.C[209])
#undef Sub3957 
#define Sub3957 CtoV2(var1s.C[210])
#undef Sub3657 
#define Sub3657 CtoV2(var1s.C[211])
#undef Sub62 
#define Sub62 CtoV2(var1s.C[212])
#undef Sub3961 
#define Sub3961 CtoV2(var1s.C[213])
#undef Sub4085 
#define Sub4085 CtoV2(var1s.C[214])
#undef Sub919 
#define Sub919 CtoV2(var1s.C[215])
#undef Sub3931 
#define Sub3931 CtoV2(var1s.C[216])
#undef Sub71 
#define Sub71 CtoV2(var1s.C[217])
#undef Sub825 
#define Sub825 CtoV2(var1s.C[218])
#undef Sub4084 
#define Sub4084 CtoV2(var1s.C[219])
#undef Sub809 
#define Sub809 CtoV2(var1s.C[220])
#undef Sub833 
#define Sub833 CtoV2(var1s.C[221])
#undef Sub808 
#define Sub808 CtoV2(var1s.C[222])
#undef Sub832 
#define Sub832 CtoV2(var1s.C[223])
#undef Sub50 
#define Sub50 CtoV2(var1s.C[224])
#undef Sub38 
#define Sub38 CtoV2(var1s.C[225])
#undef Sub3907 
#define Sub3907 CtoV2(var1s.C[226])
#undef Sub4025 
#define Sub4025 CtoV2(var1s.C[227])
#undef Sub852 
#define Sub852 CtoV2(var1s.C[228])
#undef Sub4059 
#define Sub4059 CtoV2(var1s.C[229])
#undef Sub4055 
#define Sub4055 CtoV2(var1s.C[230])
#undef Sub4083 
#define Sub4083 CtoV2(var1s.C[231])
#undef Sub4052 
#define Sub4052 CtoV2(var1s.C[232])
#undef Sub801 
#define Sub801 CtoV2(var1s.C[233])
#undef Sub4050 
#define Sub4050 CtoV2(var1s.C[234])
#undef Sub4048 
#define Sub4048 CtoV2(var1s.C[235])
#undef Sub4026 
#define Sub4026 CtoV2(var1s.C[236])
#undef Sub807 
#define Sub807 CtoV2(var1s.C[237])
#undef Sub823 
#define Sub823 CtoV2(var1s.C[238])
#undef Sub4024 
#define Sub4024 CtoV2(var1s.C[239])
#undef Sub4047 
#define Sub4047 CtoV2(var1s.C[240])
#undef Sub4053 
#define Sub4053 CtoV2(var1s.C[241])
#undef Sub37 
#define Sub37 CtoV2(var1s.C[242])
#undef Sub4049 
#define Sub4049 CtoV2(var1s.C[243])
#undef Sub4061 
#define Sub4061 CtoV2(var1s.C[244])
#undef Sub4057 
#define Sub4057 CtoV2(var1s.C[245])
#undef Sub4060 
#define Sub4060 CtoV2(var1s.C[246])
#undef Sub4064 
#define Sub4064 CtoV2(var1s.C[247])
#undef Sub911 
#define Sub911 CtoV2(var1s.C[248])
#undef Sub4066 
#define Sub4066 CtoV2(var1s.C[249])
#undef Sub815 
#define Sub815 CtoV2(var1s.C[250])
#undef Sub855 
#define Sub855 CtoV2(var1s.C[251])
#undef Sub810 
#define Sub810 CtoV2(var1s.C[252])
#undef Sub858 
#define Sub858 CtoV2(var1s.C[253])
#undef Sub817 
#define Sub817 CtoV2(var1s.C[254])
#undef Sub4006 
#define Sub4006 CtoV2(var1s.C[255])
#undef Sub3940 
#define Sub3940 CtoV2(var1s.C[256])
#undef Sub816 
#define Sub816 CtoV2(var1s.C[257])
#undef Sub4046 
#define Sub4046 CtoV2(var1s.C[258])
#undef Sub824 
#define Sub824 CtoV2(var1s.C[259])
#undef Sub3936 
#define Sub3936 CtoV2(var1s.C[260])
#undef Sub888 
#define Sub888 CtoV2(var1s.C[261])
#undef Sub53 
#define Sub53 CtoV2(var1s.C[262])
#undef Sub4039 
#define Sub4039 CtoV2(var1s.C[263])
#undef Sub3963 
#define Sub3963 CtoV2(var1s.C[264])
#undef Sub14850 
#define Sub14850 CtoV2(var1s.C[265])
#undef Sub15382 
#define Sub15382 CtoV2(var1s.C[266])
#undef Sub14847 
#define Sub14847 CtoV2(var1s.C[267])
#undef Sub14892 
#define Sub14892 CtoV2(var1s.C[268])
#undef Sub14891 
#define Sub14891 CtoV2(var1s.C[269])
#undef Sub14904 
#define Sub14904 CtoV2(var1s.C[270])
#undef Sub14903 
#define Sub14903 CtoV2(var1s.C[271])
#undef Sub14859 
#define Sub14859 CtoV2(var1s.C[272])
#undef Sub15286 
#define Sub15286 CtoV2(var1s.C[273])
#undef Sub14997 
#define Sub14997 CtoV2(var1s.C[274])
#undef Sub14902 
#define Sub14902 CtoV2(var1s.C[275])
#undef Sub14901 
#define Sub14901 CtoV2(var1s.C[276])
#undef Sub15109 
#define Sub15109 CtoV2(var1s.C[277])
#undef Sub15214 
#define Sub15214 CtoV2(var1s.C[278])
#undef Sub15249 
#define Sub15249 CtoV2(var1s.C[279])
#undef Sub15016 
#define Sub15016 CtoV2(var1s.C[280])
#undef Sub15742 
#define Sub15742 CtoV2(var1s.C[281])
#undef Sub15128 
#define Sub15128 CtoV2(var1s.C[282])
#undef Sub15110 
#define Sub15110 CtoV2(var1s.C[283])
#undef Sub15771 
#define Sub15771 CtoV2(var1s.C[284])
#undef Sub15297 
#define Sub15297 CtoV2(var1s.C[285])
#undef Sub15340 
#define Sub15340 CtoV2(var1s.C[286])
#undef Sub15095 
#define Sub15095 CtoV2(var1s.C[287])
#undef Sub15100 
#define Sub15100 CtoV2(var1s.C[288])
#undef Sub15201 
#define Sub15201 CtoV2(var1s.C[289])
#undef Sub15149 
#define Sub15149 CtoV2(var1s.C[290])
#undef Sub15244 
#define Sub15244 CtoV2(var1s.C[291])
#undef Sub15129 
#define Sub15129 CtoV2(var1s.C[292])
#undef Sub15087 
#define Sub15087 CtoV2(var1s.C[293])
#undef Sub15191 
#define Sub15191 CtoV2(var1s.C[294])
#undef Sub15086 
#define Sub15086 CtoV2(var1s.C[295])
#undef Sub15101 
#define Sub15101 CtoV2(var1s.C[296])
#undef Sub15190 
#define Sub15190 CtoV2(var1s.C[297])
#undef Sub15206 
#define Sub15206 CtoV2(var1s.C[298])
#undef Sub15185 
#define Sub15185 CtoV2(var1s.C[299])
#undef Sub15083 
#define Sub15083 CtoV2(var1s.C[300])
#undef Sub15080 
#define Sub15080 CtoV2(var1s.C[301])
#undef Sub15179 
#define Sub15179 CtoV2(var1s.C[302])
#undef Sub15076 
#define Sub15076 CtoV2(var1s.C[303])
#undef Sub15077 
#define Sub15077 CtoV2(var1s.C[304])
#undef Sub15184 
#define Sub15184 CtoV2(var1s.C[305])
#undef Sub15009 
#define Sub15009 CtoV2(var1s.C[306])
#undef Sub15133 
#define Sub15133 CtoV2(var1s.C[307])
#undef Sub15187 
#define Sub15187 CtoV2(var1s.C[308])
#undef Sub15257 
#define Sub15257 CtoV2(var1s.C[309])
#undef Sub699 
#define Sub699 CtoV2(var1s.C[310])
#undef Sub749 
#define Sub749 CtoV2(var1s.C[311])
#undef Sub750 
#define Sub750 CtoV2(var1s.C[312])
#undef Sub701 
#define Sub701 CtoV2(var1s.C[313])
#undef Sub676 
#define Sub676 CtoV2(var1s.C[314])
#undef Sub703 
#define Sub703 CtoV2(var1s.C[315])
#undef Sub705 
#define Sub705 CtoV2(var1s.C[316])
#undef Sub751 
#define Sub751 CtoV2(var1s.C[317])
#undef Sub752 
#define Sub752 CtoV2(var1s.C[318])
#undef Sub15544 
#define Sub15544 CtoV2(var1s.C[319])
#undef Sub15543 
#define Sub15543 CtoV2(var1s.C[320])
#undef Sub15536 
#define Sub15536 CtoV2(var1s.C[321])
#undef Sub15551 
#define Sub15551 CtoV2(var1s.C[322])
#undef Sub15568 
#define Sub15568 CtoV2(var1s.C[323])
#undef Sub15569 
#define Sub15569 CtoV2(var1s.C[324])
#undef Sub15552 
#define Sub15552 CtoV2(var1s.C[325])
#undef Sub15537 
#define Sub15537 CtoV2(var1s.C[326])
#undef Sub15570 
#define Sub15570 CtoV2(var1s.C[327])
#undef Sub15538 
#define Sub15538 CtoV2(var1s.C[328])
#undef Sub15523 
#define Sub15523 CtoV2(var1s.C[329])
#undef Sub15587 
#define Sub15587 CtoV2(var1s.C[330])
#undef Sub15437 
#define Sub15437 CtoV2(var1s.C[331])
#undef Sub15514 
#define Sub15514 CtoV2(var1s.C[332])
#undef Sub15515 
#define Sub15515 CtoV2(var1s.C[333])
#undef Sub83 
#define Sub83 CtoV2(var1s.C[334])
#undef Sub55 
#define Sub55 CtoV2(var1s.C[335])
#undef Sub79 
#define Sub79 CtoV2(var1s.C[336])
#undef Sub74 
#define Sub74 CtoV2(var1s.C[337])
#undef Sub69 
#define Sub69 CtoV2(var1s.C[338])
#undef Sub86 
#define Sub86 CtoV2(var1s.C[339])
#undef Sub63 
#define Sub63 CtoV2(var1s.C[340])
#undef Sub73 
#define Sub73 CtoV2(var1s.C[341])
#undef Sub91 
#define Sub91 CtoV2(var1s.C[342])
#undef Sub93 
#define Sub93 CtoV2(var1s.C[343])
#undef Sub116 
#define Sub116 CtoV2(var1s.C[344])
#undef Sub115 
#define Sub115 CtoV2(var1s.C[345])
#undef Sub70 
#define Sub70 CtoV2(var1s.C[346])
#undef Sub59 
#define Sub59 CtoV2(var1s.C[347])
#undef Sub60 
#define Sub60 CtoV2(var1s.C[348])
#undef Sub87 
#define Sub87 CtoV2(var1s.C[349])
#undef Sub54 
#define Sub54 CtoV2(var1s.C[350])
#undef Sub56 
#define Sub56 CtoV2(var1s.C[351])
#undef Sub14940
#define Sub14940(i) CtoV2(var1s.C[351+i])
#undef Sub14951
#define Sub14951(i) CtoV2(var1s.C[354+i])
#undef Sub14931
#define Sub14931(i) CtoV2(var1s.C[357+i])
#undef Sub14932
#define Sub14932(i) CtoV2(var1s.C[360+i])
#undef Sub14933
#define Sub14933(i) CtoV2(var1s.C[363+i])
#undef Sub14952
#define Sub14952(i) CtoV2(var1s.C[366+i])
#undef Sub14941
#define Sub14941(i) CtoV2(var1s.C[369+i])
#undef Sub14949
#define Sub14949(i) CtoV2(var1s.C[372+i])
#undef Sub14938
#define Sub14938(i) CtoV2(var1s.C[375+i])
#undef Sub14942
#define Sub14942(i) CtoV2(var1s.C[378+i])
#undef Sub14939
#define Sub14939(i) CtoV2(var1s.C[381+i])
#undef Sub14950
#define Sub14950(i) CtoV2(var1s.C[384+i])
#undef Sub4091 
#define Sub4091 CtoV2(var1s.C[388])
#undef Sub846 
#define Sub846 CtoV2(var1s.C[389])
#undef Sub4076 
#define Sub4076 CtoV2(var1s.C[390])
#undef Sub4075 
#define Sub4075 CtoV2(var1s.C[391])
#undef Sub4079 
#define Sub4079 CtoV2(var1s.C[392])
#undef Sub4080 
#define Sub4080 CtoV2(var1s.C[393])
#undef Sub4090 
#define Sub4090 CtoV2(var1s.C[394])
#undef Sub72 
#define Sub72 CtoV2(var1s.C[395])
#undef Sub94 
#define Sub94 CtoV2(var1s.C[396])
#undef Sub124 
#define Sub124 CtoV2(var1s.C[397])
#undef Sub133 
#define Sub133 CtoV2(var1s.C[398])
#undef Sub821 
#define Sub821 CtoV2(var1s.C[399])
#undef Sub822 
#define Sub822 CtoV2(var1s.C[400])
#undef Sub3993 
#define Sub3993 CtoV2(var1s.C[401])
#undef Sub3999 
#define Sub3999 CtoV2(var1s.C[402])
#undef Sub3656 
#define Sub3656 CtoV2(var1s.C[403])
#undef Sub4012 
#define Sub4012 CtoV2(var1s.C[404])
#undef Sub4027 
#define Sub4027 CtoV2(var1s.C[405])
#undef Sub4022 
#define Sub4022 CtoV2(var1s.C[406])
#undef Sub3946 
#define Sub3946 CtoV2(var1s.C[407])
#undef Sub862 
#define Sub862 CtoV2(var1s.C[408])
#undef Sub52 
#define Sub52 CtoV2(var1s.C[409])
#undef Sub122 
#define Sub122 CtoV2(var1s.C[410])
#undef Sub61 
#define Sub61 CtoV2(var1s.C[411])
#undef Sub80 
#define Sub80 CtoV2(var1s.C[412])
#undef Sub854 
#define Sub854 CtoV2(var1s.C[413])
#undef Sub849 
#define Sub849 CtoV2(var1s.C[414])
#undef Sub89 
#define Sub89 CtoV2(var1s.C[415])
#undef Sub870 
#define Sub870 CtoV2(var1s.C[416])
#undef Sub872 
#define Sub872 CtoV2(var1s.C[417])
#undef Sub3904 
#define Sub3904 CtoV2(var1s.C[418])
#undef Sub3906 
#define Sub3906 CtoV2(var1s.C[419])
#undef Sub3908 
#define Sub3908 CtoV2(var1s.C[420])
#undef Sub890 
#define Sub890 CtoV2(var1s.C[421])
#undef Sub125 
#define Sub125 CtoV2(var1s.C[422])
#undef Sub97 
#define Sub97 CtoV2(var1s.C[423])
#undef Sub3926 
#define Sub3926 CtoV2(var1s.C[424])
#undef Sub889 
#define Sub889 CtoV2(var1s.C[425])
#undef Sub3928 
#define Sub3928 CtoV2(var1s.C[426])
#undef Sub3954 
#define Sub3954 CtoV2(var1s.C[427])
#undef Sub896 
#define Sub896 CtoV2(var1s.C[428])
#undef Sub3966 
#define Sub3966 CtoV2(var1s.C[429])
#undef Sub3968 
#define Sub3968 CtoV2(var1s.C[430])
#undef Sub4041 
#define Sub4041 CtoV2(var1s.C[431])
#undef Sub898 
#define Sub898 CtoV2(var1s.C[432])
#undef Sub4023 
#define Sub4023 CtoV2(var1s.C[433])
#undef Sub3944 
#define Sub3944 CtoV2(var1s.C[434])
#undef Sub3945 
#define Sub3945 CtoV2(var1s.C[435])
#undef Sub881 
#define Sub881 CtoV2(var1s.C[436])
#undef Sub4008 
#define Sub4008 CtoV2(var1s.C[437])
#undef Sub4007 
#define Sub4007 CtoV2(var1s.C[438])
#undef Sub860 
#define Sub860 CtoV2(var1s.C[439])
#undef Sub859 
#define Sub859 CtoV2(var1s.C[440])
#undef Sub819 
#define Sub819 CtoV2(var1s.C[441])
#undef Sub900 
#define Sub900 CtoV2(var1s.C[442])
#undef Sub899 
#define Sub899 CtoV2(var1s.C[443])
#undef Sub828 
#define Sub828 CtoV2(var1s.C[444])
#undef Sub820 
#define Sub820 CtoV2(var1s.C[445])
#undef Sub826 
#define Sub826 CtoV2(var1s.C[446])
#undef Sub3925 
#define Sub3925 CtoV2(var1s.C[447])
#undef Sub893 
#define Sub893 CtoV2(var1s.C[448])
#undef Sub818 
#define Sub818 CtoV2(var1s.C[449])
#undef Sub101 
#define Sub101 CtoV2(var1s.C[450])
#undef Sub869 
#define Sub869 CtoV2(var1s.C[451])
#undef Sub68 
#define Sub68 CtoV2(var1s.C[452])
#undef Sub49 
#define Sub49 CtoV2(var1s.C[453])
#undef Sub891 
#define Sub891 CtoV2(var1s.C[454])
#undef Sub48 
#define Sub48 CtoV2(var1s.C[455])
#undef Sub114 
#define Sub114 CtoV2(var1s.C[456])
#undef Sub3971 
#define Sub3971 CtoV2(var1s.C[457])
#undef Sub58 
#define Sub58 CtoV2(var1s.C[458])
#undef Sub892 
#define Sub892 CtoV2(var1s.C[459])
#undef Sub3959 
#define Sub3959 CtoV2(var1s.C[460])
#undef Sub15088 
#define Sub15088 CtoV2(var1s.C[461])
#undef Sub15192 
#define Sub15192 CtoV2(var1s.C[462])
#undef Sub15130 
#define Sub15130 CtoV2(var1s.C[463])
#undef Sub15138 
#define Sub15138 CtoV2(var1s.C[464])
#undef Sub15238 
#define Sub15238 CtoV2(var1s.C[465])
#undef Sub15150 
#define Sub15150 CtoV2(var1s.C[466])
#undef Sub15252 
#define Sub15252 CtoV2(var1s.C[467])
#undef Sub15132 
#define Sub15132 CtoV2(var1s.C[468])
#undef Sub15232 
#define Sub15232 CtoV2(var1s.C[469])
#undef Sub103 
#define Sub103 CtoV2(var1s.C[470])
#undef Sub110 
#define Sub110 CtoV2(var1s.C[471])
#undef Sub92 
#define Sub92 CtoV2(var1s.C[472])
#undef Sub123 
#define Sub123 CtoV2(var1s.C[473])
#undef Sub119 
#define Sub119 CtoV2(var1s.C[474])
#undef Sub130 
#define Sub130 CtoV2(var1s.C[475])
#undef Sub81 
#define Sub81 CtoV2(var1s.C[476])
#undef Sub129 
#define Sub129 CtoV2(var1s.C[477])
#undef Sub117 
#define Sub117 CtoV2(var1s.C[478])
#undef Sub64 
#define Sub64 CtoV2(var1s.C[479])
#undef Sub120 
#define Sub120 CtoV2(var1s.C[480])
#undef Sub76 
#define Sub76 CtoV2(var1s.C[481])
#undef Sub84 
#define Sub84 CtoV2(var1s.C[482])
#undef Sub102 
#define Sub102 CtoV2(var1s.C[483])
#undef Sub57 
#define Sub57 CtoV2(var1s.C[484])
#undef Sub111 
#define Sub111 CtoV2(var1s.C[485])
#undef Sub78 
#define Sub78 CtoV2(var1s.C[486])
#undef Sub14929
#define Sub14929(i) CtoV2(var1s.C[486+i])
#undef Sub14930
#define Sub14930(i) CtoV2(var1s.C[489+i])
#undef Sub14935
#define Sub14935(i) CtoV2(var1s.C[492+i])
#undef Sub14934
#define Sub14934(i) CtoV2(var1s.C[495+i])
#undef Sub14946
#define Sub14946(i) CtoV2(var1s.C[498+i])
#undef Sub4089 
#define Sub4089 CtoV2(var1s.C[502])
#undef Sub873 
#define Sub873 CtoV2(var1s.C[503])
#undef Sub868 
#define Sub868 CtoV2(var1s.C[504])
#undef Sub4081 
#define Sub4081 CtoV2(var1s.C[505])
#undef Sub4077 
#define Sub4077 CtoV2(var1s.C[506])
#undef Sub3989 
#define Sub3989 CtoV2(var1s.C[507])
#undef Sub805 
#define Sub805 CtoV2(var1s.C[508])
#undef Sub839 
#define Sub839 CtoV2(var1s.C[509])
#undef Sub3909 
#define Sub3909 CtoV2(var1s.C[510])
#undef Sub829 
#define Sub829 CtoV2(var1s.C[511])
#undef Sub885 
#define Sub885 CtoV2(var1s.C[512])
#undef Sub4029 
#define Sub4029 CtoV2(var1s.C[513])
#undef Sub4009 
#define Sub4009 CtoV2(var1s.C[514])
#undef Sub3955 
#define Sub3955 CtoV2(var1s.C[515])
#undef Sub41 
#define Sub41 CtoV2(var1s.C[516])
#undef Sub4045 
#define Sub4045 CtoV2(var1s.C[517])
#undef Sub3973 
#define Sub3973 CtoV2(var1s.C[518])
#undef Sub109 
#define Sub109 CtoV2(var1s.C[519])
#undef Sub851 
#define Sub851 CtoV2(var1s.C[520])
#undef Sub864 
#define Sub864 CtoV2(var1s.C[521])
#undef Sub811 
#define Sub811 CtoV2(var1s.C[522])
#undef Sub42 
#define Sub42 CtoV2(var1s.C[523])
#undef Sub45 
#define Sub45 CtoV2(var1s.C[524])
#undef Sub100 
#define Sub100 CtoV2(var1s.C[525])
#undef Sub875 
#define Sub875 CtoV2(var1s.C[526])
#undef Sub914 
#define Sub914 CtoV2(var1s.C[527])
#undef Sub43 
#define Sub43 CtoV2(var1s.C[528])
#undef Sub40 
#define Sub40 CtoV2(var1s.C[529])
#undef Sub874 
#define Sub874 CtoV2(var1s.C[530])
#undef Sub876 
#define Sub876 CtoV2(var1s.C[531])
#undef Sub915 
#define Sub915 CtoV2(var1s.C[532])
#undef Sub916 
#define Sub916 CtoV2(var1s.C[533])
#undef Sub4044 
#define Sub4044 CtoV2(var1s.C[534])
#undef Sub3975 
#define Sub3975 CtoV2(var1s.C[535])
#undef Sub3977 
#define Sub3977 CtoV2(var1s.C[536])
#undef Sub3974 
#define Sub3974 CtoV2(var1s.C[537])
#undef Sub47 
#define Sub47 CtoV2(var1s.C[538])
#undef Sub3970 
#define Sub3970 CtoV2(var1s.C[539])
#undef Sub14860 
#define Sub14860 CtoV2(var1s.C[540])
#undef Sub14849 
#define Sub14849 CtoV2(var1s.C[541])
#undef Sub132 
#define Sub132 CtoV2(var1s.C[542])
#undef Sub95 
#define Sub95 CtoV2(var1s.C[543])
#undef Sub106 
#define Sub106 CtoV2(var1s.C[544])
#undef Sub104 
#define Sub104 CtoV2(var1s.C[545])
#undef Sub127 
#define Sub127 CtoV2(var1s.C[546])
#undef Sub98 
#define Sub98 CtoV2(var1s.C[547])
#undef Sub134 
#define Sub134 CtoV2(var1s.C[548])
#undef Sub108 
#define Sub108 CtoV2(var1s.C[549])
#undef Sub909 
#define Sub909 CtoV2(var1s.C[550])
#undef Sub913 
#define Sub913 CtoV2(var1s.C[551])
#undef Sub4078 
#define Sub4078 CtoV2(var1s.C[552])
#undef Sub3913 
#define Sub3913 CtoV2(var1s.C[553])
#undef Sub841 
#define Sub841 CtoV2(var1s.C[554])
#undef Sub906 
#define Sub906 CtoV2(var1s.C[555])
#undef Sub838 
#define Sub838 CtoV2(var1s.C[556])
#undef Sub3969 
#define Sub3969 CtoV2(var1s.C[557])
#undef Sub44 
#define Sub44 CtoV2(var1s.C[558])
#undef Sub46 
#define Sub46 CtoV2(var1s.C[559])
#undef Sub15526 
#define Sub15526 CtoV2(var1s.C[560])
#undef Sub14943
#define Sub14943(i) CtoV2(var1s.C[560+i])
#undef Sub14953
#define Sub14953(i) CtoV2(var1s.C[563+i])
#undef Sub836 
#define Sub836 CtoV2(var1s.C[567])
#undef Sub837 
#define Sub837 CtoV2(var1s.C[568])
#undef Sub840 
#define Sub840 CtoV2(var1s.C[569])
#undef Sub907 
#define Sub907 CtoV2(var1s.C[570])
#undef Sub14928
#define Sub14928(i) CtoV2(var1s.C[570+i])
#undef Sub842 
#define Sub842 CtoV2(var1s.C[574])
#undef Sub908 
#define Sub908 CtoV2(var1s.C[575])
#undef pave6
#define pave6(i) CtoV2(var1s.C[575+i])
#undef pave7
#define pave7(i) CtoV2(var1s.C[575+i+Nbb])
#undef pave8
#define pave8(i) CtoV2(var1s.C[575+i+2*Nbb])
#undef pave12
#define pave12(i) CtoV2(var1s.C[575+i+3*Nbb])
#undef pave13
#define pave13(i) CtoV2(var1s.C[575+i+4*Nbb])
#undef pave14
#define pave14(i) CtoV2(var1s.C[575+i+5*Nbb])
#undef pave15
#define pave15(i) CtoV2(var1s.C[575+i+6*Nbb])
#undef pave16
#define pave16(i) CtoV2(var1s.C[575+i+7*Nbb])
#undef pave17
#define pave17(i) CtoV2(var1s.C[575+i+8*Nbb])
#undef pave18
#define pave18(i) CtoV2(var1s.C[575+i+9*Nbb])
#undef pave19
#define pave19(i) CtoV2(var1s.C[575+i+10*Nbb])
#undef pave20
#define pave20(i) CtoV2(var1s.C[575+i+11*Nbb])
#undef pave23 
#define pave23 CtoV2(var1s.C[576 + 12*Nbb])
#undef pave24
#define pave24(i) CtoV2(var1s.C[576+i+12*Nbb])
#undef pave25
#define pave25(i) CtoV2(var1s.C[576+i+13*Nbb])
#undef pave26
#define pave26(i) CtoV2(var1s.C[576+i+14*Nbb])
#undef pave27
#define pave27(i) CtoV2(var1s.C[576+i+15*Nbb])
#undef pave28
#define pave28(i) CtoV2(var1s.C[576+i+16*Nbb])
#undef pave29
#define pave29(i) CtoV2(var1s.C[576+i+17*Nbb])
#undef pave30
#define pave30(i) CtoV2(var1s.C[576+i+18*Nbb])
#undef pave31
#define pave31(i) CtoV2(var1s.C[576+i+19*Nbb])
#undef pave32
#define pave32(i) CtoV2(var1s.C[576+i+20*Nbb])
#undef pave33
#define pave33(i) CtoV2(var1s.C[576+i+20*Nbb+Ncc])
#undef pave34
#define pave34(i) CtoV2(var1s.C[576+i+20*Nbb+2*Ncc])
#undef pave35
#define pave35(i) CtoV2(var1s.C[576+i+20*Nbb+3*Ncc])
#undef pave36
#define pave36(i) CtoV2(var1s.C[576+i+20*Nbb+4*Ncc])
#undef pave37
#define pave37(i) CtoV2(var1s.C[576+i+20*Nbb+5*Ncc])
#undef pave38
#define pave38(i) CtoV2(var1s.C[576+i+20*Nbb+6*Ncc])
#undef pave39
#define pave39(i) CtoV2(var1s.C[576+i+20*Nbb+7*Ncc])
#undef pave40
#define pave40(i) CtoV2(var1s.C[576+i+20*Nbb+8*Ncc])
#undef pave41
#define pave41(i) CtoV2(var1s.C[576+i+20*Nbb+9*Ncc])
#undef pave42
#define pave42(i) CtoV2(var1s.C[576+i+20*Nbb+10*Ncc])
#undef pave43
#define pave43(i) CtoV2(var1s.C[576+i+20*Nbb+11*Ncc])
#undef pave45
#define pave45(i) CtoV2(var1s.C[576+i+20*Nbb+12*Ncc])
#undef pave46
#define pave46(i) CtoV2(var1s.C[576+i+20*Nbb+13*Ncc])
#undef pave47
#define pave47(i) CtoV2(var1s.C[576+i+21*Nbb+13*Ncc])
#undef pave48
#define pave48(i) CtoV2(var1s.C[576+i+21*Nbb+14*Ncc])
#undef pave49
#define pave49(i) CtoV2(var1s.C[576+i+21*Nbb+15*Ncc])
#undef pave50
#define pave50(i) CtoV2(var1s.C[576+i+21*Nbb+16*Ncc])
#undef pave51
#define pave51(i) CtoV2(var1s.C[576+i+21*Nbb+17*Ncc])
#undef pave58
#define pave58(i) CtoV2(var1s.C[576+i+21*Nbb+18*Ncc])
#undef pave59
#define pave59(i) CtoV2(var1s.C[576+i+21*Nbb+19*Ncc])
#undef pave60
#define pave60(i) CtoV2(var1s.C[576+i+21*Nbb+20*Ncc])
#undef pave61
#define pave61(i) CtoV2(var1s.C[576+i+21*Nbb+21*Ncc])
#undef pave62
#define pave62(i) CtoV2(var1s.C[576+i+21*Nbb+22*Ncc])
#undef pave63
#define pave63(i) CtoV2(var1s.C[576+i+21*Nbb+23*Ncc])
#undef pave65
#define pave65(i) CtoV2(var1s.C[576+i+21*Nbb+24*Ncc])
#undef pave66
#define pave66(i) CtoV2(var1s.C[576+i+21*Nbb+25*Ncc])
#undef pave67
#define pave67(i) CtoV2(var1s.C[576+i+21*Nbb+26*Ncc])
#undef pave68
#define pave68(i) CtoV2(var1s.C[576+i+21*Nbb+27*Ncc])
#undef pave69
#define pave69(i) CtoV2(var1s.C[576+i+21*Nbb+28*Ncc])
#undef pave72
#define pave72(i) CtoV2(var1s.C[576+i+21*Nbb+29*Ncc])
#undef pave73
#define pave73(i) CtoV2(var1s.C[576+i+21*Nbb+30*Ncc])
#undef pave74
#define pave74(i) CtoV2(var1s.C[576+i+21*Nbb+31*Ncc])
#undef pave75
#define pave75(i) CtoV2(var1s.C[576+i+21*Nbb+32*Ncc])
#undef pave76
#define pave76(i) CtoV2(var1s.C[576+i+21*Nbb+33*Ncc])
#undef pave77
#define pave77(i) CtoV2(var1s.C[576+i+21*Nbb+34*Ncc])
#undef pave78
#define pave78(i) CtoV2(var1s.C[576+i+21*Nbb+35*Ncc])
#undef pave82
#define pave82(i) CtoV2(var1s.C[576+i+21*Nbb+36*Ncc])
#undef pave84
#define pave84(i) CtoV2(var1s.C[576+i+21*Nbb+37*Ncc])
#undef pave87
#define pave87(i) CtoV2(var1s.C[576+i+21*Nbb+38*Ncc])
#undef pave88
#define pave88(i) CtoV2(var1s.C[576+i+21*Nbb+39*Ncc])
#undef pave89
#define pave89(i) CtoV2(var1s.C[576+i+21*Nbb+40*Ncc])
#undef pave92
#define pave92(i) CtoV2(var1s.C[576+i+21*Nbb+41*Ncc])
#undef pave94
#define pave94(i) CtoV2(var1s.C[576+i+21*Nbb+42*Ncc])
#undef pave95
#define pave95(i) CtoV2(var1s.C[576+i+21*Nbb+43*Ncc])
#undef pave99
#define pave99(i) CtoV2(var1s.C[576+i+21*Nbb+43*Ncc+Ndd])
#undef pave104
#define pave104(i) CtoV2(var1s.C[576+i+21*Nbb+43*Ncc+2*Ndd])
#undef pave117
#define pave117(i) CtoV2(var1s.C[576+i+21*Nbb+44*Ncc+2*Ndd])
#undef pave118
#define pave118(i) CtoV2(var1s.C[576+i+21*Nbb+44*Ncc+3*Ndd])
#undef pave134
#define pave134(i) CtoV2(var1s.C[576+i+21*Nbb+44*Ncc+4*Ndd])
#undef pave139
#define pave139(i) CtoV2(var1s.C[576+i+21*Nbb+44*Ncc+5*Ndd])
#undef pave148
#define pave148(i) CtoV2(var1s.C[576+i+21*Nbb+44*Ncc+6*Ndd])
#undef pave149
#define pave149(i) CtoV2(var1s.C[579+i+21*Nbb+44*Ncc+6*Ndd])
#undef pave150
#define pave150(i) CtoV2(var1s.C[582+i+21*Nbb+44*Ncc+6*Ndd])
#undef pave151
#define pave151(i,j) CtoV2(var1s.C[585+i+20*Nbb+j*Nbb+44*Ncc+6*Ndd])
#undef pave152
#define pave152(i,j) CtoV2(var1s.C[585+i+23*Nbb+j*Nbb+44*Ncc+6*Ndd])
#undef pave153
#define pave153(i,j) CtoV2(var1s.C[585+i+26*Nbb+j*Nbb+44*Ncc+6*Ndd])
#undef pave158
#define pave158(i) CtoV2(var1s.C[585+i+30*Nbb+44*Ncc+6*Ndd])
#undef pave159
#define pave159(i) CtoV2(var1s.C[585+i+31*Nbb+44*Ncc+6*Ndd])
#undef pave161
#define pave161(i) CtoV2(var1s.C[585+i+32*Nbb+44*Ncc+6*Ndd])
#undef pave165 
#define pave165 CtoV2(var1s.C[586 + 33*Nbb + 44*Ncc + 6*Ndd])
#undef pave166 
#define pave166 CtoV2(var1s.C[587 + 33*Nbb + 44*Ncc + 6*Ndd])
#undef pave175
#define pave175(i) CtoV2(var1s.C[587+i+33*Nbb+44*Ncc+6*Ndd])
#undef pave176
#define pave176(i) CtoV2(var1s.C[587+i+34*Nbb+44*Ncc+6*Ndd])
#undef pave177
#define pave177(i) CtoV2(var1s.C[587+i+34*Nbb+45*Ncc+6*Ndd])
#undef pave180
#define pave180(i) CtoV2(var1s.C[587+i+34*Nbb+46*Ncc+6*Ndd])
#undef pave184
#define pave184(i) CtoV2(var1s.C[587+i+34*Nbb+47*Ncc+6*Ndd])

#undef Sub152 
#define Sub152 CtoV2(var0a.C[0])
#undef Sub257 
#define Sub257 CtoV2(var0a.C[1])
#undef Sub385 
#define Sub385 CtoV2(var0a.C[2])
#undef Sub150 
#define Sub150 CtoV2(var0a.C[3])
#undef Sub14828 
#define Sub14828 CtoV2(var0a.C[4])
#undef Sub14830 
#define Sub14830 CtoV2(var0a.C[5])
#undef Sub14832 
#define Sub14832 CtoV2(var0a.C[6])
#undef Sub14834 
#define Sub14834 CtoV2(var0a.C[7])

#undef Opt8 
#define Opt8 CtoV2(var1a.C[0])
#undef Opt16 
#define Opt16 CtoV2(var1a.C[1])
#undef Opt17 
#define Opt17 CtoV2(var1a.C[2])
#undef Opt18 
#define Opt18 CtoV2(var1a.C[3])
#undef Opt24
#define Opt24(i) CtoV2(var1a.C[3+i])
#undef Sub14836 
#define Sub14836 CtoV2(var1a.C[7])
#undef Sub621 
#define Sub621 CtoV2(var1a.C[8])
#undef Sub629 
#define Sub629 CtoV2(var1a.C[9])
#undef Sub1401 
#define Sub1401 CtoV2(var1a.C[10])
#undef Sub1059 
#define Sub1059 CtoV2(var1a.C[11])
#undef Sub2009 
#define Sub2009 CtoV2(var1a.C[12])
#undef Sub553 
#define Sub553 CtoV2(var1a.C[13])
#undef Sub657 
#define Sub657 CtoV2(var1a.C[14])
#undef Sub545 
#define Sub545 CtoV2(var1a.C[15])
#undef Sub546 
#define Sub546 CtoV2(var1a.C[16])
#undef Sub552 
#define Sub552 CtoV2(var1a.C[17])
#undef Sub656 
#define Sub656 CtoV2(var1a.C[18])
#undef Sub3674 
#define Sub3674 CtoV2(var1a.C[19])
#undef Sub9611 
#define Sub9611 CtoV2(var1a.C[20])
#undef Sub204 
#define Sub204 CtoV2(var1a.C[21])
#undef Sub634 
#define Sub634 CtoV2(var1a.C[22])
#undef Sub544 
#define Sub544 CtoV2(var1a.C[23])
#undef Sub655 
#define Sub655 CtoV2(var1a.C[24])
#undef Sub3025 
#define Sub3025 CtoV2(var1a.C[25])
#undef Sub3707 
#define Sub3707 CtoV2(var1a.C[26])
#undef Sub7791 
#define Sub7791 CtoV2(var1a.C[27])
#undef Sub7350 
#define Sub7350 CtoV2(var1a.C[28])
#undef Sub10626 
#define Sub10626 CtoV2(var1a.C[29])
#undef Sub10627 
#define Sub10627 CtoV2(var1a.C[30])
#undef Sub10464 
#define Sub10464 CtoV2(var1a.C[31])
#undef Sub1951 
#define Sub1951 CtoV2(var1a.C[32])
#undef Sub2746 
#define Sub2746 CtoV2(var1a.C[33])
#undef Sub2124 
#define Sub2124 CtoV2(var1a.C[34])
#undef Sub986 
#define Sub986 CtoV2(var1a.C[35])
#undef Sub8653 
#define Sub8653 CtoV2(var1a.C[36])
#undef Sub6423 
#define Sub6423 CtoV2(var1a.C[37])
#undef Sub4255 
#define Sub4255 CtoV2(var1a.C[38])
#undef Sub10451 
#define Sub10451 CtoV2(var1a.C[39])
#undef Sub10761 
#define Sub10761 CtoV2(var1a.C[40])
#undef Sub13625 
#define Sub13625 CtoV2(var1a.C[41])
#undef Sub190 
#define Sub190 CtoV2(var1a.C[42])
#undef Sub1353 
#define Sub1353 CtoV2(var1a.C[43])
#undef Sub10738 
#define Sub10738 CtoV2(var1a.C[44])
#undef Sub4838 
#define Sub4838 CtoV2(var1a.C[45])
#undef Sub8982 
#define Sub8982 CtoV2(var1a.C[46])
#undef Sub4521 
#define Sub4521 CtoV2(var1a.C[47])
#undef Sub4526 
#define Sub4526 CtoV2(var1a.C[48])
#undef Sub15060 
#define Sub15060 CtoV2(var1a.C[49])
#undef Sub14839 
#define Sub14839 CtoV2(var1a.C[50])
#undef Sub15287 
#define Sub15287 CtoV2(var1a.C[51])
#undef Sub14866 
#define Sub14866 CtoV2(var1a.C[52])
#undef Sub14919 
#define Sub14919 CtoV2(var1a.C[53])
#undef Sub14835 
#define Sub14835 CtoV2(var1a.C[54])
#undef Sub14882 
#define Sub14882 CtoV2(var1a.C[55])
#undef Sub14868 
#define Sub14868 CtoV2(var1a.C[56])
#undef Sub14841 
#define Sub14841 CtoV2(var1a.C[57])
#undef Sub15311 
#define Sub15311 CtoV2(var1a.C[58])
#undef Sub15659 
#define Sub15659 CtoV2(var1a.C[59])
#undef Sub15280 
#define Sub15280 CtoV2(var1a.C[60])
#undef Sub15015 
#define Sub15015 CtoV2(var1a.C[61])
#undef Sub15312 
#define Sub15312 CtoV2(var1a.C[62])
#undef Sub15033 
#define Sub15033 CtoV2(var1a.C[63])
#undef Sub15059 
#define Sub15059 CtoV2(var1a.C[64])
#undef Sub15020 
#define Sub15020 CtoV2(var1a.C[65])
#undef Sub15000 
#define Sub15000 CtoV2(var1a.C[66])
#undef Sub15034 
#define Sub15034 CtoV2(var1a.C[67])
#undef Sub15289 
#define Sub15289 CtoV2(var1a.C[68])
#undef Sub14999 
#define Sub14999 CtoV2(var1a.C[69])
#undef Sub15003 
#define Sub15003 CtoV2(var1a.C[70])
#undef Sub15035 
#define Sub15035 CtoV2(var1a.C[71])
#undef Sub15073 
#define Sub15073 CtoV2(var1a.C[72])
#undef Sub15302 
#define Sub15302 CtoV2(var1a.C[73])
#undef Sub15360 
#define Sub15360 CtoV2(var1a.C[74])
#undef Sub15074 
#define Sub15074 CtoV2(var1a.C[75])
#undef Sub15307 
#define Sub15307 CtoV2(var1a.C[76])
#undef Sub15317 
#define Sub15317 CtoV2(var1a.C[77])
#undef Sub15047 
#define Sub15047 CtoV2(var1a.C[78])
#undef Sub15389 
#define Sub15389 CtoV2(var1a.C[79])
#undef Sub15683 
#define Sub15683 CtoV2(var1a.C[80])
#undef Sub15303 
#define Sub15303 CtoV2(var1a.C[81])
#undef Sub15042 
#define Sub15042 CtoV2(var1a.C[82])
#undef Sub15065 
#define Sub15065 CtoV2(var1a.C[83])
#undef Sub15712 
#define Sub15712 CtoV2(var1a.C[84])
#undef Sub15652 
#define Sub15652 CtoV2(var1a.C[85])
#undef Sub15740 
#define Sub15740 CtoV2(var1a.C[86])
#undef Sub15799 
#define Sub15799 CtoV2(var1a.C[87])
#undef Sub15769 
#define Sub15769 CtoV2(var1a.C[88])
#undef Sub15800 
#define Sub15800 CtoV2(var1a.C[89])
#undef Sub15709 
#define Sub15709 CtoV2(var1a.C[90])
#undef Sub15770 
#define Sub15770 CtoV2(var1a.C[91])
#undef Sub15710 
#define Sub15710 CtoV2(var1a.C[92])
#undef Sub15741 
#define Sub15741 CtoV2(var1a.C[93])
#undef Sub15609 
#define Sub15609 CtoV2(var1a.C[94])
#undef Sub15474 
#define Sub15474 CtoV2(var1a.C[95])
#undef Sub15475 
#define Sub15475 CtoV2(var1a.C[96])
#undef Sub15449 
#define Sub15449 CtoV2(var1a.C[97])
#undef Sub15476 
#define Sub15476 CtoV2(var1a.C[98])
#undef Sub15454 
#define Sub15454 CtoV2(var1a.C[99])
#undef Sub15477 
#define Sub15477 CtoV2(var1a.C[100])
#undef Sub15603 
#define Sub15603 CtoV2(var1a.C[101])
#undef Sub15637 
#define Sub15637 CtoV2(var1a.C[102])
#undef Sub15624 
#define Sub15624 CtoV2(var1a.C[103])
#undef Sub15604 
#define Sub15604 CtoV2(var1a.C[104])
#undef Sub15638 
#define Sub15638 CtoV2(var1a.C[105])
#undef Sub15478 
#define Sub15478 CtoV2(var1a.C[106])
#undef Sub15450 
#define Sub15450 CtoV2(var1a.C[107])
#undef Sub15479 
#define Sub15479 CtoV2(var1a.C[108])
#undef Sub15455 
#define Sub15455 CtoV2(var1a.C[109])
#undef Sub15656 
#define Sub15656 CtoV2(var1a.C[110])
#undef Sub15747 
#define Sub15747 CtoV2(var1a.C[111])
#undef Sub15805 
#define Sub15805 CtoV2(var1a.C[112])
#undef Sub15775 
#define Sub15775 CtoV2(var1a.C[113])
#undef Sub15812 
#define Sub15812 CtoV2(var1a.C[114])
#undef Sub15718 
#define Sub15718 CtoV2(var1a.C[115])
#undef Sub15778 
#define Sub15778 CtoV2(var1a.C[116])
#undef Sub15713 
#define Sub15713 CtoV2(var1a.C[117])
#undef Sub15743 
#define Sub15743 CtoV2(var1a.C[118])
#undef Sub15486 
#define Sub15486 CtoV2(var1a.C[119])
#undef Sub15480 
#define Sub15480 CtoV2(var1a.C[120])
#undef Sub15554 
#define Sub15554 CtoV2(var1a.C[121])
#undef Sub15584 
#define Sub15584 CtoV2(var1a.C[122])
#undef Sub15487 
#define Sub15487 CtoV2(var1a.C[123])
#undef Sub15488 
#define Sub15488 CtoV2(var1a.C[124])
#undef Sub15489 
#define Sub15489 CtoV2(var1a.C[125])
#undef Sub15464 
#define Sub15464 CtoV2(var1a.C[126])
#undef Sub15481 
#define Sub15481 CtoV2(var1a.C[127])
#undef Sub15500 
#define Sub15500 CtoV2(var1a.C[128])
#undef Sub15421 
#define Sub15421 CtoV2(var1a.C[129])
#undef Sub15749 
#define Sub15749 CtoV2(var1a.C[130])
#undef Sub15808 
#define Sub15808 CtoV2(var1a.C[131])
#undef Sub15776 
#define Sub15776 CtoV2(var1a.C[132])
#undef Sub15801 
#define Sub15801 CtoV2(var1a.C[133])
#undef Sub15719 
#define Sub15719 CtoV2(var1a.C[134])
#undef Sub15773 
#define Sub15773 CtoV2(var1a.C[135])
#undef Sub15714 
#define Sub15714 CtoV2(var1a.C[136])
#undef Sub15745 
#define Sub15745 CtoV2(var1a.C[137])
#undef Sub15615 
#define Sub15615 CtoV2(var1a.C[138])
#undef Sub15644 
#define Sub15644 CtoV2(var1a.C[139])
#undef Sub15490 
#define Sub15490 CtoV2(var1a.C[140])
#undef Sub15605 
#define Sub15605 CtoV2(var1a.C[141])
#undef Sub15639 
#define Sub15639 CtoV2(var1a.C[142])
#undef Sub15451 
#define Sub15451 CtoV2(var1a.C[143])
#undef Sub15482 
#define Sub15482 CtoV2(var1a.C[144])
#undef Sub15465 
#define Sub15465 CtoV2(var1a.C[145])
#undef Sub15483 
#define Sub15483 CtoV2(var1a.C[146])
#undef Sub15438 
#define Sub15438 CtoV2(var1a.C[147])
#undef Sub15750 
#define Sub15750 CtoV2(var1a.C[148])
#undef Sub15809 
#define Sub15809 CtoV2(var1a.C[149])
#undef Sub15772 
#define Sub15772 CtoV2(var1a.C[150])
#undef Sub15802 
#define Sub15802 CtoV2(var1a.C[151])
#undef Sub15720 
#define Sub15720 CtoV2(var1a.C[152])
#undef Sub15779 
#define Sub15779 CtoV2(var1a.C[153])
#undef Sub15715 
#define Sub15715 CtoV2(var1a.C[154])
#undef Sub15744 
#define Sub15744 CtoV2(var1a.C[155])
#undef Sub15491 
#define Sub15491 CtoV2(var1a.C[156])
#undef Sub15468 
#define Sub15468 CtoV2(var1a.C[157])
#undef Sub15484 
#define Sub15484 CtoV2(var1a.C[158])
#undef Sub15456 
#define Sub15456 CtoV2(var1a.C[159])
#undef Sub15422 
#define Sub15422 CtoV2(var1a.C[160])
#undef Sub15428 
#define Sub15428 CtoV2(var1a.C[161])
#undef Sub15655 
#define Sub15655 CtoV2(var1a.C[162])
#undef Sub15425 
#define Sub15425 CtoV2(var1a.C[163])
#undef Sub15704 
#define Sub15704 CtoV2(var1a.C[164])
#undef Sub15728 
#define Sub15728 CtoV2(var1a.C[165])
#undef Sub15485 
#define Sub15485 CtoV2(var1a.C[166])
#undef Sub15653 
#define Sub15653 CtoV2(var1a.C[167])
#undef Sub15806 
#define Sub15806 CtoV2(var1a.C[168])
#undef Sub15803 
#define Sub15803 CtoV2(var1a.C[169])
#undef Sub15721 
#define Sub15721 CtoV2(var1a.C[170])
#undef Sub15763 
#define Sub15763 CtoV2(var1a.C[171])
#undef Sub15785 
#define Sub15785 CtoV2(var1a.C[172])
#undef Sub15716 
#define Sub15716 CtoV2(var1a.C[173])
#undef Sub15734 
#define Sub15734 CtoV2(var1a.C[174])
#undef Sub15756 
#define Sub15756 CtoV2(var1a.C[175])
#undef Sub15671 
#define Sub15671 CtoV2(var1a.C[176])
#undef Sub15810 
#define Sub15810 CtoV2(var1a.C[177])
#undef Sub15813 
#define Sub15813 CtoV2(var1a.C[178])
#undef Sub15723 
#define Sub15723 CtoV2(var1a.C[179])
#undef Sub15782 
#define Sub15782 CtoV2(var1a.C[180])
#undef Sub15788 
#define Sub15788 CtoV2(var1a.C[181])
#undef Sub15725 
#define Sub15725 CtoV2(var1a.C[182])
#undef Sub15753 
#define Sub15753 CtoV2(var1a.C[183])
#undef Sub15759 
#define Sub15759 CtoV2(var1a.C[184])
#undef Sub15492 
#define Sub15492 CtoV2(var1a.C[185])
#undef Sub15469 
#define Sub15469 CtoV2(var1a.C[186])
#undef Sub15496 
#define Sub15496 CtoV2(var1a.C[187])
#undef Sub15501 
#define Sub15501 CtoV2(var1a.C[188])
#undef Sub14963
#define Sub14963(i) CtoV2(var1a.C[188+i])
#undef Sub14964
#define Sub14964(i) CtoV2(var1a.C[191+i])
#undef Sub14965
#define Sub14965(i) CtoV2(var1a.C[194+i])
#undef Sub14988
#define Sub14988(i) CtoV2(var1a.C[197+i])
#undef Sub14973
#define Sub14973(i) CtoV2(var1a.C[200+i])
#undef Sub14921
#define Sub14921(i) CtoV2(var1a.C[203+i])
#undef Sub14922
#define Sub14922(i) CtoV2(var1a.C[206+i])
#undef Sub14925
#define Sub14925(i) CtoV2(var1a.C[209+i])
#undef Sub14924
#define Sub14924(i) CtoV2(var1a.C[212+i])
#undef Sub14969
#define Sub14969(i) CtoV2(var1a.C[215+i])
#undef Sub14984
#define Sub14984(i) CtoV2(var1a.C[218+i])
#undef Sub14986
#define Sub14986(i) CtoV2(var1a.C[221+i])
#undef Sub14971
#define Sub14971(i) CtoV2(var1a.C[224+i])
#undef Sub15397
#define Sub15397(i) CtoV2(var1a.C[227+i])
#undef Sub15417
#define Sub15417(i) CtoV2(var1a.C[230+i])
#undef Sub14970
#define Sub14970(i) CtoV2(var1a.C[233+i])
#undef Sub14972
#define Sub14972(i) CtoV2(var1a.C[236+i])
#undef Sub14981
#define Sub14981(i) CtoV2(var1a.C[239+i])
#undef Sub14985
#define Sub14985(i) CtoV2(var1a.C[242+i])
#undef Sub14987
#define Sub14987(i) CtoV2(var1a.C[245+i])
#undef Sub2580 
#define Sub2580 CtoV2(var1a.C[249])
#undef Sub2844 
#define Sub2844 CtoV2(var1a.C[250])
#undef Sub2965 
#define Sub2965 CtoV2(var1a.C[251])
#undef Sub14302 
#define Sub14302 CtoV2(var1a.C[252])
#undef Sub2698 
#define Sub2698 CtoV2(var1a.C[253])
#undef Sub5678 
#define Sub5678 CtoV2(var1a.C[254])
#undef Sub14285 
#define Sub14285 CtoV2(var1a.C[255])
#undef Sub14226 
#define Sub14226 CtoV2(var1a.C[256])
#undef Sub14263 
#define Sub14263 CtoV2(var1a.C[257])
#undef Sub10901 
#define Sub10901 CtoV2(var1a.C[258])
#undef Sub14262 
#define Sub14262 CtoV2(var1a.C[259])
#undef Sub2050 
#define Sub2050 CtoV2(var1a.C[260])
#undef Sub7199 
#define Sub7199 CtoV2(var1a.C[261])
#undef Sub6830 
#define Sub6830 CtoV2(var1a.C[262])
#undef Sub7276 
#define Sub7276 CtoV2(var1a.C[263])
#undef Sub9711 
#define Sub9711 CtoV2(var1a.C[264])
#undef Sub6842 
#define Sub6842 CtoV2(var1a.C[265])
#undef Sub9946 
#define Sub9946 CtoV2(var1a.C[266])
#undef Sub9942 
#define Sub9942 CtoV2(var1a.C[267])
#undef Sub14131 
#define Sub14131 CtoV2(var1a.C[268])
#undef Sub6826 
#define Sub6826 CtoV2(var1a.C[269])
#undef Sub9562 
#define Sub9562 CtoV2(var1a.C[270])
#undef Sub10998 
#define Sub10998 CtoV2(var1a.C[271])
#undef Sub10999 
#define Sub10999 CtoV2(var1a.C[272])
#undef Sub10774 
#define Sub10774 CtoV2(var1a.C[273])
#undef Sub9347 
#define Sub9347 CtoV2(var1a.C[274])
#undef Sub1174 
#define Sub1174 CtoV2(var1a.C[275])
#undef Sub1039 
#define Sub1039 CtoV2(var1a.C[276])
#undef Sub7211 
#define Sub7211 CtoV2(var1a.C[277])
#undef Sub2324 
#define Sub2324 CtoV2(var1a.C[278])
#undef Sub7903 
#define Sub7903 CtoV2(var1a.C[279])
#undef Sub7465 
#define Sub7465 CtoV2(var1a.C[280])
#undef Sub4562 
#define Sub4562 CtoV2(var1a.C[281])
#undef Sub6827 
#define Sub6827 CtoV2(var1a.C[282])
#undef Sub4335 
#define Sub4335 CtoV2(var1a.C[283])
#undef Sub5845 
#define Sub5845 CtoV2(var1a.C[284])
#undef Sub11500 
#define Sub11500 CtoV2(var1a.C[285])
#undef Sub10249 
#define Sub10249 CtoV2(var1a.C[286])
#undef Sub2321 
#define Sub2321 CtoV2(var1a.C[287])
#undef Sub4775 
#define Sub4775 CtoV2(var1a.C[288])
#undef Sub6449 
#define Sub6449 CtoV2(var1a.C[289])
#undef Sub4353 
#define Sub4353 CtoV2(var1a.C[290])
#undef Sub6843 
#define Sub6843 CtoV2(var1a.C[291])
#undef Sub10447 
#define Sub10447 CtoV2(var1a.C[292])
#undef Sub10119 
#define Sub10119 CtoV2(var1a.C[293])
#undef Sub13781 
#define Sub13781 CtoV2(var1a.C[294])
#undef Sub4160 
#define Sub4160 CtoV2(var1a.C[295])
#undef Sub11017 
#define Sub11017 CtoV2(var1a.C[296])
#undef Sub3342 
#define Sub3342 CtoV2(var1a.C[297])
#undef Sub1211 
#define Sub1211 CtoV2(var1a.C[298])
#undef Sub3503 
#define Sub3503 CtoV2(var1a.C[299])
#undef Sub10307 
#define Sub10307 CtoV2(var1a.C[300])
#undef Sub13626 
#define Sub13626 CtoV2(var1a.C[301])
#undef Sub13627 
#define Sub13627 CtoV2(var1a.C[302])
#undef Sub4148 
#define Sub4148 CtoV2(var1a.C[303])
#undef Sub13777 
#define Sub13777 CtoV2(var1a.C[304])
#undef Sub13656 
#define Sub13656 CtoV2(var1a.C[305])
#undef Sub13663 
#define Sub13663 CtoV2(var1a.C[306])
#undef Sub8662 
#define Sub8662 CtoV2(var1a.C[307])
#undef Sub4518 
#define Sub4518 CtoV2(var1a.C[308])
#undef Sub142 
#define Sub142 CtoV2(var1a.C[309])
#undef Sub15388 
#define Sub15388 CtoV2(var1a.C[310])
#undef Sub14875 
#define Sub14875 CtoV2(var1a.C[311])
#undef Sub14879 
#define Sub14879 CtoV2(var1a.C[312])
#undef Sub15341 
#define Sub15341 CtoV2(var1a.C[313])
#undef Sub15305 
#define Sub15305 CtoV2(var1a.C[314])
#undef Sub15279 
#define Sub15279 CtoV2(var1a.C[315])
#undef Sub15281 
#define Sub15281 CtoV2(var1a.C[316])
#undef Sub15661 
#define Sub15661 CtoV2(var1a.C[317])
#undef Sub15662 
#define Sub15662 CtoV2(var1a.C[318])
#undef Sub15399
#define Sub15399(i) CtoV2(var1a.C[318+i])
#undef Sub15412
#define Sub15412(i) CtoV2(var1a.C[321+i])
#undef Sub15400
#define Sub15400(i) CtoV2(var1a.C[324+i])
#undef Sub14958
#define Sub14958(i) CtoV2(var1a.C[327+i])
#undef Sub14980
#define Sub14980(i) CtoV2(var1a.C[330+i])
#undef Sub15413
#define Sub15413(i) CtoV2(var1a.C[333+i])
#undef Sub14960
#define Sub14960(i) CtoV2(var1a.C[336+i])
#undef Sub14961
#define Sub14961(i) CtoV2(var1a.C[339+i])
#undef Sub15401
#define Sub15401(i) CtoV2(var1a.C[342+i])
#undef Sub15414
#define Sub15414(i) CtoV2(var1a.C[345+i])
#undef Sub15402
#define Sub15402(i) CtoV2(var1a.C[348+i])
#undef Sub15415
#define Sub15415(i) CtoV2(var1a.C[351+i])
#undef Sub15403
#define Sub15403(i) CtoV2(var1a.C[354+i])
#undef Sub15416
#define Sub15416(i) CtoV2(var1a.C[357+i])
#undef Sub15409
#define Sub15409(i) CtoV2(var1a.C[360+i])
#undef Sub14966
#define Sub14966(i) CtoV2(var1a.C[363+i])
#undef Sub14979
#define Sub14979(i) CtoV2(var1a.C[366+i])
#undef Sub5764 
#define Sub5764 CtoV2(var1a.C[370])
#undef Sub3773 
#define Sub3773 CtoV2(var1a.C[371])
#undef Sub5756 
#define Sub5756 CtoV2(var1a.C[372])
#undef Sub6795 
#define Sub6795 CtoV2(var1a.C[373])
#undef Sub6515 
#define Sub6515 CtoV2(var1a.C[374])
#undef Sub1024 
#define Sub1024 CtoV2(var1a.C[375])
#undef Sub14069 
#define Sub14069 CtoV2(var1a.C[376])
#undef Sub10215 
#define Sub10215 CtoV2(var1a.C[377])
#undef Sub1384 
#define Sub1384 CtoV2(var1a.C[378])
#undef Sub13493 
#define Sub13493 CtoV2(var1a.C[379])
#undef Sub13714 
#define Sub13714 CtoV2(var1a.C[380])
#undef Sub2830 
#define Sub2830 CtoV2(var1a.C[381])
#undef Sub2703 
#define Sub2703 CtoV2(var1a.C[382])
#undef Sub538 
#define Sub538 CtoV2(var1a.C[383])
#undef Sub5507 
#define Sub5507 CtoV2(var1a.C[384])
#undef Sub1232 
#define Sub1232 CtoV2(var1a.C[385])
#undef Sub14382 
#define Sub14382 CtoV2(var1a.C[386])
#undef Sub2857 
#define Sub2857 CtoV2(var1a.C[387])
#undef Sub2863 
#define Sub2863 CtoV2(var1a.C[388])
#undef Sub14137 
#define Sub14137 CtoV2(var1a.C[389])
#undef Sub13801 
#define Sub13801 CtoV2(var1a.C[390])
#undef Sub7271 
#define Sub7271 CtoV2(var1a.C[391])
#undef Sub2045 
#define Sub2045 CtoV2(var1a.C[392])
#undef Sub326 
#define Sub326 CtoV2(var1a.C[393])
#undef Sub5839 
#define Sub5839 CtoV2(var1a.C[394])
#undef Sub402 
#define Sub402 CtoV2(var1a.C[395])
#undef Sub412 
#define Sub412 CtoV2(var1a.C[396])
#undef Sub1691 
#define Sub1691 CtoV2(var1a.C[397])
#undef Sub5599 
#define Sub5599 CtoV2(var1a.C[398])
#undef Sub287 
#define Sub287 CtoV2(var1a.C[399])
#undef Sub2200 
#define Sub2200 CtoV2(var1a.C[400])
#undef Sub997 
#define Sub997 CtoV2(var1a.C[401])
#undef Sub9514 
#define Sub9514 CtoV2(var1a.C[402])
#undef Sub7272 
#define Sub7272 CtoV2(var1a.C[403])
#undef Sub10325 
#define Sub10325 CtoV2(var1a.C[404])
#undef Sub1568 
#define Sub1568 CtoV2(var1a.C[405])
#undef Sub7273 
#define Sub7273 CtoV2(var1a.C[406])
#undef Sub6825 
#define Sub6825 CtoV2(var1a.C[407])
#undef Sub6824 
#define Sub6824 CtoV2(var1a.C[408])
#undef Sub8228 
#define Sub8228 CtoV2(var1a.C[409])
#undef Sub7902 
#define Sub7902 CtoV2(var1a.C[410])
#undef Sub4765 
#define Sub4765 CtoV2(var1a.C[411])
#undef Sub4243 
#define Sub4243 CtoV2(var1a.C[412])
#undef Sub9663 
#define Sub9663 CtoV2(var1a.C[413])
#undef Sub8857 
#define Sub8857 CtoV2(var1a.C[414])
#undef Sub9662 
#define Sub9662 CtoV2(var1a.C[415])
#undef Sub10397 
#define Sub10397 CtoV2(var1a.C[416])
#undef Sub9473 
#define Sub9473 CtoV2(var1a.C[417])
#undef Sub1209 
#define Sub1209 CtoV2(var1a.C[418])
#undef Sub9298 
#define Sub9298 CtoV2(var1a.C[419])
#undef Sub10653 
#define Sub10653 CtoV2(var1a.C[420])
#undef Sub10058 
#define Sub10058 CtoV2(var1a.C[421])
#undef Sub9158 
#define Sub9158 CtoV2(var1a.C[422])
#undef Sub9556 
#define Sub9556 CtoV2(var1a.C[423])
#undef Sub9558 
#define Sub9558 CtoV2(var1a.C[424])
#undef Sub8888 
#define Sub8888 CtoV2(var1a.C[425])
#undef Sub10306 
#define Sub10306 CtoV2(var1a.C[426])
#undef Sub1206 
#define Sub1206 CtoV2(var1a.C[427])
#undef Sub9010 
#define Sub9010 CtoV2(var1a.C[428])
#undef Sub10902 
#define Sub10902 CtoV2(var1a.C[429])
#undef Sub10027 
#define Sub10027 CtoV2(var1a.C[430])
#undef Sub9557 
#define Sub9557 CtoV2(var1a.C[431])
#undef Sub8766 
#define Sub8766 CtoV2(var1a.C[432])
#undef Sub4660 
#define Sub4660 CtoV2(var1a.C[433])
#undef Sub317 
#define Sub317 CtoV2(var1a.C[434])
#undef Sub924 
#define Sub924 CtoV2(var1a.C[435])
#undef Sub9561 
#define Sub9561 CtoV2(var1a.C[436])
#undef Sub571 
#define Sub571 CtoV2(var1a.C[437])
#undef Sub7577 
#define Sub7577 CtoV2(var1a.C[438])
#undef Sub1856 
#define Sub1856 CtoV2(var1a.C[439])
#undef Sub5630 
#define Sub5630 CtoV2(var1a.C[440])
#undef Sub8983 
#define Sub8983 CtoV2(var1a.C[441])
#undef Sub327 
#define Sub327 CtoV2(var1a.C[442])
#undef Sub413 
#define Sub413 CtoV2(var1a.C[443])
#undef Sub7952 
#define Sub7952 CtoV2(var1a.C[444])
#undef Sub1859 
#define Sub1859 CtoV2(var1a.C[445])
#undef Sub11504 
#define Sub11504 CtoV2(var1a.C[446])
#undef Sub1883 
#define Sub1883 CtoV2(var1a.C[447])
#undef Sub2348 
#define Sub2348 CtoV2(var1a.C[448])
#undef Sub1528 
#define Sub1528 CtoV2(var1a.C[449])
#undef Sub10632 
#define Sub10632 CtoV2(var1a.C[450])
#undef Sub10216 
#define Sub10216 CtoV2(var1a.C[451])
#undef Sub10656 
#define Sub10656 CtoV2(var1a.C[452])
#undef Sub4099 
#define Sub4099 CtoV2(var1a.C[453])
#undef Sub14558 
#define Sub14558 CtoV2(var1a.C[454])
#undef Sub3349 
#define Sub3349 CtoV2(var1a.C[455])
#undef Sub14047 
#define Sub14047 CtoV2(var1a.C[456])
#undef Sub2913 
#define Sub2913 CtoV2(var1a.C[457])
#undef Sub8526 
#define Sub8526 CtoV2(var1a.C[458])
#undef Sub14045 
#define Sub14045 CtoV2(var1a.C[459])
#undef Sub10716 
#define Sub10716 CtoV2(var1a.C[460])
#undef Sub3341 
#define Sub3341 CtoV2(var1a.C[461])
#undef Sub153 
#define Sub153 CtoV2(var1a.C[462])
#undef Sub8949 
#define Sub8949 CtoV2(var1a.C[463])
#undef Sub1385 
#define Sub1385 CtoV2(var1a.C[464])
#undef Sub536 
#define Sub536 CtoV2(var1a.C[465])
#undef Sub8834 
#define Sub8834 CtoV2(var1a.C[466])
#undef Sub13551 
#define Sub13551 CtoV2(var1a.C[467])
#undef Sub939 
#define Sub939 CtoV2(var1a.C[468])
#undef Sub2726 
#define Sub2726 CtoV2(var1a.C[469])
#undef Sub14318 
#define Sub14318 CtoV2(var1a.C[470])
#undef Sub13681 
#define Sub13681 CtoV2(var1a.C[471])
#undef Sub1051 
#define Sub1051 CtoV2(var1a.C[472])
#undef Sub3116 
#define Sub3116 CtoV2(var1a.C[473])
#undef Sub4410 
#define Sub4410 CtoV2(var1a.C[474])
#undef Sub11365 
#define Sub11365 CtoV2(var1a.C[475])
#undef Sub10843 
#define Sub10843 CtoV2(var1a.C[476])
#undef Sub8970 
#define Sub8970 CtoV2(var1a.C[477])
#undef Sub10466 
#define Sub10466 CtoV2(var1a.C[478])
#undef Sub10445 
#define Sub10445 CtoV2(var1a.C[479])
#undef Sub10649 
#define Sub10649 CtoV2(var1a.C[480])
#undef Sub10648 
#define Sub10648 CtoV2(var1a.C[481])
#undef Sub10964 
#define Sub10964 CtoV2(var1a.C[482])
#undef Sub10248 
#define Sub10248 CtoV2(var1a.C[483])
#undef Sub4244 
#define Sub4244 CtoV2(var1a.C[484])
#undef Sub8984 
#define Sub8984 CtoV2(var1a.C[485])
#undef Sub8087 
#define Sub8087 CtoV2(var1a.C[486])
#undef Sub12453 
#define Sub12453 CtoV2(var1a.C[487])
#undef Sub13650 
#define Sub13650 CtoV2(var1a.C[488])
#undef Sub633 
#define Sub633 CtoV2(var1a.C[489])
#undef Sub14407 
#define Sub14407 CtoV2(var1a.C[490])
#undef Sub653 
#define Sub653 CtoV2(var1a.C[491])
#undef Sub13780 
#define Sub13780 CtoV2(var1a.C[492])
#undef Sub13696 
#define Sub13696 CtoV2(var1a.C[493])
#undef Sub13678 
#define Sub13678 CtoV2(var1a.C[494])
#undef Sub8477 
#define Sub8477 CtoV2(var1a.C[495])
#undef Sub10191 
#define Sub10191 CtoV2(var1a.C[496])
#undef Sub9870 
#define Sub9870 CtoV2(var1a.C[497])
#undef Sub13409 
#define Sub13409 CtoV2(var1a.C[498])
#undef Sub189 
#define Sub189 CtoV2(var1a.C[499])
#undef Sub540 
#define Sub540 CtoV2(var1a.C[500])
#undef Sub14869 
#define Sub14869 CtoV2(var1a.C[501])
#undef Sub15711 
#define Sub15711 CtoV2(var1a.C[502])
#undef Sub15777 
#define Sub15777 CtoV2(var1a.C[503])
#undef Sub15746 
#define Sub15746 CtoV2(var1a.C[504])
#undef Sub15783 
#define Sub15783 CtoV2(var1a.C[505])
#undef Sub15754 
#define Sub15754 CtoV2(var1a.C[506])
#undef Sub5441 
#define Sub5441 CtoV2(var1a.C[507])
#undef Sub4123 
#define Sub4123 CtoV2(var1a.C[508])
#undef Sub13382 
#define Sub13382 CtoV2(var1a.C[509])
#undef Sub8541 
#define Sub8541 CtoV2(var1a.C[510])
#undef Sub2071 
#define Sub2071 CtoV2(var1a.C[511])
#undef Sub6823 
#define Sub6823 CtoV2(var1a.C[512])
#undef Sub2513 
#define Sub2513 CtoV2(var1a.C[513])
#undef Sub7268 
#define Sub7268 CtoV2(var1a.C[514])
#undef Sub2285 
#define Sub2285 CtoV2(var1a.C[515])
#undef Sub5603 
#define Sub5603 CtoV2(var1a.C[516])
#undef Sub5602 
#define Sub5602 CtoV2(var1a.C[517])
#undef Sub8543 
#define Sub8543 CtoV2(var1a.C[518])
#undef Sub6740 
#define Sub6740 CtoV2(var1a.C[519])
#undef Sub7210 
#define Sub7210 CtoV2(var1a.C[520])
#undef Sub2785 
#define Sub2785 CtoV2(var1a.C[521])
#undef Sub12782 
#define Sub12782 CtoV2(var1a.C[522])
#undef Sub13651 
#define Sub13651 CtoV2(var1a.C[523])
#undef Sub11334 
#define Sub11334 CtoV2(var1a.C[524])
#undef Sub11351 
#define Sub11351 CtoV2(var1a.C[525])
#undef Sub8347 
#define Sub8347 CtoV2(var1a.C[526])
#undef Sub11497 
#define Sub11497 CtoV2(var1a.C[527])
#undef Sub10994 
#define Sub10994 CtoV2(var1a.C[528])
#undef Sub14157 
#define Sub14157 CtoV2(var1a.C[529])
#undef Sub13509 
#define Sub13509 CtoV2(var1a.C[530])
#undef Sub4135 
#define Sub4135 CtoV2(var1a.C[531])
#undef Sub2988 
#define Sub2988 CtoV2(var1a.C[532])
#undef Sub14228 
#define Sub14228 CtoV2(var1a.C[533])
#undef Sub14227 
#define Sub14227 CtoV2(var1a.C[534])
#undef Sub3094 
#define Sub3094 CtoV2(var1a.C[535])
#undef Sub10296 
#define Sub10296 CtoV2(var1a.C[536])
#undef Sub4716 
#define Sub4716 CtoV2(var1a.C[537])
#undef Sub10045 
#define Sub10045 CtoV2(var1a.C[538])
#undef Sub6741 
#define Sub6741 CtoV2(var1a.C[539])
#undef Sub4329 
#define Sub4329 CtoV2(var1a.C[540])
#undef Sub258 
#define Sub258 CtoV2(var1a.C[541])
#undef Sub11725 
#define Sub11725 CtoV2(var1a.C[542])
#undef Sub13542 
#define Sub13542 CtoV2(var1a.C[543])
#undef Sub7821 
#define Sub7821 CtoV2(var1a.C[544])
#undef Sub13779 
#define Sub13779 CtoV2(var1a.C[545])
#undef Sub3498 
#define Sub3498 CtoV2(var1a.C[546])
#undef Sub4157 
#define Sub4157 CtoV2(var1a.C[547])
#undef Sub8975 
#define Sub8975 CtoV2(var1a.C[548])
#undef Sub12301 
#define Sub12301 CtoV2(var1a.C[549])
#undef Sub12513 
#define Sub12513 CtoV2(var1a.C[550])
#undef Sub2331 
#define Sub2331 CtoV2(var1a.C[551])
#undef Sub11358 
#define Sub11358 CtoV2(var1a.C[552])
#undef Sub8596 
#define Sub8596 CtoV2(var1a.C[553])
#undef Sub13778 
#define Sub13778 CtoV2(var1a.C[554])
#undef Sub3151 
#define Sub3151 CtoV2(var1a.C[555])
#undef Sub14139 
#define Sub14139 CtoV2(var1a.C[556])
#undef Sub13671 
#define Sub13671 CtoV2(var1a.C[557])
#undef Sub15660 
#define Sub15660 CtoV2(var1a.C[558])
#undef Sub9485 
#define Sub9485 CtoV2(var1a.C[559])
#undef Sub13207 
#define Sub13207 CtoV2(var1a.C[560])
#undef Sub2288 
#define Sub2288 CtoV2(var1a.C[561])
#undef Sub9075 
#define Sub9075 CtoV2(var1a.C[562])
#undef Sub8838 
#define Sub8838 CtoV2(var1a.C[563])
#undef Sub2320 
#define Sub2320 CtoV2(var1a.C[564])
#undef Sub2330 
#define Sub2330 CtoV2(var1a.C[565])
#undef Sub13680 
#define Sub13680 CtoV2(var1a.C[566])
#undef Sub10995 
#define Sub10995 CtoV2(var1a.C[567])
#undef Sub10114 
#define Sub10114 CtoV2(var1a.C[568])
#undef Sub4399 
#define Sub4399 CtoV2(var1a.C[569])
#undef Sub4320 
#define Sub4320 CtoV2(var1a.C[570])
#undef Sub384 
#define Sub384 CtoV2(var1a.C[571])
#undef Sub10044 
#define Sub10044 CtoV2(var1a.C[572])
#undef Sub12024 
#define Sub12024 CtoV2(var1a.C[573])
#undef Sub4834 
#define Sub4834 CtoV2(var1a.C[574])
#undef Sub151 
#define Sub151 CtoV2(var1a.C[575])
#undef Sub7911 
#define Sub7911 CtoV2(var1a.C[576])
#undef Sub9806 
#define Sub9806 CtoV2(var1a.C[577])
#undef Sub10057 
#define Sub10057 CtoV2(var1a.C[578])
#undef Sub5452 
#define Sub5452 CtoV2(var1a.C[579])
#undef Sub2087 
#define Sub2087 CtoV2(var1a.C[580])
#undef Sub10305 
#define Sub10305 CtoV2(var1a.C[581])
#undef Sub160 
#define Sub160 CtoV2(var1a.C[582])
#undef Sub627 
#define Sub627 CtoV2(var1a.C[583])
#undef Sub14184 
#define Sub14184 CtoV2(var1a.C[584])
#undef Sub7354 
#define Sub7354 CtoV2(var1a.C[585])
#undef Sub11748 
#define Sub11748 CtoV2(var1a.C[586])
#undef Sub539 
#define Sub539 CtoV2(var1a.C[587])
#undef Sub178 
#define Sub178 CtoV2(var1a.C[588])
#undef Sub202 
#define Sub202 CtoV2(var1a.C[589])
#undef Sub549 
#define Sub549 CtoV2(var1a.C[590])
#undef Sub3152 
#define Sub3152 CtoV2(var1a.C[591])
#undef Sub13717 
#define Sub13717 CtoV2(var1a.C[592])
#undef Sub14957
#define Sub14957(i) CtoV2(var1a.C[592+i])
#undef Sub4324 
#define Sub4324 CtoV2(var1a.C[596])
#undef Sub12300 
#define Sub12300 CtoV2(var1a.C[597])
#undef Sub4658 
#define Sub4658 CtoV2(var1a.C[598])
#undef Sub9072 
#define Sub9072 CtoV2(var1a.C[599])
#undef Sub9836 
#define Sub9836 CtoV2(var1a.C[600])
#undef Sub2190 
#define Sub2190 CtoV2(var1a.C[601])
#undef Sub10095 
#define Sub10095 CtoV2(var1a.C[602])
#undef Sub8529 
#define Sub8529 CtoV2(var1a.C[603])
#undef Sub3552 
#define Sub3552 CtoV2(var1a.C[604])
#undef Sub7895 
#define Sub7895 CtoV2(var1a.C[605])
#undef Sub158 
#define Sub158 CtoV2(var1a.C[606])
#undef Sub139 
#define Sub139 CtoV2(var1a.C[607])
#undef Sub7543 
#define Sub7543 CtoV2(var1a.C[608])
#undef Sub2082 
#define Sub2082 CtoV2(var1a.C[609])
#undef Sub9369 
#define Sub9369 CtoV2(var1a.C[610])
#undef Sub4349 
#define Sub4349 CtoV2(var1a.C[611])
#undef Sub644 
#define Sub644 CtoV2(var1a.C[612])
#undef Sub11536 
#define Sub11536 CtoV2(var1a.C[613])
#undef Sub4525 
#define Sub4525 CtoV2(var1a.C[614])
#undef Sub2264 
#define Sub2264 CtoV2(var1a.C[615])
#undef Sub2267 
#define Sub2267 CtoV2(var1a.C[616])
#undef Sub2407 
#define Sub2407 CtoV2(var1a.C[617])
#undef Sub12620 
#define Sub12620 CtoV2(var1a.C[618])
#undef Sub14974
#define Sub14974(i) CtoV2(var1a.C[618+i])
#undef Sub14989
#define Sub14989(i) CtoV2(var1a.C[621+i])
#undef Sub620 
#define Sub620 CtoV2(var1a.C[625])
#undef Sub628 
#define Sub628 CtoV2(var1a.C[626])
#undef Sub2579 
#define Sub2579 CtoV2(var1a.C[627])
#undef pave1
#define pave1(i) CtoV2(var1a.C[627+i])
#undef pave2
#define pave2(i) CtoV2(var1a.C[627+i+Ndd])
#undef pave3
#define pave3(i) CtoV2(var1a.C[627+i+2*Ndd])
#undef pave4
#define pave4(i,j) CtoV2(var1a.C[627+i-Nbb+j*Nbb+3*Ndd])
#undef pave5
#define pave5(i,j) CtoV2(var1a.C[627+i+2*Nbb+j*Nbb+3*Ndd])
#undef pave9
#define pave9(i) CtoV2(var1a.C[627+i+6*Nbb+3*Ndd])
#undef pave10
#define pave10(i) CtoV2(var1a.C[627+i+7*Nbb+3*Ndd])
#undef pave11
#define pave11(i) CtoV2(var1a.C[627+i+8*Nbb+3*Ndd])
#undef pave21
#define pave21(i) CtoV2(var1a.C[627+i+9*Nbb+3*Ndd])
#undef pave22
#define pave22(i) CtoV2(var1a.C[627+i+10*Nbb+3*Ndd])
#undef pave44
#define pave44(i) CtoV2(var1a.C[627+i+11*Nbb+3*Ndd])
#undef pave52
#define pave52(i) CtoV2(var1a.C[627+i+11*Nbb+Ncc+3*Ndd])
#undef pave53
#define pave53(i) CtoV2(var1a.C[627+i+11*Nbb+2*Ncc+3*Ndd])
#undef pave54
#define pave54(i) CtoV2(var1a.C[627+i+11*Nbb+3*Ncc+3*Ndd])
#undef pave55
#define pave55(i) CtoV2(var1a.C[627+i+11*Nbb+4*Ncc+3*Ndd])
#undef pave56
#define pave56(i) CtoV2(var1a.C[627+i+11*Nbb+5*Ncc+3*Ndd])
#undef pave57
#define pave57(i) CtoV2(var1a.C[627+i+11*Nbb+6*Ncc+3*Ndd])
#undef pave64
#define pave64(i) CtoV2(var1a.C[627+i+11*Nbb+7*Ncc+3*Ndd])
#undef pave70
#define pave70(i) CtoV2(var1a.C[627+i+11*Nbb+8*Ncc+3*Ndd])
#undef pave71
#define pave71(i) CtoV2(var1a.C[627+i+11*Nbb+9*Ncc+3*Ndd])
#undef pave79
#define pave79(i) CtoV2(var1a.C[627+i+11*Nbb+10*Ncc+3*Ndd])
#undef pave80
#define pave80(i) CtoV2(var1a.C[627+i+11*Nbb+11*Ncc+3*Ndd])
#undef pave81
#define pave81(i) CtoV2(var1a.C[627+i+11*Nbb+12*Ncc+3*Ndd])
#undef pave83
#define pave83(i) CtoV2(var1a.C[627+i+11*Nbb+13*Ncc+3*Ndd])
#undef pave85
#define pave85(i) CtoV2(var1a.C[627+i+11*Nbb+14*Ncc+3*Ndd])
#undef pave86
#define pave86(i) CtoV2(var1a.C[627+i+11*Nbb+15*Ncc+3*Ndd])
#undef pave90
#define pave90(i) CtoV2(var1a.C[627+i+11*Nbb+16*Ncc+3*Ndd])
#undef pave91
#define pave91(i) CtoV2(var1a.C[627+i+11*Nbb+17*Ncc+3*Ndd])
#undef pave93
#define pave93(i) CtoV2(var1a.C[627+i+11*Nbb+18*Ncc+3*Ndd])
#undef pave96
#define pave96(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+3*Ndd])
#undef pave97
#define pave97(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+4*Ndd])
#undef pave98
#define pave98(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+5*Ndd])
#undef pave100
#define pave100(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+6*Ndd])
#undef pave101
#define pave101(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+7*Ndd])
#undef pave102
#define pave102(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+8*Ndd])
#undef pave103
#define pave103(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+9*Ndd])
#undef pave105
#define pave105(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+10*Ndd])
#undef pave106
#define pave106(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+11*Ndd])
#undef pave107
#define pave107(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+12*Ndd])
#undef pave108
#define pave108(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+13*Ndd])
#undef pave109
#define pave109(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+14*Ndd])
#undef pave110
#define pave110(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+15*Ndd])
#undef pave111
#define pave111(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+16*Ndd])
#undef pave112
#define pave112(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+17*Ndd])
#undef pave113
#define pave113(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+18*Ndd])
#undef pave114
#define pave114(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+19*Ndd])
#undef pave115
#define pave115(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+20*Ndd])
#undef pave116
#define pave116(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+21*Ndd])
#undef pave119
#define pave119(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+22*Ndd])
#undef pave120
#define pave120(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+23*Ndd])
#undef pave121
#define pave121(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+24*Ndd])
#undef pave122
#define pave122(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+25*Ndd])
#undef pave123
#define pave123(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+26*Ndd])
#undef pave124
#define pave124(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+27*Ndd])
#undef pave125
#define pave125(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+28*Ndd])
#undef pave126
#define pave126(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+29*Ndd])
#undef pave127
#define pave127(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+30*Ndd])
#undef pave128
#define pave128(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+31*Ndd])
#undef pave129
#define pave129(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+32*Ndd])
#undef pave130
#define pave130(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+33*Ndd])
#undef pave131
#define pave131(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+34*Ndd])
#undef pave132
#define pave132(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+35*Ndd])
#undef pave133
#define pave133(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+36*Ndd])
#undef pave135
#define pave135(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+37*Ndd])
#undef pave136
#define pave136(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+38*Ndd])
#undef pave137
#define pave137(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+39*Ndd])
#undef pave138
#define pave138(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+40*Ndd])
#undef pave140
#define pave140(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+41*Ndd])
#undef pave141
#define pave141(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+42*Ndd])
#undef pave142
#define pave142(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+43*Ndd])
#undef pave143
#define pave143(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+44*Ndd])
#undef pave144
#define pave144(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+45*Ndd])
#undef pave145
#define pave145(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+46*Ndd])
#undef pave146
#define pave146(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+47*Ndd])
#undef pave147
#define pave147(i) CtoV2(var1a.C[627+i+11*Nbb+19*Ncc+48*Ndd])
#undef pave154
#define pave154(i,j) CtoV2(var1a.C[627+i+10*Nbb+j*Nbb+19*Ncc+49*Ndd])
#undef pave155
#define pave155(i,j) CtoV2(var1a.C[627+i+14*Nbb+18*Ncc+j*Ncc+49*Ndd])
#undef pave156
#define pave156(i,j) CtoV2(var1a.C[627+i+14*Nbb+21*Ncc+j*Ncc+49*Ndd])
#undef pave157
#define pave157(i,j) CtoV2(var1a.C[627+i+14*Nbb+24*Ncc+j*Ncc+49*Ndd])
#undef pave160
#define pave160(i) CtoV2(var1a.C[627+i+14*Nbb+28*Ncc+49*Ndd])
#undef pave162
#define pave162(i) CtoV2(var1a.C[627+i+14*Nbb+29*Ncc+49*Ndd])
#undef pave163
#define pave163(i) CtoV2(var1a.C[627+i+14*Nbb+30*Ncc+49*Ndd])
#undef pave164
#define pave164(i) CtoV2(var1a.C[627+i+14*Nbb+31*Ncc+49*Ndd])
#undef pave167
#define pave167(i) CtoV2(var1a.C[627+i+14*Nbb+31*Ncc+50*Ndd])
#undef pave168
#define pave168(i) CtoV2(var1a.C[627+i+15*Nbb+31*Ncc+50*Ndd])
#undef pave169
#define pave169(i) CtoV2(var1a.C[627+i+15*Nbb+32*Ncc+50*Ndd])
#undef pave170
#define pave170(i) CtoV2(var1a.C[627+i+15*Nbb+32*Ncc+51*Ndd])
#undef pave171
#define pave171(i) CtoV2(var1a.C[627+i+15*Nbb+32*Ncc+52*Ndd])
#undef pave172
#define pave172(i) CtoV2(var1a.C[627+i+15*Nbb+33*Ncc+52*Ndd])
#undef pave173
#define pave173(i) CtoV2(var1a.C[627+i+15*Nbb+34*Ncc+52*Ndd])
#undef pave174
#define pave174(i) CtoV2(var1a.C[627+i+15*Nbb+35*Ncc+52*Ndd])
#undef pave178
#define pave178(i) CtoV2(var1a.C[627+i+15*Nbb+36*Ncc+52*Ndd])
#undef pave179
#define pave179(i) CtoV2(var1a.C[627+i+15*Nbb+37*Ncc+52*Ndd])
#undef pave181
#define pave181(i) CtoV2(var1a.C[627+i+15*Nbb+38*Ncc+52*Ndd])
#undef pave182
#define pave182(i) CtoV2(var1a.C[627+i+15*Nbb+39*Ncc+52*Ndd])
#undef pave183
#define pave183(i) CtoV2(var1a.C[627+i+15*Nbb+39*Ncc+53*Ndd])

#undef Divergence
#define Divergence DtoV2(renorm_.Divergence)
#undef mudim
#define mudim DtoV2(renorm_.mudim)
#undef lambda
#define lambda DtoV2(renorm_.lambda)
#undef muscale
#define muscale DtoV2(renorm_.muscale)
#undef epscoeff
#define epscoeff DtoV2((double)renorm_.epscoeff)
#undef Finite
#define Finite DtoV2(1.0)

#define dMWsq1 renconst.dMWsq1
#undef dMZsq1
#define dMZsq1 CtoV2(renconst.dMZsq1)
#undef dSW1
#define dSW1 CtoV2(renconst.dSW1)
#undef dZAA1
#define dZAA1 CtoV2(renconst.dZAA1)
#undef dZAZ1
#define dZAZ1 CtoV2(renconst.dZAZ1)
#undef dZe1
#define dZe1 CtoV2(renconst.dZe1)
#undef dZZA1
#define dZZA1 CtoV2(renconst.dZZA1)
#undef dZZZ1
#define dZZZ1 CtoV2(renconst.dZZZ1)
#undef dZfL1
#define dZfL1(i,j,k) CtoV2(renconst.dZfL1[k-1][j-1][i-1])
#undef dZfR1
#define dZfR1(i,j,k) CtoV2(renconst.dZfR1[k-1][j-1][i-1])

#undef Power
#define Power(x, n) \
  (sizeof(x) == sizeof(ComplexType) ? DtoV2(RPower(x, n)) : DtoV2(RPower(x, n)))
/*(sizeof(x) == sizeof(__m256d) ? (V2CPower(x, n) : DtoV2(RPower(x, n))))*/
 // (sizeof(x) == sizeof(ComplexType) ? DtoV2(RPower(x, n)) : (V2CPower(x, n)) )


#undef Conjugate
#define Conjugate Conjugate_AVX

__m256d Conjugate_AVX(__m256d a){
	__m256d aa;
	aa =_mm256_setr_pd(1,-1,1,-1);
	return a*aa;
}	
static inline __m256d V2CPower(__m256d x, int n) {
	/*ComplexType result1 = 1;*/
	/*ComplexType result2 = 1;*/
  v2complex tmp,tmp2;
  tmp.v2 = x;
  /*tmp.v2 = x;*/
  tmp2.c[0] = 1;
  tmp2.c[1] = 1;
  while( n ) {
    if( n & 1 ) {
	    tmp2 = cmult_AVX(tmp2,tmp);
    }
    n >>= 1;
    tmp = cmult_AVX(tmp,tmp);
  }
  return tmp2.v2;
}

/*#define Power(x, n) ({ \*/
/*typeof(x) _x = x, _r = 1; \*/
/*typeof(n) _n = n; \*/
/*while( _n ) { \*/
/*if( _n & 1 ) _r *= _x; \*/
/*_n >>= 1; \*/
/*_x *= _x; \*/
/*} \*/
/*_r; \*/
/*})*/

#undef Mf2
#define Mf2(t,g) DtoV2(smpara_.Mf2[g-1][t-1])
