//#define CHECK

#if 0
* SquaredME.c
* assembly of squared matrix element
* generated by FormCalc 8.0 on 6-Mar-2013 10:48
#endif

#include <math.h>
#include "vars.h"

#if NOUNDERSCORE
#define squaredme_ squaredme
#define squaredmehel_ squaredmehel
#endif

struct formfactors formfactors = {
  .MatSUN[0 ... 0][0 ... 0] = NAN };

/**********************************************************************/

static RealType sumup(ComplexType CCloop[1],
  ComplexType CCtree[1]) {

#include "vars.h"

  ComplexType s = 0;

  ComplexType m = 0;
  m += CCloop[1-1]*MatSUN(1,1);
  s += Re(Conjugate(CCtree[1-1])*m);
  return s;
}

/**********************************************************************/

void squaredmehel_(RealType *result, int *flags) {

#include "vars.h"

// BEGIN ABBR_HEL
  abbr0h();
  TEST(flags, BIT_LOOP)
  abbr1h();
  ENDTEST(flags, BIT_LOOP)
// END ABBR_HEL

// BEGIN FF_INI
  Ctree(1) = 0;

  Cloop(1) = 0;
// END FF_INI

// BEGIN FF_TREE
  born();

  result[0] += sumup(Ctree, Ctree);
// END FF_TREE

  TEST(flags, BIT_LOOP)
// BEGIN FF_LOOP
  self();
  vert();
  box();

  LOOP(Gen5, 1,3,1)
  self_Gen5();
  ENDLOOP(Gen5)

  result[1] += 2*sumup(Cloop, Ctree);
// END FF_LOOP
  ENDTEST(flags, BIT_LOOP)
}

/**********************************************************************/

void squaredme_(RealType *result, long long int *helicities, int *flags) {

#include "vars.h"

// BEGIN VARDECL
  int Hel1, Hel2, Hel3, Hel4;
// END VARDECL

  PREP(seq,seq_end, vec,vec_end, varangle,varangle_end, vars,vars_end);

// BEGIN INVARIANTS
  S = SInvariant(k(1),k(2));
  T = TInvariant(k(1),k(3));
  U = TInvariant(k(2),k(3));
// END INVARIANTS

  TEST(flags, BIT_RESET)
// BEGIN ABBR_S
  ++seq(1);
  INI_S(seq);
  abbr0s();
  TEST(flags, BIT_LOOP)
  abbr1s();
  ENDTEST(flags, BIT_LOOP)
// END ABBR_S
  ENDTEST(flags, BIT_RESET)

// BEGIN ABBR_ANGLE
  ++seq(2);
  INI_ANGLE(seq);
  TEST(flags, BIT_LOOP)
  abbr1a();
  ENDTEST(flags, BIT_LOOP)
// END ABBR_ANGLE

// BEGIN RES_INI
  result[0] = 0;
  result[1] = 0;
// END RES_INI

// BEGIN HEL_LOOPS
  LOOP_HEL(Hel(1))
  TEST(helicities, BIT_HEL(1))

  LOOP_HEL(Hel(2))
  TEST(helicities, BIT_HEL(2))

  LOOP_HEL(Hel(3))
  TEST(helicities, BIT_HEL(3))

  LOOP_HEL(Hel(4))
  TEST(helicities, BIT_HEL(4))

  EXEC(squaredmehel_, result, flags);

  ENDTEST(helicities, BIT_HEL(4))
  ENDLOOP_HEL(Hel4)

  ENDTEST(helicities, BIT_HEL(3))
  ENDLOOP_HEL(Hel3)

  ENDTEST(helicities, BIT_HEL(2))
  ENDLOOP_HEL(Hel2)

  ENDTEST(helicities, BIT_HEL(1))
  ENDLOOP_HEL(Hel1)
// END HEL_LOOPS

  SYNC(result);
  DEINI(seq);

#ifdef CHECK
  printf("S = %g\n", S);
  printf("T = %g\n", T);
  printf("U = %g\n", U);
  printf("tree = (%g,%g)\n",  Re(result[0]), Im(result[0]));
  printf("loop = (%g,%g)\n",  Re(result[1]), Im(result[1]));
  exit(1);
#endif

// END SQUAREDME
}
