#if 0
* abbr1a.c
* abbreviations for {-F[2, {1}], F[2, {1}]} -> {-F[3, {3, Col3}], F[3, {3, Col4}], V[1]}
* generated by FormCalc 8.2 on 11-Apr-2013 14:53
#endif

#include "vars.h"
#include "inline.h"


void abbr1a() {

#include "vars.h"

#include "inline.h"

  Opt8 = -S - 2*S34 - T - 2*T14 - 2*T24 - U;

  Opt9 = -T - T14 + T24 + U;

  Opt10 = -S - 2*S34 - 2*T - T14 - T24 - 2*U;

  Opt16 = -T - T14 - T24 - U;

  Opt18 = -S - 2*S34 - 2*T - T14 - T24 - 2*U;

  Sub2077 = (-3 + 4*SW2)*(S34*Sub797) + 3*MT2*Sub839;

  Sub2835 = 1/CW2*(Sub798*(-S34 + T) + 9*CW2*MT2*(S34 + T));

  Sub294 = (-MT2 + 2*MW2)*S + 2*MW2*(T14 + T24) + 
     MB2*(S + T14 + T24);

  Sub6602 = 8*MT2 - 3*(S + S34 + T14 + T24);

  Sub10124 = 1/SW2*(MT2*(-3 + 4*SW2) + 3*(S + U) - 4*SW2*U);

  Sub10125 = -3*S + SW2*(4*MT2 - 4*U);

  Sub2039 = 1/MW2*(MW2*(-4*MT2 + 2*S34) + MB2*(T + U));

  Sub1773 = 1/CW2*(Sub818*(2*MT2 - T - U) + 3*CW2*MT2*(T + U))
   ;

  Sub984 = Sub850 + MB2*
      (MT2*(-6 + 8*SW2) + (3 - 4*SW2)*(T + U)) + 
     MW2*(MT2*(12 - 16*SW2) + (-6 + 8*SW2)*(T + U));

  Sub7575 = Sub3926 + MT2*(6 - 4*SW2) + (-3 + 2*SW2)*(T + U);

  Sub5515 = 4*(T14 + T24) + 3*(S + T + U);

  Sub10047 = MT2*(-9 + 4*SW2) + 3*(T24 + U);

  Sub14362 = -2*(MT2 + S34 + T + T14) + 3*(S + T24 + U);

  Sub8764 = 4*T + 3*(S34 + T14 + T24 + U);

  Sub1390 = 4*MT2 - 3*(S + S34 + T + T14 + T24 + U);

  Sub10266 = 11*MT2 - 3*(S + S34 + T + T14 + T24 + U);

  Sub5618 = 14*MT2 - 3*(S + S34 + T + T14 + T24 + U);

  Sub8062 = 17*MT2 - 3*(S + S34 + T + T14 + T24 + U);

  Sub4945 = 20*MT2 - 3*(S + S34 + T + T14 + T24 + U);

  Sub4951 = 3*S + 2*(S34 + 2*(T + T14 + T24 + U));

  Sub2634 = 1/CW2*(S - S34 + CW2*(S - S34));

  Sub3128 = 4*MT2 - T - 2*(S34 + T14);

  Sub3106 = 10*MT2 - 3*S34 - 5*(T + T14);

  Sub14420 = 6*MT2 - 4*S - 3*(T + T14);

  Sub14419 = 6*MT2 - 2*S - 3*(T + T14);

  Sub2558 = 6*MT2 - 2*S34 - 3*(T + T14);

  Sub6675 = 4*MT2 - S34 - 3*(T + T14);

  Sub14392 = 4*MT2 - 3*S34 - 2*(T + T14);

  Sub7909 = 3*MT2 - S34 - 2*(T + T14);

  Sub14345 = 4*MT2 - S34 - 2*(T + T14);

  Sub4101 = 8*MT2 - S34 - 4*(S + T + T14);

  Sub10089 = 4*MT2 - S34 - 2*(S + T + T14);

  Sub4102 = 4*MT2 + S34 - 2*(S + T + T14);

  Sub13217 = 20*MT2 - 3*S34 - 5*(T14 + T24);

  Sub1416 = 4*MT2 - 4*S - 3*(T14 + T24);

  Sub6419 = 3*S + 2*S34 + 4*(T14 + T24);

  Sub12012 = 10*MT2 - S - 4*(S34 + T14 + T24);

  Sub10361 = 6*MT2 - 2*S - 3*(S34 + T14 + T24);

  Sub4536 = 3*MT2 - S - 2*(S34 + T14 + T24);

  Sub12008 = 10*MT2 + S - 2*(S34 + T14 + T24);

  Sub5772 = 10*MT2 + S - 4*S34 - 2*(T14 + T24);

  Sub9356 = 4*MT2 - 3*(S + T) - 2*U;

  Sub10133 = 6*MT2 - 2*(S + S34 + T + T14) - U;

  Sub10134 = 6*MT2 - 2*(S + T + T14 + T24) - U;

  Sub10334 = 9*MT2 - 3*(S + S34 + T + T14 + T24) - U;

  Sub9863 = 2*(T + T14) + 4*T24 + 3*U;

  Sub8825 = 2*T + 3*(S34 + T24) + 4*U;

  Sub8819 = 2*(S + T14) + 3*(S34 + T24) + 4*U;

  Sub1194 = 3*MT2 - T24 - 2*(S34 + U);

  Sub1049 = 4*MT2 - T24 - 2*(S34 + U);

  Sub6431 = 10*MT2 - 3*S34 - 5*(T + U);

  Sub2498 = 4*MT2 - 4*S - 3*(T + U);

  Sub6784 = 6*MT2 - 2*S - 3*(T + U);

  Sub6074 = 8*MT2 - 2*S34 - 3*(T + U);

  Sub4368 = 2*MT2 - 3*S - 2*(T + U);

  Sub5763 = 2*MT2 - S - 2*(T + U);

  Sub4257 = 4*MT2 - S - 2*(T + U);

  Sub4983 = 6*MT2 - S34 - 2*(T + U);

  Sub10152 = 4*S + 3*(S34 + T14 + T24) - 2*(T + U);

  Sub10554 = 4*MT2 - S34 - 2*(S + T + U);

  Sub2286 = 8*MT2 - 3*(S34 + T14 + T24) - 2*(S + T + U);

  Sub4250 = 10*MT2 - 2*(S + T14 + T24) - 3*(S34 + T + U);

  Sub9852 = 9*MT2 - 3*(S34 + T24) - 2*(S + T + T14 + U);

  Sub9484 = 8*MT2 - T24 - 2*(S + S34 + T + T14 + U);

  Sub13516 = 10*MT2 - 3*S - 5*(T24 + U);

  Sub4098 = 6*MT2 - 2*S - 3*(T24 + U);

  Sub10182 = 7*MT2 - 2*S34 - 3*(T24 + U);

  Sub13563 = 4*MT2 - S - 2*(T24 + U);

  Sub3411 = 3*MT2 - 3*S34 - 2*(T24 + U);

  Sub1235 = 4*MT2 - 3*S34 - 2*(T24 + U);

  Sub3478 = 4*MT2 - S34 - 2*(T24 + U);

  Sub9809 = 5*MT2 - S34 - 2*(T24 + U);

  Sub13512 = 2*S34 + 3*(T + T14) - 2*(MT2 + T24 + U);

  Sub13361 = 4*S34 + 2*(MT2 + T + T14) - 3*(S + T24 + U);

  Sub8763 = 13*MT2 - 4*T - 3*(S + S34 + T14 + T24 + U);

  Sub142 = 20*MT2 - S - 5*(S34 + T + T14 + T24 + U);

  Sub7846 = 10*MT2 - 4*S - 3*(S34 + T + T14 + T24 + U);

  Sub6289 = 10*MT2 - 4*S34 - 3*T - 6*T14;

  Sub6466 = 5*MT2 - 2*S34 - T - 4*T14;

  Sub3806 = 4*MT2 - S34 + T - 3*T14;

  Sub6518 = 2*MT2 - S34 - T - 2*T14;

  Sub5925 = 3*MT2 - S34 - T - 2*T14;

  Sub1033 = 2*MT2 - S34 - 2*T - T14;

  Sub14309 = 2*MT2 - 2*S - T - T14;

  Sub9761 = MT2 - S - T - T14;

  Sub1451 = 3*MT2 - S - T - T14;

  Sub14313 = 2*MT2 + S - T - T14;

  Sub13391 = 2*MT2 - 4*S34 - T - T14;

  Sub2911 = 2*MT2 - 3*S34 - T - T14;

  Sub2561 = 2*MT2 - 2*S34 - T - T14;

  Sub387 = 2*MT2 - S34 - T - T14;

  Sub7003 = 3*MT2 - S34 - T - T14;

  Sub1253 = 2*MT2 + S34 - T - T14;

  Sub2927 = 2*MT2 - S34 + T - T14;

  Sub3157 = 2*MT2 - S34 + 3*T - T14;

  Sub13554 = -2*MT2 + 2*S34 + T + T14;

  Sub6480 = 2*MT2 - 4*S - T14 - T24;

  Sub1409 = 4*MT2 - 4*S - T14 - T24;

  Sub438 = 2*MT2 - 3*S - T14 - T24;

  Sub4977 = MT2 - 2*S - T14 - T24;

  Sub278 = 2*MT2 - 2*S - T14 - T24;

  Sub257 = MT2 - S - T14 - T24;

  Sub1749 = 2*MT2 - S - T14 - T24;

  Sub4538 = 3*MT2 - 2*S34 - T14 - T24;

  Sub388 = 2*MT2 - S34 - T14 - T24;

  Sub1958 = 4*MT2 - S34 - T14 - T24;

  Sub994 = 6*MT2 - S34 - T14 - T24;

  Sub11078 = 8*MT2 - S34 - T14 - T24;

  Sub6481 = 2*S - S34 - T14 - T24;

  Sub10614 = 2*MT2 + S34 - T14 - T24;

  Sub6482 = 4*MT2 + 2*S - S34 - 5*(T14 + T24);

  Sub5771 = 8*MT2 - 5*S - 2*S34 - 4*(T14 + T24);

  Sub7147 = 4*MT2 - 3*S - S34 - 4*(T14 + T24);

  Sub6783 = 6*MT2 - S - 2*S34 - 3*(T14 + T24);

  Sub5369 = 4*MT2 - 2*S - S34 - 3*(T14 + T24);

  Sub4169 = 2*MT2 - 3*S - S34 - 2*(T14 + T24);

  Sub9412 = 8*MT2 - 2*S - 3*T - 5*U;

  Sub8458 = 8*MT2 - 2*S34 - T24 - 5*U;

  Sub9912 = 10*MT2 - 2*(S + T + T14) - 3*(S34 + T24) - 4*U;

  Sub9411 = 2*MT2 - S - T - 3*U;

  Sub9820 = 8*MT2 - S34 - 2*(S + T14) - 3*U;

  Sub8882 = 10*MT2 + S34 - 4*T24 - 3*U;

  Sub1236 = 5*MT2 - 4*S34 - T24 - 3*U;

  Sub8798 = 5*MT2 - S34 - T24 - 3*U;

  Sub9959 = 8*MT2 - S34 - 2*(S + T24) - 3*U;

  Sub9757 = 7*MT2 - T - 2*(S + S34 + T14 + T24) - 3*U;

  Sub8752 = 8*MT2 - S34 - 2*(S + T + T14 + T24) - 3*U;

  Sub9350 = MT2 - S - T - 2*U;

  Sub9352 = 2*MT2 - S - T - 2*U;

  Sub8806 = 3*MT2 - S - T - 2*U;

  Sub9808 = 5*MT2 - S34 - 3*T24 - 2*U;

  Sub1233 = 3*MT2 - 3*S34 - T24 - 2*U;

  Sub8543 = 3*MT2 - S34 - T24 - 2*U;

  Sub10090 = 4*MT2 + S34 - T24 - 2*U;

  Sub9433 = 15*MT2 - 5*(S + T + T14) - 3*(S34 + T24) - 2*U;

  Sub9351 = 3*MT2 - 2*S - 3*T - U;

  Sub8783 = MT2 - S - 2*T - U;

  Sub5248 = 2*MT2 - 4*S - T - U;

  Sub400 = 2*MT2 - 3*S - T - U;

  Sub921 = 2*MT2 - 2*S - T - U;

  Sub9355 = MT2 - S - T - U;

  Sub1765 = 2*MT2 - S - T - U;

  Sub6229 = 4*MT2 - S - T - U;

  Sub1971 = 2*MT2 + S - T - U;

  Sub4655 = 3*MT2 - 2*S34 - T - U;

  Sub8063 = MT2 - S34 - T - U;

  Sub262 = 2*MT2 - S34 - T - U;

  Sub258 = 4*MT2 - S34 - T - U;

  Sub7312 = 5*MT2 - S34 - T - U;

  Sub1976 = 6*MT2 - S34 - T - U;

  Sub10147 = 2*MT2 + S34 - T - U;

  Sub1936 = 2*MT2 - Sub262 - T - U;

  Sub2245 = 2*MT2 + Sub388 - T - U;

  Sub9926 = 5*MT2 - 2*S34 - 3*T24 - U;

  Sub9762 = 3*MT2 - S34 - 2*T24 - U;

  Sub9962 = 4*MT2 - S34 - 2*T24 - U;

  Sub4039 = 4*MT2 + S34 - 2*T24 - U;

  Sub13817 = 2*MT2 + MZ2 - T24 - U;

  Sub3043 = 2*MT2 - 3*S - T24 - U;

  Sub14326 = 2*MT2 - 2*S - T24 - U;

  Sub2756 = MT2 - S - T24 - U;

  Sub8525 = 3*MT2 - S - T24 - U;

  Sub14463 = 2*MT2 + S - T24 - U;

  Sub9996 = 4*MT2 - 3*S34 - T24 - U;

  Sub3410 = MT2 - 2*S34 - T24 - U;

  Sub154 = 2*MT2 - 2*S34 - T24 - U;

  Sub8502 = 3*MT2 - 2*S34 - T24 - U;

  Sub1452 = MT2 - S34 - T24 - U;

  Sub407 = 2*MT2 - S34 - T24 - U;

  Sub8433 = 3*MT2 - S34 - T24 - U;

  Sub13731 = S - S34 - T24 - U;

  Sub933 = 2*MT2 + S34 - T24 - U;

  Sub2599 = 2*MT2 - Sub153 - T24 - U;

  Sub14265 = 6*MT2 - 2*(T + T14) - T24 - U;

  Sub13857 = S + 2*(T + T14) - T24 - U;

  Sub1058 = 2*MT2 - S34 + T24 - U;

  Sub3215 = 2*MT2 - S34 + 3*T24 - U;

  Sub4906 = 3*MT2 - T - 2*T14 - 2*T24 - U;

  Sub10357 = 7*MT2 - 2*T - 3*(S + S34 + T14 + T24) - U;

  Sub13792 = -S34 - T - T14 + U;

  Sub8050 = 3*S34 + T + 5*(T14 + T24) + U;

  Sub9851 = 8*MT2 - 2*(S + T + T14) - 4*T24 - 3*(S34 + U);

  Sub9956 = 10*MT2 - 2*(S + T + T14) - 4*T24 - 3*(S34 + U);

  Sub9955 = 11*MT2 - 2*(S + T + T14) - 4*T24 - 3*(S34 + U);

  Sub11341 = 6*MT2 - S - S34 - 3*T - 3*U;

  Sub10553 = -S34 + Sub4257;

  Sub4170 = 4*MT2 + T14 + T24 - 2*(T + U);

  Sub8058 = 4*S + 3*S34 + 5*(T14 + T24) + 6*(T + U);

  Sub7538 = -8*MT2 + S + T14 + T24 + 4*(T + U);

  Sub7535 = S - 2*S34 + 6*Sub318 + 4*(MT2 + Sub4257) + 
     2*(T + U);

  Sub11614 = 2*MT2 - T14 - T24 - 2*(S34 + T + U);

  Sub13350 = -7*S34 + Sub13516;

  Sub662 = 4*MT2 - 10*S34 + 3*(S + T + T14) - 5*(T24 + U);

  Sub14137 = 8*MT2 + S - 3*S34 - 4*(T24 + U);

  Sub626 = 2*MT2 - 9*S34 + 3*(S + T + T14) - 4*(T24 + U);

  Sub13515 = -5*S34 + Sub4098;

  Sub13374 = 6*MT2 - S - 5*S34 - 3*(T24 + U);

  Sub13854 = -S34 + Sub4098;

  Sub10030 = 8*MT2 - S34 - 2*(S + T14) - 3*(T24 + U);

  Sub9527 = 15*MT2 - 2*S34 - 4*(S + T + T14) - 3*(T24 + U);

  Sub9295 = 8*MT2 - S34 - 2*(S + T + T14) - 3*(T24 + U);

  Sub14063 = -S34 + Sub13563;

  Sub13868 = 6*MT2 - T - T14 - 2*(S + T24) - 2*U;

  Sub189 = 4*MT2 - 4*S34 - 5*(T + T14) + 3*(S + T24 + U);

  Sub537 = 2*MT2 - 3*S34 - 4*(T + T14) + 3*(S + T24 + U);

  Sub4477 = 2*MT2 - S - S34 - Sub262 + Sub388;

  Sub4049 = -S34 + Sub152;

  Sub14138 = 2*MT2 - 2*Sub14137 + 4*Sub3478 - T - T14;

  Sub9452 = 5*MT2 - S34 - 2*(S + T) - 2*T14 - T24;

  Sub1436 = -3*MB2 + MT2 - S - T14 - T24;

  Sub5769 = 2*MT2 + S - 3*S34 - T14 - T24;

  Sub2229 = -S34 + Sub1749;

  Sub4542 = MT2 - 4*S + 2*S34 - T14 - T24;

  Sub4541 = 2*S34 + Sub4977;

  Sub5714 = 10*MT2 - 2*S - 3*S34 + T14 + T24;

  Sub6430 = 8*MT2 - S - 2*S34 + T14 + T24;

  Sub12744 = 6*MT2 - S - S34 - 3*T - 3*U;

  Sub11431 = 6*MT2 - S - 2*S34 - T - U;

  Sub11567 = -2*S34 + Sub1971;

  Sub7238 = -S34 + Sub1765;

  Sub10146 = S34 + Sub1971;

  Sub10129 = 11*MT2 - 3*S34 - 4*(S + T + T14) - 2*T24 - U;

  Sub14195 = 2*MT2 - 4*S - 3*S34 - T24 - U;

  Sub4058 = -S34 + Sub153;

  Sub2797 = 4*MT2 - S - S34 - T24 - U;

  Sub14347 = S34 + Sub3043;

  Sub14346 = 3*S34 + Sub3043;

  Sub2859 = Sub8525 - T;

  Sub9835 = Sub318 - U;

  Sub8276 = 6*MT2 - S34 - 2*(S + T) - 2*T14 - T24 - U;

  Sub5715 = 2*S - T + T14 + T24 - U;

  Sub11562 = S34 - T + 2*T14 + 2*T24 - U;

  Sub6791 = Sub258 - 2*(S + T14 + T24);

  Sub6713 = 2*S + T - T14 - T24 + U;

  Sub13945 = Opt9 + 2*S34;

  Sub13514 = Opt9 + 3*S34;

  Sub3353 = 2*MT2 + S - 2*(T + T14) + T24 + U;

  Sub13147 = 38*MT2 - 4*S - 8*S34 - 7*(T14 + T24) - 6*(T + U)
   ;

  Sub10976 = 8*MT2 - S - 4*T - T14 - T24 - 4*U;

  Sub4188 = 2*S + S34 + T14 + T24 + 3*(T + U);

  Sub11113 = -6*MT2 + S34 + T + U;

  Sub2290 = Sub388 - 2*(S + T + U);

  Sub2293 = Sub994 - 2*(S + T + U);

  Sub4268 = Sub1749 - 2*(S34 + T + U);

  Sub13513 = 4*MT2 - 3*S + 2*S34 + 3*(T + T14) - 5*(T24 + U);

  Sub3241 = 2*MT2 + S + T + T14 - 2*(T24 + U);

  Sub13850 = -S34 + Sub13868;

  Sub9265 = -S34 + Sub9761 - T24;

  Sub10972 = 8*MT2 - S - 4*T - T14 - T24 - 4*U;

  Sub3630 = 6*MT2 - S - T - T14 - 2*T24 - 2*U;

  Sub2178 = Sub1033 - T24 - 2*U;

  Sub8580 = Sub152 - T24 - 2*U;

  Sub8437 = Sub1451 - T24 - 2*U;

  Sub2285 = Sub318 - 2*(S + T + U);

  Sub2289 = Sub994 - 2*(S + T + U);

  Sub13856 = 6*MT2 - S34 - T - T14 - 2*(S + T24) - 2*U;

  Sub10130 = -2*S34 + Sub6229 - T14;

  Sub9733 = -S34 + Sub1451 - U;

  Sub9479 = -S34 + Sub6229 - T14;

  Sub4238 = Sub258 - 2*(S + T14 + T24);

  Sub382 = Sub1976 - 2*(S + T14 + T24);

  Sub8265 = 6*MT2 - S34 - 2*(S + T) - 2*T14 - T24 - U;

  Sub4578 = Sub152 - T24 - U;

  Sub151 = Sub6229 - T14 - T24;

  Sub6768 = 4*MT2 + Opt16 - 2*S34;

  Sub11823 = 12*MT2 + Opt16 - 2*S34;

  Sub9756 = Sub387 - T24 - U;

  Sub4490 = Sub7003 - T24 - U;

  Sub1724 = Sub1958 - T - U;

  Sub533 = Sub13731 + T + T14;

  Sub4092 = 10*MT2 - 3*S - S34 - 4*T - 4*T14 - T24 - U;

  Sub10219 = 2*(MT2 + S) + S34 - T + T14 + T24 - U;

  Sub536 = S + Sub13792 + T24;

  Sub198 = Opt9 + S + 4*S34;

  Sub551 = 8*S34 + Sub3353;

  Sub3242 = 10*MT2 - S - 2*S34 - T - T14 - 4*T24 - 4*U;

  Sub13394 = 4*MT2 - S - 7*S34 + T + T14 - 3*(T24 + U);

  Sub8577 = -S + Sub1958 - T - 2*U;

  Sub9560 = -S + Sub11078 - T - 2*U;

  Sub1931 = 10*MT2 - S - 2*S34 - T - 2*T14 - 2*T24 - U;

  Sub9888 = Sub9733 - 2*T24;

  Sub8527 = Sub9479 - 2*T24;

  Sub3451 = 8*MT2 - S - 2*S34 - 3*T - 3*T14 - T24 - U;

  Sub6777 = S + Sub9996 - T - T14;

  Sub155 = Sub10130 - T24;

  Sub6195 = -S34 + Sub14309 - T24 - U;

  Sub9209 = Sub9265 - U;

  Sub11841 = -S + Sub7312 - T14 - T24;

  Sub4950 = -S + Sub994 - T - U;

  Sub2140 = -S + Sub11078 - T - U;

  Sub2143 = 10*MT2 + Opt16 - S - S34;

  Sub2873 = 12*MT2 + Opt16 - S - S34;

  Sub6599 = -S + Sub2927 - T24 + U;

  Dput(&pave1(dd0),S34,0.,ME2,ME2,S,Sub14661,ME2,ME2,ME2,0.);

  Dput(&pave2(dd0),S34,0.,Sub14663,MT2,S,MT2,MT2,MT2,MT2,0.);

  Dput(&pave3(dd0),S34,0.,Sub14663,MT2,S,MT2,MT2,MT2,MT2,MZ2)
   ;

  Bput(&pave8(bb0),S34,MB2,MB2);

  Bput(&pave9(bb0),S34,MT2,MT2);

  Bput(&pave10(bb0),S34,MW2,MW2);

  Bput(&pave20(bb0),S34,0.,0.);

  Bput(&pave21(bb0),S34,MH2,MZ2);

  Cput(&pave40(cc0),MT2,S34,MT2,MB2,MW2,MW2);

  Cput(&pave47(cc0),0.,S34,S,MW2,MW2,MW2);

  Cput(&pave48(cc0),S34,0.,S,MW2,MW2,MW2);

  Cput(&pave49(cc0),S34,ME2,Sub14667,ME2,ME2,MZ2);

  Cput(&pave50(cc0),S34,MT2,MT2,MT2,MT2,MH2);

  Cput(&pave57(cc0),ME2,S34,Sub14661,0.,MW2,MW2);

  Cput(&pave63(cc0),MT2,S34,MT2,MT2,MH2,MZ2);

  Cput(&pave64(cc0),MT2,S34,MT2,MT2,MZ2,MH2);

  Cput(&pave72(cc0),S34,ME2,Sub14667,0.,0.,MW2);

  Cput(&pave74(cc0),S34,ME2,Sub14667,ME2,ME2,0.);

  Cput(&pave76(cc0),S34,MT2,MT2,MB2,MB2,MW2);

  Cput(&pave77(cc0),S34,MT2,MT2,MT2,MT2,0.);

  Cput(&pave78(cc0),S34,MT2,MT2,MT2,MT2,MZ2);

  Cput(&pave80(cc0),S34,Sub14661,ME2,ME2,ME2,0.);

  Cput(&pave82(cc0),S34,Sub14661,ME2,ME2,ME2,MZ2);

  Cput(&pave83(cc0),Sub14667,S34,ME2,0.,MW2,MW2);

  Cput(&pave85(cc0),S34,Sub14661,ME2,0.,0.,MW2);

  Cput(&pave89(cc0),Sub14667,S34,ME2,ME2,MZ2,MZ2);

  Cput(&pave91(cc0),ME2,S34,Sub14661,ME2,MZ2,MZ2);

  Dput(&pave94(dd0),T,MT2,S34,Sub14667,ME2,MT2,ME2,MT2,MZ2,0.)
   ;

  Dput(&pave95(dd0),U,MT2,S34,Sub14661,ME2,MT2,ME2,MT2,0.,MZ2)
   ;

  Dput(&pave96(dd0),U,MT2,S34,Sub14661,ME2,MT2,ME2,MT2,MZ2,0.)
   ;

  Dput(&pave97(dd0),0.,ME2,S34,ME2,Sub14667,Sub14661,ME2,ME2,
    MZ2,MZ2);

  Dput(&pave99(dd0),S34,S,Sub14665,MT2,0.,MT2,MT2,MT2,MT2,MZ2)
   ;

  Dput(&pave100(dd0),T,MT2,S,ME2,ME2,Sub14663,ME2,MT2,0.,MZ2)
   ;

  Dput(&pave101(dd0),T,MT2,S,ME2,ME2,Sub14663,ME2,MT2,MZ2,0.)
   ;

  Dput(&pave102(dd0),T,MT2,S34,Sub14667,ME2,MT2,ME2,MT2,0.,MZ2)
   ;

  Dput(&pave104(dd0),T14,MT2,S,ME2,ME2,Sub14665,ME2,MT2,0.,0.)
   ;

  Dput(&pave105(dd0),T14,MT2,S,ME2,ME2,Sub14665,ME2,MT2,0.,MZ2)
   ;

  Dput(&pave106(dd0),T14,MT2,S,ME2,ME2,Sub14665,ME2,MT2,MZ2,0.)
   ;

  Dput(&pave107(dd0),T14,MT2,S34,Sub14667,ME2,MT2,ME2,MT2,0.,
    MZ2);

  Dput(&pave108(dd0),T14,MT2,S34,Sub14667,ME2,MT2,ME2,MT2,MZ2,
    0.);

  Dput(&pave109(dd0),T24,MT2,S34,Sub14661,ME2,MT2,ME2,MT2,0.,
    MZ2);

  Dput(&pave110(dd0),T24,MT2,S34,Sub14661,ME2,MT2,ME2,MT2,MZ2,
    0.);

  Dput(&pave111(dd0),T24,Sub14665,S,ME2,ME2,MT2,ME2,MT2,0.,MZ2)
   ;

  Dput(&pave112(dd0),T24,Sub14665,S,ME2,ME2,MT2,ME2,MT2,MZ2,0.)
   ;

  Dput(&pave113(dd0),T24,MT2,S34,Sub14661,ME2,MT2,ME2,MT2,0.,
    0.);

  Dput(&pave114(dd0),U,MT2,S34,Sub14661,ME2,MT2,ME2,MT2,0.,0.)
   ;

  Dput(&pave115(dd0),U,MT2,S34,Sub14661,ME2,MT2,ME2,MT2,MZ2,
    MZ2);

  Dput(&pave116(dd0),U,Sub14663,S,ME2,ME2,MT2,ME2,MT2,0.,MZ2)
   ;

  Dput(&pave117(dd0),U,Sub14663,S,ME2,ME2,MT2,ME2,MT2,MZ2,0.)
   ;

  Dput(&pave120(dd0),ME2,0.,S34,ME2,Sub14667,S,0.,MW2,MW2,MW2)
   ;

  Dput(&pave121(dd0),ME2,S34,0.,ME2,Sub14661,S,0.,MW2,MW2,MW2)
   ;

  Dput(&pave122(dd0),MT2,S34,0.,Sub14663,MT2,S,MB2,MW2,MW2,MW2)
   ;

  Dput(&pave123(dd0),MT2,S34,S,Sub14665,MT2,0.,MB2,MW2,MW2,MW2)
   ;

  Dput(&pave124(dd0),S34,0.,Sub14663,MT2,S,MT2,MB2,MB2,MB2,MW2)
   ;

  Dput(&pave125(dd0),S34,S,Sub14665,MT2,0.,MT2,MB2,MB2,MB2,MW2)
   ;

  Dput(&pave126(dd0),S34,S,Sub14665,MT2,0.,MT2,MT2,MT2,MT2,0.)
   ;

  Dput(&pave127(dd0),S34,0.,Sub14663,MT2,S,MT2,MT2,MT2,MT2,MH2)
   ;

  Dput(&pave128(dd0),S34,S,Sub14665,MT2,0.,MT2,MT2,MT2,MT2,MH2)
   ;

  Dput(&pave130(dd0),0.,S34,ME2,ME2,S,Sub14667,ME2,ME2,ME2,0.)
   ;

  Dput(&pave131(dd0),0.,S34,ME2,ME2,S,Sub14667,ME2,ME2,ME2,MZ2)
   ;

  Dput(&pave132(dd0),S34,0.,ME2,ME2,S,Sub14661,ME2,ME2,ME2,MZ2)
   ;

  Dput(&pave133(dd0),S34,ME2,0.,ME2,Sub14667,Sub14661,0.,0.,
    MW2,MW2);

  Dput(&pave135(dd0),T14,MT2,S,ME2,ME2,Sub14665,0.,MB2,MW2,MW2)
   ;

  Dput(&pave136(dd0),U,Sub14663,S,ME2,ME2,MT2,0.,MB2,MW2,MW2)
   ;

  Dput(&pave137(dd0),T24,MT2,S34,Sub14661,ME2,MT2,ME2,MT2,MZ2,
    MZ2);

  Dput(&pave138(dd0),T24,Sub14665,S,ME2,ME2,MT2,ME2,MT2,0.,0.)
   ;

  Dput(&pave139(dd0),T14,MT2,S,ME2,ME2,Sub14665,ME2,MT2,MZ2,
    MZ2);

  Dput(&pave140(dd0),T24,Sub14665,S,ME2,ME2,MT2,ME2,MT2,MZ2,
    MZ2);

  Dput(&pave141(dd0),U,MT2,S34,Sub14661,ME2,MT2,0.,MB2,MW2,MW2)
   ;

  Dput(&pave142(dd0),T,MT2,S,ME2,ME2,Sub14663,ME2,MT2,0.,0.);

  Dput(&pave143(dd0),U,Sub14663,S,ME2,ME2,MT2,ME2,MT2,0.,0.);

  Dput(&pave144(dd0),T,MT2,S,ME2,ME2,Sub14663,ME2,MT2,MZ2,MZ2)
   ;

  Dput(&pave145(dd0),U,Sub14663,S,ME2,ME2,MT2,ME2,MT2,MZ2,MZ2)
   ;

  Dput(&pave146(dd0),T14,MT2,S34,Sub14667,ME2,MT2,0.,MB2,MW2,
    MW2);

  Cput(&pave163(cc0),S34,S,0.,MT2,MT2,MT2);

  Cput(&pave166(cc0),S34,S,0.,MW2,MW2,MW2);

  Dput(&pave167(dd0),T,MT2,S34,Sub14667,ME2,MT2,ME2,MT2,MZ2,
    MZ2);

  Dput(&pave168(dd0),T14,MT2,S34,Sub14667,ME2,MT2,ME2,MT2,MZ2,
    MZ2);

  Cput(&pave170(cc0),S34,0.,S,MB2,MB2,MB2);

  Cput(&pave171(cc0),S34,S,0.,MB2,MB2,MB2);

  Bput(&pave172(bb0),S34,ME2,ME2);

  Cput(&pave175(cc0),T24,MT2,Sub14661,ME2,MT2,MZ2);

  Cput(&pave176(cc0),T24,MT2,Sub14661,ME2,MT2,0.);

  Cput(&pave177(cc0),T,MT2,Sub14667,ME2,MT2,0.);

  Cput(&pave178(cc0),S34,0.,S,MT2,MT2,MT2);

  Dput(&pave179(dd0),T,MT2,S34,Sub14667,ME2,MT2,ME2,MT2,0.,0.)
   ;

  Dput(&pave180(dd0),T14,MT2,S34,Sub14667,ME2,MT2,ME2,MT2,0.,
    0.);

  Cput(&pave181(cc0),T,MT2,Sub14667,ME2,MT2,MZ2);

  Cput(&pave183(cc0),0.,S34,S,ME2,ME2,ME2);

  Cput(&pave184(cc0),S34,0.,S,ME2,ME2,ME2);

  Sub2033 = 2*(MT2*MT2) + (MB2 - 2*MW2)*Sub262;

  Sub1461 = 3*Sub1451 + MT2*(-3 + 4*SW2);

  Sub1046 = 3*MT2 + (3 - 4*SW2)*Sub388;

  Sub2325 = 6*(MT2*MT2) + 
     (MB2*(3 - 4*SW2) + MW2*(-6 + 8*SW2))*Sub388;

  Sub541 = 1/(CW2*(SW2*SW2))*(-(SW2*Sub387) + CW2*Sub537);

  Sub631 = 1/(CW2*(SW2*SW2))*(-(SW2*Sub407) + CW2*Sub626);

  Sub540 = 1/(CW2*SW2)*(SW2*Sub387 - CW2*Sub537);

  Sub630 = 1/(CW2*SW2)*(SW2*Sub407 - CW2*Sub626);

  Sub13883 = (MT*Power(1 - 2*SW2,2))/SW2*(MZ2 - Sub13856);

  Sub14679 = 3*pave20(bb00) - pave21(bb00);

  Sub15025 = pave10(bb0) + 2*pave10(bb1);

  Sub14706 = 5*pave10(bb0) + 2*pave10(bb1);

  Sub14752 = 2*Finite + 1/MW2*((MH2 + 6*MW2)*pave10(bb1));

  Sub14675 = Sub152*pave10(bb0) - 2*Sub154*pave10(bb1);

  Sub14708 = Sub153*pave10(bb0) - 2*Sub387*pave10(bb1);

  Sub14671 = Sub152*pave10(bb0) - 2*Sub407*pave10(bb1);

  Sub14680 = 3*pave20(bb11) - pave21(bb11);

  Sub15048 = MW2*(-1 + 2*SW2)*pave34(cc0) + pave20(bb0);

  Sub15462 = pave47(cc0) + pave48(cc0);

  Sub15132 = pave34(cc00) + pave57(cc00);

  Sub15049 = pave63(cc00) + pave64(cc00);

  Sub15084 = (-1 + 2*SW2)*Sub15083 - 2*pave72(cc00);

  Sub15096 = pave73(cc00) + pave74(cc00);

  Sub15117 = pave49(cc00) + pave75(cc00);

  Sub15097 = 9*Sub15096 + 4*pave77(cc00);

  Sub15046 = pave79(cc00) + pave80(cc00);

  Sub15069 = pave81(cc00) + pave82(cc00);

  Sub15173 = pave55(cc00) + pave83(cc00);

  Sub14823 = 4*(CW2*pave77(cc1) + SW2*pave78(cc1)) - 
     3*pave78(cc1);

  Sub15043 = pave63(cc11) + pave64(cc11);

  Sub15104 = 9*pave74(cc11) + 4*pave77(cc11);

  Sub15013 = 1/(CW2*MW2)*
     (CW2*(3*MB2 - 3*MT2 + 6*MW2)*pave76(cc11) + 
       MW2*(-6 + 16*SW2)*pave78(cc11));

  Sub15054 = 4*pave77(cc11) + 9*pave80(cc11);

  Sub15059 = pave63(cc12) + pave64(cc12);

  Sub15016 = pave83(cc11) + pave83(cc12);

  Sub15044 = pave63(cc22) + pave64(cc22);

  Sub15168 = pave74(cc12) + pave74(cc22);

  Sub15191 = pave49(cc12) + pave49(cc22);

  Sub15516 = pave95(dd0) + pave96(dd0);

  Sub15455 = pave91(cc0) - 2*pave97(dd00);

  Sub15545 = pave100(dd00) + pave101(dd00);

  Sub15602 = pave102(dd00) + pave94(dd00);

  Sub15575 = pave105(dd00) + pave106(dd00);

  Sub15603 = pave107(dd00) + pave108(dd00);

  Sub15513 = pave109(dd00) + pave110(dd00);

  Sub15576 = pave111(dd00) + pave112(dd00);

  Sub15514 = pave95(dd00) + pave96(dd00);

  Sub15546 = pave116(dd00) + pave117(dd00);

  Sub15418 = pave120(dd001) + pave121(dd001);

  Sub15287 = pave122(dd001) + pave123(dd001);

  Sub15288 = pave124(dd001) + pave125(dd001);

  Sub15262 = pave126(dd001) + pave2(dd001);

  Sub15289 = pave127(dd001) + pave128(dd001);

  Sub15267 = pave3(dd001) + pave99(dd001);

  Sub15290 = pave122(dd002) + pave123(dd002);

  Sub15412 = pave1(dd002) + pave130(dd002);

  Sub15440 = pave131(dd002) + pave132(dd002);

  Sub15427 = pave120(dd003) + pave121(dd003);

  Sub15413 = pave1(dd003) + pave130(dd003);

  Sub15441 = pave131(dd003) + pave132(dd003);

  Sub15291 = pave124(dd003) + pave125(dd003);

  Sub15263 = pave126(dd003) + pave2(dd003);

  Sub15292 = pave127(dd003) + pave128(dd003);

  Sub15268 = pave3(dd003) + pave99(dd003);

  Sub15459 = pave120(dd1) + pave121(dd1);

  Sub15552 = pave100(dd11) + pave101(dd11);

  Sub15611 = pave102(dd11) + pave94(dd11);

  Sub15582 = pave105(dd11) + pave106(dd11);

  Sub15604 = pave107(dd11) + pave108(dd11);

  Sub15522 = pave109(dd11) + pave110(dd11);

  Sub15579 = pave111(dd11) + pave112(dd11);

  Sub15517 = pave95(dd11) + pave96(dd11);

  Sub15548 = pave116(dd11) + pave117(dd11);

  Sub15299 = pave122(dd111) + pave123(dd111);

  Sub15293 = pave124(dd111) + pave125(dd111);

  Sub15360 = pave126(dd111) + pave2(dd111);

  Sub15393 = pave127(dd111) + pave128(dd111);

  Sub15300 = pave3(dd111) + pave99(dd111);

  Sub15301 = pave122(dd112) + pave123(dd112);

  Sub15302 = pave124(dd113) + pave125(dd113);

  Sub15277 = pave126(dd113) + pave2(dd113);

  Sub15294 = pave127(dd113) + pave128(dd113);

  Sub15313 = pave3(dd113) + pave99(dd113);

  Sub15237 = 1/(MW2*SW2)*
     (9*MT2*pave128(dd12) + 32*MW2*SW2*pave2(dd12));

  Sub15553 = pave100(dd12) + pave101(dd12);

  Sub15609 = pave102(dd12) + pave94(dd12);

  Sub15583 = pave105(dd12) + pave106(dd12);

  Sub15605 = pave107(dd12) + pave108(dd12);

  Sub15523 = pave109(dd12) + pave110(dd12);

  Sub15585 = pave111(dd12) + pave112(dd12);

  Sub15518 = pave95(dd12) + pave96(dd12);

  Sub15549 = pave116(dd12) + pave117(dd12);

  Sub15422 = pave130(dd112) + pave130(dd122);

  Sub15447 = pave131(dd112) + pave131(dd122);

  Sub15303 = pave122(dd122) + pave123(dd122);

  Sub15414 = pave1(dd112) + pave1(dd122);

  Sub15442 = pave132(dd112) + pave132(dd122);

  Sub15264 = pave2(dd112) + pave2(dd122);

  Sub15295 = pave127(dd112) + pave127(dd122);

  Sub15278 = pave126(dd112) + pave126(dd122);

  Sub15296 = pave128(dd112) + pave128(dd122);

  Sub15554 = pave100(dd13) + pave101(dd13);

  Sub15612 = pave102(dd13) + pave94(dd13);

  Sub15578 = pave105(dd13) + pave106(dd13);

  Sub15606 = pave107(dd13) + pave108(dd13);

  Sub15524 = pave109(dd13) + pave110(dd13);

  Sub15580 = pave111(dd13) + pave112(dd13);

  Sub15519 = pave95(dd13) + pave96(dd13);

  Sub15550 = pave116(dd13) + pave117(dd13);

  Sub15304 = pave124(dd133) + pave125(dd133);

  Sub15281 = pave126(dd133) + pave2(dd133);

  Sub15297 = pave127(dd133) + pave128(dd133);

  Sub15269 = pave3(dd133) + pave99(dd133);

  Sub15238 = pave1(dd2) + pave130(dd1);

  Sub15244 = pave131(dd1) + pave132(dd2);

  Sub15458 = pave97(dd12) + pave97(dd22);

  Sub15241 = 27*pave1(dd11) + 8*pave2(dd22);

  Sub15506 = pave113(dd22) + pave114(dd22);

  Sub15532 = pave115(dd22) + pave137(dd22);

  Sub15298 = pave122(dd222) + pave123(dd222);

  Sub15456 = pave97(dd13) + pave97(dd23);

  Sub15613 = pave102(dd23) + pave94(dd23);

  Sub15607 = pave107(dd23) + pave108(dd23);

  Sub15525 = pave109(dd23) + pave110(dd23);

  Sub15569 = pave104(dd23) + pave138(dd23);

  Sub15591 = pave139(dd23) + pave140(dd23);

  Sub15520 = pave95(dd23) + pave96(dd23);

  Sub15539 = pave142(dd23) + pave143(dd23);

  Sub15562 = pave144(dd23) + pave145(dd23);

  Sub15477 = pave133(dd133) + pave133(dd233);

  Sub15614 = pave102(dd33) + pave94(dd33);

  Sub15616 = pave107(dd33) + pave108(dd33);

  Sub15527 = pave109(dd33) + pave110(dd33);

  Sub15588 = pave104(dd33) + pave138(dd33);

  Sub15594 = pave139(dd33) + pave140(dd33);

  Sub15529 = pave95(dd33) + pave96(dd33);

  Sub15558 = pave142(dd33) + pave143(dd33);

  Sub15564 = pave144(dd33) + pave145(dd33);

  Sub15305 = pave124(dd333) + pave125(dd333);

  Sub15282 = pave126(dd333) + pave2(dd333);

  Sub15309 = pave127(dd333) + pave128(dd333);

  Sub15314 = pave3(dd333) + pave99(dd333);

  Sub15200 = Sub15204 + Sub1314*pave10(bb0);

  Sub15047 = 18*Sub15046 - 9*pave161(bb0) + 8*pave77(cc00);

  Sub15163 = 18*Sub15096 - 9*pave162(bb0) + 8*pave77(cc00);

  Sub15032 = (1 - 2*SW2)*Sub15031 + 2*pave85(cc00);

  Sub15015 = Sub15168 + pave74(cc1);

  Sub15018 = Sub15191 + pave49(cc1);

  Sub15464 = pave120(dd12) + pave120(dd22) - pave121(dd12);

  Sub15465 = -pave120(dd23) + pave121(dd22) + pave121(dd23);

  Sub5770 = 8*MT2 - Sub6419;

  Sub15515 = pave109(dd22) + pave110(dd22) + pave95(dd22) + 
     pave96(dd22);

  Sub15584 = pave105(dd23) + pave106(dd23) + pave111(dd23) + 
     pave112(dd23);

  Sub15551 = pave100(dd23) + pave101(dd23) + pave116(dd23) + 
     pave117(dd23);

  Sub15589 = pave105(dd33) + pave106(dd33) + pave111(dd33) + 
     pave112(dd33);

  Sub15559 = pave100(dd33) + pave101(dd33) + pave116(dd33) + 
     pave117(dd33);

  Sub14072 = -Sub154 + Sub387;

  Sub4162 = -2*S + Sub994;

  Sub6477 = S + Sub388;

  Sub2175 = 2*S + Sub11078;

  Sub2968 = 4*S + Sub262;

  Sub13669 = -2*Sub153 + Sub933;

  Sub5297 = 2*MT2 + Opt16;

  Sub319 = 6*MT2 + Opt8;

  Sub11801 = 10*MT2 + Opt8;

  Sub7474 = 8*MT2 + Opt10;

  Sub10973 = 12*MT2 + Opt10;

  Sub15463 = 3*Sub15462 - 4*Sub387*pave120(dd2) + 
     8*(pave120(dd00) + pave121(dd00)) + 4*Sub152*pave121(dd2);

  Sub12318 = 4*MT2 + Opt16 - 2*S;

  Sub9807 = MT2 - Opt9 + S;

  Sub157 = S - Sub13945;

  Sub168 = S + Sub13945;

  Sub2692 = 6*MT2 + Opt18;

  Sub10975 = 12*MT2 + Opt18;

  Sub137 = -3*S + Sub1724;

  Sub1718 = -2*S + Sub1724;

  Sub435 = -S + Sub1724;

  Sub2633 = -Sub2634;

  Sub3707 = MT2*Sub1058 + (2*MB2 - 2*MW2)*T24;

  Sub7075 = -(MB2*Sub258) + MT2*(-S + Sub258 - T14 - T24);

  Sub15201 = Sub15200 + (-3*S + S34)*pave47(cc2);

  Sub11675 = S - Sub11078 - 2*(MT2 + T14 + T24);

  Sub5775 = S - Sub5771 - 2*(MT2 + T14 + T24);

  Sub6485 = 5*S - Sub6482 - 2*(MT2 + T14 + T24);

  Sub13778 = -10*MT2 + 2*Sub388 + 3*(S34 + T14 + T24);

  Sub14714 = Finite*Sub151 + 
     1/MW2*((MH2 + 6*MW2)*(-(1/4.*(Sub153*pave10(bb0))) - 
          1/2.*((-2*MT2 + T + T14)*pave10(bb1))));

  Sub2201 = S - S34 - Sub262 - Sub388;

  Sub4175 = 4*MT2 - S - S34 + Sub4169;

  Sub6404 = MT2 - S34 - Sub2756 - T14;

  Sub14045 = 2*MT2 - Sub154 - T - T14;

  Sub1602 = 2*MT2 + Sub262 - T14 - T24;

  Sub14676 = -4*Finite*Sub155 + 1/MW2*((MH2 + 6*MW2)*Sub14675)
   ;

  Sub663 = 1/CW2*(-(SW2*Sub157) + CW2*(Sub157 + Sub662));

  Sub14669 = -(Sub663*pave10(bb1)) + 
     2*Sub154*Sub156*pave10(bb11);

  Sub15130 = 9*Sub15046 + 4*pave77(cc00);

  Sub15485 = 4*Sub15427 - pave56(cc2);

  LOOP(Gen6, 1,3,1)

  Bput(&pave153(bb0,Gen6),S34,Mf2(2,Gen6),Mf2(2,Gen6));

  Bput(&pave154(bb0,Gen6),S34,Mf2(3,Gen6),Mf2(3,Gen6));

  Bput(&pave155(bb0,Gen6),S34,Mf2(4,Gen6),Mf2(4,Gen6));

  Cput(&pave156(cc0,Gen6),0.,S34,S,Mf2(3,Gen6),Mf2(3,Gen6),
    Mf2(3,Gen6));

  Cput(&pave157(cc0,Gen6),0.,S34,S,Mf2(2,Gen6),Mf2(2,Gen6),
    Mf2(2,Gen6));

  Cput(&pave158(cc0,Gen6),0.,S34,S,Mf2(4,Gen6),Mf2(4,Gen6),
    Mf2(4,Gen6));

  Sub14797(Gen6) = pave149(Gen6) - 2*pave153(bb00,Gen6);

  Sub14798(Gen6) = pave147(Gen6) - 2*pave154(bb00,Gen6);

  Sub14799(Gen6) = pave148(Gen6) - 2*pave155(bb00,Gen6);

  Sub14807(Gen6) = (-9 + (24 - 32*SW2)*SW2)*
      pave154(bb00,Gen6) + 
     (-9 + (12 - 8*SW2)*SW2)*pave155(bb00,Gen6);

  Sub14755(Gen6) = Sub152*pave154(bb0,Gen6) - 
     2*Sub154*pave154(bb1,Gen6);

  Sub14759(Gen6) = Sub153*pave154(bb0,Gen6) - 
     2*Sub387*pave154(bb1,Gen6);

  Sub14756(Gen6) = Sub152*pave154(bb0,Gen6) - 
     2*Sub407*pave154(bb1,Gen6);

  Sub14816(Gen6) = (-9 + (24 - 32*SW2)*SW2)*
      pave154(bb1,Gen6) + (-9 + (12 - 8*SW2)*SW2)*pave155(bb1,Gen6)
    ;

  Sub14803(Gen6) = (9 + SW2*(-24 + 32*SW2))*
      pave154(bb1,Gen6) + (9 + SW2*(-12 + 8*SW2))*pave155(bb1,Gen6)
    ;

  Sub14793(Gen6) = SW2*
      (16*pave154(bb11,Gen6) + 4*pave155(bb11,Gen6)) - 
     6*pave154(bb11,Gen6) - 3*pave155(bb11,Gen6);

  Sub14818(Gen6) = (-9 + (24 - 32*SW2)*SW2)*
      pave154(bb11,Gen6) + 
     (-9 + (12 - 8*SW2)*SW2)*pave155(bb11,Gen6);

  Sub14805(Gen6) = (9 + SW2*(-24 + 32*SW2))*
      pave154(bb11,Gen6) + 
     (9 + SW2*(-12 + 8*SW2))*pave155(bb11,Gen6);

  Sub15213(Gen6) = pave154(bb0,Gen6) - 4*pave156(cc00,Gen6);

  Sub15233(Gen6) = SW2*
      (12*Mf2(2,Gen6)*pave157(cc0,Gen6) + 
        4*Mf2(4,Gen6)*pave158(cc0,Gen6)) - 
     3*(Mf2(2,Gen6)*pave157(cc0,Gen6) + 
        Mf2(4,Gen6)*pave158(cc0,Gen6));

  Sub14794(Gen6) = (-1 + 4*SW2)*pave153(bb11,Gen6) + 
     1/3.*Sub14793(Gen6);

  Sub14804(Gen6) = 3*(1 + SW2*(-4 + 8*SW2))*
      pave153(bb1,Gen6) + Sub14803(Gen6);

  Sub14806(Gen6) = 3*(1 + SW2*(-4 + 8*SW2))*
      pave153(bb11,Gen6) + Sub14805(Gen6);

  Sub14817(Gen6) = 3*(1 + SW2*(-4 + 8*SW2))*
      pave153(bb1,Gen6) - Sub14816(Gen6);

  Sub14819(Gen6) = 3*(1 + SW2*(-4 + 8*SW2))*
      pave153(bb11,Gen6) - Sub14818(Gen6);

  Sub15215(Gen6) = 3*pave153(bb0,Gen6) - 4*pave154(bb0,Gen6) + 
     pave155(bb0,Gen6);

  Sub15228(Gen6) = SW2*
      (12*pave153(bb0,Gen6) - 16*pave154(bb0,Gen6) + 
        4*pave155(bb0,Gen6)) + 6*pave154(bb0,Gen6) - 
     3*(pave153(bb0,Gen6) + pave155(bb0,Gen6));

  Sub15216(Gen6) = 3*pave153(bb1,Gen6) - 4*pave154(bb1,Gen6) + 
     pave155(bb1,Gen6);

  Sub14796(Gen6) = 3*pave153(bb1,Gen6) + 4*pave154(bb1,Gen6) + 
     pave155(bb1,Gen6);

  Sub15229(Gen6) = SW2*
      (12*pave153(bb1,Gen6) - 16*pave154(bb1,Gen6) + 
        4*pave155(bb1,Gen6)) + 6*pave154(bb1,Gen6) - 
     3*(pave153(bb1,Gen6) + pave155(bb1,Gen6));

  Sub14792(Gen6) = SW2*
      (12*pave153(bb1,Gen6) + 16*pave154(bb1,Gen6) + 
        4*pave155(bb1,Gen6)) - 6*pave154(bb1,Gen6) - 
     3*(pave153(bb1,Gen6) + pave155(bb1,Gen6));

  Sub15217(Gen6) = -4*pave156(cc00,Gen6) + 
     3*pave157(cc00,Gen6) + pave158(cc00,Gen6);

  Sub15230(Gen6) = SW2*
      (-16*pave156(cc00,Gen6) + 12*pave157(cc00,Gen6) + 
        4*pave158(cc00,Gen6)) + 6*pave156(cc00,Gen6) - 
     3*(pave157(cc00,Gen6) + pave158(cc00,Gen6));

  Sub15218(Gen6) = -4*pave156(cc12,Gen6) + 
     3*pave157(cc12,Gen6) + pave158(cc12,Gen6);

  Sub15231(Gen6) = SW2*
      (-16*pave156(cc12,Gen6) + 12*pave157(cc12,Gen6) + 
        4*pave158(cc12,Gen6)) + 6*pave156(cc12,Gen6) - 
     3*(pave157(cc12,Gen6) + pave158(cc12,Gen6));

  Sub15219(Gen6) = -4*pave156(cc2,Gen6) + 
     3*pave157(cc2,Gen6) + pave158(cc2,Gen6);

  Sub15232(Gen6) = SW2*
      (-16*pave156(cc2,Gen6) + 12*pave157(cc2,Gen6) + 
        4*pave158(cc2,Gen6)) + 6*pave156(cc2,Gen6) - 
     3*(pave157(cc2,Gen6) + pave158(cc2,Gen6));

  Sub15225(Gen6) = -4*Mf2(3,Gen6)*pave156(cc0,Gen6) + 
     3*Mf2(2,Gen6)*pave157(cc0,Gen6) + 
     Mf2(4,Gen6)*pave158(cc0,Gen6);

  Sub14800(Gen6) = SW2*
      (12*Sub14797(Gen6) + 16*Sub14798(Gen6) + 4*Sub14799(Gen6)) - 
     6*Sub14798(Gen6) - 3*(Sub14797(Gen6) + Sub14799(Gen6));

  Sub14791(Gen6) = 4*pave147(Gen6) + 3*pave149(Gen6) - 
     6*pave153(bb00,Gen6) - 8*pave154(bb00,Gen6) + Sub14799(Gen6);

    

  Sub14808(Gen6) = SW2*(-12 + 24*SW2)*Sub14797(Gen6) + 
     9*Mf2(4,Gen6)*pave155(bb0,Gen6) + Sub14786(Gen6) + 
     3*(Mf2(2,Gen6)*pave153(bb0,Gen6) + Sub14797(Gen6)) + 
     2*Sub14807(Gen6);

  Sub14758(Gen6) = Sub153*pave154(bb0,Gen6) + 
     (-4*MT2 + 2*(T + T14))*pave154(bb1,Gen6);

  ENDLOOP(Gen6)

}
