#if 0
* born.c
* form factors for {-F[2, {1}], F[2, {1}]} -> {-F[3, {3, Col3}], F[3, {3, Col4}], V[1]}
* generated by FormCalc 8.2 on 11-Apr-2013 14:53
#endif

#include "vars.h"
#include "inline.h"

inline vectortype DtoV(RealType d){
	v2complex ret;
	int k;
	for(k=0;k<nsse;k++){
		ret.c[k] = d;
	}
	return ret.v;
}

void born() {

#include "vars.h"

#include "inline.h"
#include "varsdef.h"
	/*#undef Ctree*/
	/*#define Ctree(i) formfactors.Ctree[i-1]*/
	/*#undef Cloop*/
	/*#define Cloop(i) formfactors.Cloop[i-1]*/

	Ctree(1) = Ctree(1) + 
     Alfa*Pi*(EL*(-(2/3.*cdiv(Sub14660,-DtoV(ME2) + Sub14661)) + 
          2/3.*cdiv(Sub14666,-DtoV(ME2) + Sub14667) + 
          4/9.*(cdiv(Sub14664,-DtoV(MT2) + Sub14665) + 
             1/CW2*cdiv(Sub14662,-DtoV(MT2) + Sub14663))));

#ifdef DEBUG
  DEB("born: Ctree(1) =", Ctree(1));
#endif

}
