#if 0
* abbr0h.c
* abbreviations for {-F[2, {1}], F[2, {1}]} -> {-F[3, {3, Col3}], F[3, {3, Col4}], V[1]}
* generated by FormCalc 8.1 on 6-Apr-2013 23:49
#endif

#include "vars.h"
#include "inline.h"


void abbr0h() {

#include "vars.h"

#include "inline.h"

  F32 = ChainV2(Spinor(1,-1,2),0,ec(5),k(3),1,Spinor(4,1,2))*
     Hel(1);

  F34 = -(ChainB2(Spinor(1,-1,2),0,ec(5),k(4),0,
        Spinor(3,-1,1))*Hel(1)*Hel(3));

  F7 = -(ChainV0(Spinor(4,1,2),0,0,Spinor(3,-1,1))*Hel(3));

  F12 = ChainB0(Spinor(4,1,2),0,0,Spinor(3,-1,1))*Hel(3);

  F35 = ChainV1(Spinor(1,-1,2),0,ec(5),0,Spinor(3,-1,1))*
     Hel(1)*Hel(3);

  F4 = ChainV1(Spinor(1,-1,2),0,ec(5),1,Spinor(4,1,2))*Hel(1)
   ;

  F20 = ChainV1(Spinor(1,-1,2),0,k(4),0,Spinor(2,1,1))*Hel(1)
   ;

  F8 = -(ChainB1(Spinor(1,-1,2),0,ec(5),0,Spinor(2,1,1))*
       Hel(1));

  F33 = ChainB1(Spinor(1,-1,2),0,ec(5),0,Spinor(3,-1,1))*
     Hel(1)*Hel(3);

  F6 = -(ChainB1(Spinor(1,-1,2),0,ec(5),1,Spinor(4,1,2))*
       Hel(1));

  F30 = -(ChainB1(Spinor(1,-1,2),0,k(3),0,Spinor(2,1,1))*
       Hel(1));

  F26 = -(ChainB1(Spinor(1,-1,2),0,k(4),0,Spinor(2,1,1))*
       Hel(1));

  F11 = ChainV1(Spinor(4,1,2),0,ec(5),0,Spinor(2,1,1));

  F21 = ChainV1(Spinor(4,1,2),0,ec(5),0,Spinor(3,-1,1))*Hel(3)
   ;

  F16 = ChainV1(Spinor(4,1,2),0,k(1),0,Spinor(3,-1,1))*Hel(3)
   ;

  F17 = ChainV1(Spinor(4,1,2),0,k(2),0,Spinor(3,-1,1))*Hel(3)
   ;

  F2 = ChainB1(Spinor(4,1,2),0,ec(5),0,Spinor(2,1,1));

  F36 = -(ChainV2(Spinor(1,-1,2),0,ec(5),k(4),0,
        Spinor(3,-1,1))*Hel(1)*Hel(3));

  F27 = -(ChainB2(Spinor(1,-1,2),0,ec(5),k(2),1,Spinor(4,1,2))*
       Hel(1));

  F31 = -(ChainB2(Spinor(1,-1,2),0,ec(5),k(3),1,Spinor(4,1,2))*
       Hel(1));

  F10 = -(ChainV0(Spinor(1,-1,2),0,0,Spinor(3,-1,1))*Hel(1)*
       Hel(3));

  F15 = ChainV0(Spinor(1,-1,2),0,1,Spinor(4,1,2))*Hel(1);

  F1 = -(ChainB0(Spinor(1,-1,2),0,0,Spinor(3,-1,1))*Hel(1)*
       Hel(3));

  F25 = -(ChainB0(Spinor(1,-1,2),0,1,Spinor(4,1,2))*Hel(1));

  F5 = -(ChainV0(Spinor(2,1,1),1,0,Spinor(3,-1,1))*Hel(3));

  F3 = ChainB0(Spinor(2,1,1),1,0,Spinor(3,-1,1))*Hel(3);

  F23 = ChainV0(Spinor(4,1,2),0,0,Spinor(2,1,1));

  F13 = ChainB0(Spinor(4,1,2),0,0,Spinor(2,1,1));

  F9 = ChainV1(Spinor(1,-1,2),0,ec(5),0,Spinor(2,1,1))*Hel(1)
   ;

  F29 = ChainV1(Spinor(1,-1,2),0,k(3),0,Spinor(2,1,1))*Hel(1)
   ;

  F22 = -(ChainB1(Spinor(4,1,2),0,ec(5),0,Spinor(3,-1,1))*
       Hel(3));

  F18 = -(ChainB1(Spinor(4,1,2),0,k(1),0,Spinor(3,-1,1))*
       Hel(3));

  F19 = -(ChainB1(Spinor(4,1,2),0,k(2),0,Spinor(3,-1,1))*
       Hel(3));

  F28 = ChainV2(Spinor(1,-1,2),0,ec(5),k(2),1,Spinor(4,1,2))*
     Hel(1);

  F24 = ChainV2(Spinor(4,1,2),0,ec(5),k(1),0,Spinor(2,1,1));

  F14 = ChainB2(Spinor(4,1,2),0,ec(5),k(1),0,Spinor(2,1,1));

  Pair1 = Pair(ec(5),k(1));

  Pair2 = Pair(ec(5),k(2));

  Sub8 = F23*F33 + (F12 - F7)*F8;

  Sub12 = F3*F4 + (-F12 + F7)*F9;

  Sub373 = (F16 + F17)*F8 + F1*(F24 - 2*F23*(Pair1 + Pair2));

  Sub16 = 1/SW2*((1 - 2*SW2)*Sub12 + 2*SW2*Sub8);

  Sub14752 = F31*F5 - F17*F8 - F19*F8;

  Sub14758 = F13*F36 - F17*F9 - F19*F9;

  Sub13 = -(F20*F21) - F21*F29 - F16*F9 + 
     F3*(-F32 + F15*(2*Pair1 + 2*Pair2));

  Opt47 = -(F22*F29) + F21*(-F29 - F30) - F22*F30;

  Sub19 = F17*F8 + F23*(-F34 + MT*F33);

  Sub20 = F17*F9 + F3*(-F32 - MT*F4);

  Sub14507 = -(F18*F9) + 2*F15*F3*(Pair1 + Pair2);

  Sub11914 = F22*F26 - 2*F25*F5*(Pair1 + Pair2);

  Sub2044 = -((F18 + F19)*F9) + 
     F10*(-F14 + 2*F13*(Pair1 + Pair2));

  Sub3321 = 1/SW2*((-1 + 2*SW2)*Sub13 + MT*SW2*Sub16);

  Sub183 = F22*(F26 + F30) + F31*F5 + F18*F8;

  Sub28 = F1*F2 - F5*F6 - F12*F8 + F7*F8;

  Sub31 = F10*F11 - Sub12;

  Sub2760 = F1*F24 + F3*(-F28 + 2*F15*Pair2);

  Sub3 = -(F21*F29) - F28*F3 + 2*F15*F3*Pair2;

  Sub9 = F21*(F26 + F30) + F16*F8 - 
     F23*(-F34 + 2*F1*(Pair1 + Pair2));

  Sub29 = F21*F26 + Sub373;

  Sub10404 = F3*F32 + F23*F34 + F13*F36 + F31*F5;

  Sub1152 = -(F23*F34) - Sub14752;

  Sub1151 = F3*F32 + Sub14758;

  Sub32 = -(F20*F21) + F28*F3 - F16*F9 - F17*F9 + 
     2*F15*F3*Pair1;

  Opt19 = (F16 + F17)*(F8 + F9);

  Sub14 = F5*F6 + (F12 - F7)*F8;

  Sub10 = F13*F35 + (-F12 + F7)*F9;

  Sub22 = F19*F9 + F13*(-F36 + MT*F35);

  Sub5 = 1/SW2*((-1 + 2*SW2)*(F10*F11) + (1 - 2*SW2)*(F3*F4) + 
       SW2*(-2*F1*F2 + 2*F5*F6));

  Sub21 = 1/SW2*(2*SW2*Sub19 + (-1 + 2*SW2)*Sub20);

  Sub6 = 1/SW2*(SW2*(-2*F1*F24 + 2*F21*F30) + (1 - 2*SW2)*Sub3)
   ;

  Sub34 = 1/SW2*(2*SW2*Sub28 + (1 - 2*SW2)*Sub31);

  Sub35 = 1/SW2*(2*SW2*Sub29 + (1 - 2*SW2)*Sub32);

  Sub2805 = (F21 + F22)*(F20 + F26);

  Sub7918 = F27*F5 - F18*F8 - F19*F8;

  Sub23 = -(F19*F8) + F5*(F31 + MT*F6);

  Sub33 = F22*F26 + (F18 + F19)*F8 + F5*(-F27 - 2*F25*Pair1);

  Sub4 = F22*F30 + F5*(F27 - 2*F25*Pair2);

  Sub30 = -(F20*F22) + Sub2044;

  Sub17 = Sub3321 - 2*Sub9;

  Sub25 = F23*F33 + F13*F35 - F3*F4 - F5*F6;

  Sub346 = F21*(-F29 - F30) + Sub2760;

  Sub15 = -2*F25*F5*(Pair1 + Pair2) + Sub183;

  Sub349 = F10*F14 - F22*F29 - Sub4;

  Sub11 = -(F20*F22) - F22*F29 - F18*F9 + 
     F13*(-F36 + F10*(2*Pair1 + 2*Pair2));

  Sub593 = Sub1151 - Sub1152;

  Sub3485 = F20*(-F21 - F22) - F21*F26 - F18*F8 + 
     F16*(-F8 - F9) + Opt47 + 2*F1*F23*Pair1 + 2*F1*F23*Pair2 + 
     F10*F13*(2*Pair1 + 2*Pair2) - Sub10404 - Sub11914 + Sub14507;

    

  Sub18 = (4 - 8*SW2)*Sub11 + 8*SW2*Sub15 + 
     (3 - 4*SW2)*Sub17 + MT*((4 - 8*SW2)*Sub10 + 8*SW2*Sub14);

  Sub24 = (3 - 4*SW2)*Sub21 + (4 - 8*SW2)*Sub22 + 8*SW2*Sub23
   ;

  Sub36 = (-4 + 8*SW2)*Sub30 - 8*SW2*Sub33 + 3*MT*Sub34 + 
     (3 - 4*SW2)*Sub35;

  Sub7 = (-4 + 8*SW2)*(F10*F14) + (4 - 8*SW2)*(F22*F29) - 
     8*SW2*Sub4 + 3*MT*Sub5 + (3 - 4*SW2)*Sub6;

  Sub26 = Sub593 - MT*Sub25;

  Sub2 = Sub346 + Sub349;

  Sub1 = -(F1*F24) + F28*F3 - F18*F9 - F19*F9 - Opt19 + 
     2*F1*F23*Pair1 + 2*F15*F3*Pair1 + 2*F25*F5*Pair1 + 
     2*F1*F23*Pair2 + F10*(-F14 + F13*(2*Pair1 + 2*Pair2)) - 
     Sub2805 + Sub7918;

  Sub27 = -Sub3485 - MT*Sub25;

  Sub14831 = Sub36/(-MZ2 + S) + 8*CW2*Sub1/S;

  Sub14829 = Sub7/(-MZ2 + S) + 8*CW2*Sub2/S;

  Sub14833 = Sub18/(-MZ2 + S34) + 8*CW2*Sub27/S34;

  Sub14827 = Sub24/(-MZ2 + S34) + 8*CW2*Sub26/S34;

}
