#if 0
* abbr1h17.c
* abbreviations for {-F[2, {1}], F[2, {1}]} -> {-F[3, {3, Col3}], F[3, {3, Col4}], V[1]}
* generated by FormCalc 8.1 on 6-Apr-2013 23:49
#endif

#include "vars.h"
#include "inline.h"


void abbr1h17() {

#include "vars.h"

#include "inline.h"

  Sub14916 = Finite*Sub450 + 2*Sub565*pave19(bb1);

  Sub15735 = Sub15734*Sub9172 + Sub2*pave39(cc0);

  Sub15251 = 1/MW2*Sub15250 - 
     1/CW2*((2*Sub3823 + CW2*MT*Sub3820)*pave43(cc0));

  Sub15148 = MT2*MT2*(2*Sub3684*pave33(cc0) - 
        Sub3584*pave50(cc0)) + 
     MT*MT2*(-(Sub3687*pave33(cc0)) + Sub3586*pave50(cc0));

  Sub15024 = MT*Sub15023 + MT2*(Sub3594*pave57(cc0));

  Sub15159 = Sub15146 + Sub3857*pave58(cc0);

  Sub15224 = 1/MW2*(Sub15223 + MW2*(Sub2654*pave76(cc00)));

  Sub15203 = MT2*Sub15202 + Sub2458*pave34(cc1);

  Sub15359 = Sub15358 + 
     (-Abb28 - Pair1*Sub150 + Pair2*Sub152)*pave77(cc1);

  Sub15041 = Sub15040 - Sub938*pave77(cc1);

  Sub15064 = Sub15063 - Sub938*pave78(cc1);

  Sub15292 = Sub3277*(-(2*SW2*pave37(cc1)) + pave37(cc1)) + 
     Sub3158*pave81(cc0);

  Sub15183 = 1/CW2*(-(9*CW2*Sub15182) + Sub1337*pave76(cc1));

  Sub15239 = Sub3847*pave89(cc0) + Sub3865*pave89(cc1);

  Sub15222 = Sub2655*pave29(bb0) + Sub2767*pave36(cc12);

  Sub15096 = MT*(Pair3*Sub2613*pave38(cc11)) + 
     Sub2625*pave38(cc12);

  Sub15152 = 1/SW2*(3*Sub15151 - SW2*(Sub1690*pave50(cc12)));

  Sub15166 = 2*Sub1366*pave92(cc00) - Sub1695*pave92(cc12);

  Sub15268 = 1/MW2*(MW2*(Sub1510*pave29(bb0)) + 
       Sub2245*pave76(cc12));

  Sub15221 = 1/MW2*(MW2*((F20 + F26)*Sub2756*pave76(cc12)) + 
       Sub2474*pave36(cc1));

  Sub15343 = MT*((F12 - F7)*Sub228*Sub538*Sub819*
        pave79(cc11) - Sub1330*pave79(cc12));

  Sub15295 = MT2*((-3*F12 + 3*F7)*Sub15294) + 
     4*Sub1339*pave79(cc12);

  Sub15365 = Sub2856*pave57(cc1) + Sub1065*pave57(cc12);

  Sub15329 = (-9*F12 + 9*F7)*Sub228*Sub536*Sub815*
      pave80(cc11) + Sub1329*pave80(cc12);

  Sub15004 = SW2*(Finite*Sub1383) + MT*(Sub3648*pave80(cc12))
   ;

  Sub15373 = 1/(MW2*SW2)*
     (MW2*SW2*(Finite*Sub2801) + MT*(Sub1326*pave80(cc12)));

  Sub15061 = 1/SW2*(SW2*(Finite*Sub2818) + 
       MT*(Sub3662*pave80(cc12)));

  Sub15386 = (F12 + F7)*Sub15385 + 2*CW2*(Sub2605*pave52(cc2))
   ;

  Sub15089 = Sub928*pave48(cc1) + Sub2222*pave73(cc2);

  Sub15193 = (-2*Sub148*Sub2603 + MT*Sub2602)*pave74(cc1) + 
     Sub2650*pave74(cc2);

  Sub15242 = -(2*(SW2*SW2)*(Sub1670*pave72(cc2))) + 
     (Sub1662 - 4*SW2*Sub359)*pave45(cc2);

  Sub15094 = (F29 + F30)*Sub15093 + Sub2804*pave48(cc2);

  Sub15102 = (2*MT2*Sub2 + MT*(Sub287*Sub509))*pave33(cc2) + 
     Sub2660*pave50(cc2);

  Sub15522 = Sub11836*pave44(cc2) + Sub12090*pave53(cc2);

  Sub15002 = Sub3647*pave82(cc2) + Sub3622*pave83(cc2);

  Sub15262 = Sub15239 - Sub3871*pave89(cc2);

  Sub15092 = 1/(MW2*SW2)*
     (32*MW2*SW2*Sub15091 + 9*MT*(Sub2613*pave32(cc22)));

  Sub15104 = MT*MT2*(Sub948*pave33(cc22)) + 
     Sub2639*pave32(cc12);

  Sub15170 = MW2*(Sub1108*pave61(cc12)) - Sub3819*pave61(cc22)
   ;

  Sub15204 = Sub2671*pave34(cc22) + Sub2643*pave88(cc00);

  Sub15271 = (Sub1627*Sub37 + Sub1628*Sub39)*pave36(cc00) + 
     (Sub2196*Sub37 + Sub2192*Sub39)*pave36(cc22);

  Sub15210 = Sub2671*pave65(cc11) + 
     (Abb18*Sub1346 + MT*(Pair4*Sub2768))*pave65(cc22);

  Sub15231 = Sub1613*pave68(cc11) + Sub2108*pave68(cc22);

  Sub15347 = Sub3229*pave44(cc11) + Sub3328*pave44(cc22);

  Sub15121 = Sub2656*pave92(cc12) + 
     (F29 + F30)*Sub2497*pave92(cc22);

  Sub15273 = 1/(MW2*SW2)*
     (MW2*SW2*(Finite*Sub1620) + Sub1350*pave76(cc22));

  Sub15348 = MT2*((-3*F12 + 3*F7)*Sub2887*pave71(cc2)) - 
     4*Sub3238*pave79(cc22);

  Sub15315 = Sub1043*pave56(cc12) + Sub3274*pave56(cc22);

  Sub15045 = 2*Sub1022*pave56(cc1) - Sub992*pave56(cc22);

  Sub15318 = Sub3348*pave57(cc1) + Sub3262*pave57(cc22);

  Sub15054 = Sub967*pave57(cc12) - Sub992*pave57(cc22);

  Sub15377 = (-9*F12 + 9*F7)*Sub228*Sub538*Sub815*
      pave80(cc11) - Sub3245*pave80(cc22);

  Sub15067 = -(MT*(F7*Sub37*Sub992*pave80(cc22))) - 
     MT*(F12*Sub39*Sub992*pave80(cc22)) + 2*Sub3494*pave80(cc00);

  Sub15630 = (F20 + F29)*Sub15629 + Sub4121*pave119(dd002);

  Sub15706 = F15*F3*(Abb115 - 2*Abb139 - Pair2*Sub4099)*
      pave132(dd0) + Sub9014*pave132(dd11);

  Sub15524 = 1/(CW2*MW2)*
     (MT*MT2*(Sub11405*Sub15523) + 
       CW2*MW2*(Sub5572*pave134(dd112)));

  Sub15561 = Sub4199*pave125(dd112) + Sub7796*pave2(dd112);

  Sub15585 = Sub4394*pave126(dd112) + Sub5429*pave127(dd112);

  Sub15529 = Sub6164*pave128(dd112) + Sub6374*pave3(dd112);

  Sub15588 = -2*Sub11452*Sub15587 + Sub11404*pave118(dd12);

  Sub15764 = Sub8476*pave135(dd11) + Sub8151*pave135(dd12);

  Sub15678 = Sub6084*pave130(dd112) + Sub6054*pave131(dd122);

  Sub15598 = -(Sub6165*pave128(dd122)) + Sub6094*pave3(dd122)
   ;

  Sub15424 = (F8 + F9)*Sub15423 + Sub4188*pave1(dd13);

  Sub15512 = Sub5572*pave134(dd113) + Sub5925*pave134(dd133);

  Sub15593 = 1/MW2*(Sub15592 - MW2*(Sub14795*pave117(dd2)));

  Sub15597 = Pair3*Sub14646*pave95(dd22) + 
     Sub14813*pave95(dd23);

  Sub15765 = Sub8377*pave135(dd13) + Sub8693*pave135(dd23);

  Sub15795 = Sub6956*pave140(dd13) + Sub6977*pave140(dd23);

  Sub15533 = Sub11377*pave139(dd002) + 
     Pair4*Sub7160*pave139(dd233);

  Sub15534 = -18*Sub15531 - 2*Sub15532 + 6*Sub15533 + 
     3*MT2*(Sub11800*pave118(dd33));

  Sub14852 = (16*Sub14848)/(S*S) + Sub14851/Power(-MZ2 + S,2)
   ;

  Sub10279 = Sub10152 + MT2*(3*F21*F30 + 2*F27*F5) + 
     MT*Sub10139;

  Sub10521 = 1/(CW2*MW2)*
     (2*MW2*Sub10508 + CW2*(Sub10513 + MT*MW2*Sub10520));

  Sub11613 = 1/MW2*(Sub11612 + MW2*(2*Sub11608 + MT*Sub11609))
   ;

  Sub1187 = MB2*Sub1180 + MT2*Sub1184 + 2*MT*Sub1186;

  Sub11901 = -2*(F18 + F19)*(F20 + F26 + F29 + F30)*Pair4 + 
     F22*Sub11897 + 2*Sub11900;

  Sub12026 = 2*MW2*Sub12014 + MB2*(-Sub12014 + Sub12016) - 
     MT2*Sub12022;

  Sub12029 = 2*Sub12025 + 
     1/MW2*(Sub12026 + MT*(-Sub12028 - 2*MW2*Sub12009));

  Sub12051 = (F21 + F22)*Sub11897 - 
     2*(F20 + F26 + F29 + F30)*Sub12049 + 2*Sub12050;

  Sub12069 = (F21 + F22)*Sub11897 + 2*Sub12050 - 
     2*(F20 + F26 + F29 + F30)*Sub12068;

  Sub12087 = 2*Sub12076 + 
     1/MW2*(Sub12085 + MT*(-Sub12086 + 2*MW2*Sub12077));

  Sub12143 = 2*Sub12139 - 2*Sub12141 - F21*Sub12142 - 
     F22*Sub12142;

  Sub12361 = 2*Sub12342 + 
     1/MW2*(Sub12360 + MT*(-(2*MW2*Sub12348) + MB2*Sub12358));

  Sub12580 = Sub12471 + MT2*(Sub12439 - Sub12442) + 
     MZ2*Sub12442;

  Sub12582 = Sub12576 + MT2*(Sub12550 - Sub12551) + 
     MZ2*Sub12551;

  Sub13334 = 1/MW2*(MW2*(F21*(F20 + F26)*(-2*MT2 + S)) + 
       MT2*Sub13332);

  Sub13451 = -2*Sub13450 + 2*MT2*Sub11830 - MT*Sub13446;

  Sub14255 = Sub13614 + 2*MZ2*(F15*F3*Pair2) + MT*(S*Sub12);

  Sub14253 = Sub13616 + 2*MZ2*(F10*F13*Pair2) - MT*(S*Sub10);

  Sub13817 = (F20 + F29)*(-4*(F18 + F19)*Pair2 + F22*S) + 
     F13*(6*Abb112*F10 - Sub13815) - F9*Sub13816;

  Sub13820 = (F20 + F29)*(-4*(F16 + F17)*Pair2 + F21*S) + 
     F3*(6*Abb112*F15 - Sub13818) - F9*Sub13819;

  Sub13879 = 2*Sub13876 + (F21 + F22)*Sub13877 - 2*Sub13878;

  Sub14136 = -Sub14132 + 2*F29*Sub14135 + 2*F30*Sub14135 - 
     MT*Sub14128;

  Sub1449 = 1/MW2*(MT2*((F10*F13 + F25*F5)*Sub1446) + 
       MW2*(Sub1447 + (-MB2 - 3*MT2 + MW2)*Sub1443));

  Sub13169 = 2*Sub13167 + MT*Sub13168 + 
     MT2*((-4*(Pair1 + Pair2) + 4*(Pair3 + Pair4))*Sub148);

  Sub14254 = Sub13612 + 2*MZ2*(F25*F5*Pair2) + MT*(S*Sub2046)
   ;

  Sub12618 = 1/MW2*(-Sub12617 + 2*MW2*(Sub12442 + MT*Sub2352))
   ;

  Sub13204 = 1/MW2*(Sub13203 + 2*MW2*(Sub13202 + MT*Sub2352))
   ;

  Sub2466 = -(4*MW2*Sub2459) + MT2*Sub2462 + 
     MB2*(2*Sub2459 + Sub2464);

  Sub14043 = Sub14038 + MT2*(3*F21*(F29 + F30) - 2*Sub14026) + 
     MW2*Sub2534;

  Sub15288 = 2*Sub1374*Sub15286 - 2*Sub14997*Sub2528 + 
     Sub15287*Sub2560;

  Sub2974 = Sub150*Sub2970 - 2*Sub2971 + 2*F13*Sub2973;

  Sub2978 = Sub150*Sub2975 - 2*Sub2976 + 2*F3*Sub2977;

  Sub13955 = 2*S*Sub12138 - 2*Sub13954 + 
     (F21 + F22)*(F29 + F30)*Sub317;

  Sub1558 = 8*Sub1551 - MT2*Sub1557 + MT*(Sub1553*Sub327);

  Sub3429 = F7*((MB2 - MT2 + 2*MW2)*F45 + 
        (-MT2 + 2*MW2)*F46) + 
     (-MB2 + MT2 - 2*MW2)*(F12*(F45 + F46)) + MT2*Sub3427 + 
     MB2*(F46*F7 - Sub3428) - 2*MW2*Sub3428;

  Sub3487 = MH2*Sub3485 + MT2*(2*Sub3454 - 2*Sub3485) - 
     MT*Sub3486;

  Sub3534 = 4*Sub3518 - MT*Sub3532 - MT2*Sub3533;

  Sub3551 = 4*Sub3518 - MT2*Sub3547 - MT*Sub3550;

  Sub3617 = 2*Sub3610 - 1/MW2*Sub3613 - 
     MT/MW2*(-Sub3616 - 2*MW2*Sub3611);

  Sub3733 = 8*F1*(MT2*F24 + MT*(F2*Sub2200)) + MT2*Sub3729 - 
     MT*Sub3732;

  Sub4265 = F30*Sub1686 - F1*Sub4254 + MT*Sub4230;

  Sub2519 = 1/MW2*(Sub2518 + 
       MW2*(Sub2514 + MT*(Sub2513*Sub431)));

  Sub2813 = MT*(-MB2 + 2*MW2)*(Sub327*Sub431) + 
     MT2*(Sub2812 + 2*MT2*Sub2810);

  Sub4376 = Sub4323 + (-MB2 + MW2)*(F1*F24 + F21*F26) + 
     MT2*Sub4310;

  Sub7942 = Sub4323 + (-MT2 + MZ2)*(F1*F24) + MZ2*(F21*F26) + 
     MT2*(-(F21*F26) + Sub4310);

  Sub7941 = Sub4331 + (-MT2 + MZ2)*(F20*F21) - MZ2*(F28*F3) + 
     MT2*(F28*F3 + Sub4304);

  Sub4384 = -Sub4339 - MT2*Sub4308 - MB2*Sub4309 + MW2*Sub4309
   ;

  Sub4378 = -Sub4342 + 
     (-2*MB2 + 2*(MT2 + MW2))*(F10*F13*Pair3) + (MB2 - MW2)*Sub4306
    ;

  Sub4375 = Sub4347 + MT2*Sub4301 + (-MB2 + MW2)*Sub4302;

  Sub4571 = 1/MW2*(MB2*MT*
        ((F29 + F30)*(F39 + F40 - 3*F7*Pair3)) + 
       MW2*(Sub4568 + (2*MB2 + MT2)*((F1*F23 + F15*F3)*Pair3)));

  Sub4691 = -Sub4676 + MZ2*Sub2807 + MT2*(-Sub2807 - Sub4645)
   ;

  Sub4693 = -Sub4681 + (-MT2 + MZ2)*Sub2808 - MT*Sub4664;

  Sub4810 = 1/MW2*(Sub4809 + 
       MW2*(-2*Sub4808 + 2*(Sub4676 + MT2*Sub4645)));

  Sub5279 = -(F18*Sub5274) + 2*Sub5276 + MT*Sub5263;

  Sub5411 = 4*Abb106*F15*F3 + 2*Sub5409 + F16*Sub5410;

  Sub5511 = F16*Sub5501 + F3*(4*Abb161*F15 + 2*Sub5509) - 
     2*F21*Sub5510;

  Sub5552 = 4*Sub5549 + 2*MT*Sub5537 - MT2*Sub5551;

  Sub5981 = 2*Abb58*F1*F23 - F21*Sub5978 - 2*Sub5980;

  Sub6225 = -Sub6137 + 2*MT2*Sub6200 - MT*Sub6206;

  Sub6259 = F16*Sub6254 - F3*Sub6257 + F21*Sub6258;

  Sub6278 = F18*Sub6274 + F5*Sub6276 - F22*Sub6277;

  Sub6336 = -Sub6278 + MT2*Sub6314 - MT*Sub6322;

  Sub7041 = -(F20*F21*Sub538) - F16*F9*Sub538 - 
     2*F15*F3*Sub6368 + MT*(Sub243*Sub538);

  Sub6514 = (F20*F21 + F16*F9)*Sub538 + 2*F15*F3*Sub6368;

  Sub6369 = (2*F20*F21 + F16*F9)*Sub538 + 4*F15*F3*Sub6368;

  Sub6370 = (2*F22*F26 + F18*F8)*Sub538 + 4*F25*F5*Sub6368;

  Sub6758 = Sub6746 + MT2*
      (F20*(-4*F21 + 4*F22) + (4*F21 - 4*F22)*F29) + MT*Sub6737;

  Sub6762 = -Sub6751 + 
     MT2*(F22*(4*F26 - 4*F30) + F21*(-4*F26 + 4*F30)) + MT*Sub6735;

    

  Sub8362 = 2*Sub7024 + F22*(F30*(-MH2 + MT2) + Sub7025) - 
     2*Sub7027;

  Sub7366 = F22*Sub7342 + 
     F10*(F13*(Abb41 + Sub4776) + MT2*F14) + MT2*((F18 + F19)*F9);

    

  Sub7345 = F21*Sub7342 + F3*Sub7344 + MT2*((F16 + F17)*F9);

  Sub7400 = 1/CW2*(2*Sub7389 + 
       CW2*MT2*(-9*Sub7399 + 9*MT2*Sub7393));

  Sub7495 = Sub7023 + (-MT2 + MZ2)*(F22*F29) + MT*Sub7429;

  Sub747 = 1/CW*(-Sub744 + CW*(4*Sub743 + MT*Sub746));

  Sub13064 = F22*Sub13060 + 2*Sub13063 - F20*Sub7578;

  Sub7617 = F29*(F12*(-6*Pair3 - 12*Pair4) + 
        F7*(6*Pair3 + 12*Pair4)) + Sub7616 + 
     (6*MT2 - 3*MZ2)*(F10*F11) + (-6*MT2 + 3*MZ2)*(F3*F4);

  Sub9099 = F1*Sub7681 + 2*Sub7682 + 
     MT*((MB2 - MW2)*(F5*F6) + (-MB2 + MW2)*(F7*F8));

  Sub7703 = Sub7677 + (-MT2 + MZ2)*(F22*F30) + MT*Sub7702;

  Sub7854 = Sub7819 + (-MT2 + MZ2)*
      (-(F27*F5) + (F18 + F19)*F8) + MT2*Sub7805;

  Sub7887 = 2*Pair4*Sub7876 - 2*MT2*Sub7883 - MT*Sub7886;

  Sub7944 = Sub7892 + (-MT2 + MZ2)*(F10*F14 + F20*F22) + 
     MT*Sub7898;

  Sub14256 = Sub13610 + 2*MZ2*(F1*F23*Pair2) - MT*(S*Sub8);

  Sub12806 = 1/CW2*(-(Sub12784*Sub801) - Sub12805*Sub802 + 
       9*CW2*MT2*Sub12797);

  Sub2015 = 2*Pair4*Sub2010 + Sub2014*Sub801 + 4*Sub2005*Sub802
   ;

  Sub2593 = Sub2590*Sub801 + Sub2591*Sub802 + 3*MT2*Sub2592;

  Sub8096 = -Sub8092 + MT*Sub8094 - MT2*Sub8095;

  Sub8144 = 16*Sub8125 + 8*(F20*Sub8124 + MT*Sub8118) - 
     MT2*Sub8143;

  Sub8239 = -Sub8236 + (-4*MT2 + 2*MZ2)*(F10*F13*Pair4) + 
     MT*Sub8213;

  Sub2550 = Sub2548*Sub801 + Sub2549*Sub802 + 
     4*MT*(Pair4*(Sub2515*Sub809 + Sub2509*Sub825));

  Sub8286 = -Sub8284 + MT2*Sub8256 - MT*Sub8260;

  Sub8437 = -Sub8418 - MT2*Sub8411 + MT*Sub8421;

  Sub8429 = 4*Abb167*F10*F13 - F20*Sub8424 + 2*Sub8428;

  Sub8434 = 4*Abb167*F1*F23 - F26*Sub8430 + 2*Sub8433;

  Sub8764 = F17*Sub8761 - F3*Sub8763 + MT2*Sub8760;

  Sub8856 = -(F13*Sub8853) + F12*Sub8854 - 2*F3*Sub8855;

  Sub10614 = -Sub10567 + 
     F5*(-(MT2*Sub8910) + MT*(Sub10610 + MT2*F6));

  Sub8920 = F19*Sub8839 + F13*Sub8841 + MT2*(F3*Sub8911);

  Sub3467 = 4*(2*Sub3455 + MT2*(-Sub184 - Sub185)) + 
     1/MW2*(Sub3458*Sub913 + MT2*Sub3464 + 
        MT*(Sub3466 + 2*MW2*Sub3463));

  Sub9238 = -Sub9202 + MT2*Sub9231 - MT*Sub9232;

  Sub9425 = -Sub9419 + Sub9424 + 
     MT2*(F20*(4*F21 - 4*F22) + (-4*F21 + 4*F22)*F29);

  Sub13093 = 1/MW2*(Sub13092 + 2*MW2*(Sub13088 + MT*Sub149));

  Sub9639 = -Sub9635 - MT2*Sub9619 + MT*Sub9626;

  Sub9722 = 1/(CW2*MW2)*
     (F20*Sub9721 + CW2*MW2*(Sub9712 + MT2*Sub9707));

  Sub682 = 1/CW*(Sub107*Sub32 + 
        CW*(SW*(Sub681 + MT*(Sub149*Sub676))))/SW;

  Sub697 = 1/CW*(Sub696 + CW*((4*Sub694 - 4*Sub695)*SW))/SW;

  Sub714 = 1/(CW*(CW2*CW2))*
     (-Sub710 + CW*CW2*(SW*(2*Sub713 + 16*CW2*Sub711)))/SW;

  Sub734 = MT*Sub732 + 
     1/CW*(Sub729/SW - 4*(Sub733 + CW*Sub728));

  Sub14750 = 1/(CW2*MW2)*
     (MT2*MW2*(12 - 32*SW2)*(Pair3*Sub1044) + 
       CW2*(3*Sub14749 + MT*MW2*Sub14746));

  Sub14741 = 1/(CW2*MW2)*
     (MT2*MW2*(-12 + 32*SW2)*(Pair4*Sub1044) + 
       CW2*(3*Sub14740 + MT*MW2*Sub14737));

  Sub15495 = 1/(CW2*MW2)*
     (MW2*((F20 + F26 + F29 + F30)*(Pair1 + Pair2)*Sub15487*
          ((-24 + 64*SW2)*F12 + (24 - 64*SW2)*F7)) + 
       CW2*(-3*Sub15494 + 9*MW2*Sub15493));

  Sub1365 = 1/MW2*(2*Pair3*Sub1362 + 
       MW2*(MT*Sub1357 + (-6 + 8*SW2)*Sub1364));

  Sub14222 = 4*Sub14218 + MT*Sub14220 + (-3 + 4*SW2)*Sub14221
   ;

  Sub1969 = 1/MW2*(Sub1964 + 
       MW2*((-6 + 8*SW2)*Sub1965 + 2*MT*Sub1968));

  Sub3314 = Sub8*Sub903 + Sub2046*Sub905 + 
     (3 - 4*SW2)*(Sub3308 + MT2*Sub3303);

  Sub7838 = 1/CW2*(2*F10*F13*(Pair1 + Pair2)*Sub3931 + 
       CW2*((-9 + 12*SW2)*(F29*Sub1687) + 
          (9 - 12*SW2)*(F10*Sub4253) + MT*(9*Sub4219 + 3*Sub7837)))
    ;

  Sub8505 = (3 - 4*SW2)*Sub4342 + MT2*Sub8503 - MT*Sub8504;

  Sub8509 = (-3 + 4*SW2)*Sub4354 + MT2*Sub8507 + MT*Sub8508;

  Sub8312 = (3 - 4*SW2)*Sub8309 + MT2*Sub8310 - MT*Sub8311;

  Sub8318 = MT2*Sub8315 + (3 - 4*SW2)*Sub8316 + 
     MT*(3*Sub8293 + Sub8317);

  Sub8471 = F29*Sub8468 + (-6 + 8*SW2)*Sub6441 + 
     MT*(3 - 4*SW2)*Sub8469 - MT2*Sub8470;

  Sub2189 = Pair4*Sub2185 + MT2*Sub2188 + 
     (MW2*(6 - 8*SW2) + MB2*(3 - 4*SW2))*(Sub1048*Sub970);

  Sub2595 = 2*Power(3 - 4*SW2,2)*Sub2574 + 1/MW2*Sub2593 - 
     6*(3 - 8*SW2)*Sub2594;

  Sub4786 = Sub4785 - 2*Power(3 - 4*SW2,2)*
      (-Sub4754 + MT2*Sub4746) + 1/MW2*(-Sub4782 + 3*MT2*Sub4783);

    

  Sub10989 = 8*Sub10969 + (3 - 4*SW2)*Sub10987 + 
     (1 - 2*SW2)*Sub10988;

  Sub11739 = -2*F30*Sub11735 + (1 - 2*SW2)*(F29*Sub11734) + 
     MT*Sub11738;

  Sub12902 = 8*Sub12891 + (-3 + 4*SW2)*Sub12900 + 
     (-1 + 2*SW2)*Sub12901;

  Sub1722 = 2*Sub1271 + MT*Sub1720 + (-1 + 2*SW2)*Sub1721;

  Sub5666 = MT2*Sub5622 + (1 - 2*SW2)*Sub5663 + MT*Sub5665;

  Sub6985 = -2*Sub6983*Sub814 + 
     MB2*MT*(6 - 4*SW2)*(F12*F29*Pair4) + MT2*Sub6984;

  Sub4374 = 4*F1*F23*Sub4371*Sub814 + 
     MT2*(-Sub4373 + MT2*(3 - 2*SW2)*Sub4311);

  Sub4429 = 1/MW2*(-2*Sub4426 + 
       MW2*(MT*Sub4418 + (-3 + 2*SW2)*Sub4428));

  Sub4540 = 2*Sub4538 - MT*Sub4539 + 
     (3 - 2*SW2)*(MT2*Sub4508 + MW2*Sub4510);

  Sub6860 = (Pair1 + Pair2)*Sub6858 + 
     MT2*(-3 + 2*SW2)*(F10*F13*Sub6822) + MT*Sub6859;

  Sub7240 = 1/MW2*(2*Sub7239 + 
       MW2*(Sub7237 + (-3 + 2*SW2)*(Sub7216 + MT2*Sub7193)));

  Sub8063 = -4*F1*F23*Sub5791*Sub814 + 
     F30*(Sub8062 + 2*Sub5792*Sub814) + 
     MT2*(MT*(-3 + 2*SW2)*Sub8050 + (3 - 2*SW2)*Sub8054);

  Sub10284 = 8*Sub10280 + 
     1/(SW2*SW2)*(Sub10283 + MT*(-Sub10281 - 8*(SW2*SW2)*Sub10141))
    ;

  Sub8042 = 1/(SW2*SW2)*
     (Sub8041 + SW2*SW2*(48*F3*Sub4696 + 96*MT2*(F12*F9) + 
          (48 - 64*SW2)*Sub8039));

  Sub8756 = 1/(SW2*SW2)*
     (MT*(9 - 24*SW2)*Sub8690 + 
       SW2*SW2*(-16*(F20*Sub8718 + F9*Sub8725 + F10*Sub8726) + 
          MT2*Sub8755));

  Sub10760 = 1/(SW2*SW2)*
     ((-9 + 12*SW2)*(F3*Sub10758) + 
       SW2*SW2*(16*Sub10695 - MT*Sub10759));

  Sub6534 = 8*Sub6506 - Power(3 - 4*SW2,2)/(SW2*SW2)*Sub6514 - 
     MT*Sub6533;

  Sub8520 = 8*Sub8429 - Power(3 - 4*SW2,2)/(SW2*SW2)*Sub8415 - 
     MT*Sub8519;

  Sub8955 = -16*(F19*Sub8839 + F13*Sub8841) + 
     Power(3 - 4*SW2,2)/(SW2*SW2)*(-(F17*Sub8761) + F3*Sub8846) + 
     MT2*Sub8954;

  Sub2951 = 1/(MW2*(SW2*SW2))*
     (-(SW2*SW2*Sub2950) + 
       MW2*(4*(SW2*SW2)*Sub2948 + (-2 + 4*SW2)*Sub2949));

  Sub7970 = 1/(MW2*(SW2*SW2))*
     (2*(SW2*SW2)*(Pair4*Sub7969) + 
       MW2*((6 - 4*SW2)*(SW2*SW2)*Sub7961 + (-1 + 2*SW2)*Sub7962));

    

  Sub10591 = 4*Sub10543 + 
     Power(1 - 2*SW2,2)/(SW2*SW2)*Sub10544 - MT2*(F21*Sub10590);

  Sub5152 = 4*Sub5092 - Power(1 - 2*SW2,2)/(SW2*SW2)*Sub5097 - 
     MT*Sub5151;

  Sub5574 = 8*Sub5500 - Power(1 - 2*SW2,2)/(SW2*SW2)*Sub5511 - 
     MT*Sub5573;

  Sub5828 = 2*Sub5772 + Power(1 - 2*SW2,2)/(SW2*SW2)*Sub5760 - 
     MT*Sub5827;

  Sub8138 = -2*(-(F26*Sub8122) - 2*Sub8123) + MT*Sub8136 + 
     Power(1 - 2*SW2,2)/(SW2*SW2)*Sub8137;

  Sub8189 = -2*(-(F26*Sub8156) - 2*Sub8158) - 
     Power(1 - 2*SW2,2)/(SW2*SW2)*Sub8154 + 2*MT2*(F21*Sub8188);

  Sub8754 = -4*(F26*Sub8689 + F8*Sub8715 + F1*Sub8717) + 
     MT2*(F21*Sub8404) - Power(1 - 2*SW2,2)/(SW2*SW2)*Sub8724;

  Sub9283 = 4*Sub9215 - Power(1 - 2*SW2,2)/(SW2*SW2)*Sub9200 - 
     MT*Sub9282;

  Sub9650 = 8*Sub9625 + Power(1 - 2*SW2,2)/(SW2*SW2)*Sub9633 - 
     MT*Sub9649;

  Sub10918 = 1/SW2*(-(3*MT2*(F28*F3)) + 
       SW2*(4*Sub10913 - MT*Sub10917));

  Sub10708 = 1/SW2*(3*MT2*(F28*F3) + 
       SW2*(4*Sub10695 - MT*Sub10707));

  Sub10358 = 1/SW2*(2*Sub10355 + 
       SW2*(-2*(Pair1 + Pair2)*Sub10354 + (-1 + 2*SW2)*Sub10357));

    

  Sub11479 = 1/(CW2*MW2*SW2)*
     (-(2*MW2*SW2*Sub11476) + CW2*(Sub11475 + MT*MW2*SW2*Sub11478))
    ;

  Sub11881 = 1/(CW2*MW2*SW2)*
     (2*MW2*SW2*Sub11878 + CW2*(Sub11877 + MT*MW2*SW2*Sub11880));

  Sub11935 = 1/(CW2*MW2*SW2)*
     (2*MW2*SW2*(Sub11896*Sub1292) + 
       CW2*(Sub11931 - 2*MT*MW2*SW2*
           ((F20 + F26 + F29 + F30)*Sub11934)));

  Sub11970 = 1/(CW2*MW2*SW2)*
     (2*MW2*SW2*Sub11969 + 
       CW2*(Sub11968 + 2*MT*MW2*SW2*
           ((F20 + F26 + F29 + F30)*Sub11934)));

  Sub12173 = 1/SW2*(2*Sub12172 + 
       SW2*((-1 + 2*SW2)*Sub12171 - 8*(Sub6442 + MT*Sub7331)));

  Sub12242 = 1/(SW2*SW2)*
     (2*MB2*(SW2*SW2)*Sub12239 + (-1 + 2*SW2)*Sub12240 - 
       2*SW2*Sub12241);

  Sub12397 = 1/(CW2*SW2)*
     (SW2*Sub12390 + CW2*(2*Sub12392 + SW2*(-1 + 2*SW2)*Sub12396));

    

  Sub1246 = 1/SW2*(-2*Sub1245 + 
       SW2*(4*Sub1239 + (1 - 2*SW2)*Sub1244));

  Sub12525 = 1/(CW2*(SW2*SW2))*
     (SW2*SW2*Sub12522 + CW2*
        ((-1 + 2*SW2)*Sub12517 + 2*SW2*Sub12524 + 
          (1 - 2*SW2)*(Sub12514 + MT*Sub12509)));

  Sub12615 = 1/(CW2*(SW2*SW2))*
     (SW2*SW2*Sub12614 + CW2*
        ((-1 + 2*SW2)*Sub12604 + 2*SW2*Sub12606));

  Sub12729 = 1/SW2*(-2*Sub12728 + 
       SW2*(16*Sub12709 + (1 - 2*SW2)*Sub12727));

  Sub1289 = 1/(CW2*(SW2*SW2))*
     (SW2*SW2*Sub1288 + CW2*((-2 + 4*SW2)*Sub1276 + 2*SW2*Sub1278))
    ;

  Sub13036 = 1/SW2*(Sub13035 + 
       SW2*(3*(F8 + F9)*Sub4685*Sub571 + 
          (-12 + 16*SW2)*((F12 + F7)*Sub13006)));

  Sub13867 = 1/SW2*(Sub13866 + 
       SW2*(MW2*Sub13594 + 4*(Sub13862 + MT*Sub13863)));

  Sub1661 = 1/SW2*(-2*Sub1660 + 
       SW2*(8*Sub1657 + (1 - 2*SW2)*Sub1659));

  Sub1682 = 1/SW2*(-2*Sub1681 + 
       SW2*(8*Sub1677 + (-1 + 2*SW2)*Sub1680));

  Sub1879 = 1/(MW2*(SW2*SW2))*
     (-(4*SW2*Sub1878) + MW2*
        ((-1 + 2*SW2)*Sub1857 + 2*(SW2*SW2)*Sub1877));

  Sub2282 = 1/(CW2*(SW2*SW2))*
     (SW2*SW2*Sub2281 + CW2*((2 - 4*SW2)*Sub2271 - 2*SW2*Sub2274));

    

  Sub2434 = 1/(SW2*SW2)*
     (MB2*(SW2*SW2)*Sub2423 + (-1 + 2*SW2)*Sub2428 - 2*SW2*Sub2433)
    ;

  Sub2725 = 1/(CW2*SW2)*
     (4*SW2*Sub2720 + CW2*((1 - 2*SW2)*SW2*Sub2723 - 2*MT*Sub2724))
    ;

  Sub3111 = 1/(CW2*SW2)*
     (SW2*Sub3105 + CW2*(-4*Sub3107 + (2 - 4*SW2)*SW2*Sub3110));

  Sub3130 = 1/(CW2*(SW2*SW2))*
     (SW2*SW2*(-(MT2*Sub3124) - 2*MT*Sub3126) + 
       CW2*((-1 + 2*SW2)*Sub3121 + 2*SW2*Sub3129));

  Sub3644 = 1/SW2*(2*Sub3643 + 
       SW2*(4*Pair1*Sub302 + (1 - 2*SW2)*Sub3642));

  Sub9125 = 1/SW2*(4*F1*F23*Pair4*Sub4022 + 
       SW2*(MT2*Sub9121 + MT*Sub9124));

  Sub4364 = 1/(SW2*SW2)*
     (MB2*(SW2*SW2)*Sub4356 + (1 - 2*SW2)*Sub4359 + 2*SW2*Sub4363);

    

  Sub3405 = 1/(CW2*MW2*SW2)*
     (MW2*SW2*Sub3403 + CW2*
        (18*(MT2*MT2)*Sub593 + 
          MT*(-(18*(MT2*MT2)*Sub25) - MW2*SW2*Sub3404)));

  Sub5955 = 1/(CW2*(SW2*SW2))*
     (-(SW2*SW2*Sub5954) + 
       CW2*((1 - 2*SW2)*Sub5942 - 2*SW2*Sub5944));

  Sub624 = 1/SW2*(Finite*Sub109*
        (Sub614 + MT*((-(F13*F35) + F3*F4)*Sub150)) + 4*SW2*Sub623)
    ;

  Sub6864 = 1/(SW2*SW2)*
     (4*(SW2*SW2)*Sub6857 + (-1 + 2*SW2)*Sub6860 - 2*SW2*Sub6863);

    

  Sub6940 = 1/(SW2*SW2)*
     ((-1 + 2*SW2)*Sub6925 + 
       2*(SW2*Sub6928 + MT2*(SW2*SW2)*Sub6939) + 
       MT*(2*SW2*Sub6921 + (-1 + 2*SW2)*Sub6922));

  Sub7159 = 1/(CW2*(SW2*SW2))*
     (SW2*SW2*Sub7157 + CW2*(2*SW2*Sub7155 + (-1 + 2*SW2)*Sub7158))
    ;

  Sub7936 = 1/SW2*(2*Sub7935 + 
       SW2*(8*Sub4332 + (1 - 2*SW2)*Sub7934));

  Sub8018 = 1/SW2*(2*Sub8017 + 
       SW2*(8*Sub7998 + (-1 + 2*SW2)*Sub8016));

  Sub8112 = 1/(CW2*(SW2*SW2))*
     (SW2*SW2*Sub8111 + CW2*
        (2*SW2*Sub8096 + (1 - 2*SW2)*
           (Sub8089 + MT2*Sub8078 + MT*Sub8093)));

  Sub1598 = 1/(SW2*SW2)*
     (MB2*(SW2*SW2)*Sub1596 + (-3 + (8 - 4*SW2)*SW2)*Sub1597 - 
       4*SW2*(Sub1580*Sub814));

  Sub2102 = 1/(SW2*SW2)*
     (MB2*(SW2*SW2)*Sub2099 + (-1 + 2*SW2)*Sub2100 + 
       SW2*(-2*Sub2101 + 4*Sub2081*Sub814));

  Sub8656 = 1/SW2*(-2*Sub8652 + 
       SW2*(8*Sub8639 + (-1 + 2*SW2)*Sub8655));

  Sub8678 = 1/SW2*(2*Sub8677 + 
       SW2*(-8*F5*Sub8668 - 16*Sub8669 + (1 - 2*SW2)*Sub8676));

  Sub8729 = 1/SW2*(-(3*MT*Sub8690) + 
       SW2*(-4*(F20*Sub8718 + F9*Sub8725 + F10*Sub8726) + 
          MT2*Sub8728));

  Sub9036 = 1/SW2*(2*Sub9035 + 
       SW2*(4*Sub7541 + (-1 + 2*SW2)*Sub9034));

  Sub9053 = 1/(MW2*SW2)*
     (SW2*Sub9052 + MW2*(-2*Sub9048 + (6 - 4*SW2)*SW2*Sub9047));

  Sub9472 = 1/(CW2*(SW2*SW2))*
     (-(SW2*SW2*Sub9468) + 
       CW2*((1 - 2*SW2)*Sub9464 - 2*SW2*Sub9471));

  Sub13765 = 1/SW2*((-3 + 4*SW2)*Sub13763 + 
       SW2*(4*Sub13762 + MT*Sub13764));

  Sub13794 = 1/SW2*((-3 + 4*SW2)*Sub13791 + 
       MW2*(-(4*SW2*Sub13775) + (3 - 4*SW2)*Sub13776) + 
       SW2*(-4*Sub13786 + MT*Sub13793));

  Sub2826 = 1/SW2*((3 - 4*SW2)*Sub2708 + 
       SW2*(4*Sub2704 - MT*Sub2825));

  Sub2980 = 4*Sub2974 - (3 - 4*SW2)/SW2*Sub2978 - 
     MT/SW2*(Sub2979 + 4*SW2*Sub2967);

  Sub6910 = 1/(SW2*SW2)*
     (3*Sub6909 + 16*(SW2*SW2)*Sub6889 + (12 - 16*SW2)*SW2*Sub6897)
    ;

  Sub12117 = 1/(CW2*SW2)*
     (Power(3 - 4*SW2,2)*Sub12076 + 
       MT/MW2*((Pair1 + Pair2)*(Sub12072*Sub37 + Sub12110*Sub39)));

    

  Sub10977 = 2*(F26 + F30)*Sub10974 + 
     (4*Power(3 - 4*SW2,3))/SW2*Sub10954 + (1 - 2*SW2)*Sub10976;

  Sub5817 = 2*F30*Sub5813 + 
     (4*Power(3 - 4*SW2,3))/SW2*Sub5802 + (-1 + 2*SW2)*Sub5816;

  Sub4460 = 1/(MW2*SW2)*
     (MW2*(F15*F3*((-16 + 32*SW2)*Pair3 + (-8 + 16*SW2)*Pair4)) + 
       SW2*(Sub4458 - 2*MW2*(F1*Sub4459)));

  Sub10050 = 1/SW2*((1 - 2*SW2)*Sub10049 + 
       SW2*(2*Sub10034 - MT*Sub10048));

  Sub10126 = 1/SW2*((1 - 2*SW2)*Sub10049 + 
       SW2*(2*Sub10034 - MT*Sub10125));

  Sub1020 = 1/(MW2*SW2)*
     (SW2*(Pair3*Sub1018) + 
       MW2*((3 - 4*SW2)*SW2*Sub1014 + (4 - 8*SW2)*Sub1019));

  Sub12287 = 1/SW2*((-1 + 2*SW2)*Sub10250 + 
       SW2*(2*Sub12286 + MT*Sub12285));

  Sub12331 = 1/SW2*((-1 + 2*SW2)*Sub10323 + 
       SW2*(2*Sub12330 + MT*Sub12329));

  Sub10547 = 1/SW2*((-1 + 2*SW2)*Sub10544 + 
       SW2*(2*Sub10543 - MT2*(F21*Sub1888)));

  Sub10704 = 1/SW2*((-1 + 2*SW2)*Sub10697 + 
       SW2*(2*Sub10693 - MT*Sub10703));

  Sub10782 = 1/SW2*((-1 + 2*SW2)*(F29*Sub10728) + 
       (1 - 2*SW2)*(F3*Sub10732) + SW2*(2*Sub10726 - MT2*Sub10781))
    ;

  Sub11371 = 1/SW2*((1 - 2*SW2)*Sub11364 + 
       2*SW2*(Sub11370 + MT2*(F21*Sub2479)));

  Sub11693 = 1/SW2*((-1 + 2*SW2)*Sub11691 + 
       SW2*(2*Sub11685 + MT2*(-8*F5*F6 + 4*F7*F8)));

  Sub3332 = 1/SW2*((-8 + 16*SW2)*Sub13 + 
       SW2*(-16*Sub702 + MT*Sub3331));

  Sub13617 = 1/SW2*((-1 + 2*SW2)*Sub13614 + 
       SW2*(2*Sub13610 - MT*(S*Sub16)));

  Sub2243 = 1/SW2*((4 - 8*SW2)*Sub2238 + 
       SW2*(8*Sub2240 + (-3 + 4*SW2)*Sub2242));

  Sub424 = 1/SW2*((1 - 2*SW2)*Sub417 + 
       SW2*(2*Sub420 - MT*Sub423));

  Sub474 = 1/SW2*((4 - 8*SW2)*Sub419 + 
       SW2*(8*Sub418 - MT*Sub473));

  Sub452 = 1/SW2*((4 - 8*SW2)*Sub419 + 
       MT*(8*SW2*Sub415 + (-4 + 8*SW2)*Sub422) + 
       SW2*(8*Sub418 + (3 - 4*SW2)*Sub451));

  Sub5516 = 1/SW2*((1 - 2*SW2)*Sub5511 + 
       SW2*(4*Sub5500 - MT*Sub5515));

  Sub6755 = 1/SW2*((-2 + 4*SW2)*Sub6729 + 
       SW2*(4*Sub6725 + Pair4*(6*MT2*Sub6752 - MT*Sub6754)));

  Sub7605 = 1/SW2*((4 - 8*SW2)*Sub7565 + 
       SW2*(3*F12*Sub235*Sub571 + 8*Sub7568));

  Sub11772 = 1/SW2*((1 - 2*SW2)*Sub7572 + 
       SW2*(2*Sub7531 + MT2*(8*F21*F26 + 16*F1*F23*Pair4)));

  Sub8162 = 1/SW2*(MT2*(-2 + 4*SW2)*(F20*F21) + 
       (1 - 2*SW2)*Sub8154 + 
       SW2*(2*Sub8158 + F26*(Sub8156 + 3*MT2*F21)));

  Sub8436 = 1/SW2*((1 - 2*SW2)*Sub8415 + 
       SW2*(Sub8434 + MT*Sub8435));

  Sub8727 = 1/SW2*((1 - 2*SW2)*Sub8724 + 
       SW2*(-2*(F26*Sub8689 + F8*Sub8715 + F1*Sub8717) + 
          MT2*(F21*Sub1347)));

  Sub8860 = 1/SW2*(F17*((1 - 2*SW2)*Sub8761 - 2*SW2*Sub8842) + 
       (-1 + 2*SW2)*(F3*Sub8846) + 
       SW2*(-2*F23*Sub8843 + MT*Sub8859));

  Sub9219 = 1/SW2*((-1 + 2*SW2)*Sub9200 + 
       MT*(-(2*SW2*Sub9186) + (-1 + 2*SW2)*Sub9195) + 
       SW2*(-2*Sub9215 + MT2*Sub9218));

  Sub9236 = 1/SW2*((1 - 2*SW2)*Sub9200 + 
       SW2*(2*(Sub9215 + MT*MT2*(F12*F8)) - 2*MT2*Sub9229) + 
       MT*(-(2*SW2*Sub9233) + (-1 + 2*SW2)*Sub9235));

  Sub9358 = 1/SW2*((-1 + 2*SW2)*Sub9350 + 
       SW2*(Sub9351 + MT*Sub9357));

  Sub9637 = 1/SW2*((-1 + 2*SW2)*Sub9633 + 
       SW2*(4*Sub9625 + MT*Sub9636));

  Sub12105 = 1/SW2*((1 - 2*SW2)*Sub9997 + 
       SW2*(-2*Sub9999 + MT*Sub12104));

  Sub8953 = Power(3 - 4*SW2,2)*(F17*Sub8842 + F23*Sub8843) + 
     (MT*(3 - 4*SW2)*Power(1 - 2*SW2,2))/SW2*Sub8951 + MT2*Sub8952;

    

  Sub1602 = 1/(MW2*SW2)*
     (SW2*Sub1598 + MW2*((12 - 8*SW2)*Sub1570 + 2*SW2*Sub1601));

  Sub8924 = 16*MT2*SW2*(F5*F6) + (-3 + 4*SW2)*Sub8923 + 
     (4 - 8*SW2)*(Sub8918 + MT2*(F3*F4));

  Sub10615 = (6 - 8*SW2)*Sub10611 + (-1 + 2*SW2)*Sub10613 + 
     8*SW2*Sub10614;

  Sub10645 = (3 - 4*SW2)*Sub10642 + (4 - 8*SW2)*Sub10643 - 
     8*SW2*Sub10644;

  Sub10887 = -(8*SW2*Sub10871) + (8 - 16*SW2)*Sub10881 + 
     (3 - 4*SW2)*Sub10886;

  Sub11291 = (-4 + 8*SW2)*Sub11286 + 8*SW2*Sub11287 + 
     (-3 + 4*SW2)*Sub11290;

  Sub11431 = -(8*SW2*Sub11427) + (4 - 8*SW2)*Sub11428 + 
     (3 - 4*SW2)*Sub11430;

  Sub12811 = 1/SW2*(2*Sub12810 - 32*(SW2*SW2)*Sub12802 + 
       SW2*((F20 + F26 + F29 + F30)*Sub12809));

  Sub12866 = (F29 + F30)*Sub12865 - 
     (2*Power(3 - 4*SW2,2))/SW2*Sub12848 - 32*SW2*Sub12861;

  Sub13040 = 1/SW2*(-Sub13039 - 
       16*(SW2*SW2)*(Sub13031 + F22*Sub13038) + 
       MT*(-(16*(SW2*SW2)*Sub13018) + SW2*Sub13036));

  Sub13471 = 8*SW2*Sub13467 + (4 - 8*SW2)*Sub13469 + 
     (3 - 4*SW2)*Sub13470;

  Sub13508 = -(8*SW2*Sub13504) + (4 - 8*SW2)*Sub13506 + 
     (3 - 4*SW2)*Sub13507;

  Sub13516 = (4 - 8*SW2)*Sub13511 - 8*SW2*Sub13514 + 
     (3 - 4*SW2)*Sub13515;

  Sub13558 = (-4 + 8*SW2)*Sub13553 + 8*SW2*Sub13556 + 
     (-3 + 4*SW2)*Sub13557;

  Sub13618 = -(8*SW2*Sub13612) + (4 - 8*SW2)*Sub13616 + 
     (3 - 4*SW2)*Sub13617 + 
     MT*(S*((-4 + 8*SW2)*Sub10 - 8*SW2*Sub2046));

  Sub2596 = 1/SW2*(Sub2595 + 32*(SW2*SW2)*Sub2585 - 
       2*SW2*((F29 + F30)*Sub2589));

  Sub3020 = 1/(SW2*SW2)*
     (Sub3019 + 128*Power(SW2,3)*Sub2983 - 8*MT*SW2*Sub3016);

  Sub2999 = 1/SW2*((-3 + (14 - 16*SW2)*SW2)*
        ((F12 + F7)*Sub1116) + 8*(SW2*SW2)*Sub2992 + 2*SW2*Sub2998)
    ;

  Sub3219 = (-4 + 8*SW2)*Sub3214 + 8*SW2*Sub3215 + 
     (3 - 4*SW2)*Sub3218;

  Sub3630 = 1/SW2*(Sub3629 - 16*(SW2*SW2)*Sub3625 + 
       SW2*(-24 + 32*SW2)*((F12 + F7)*Sub992));

  Sub425 = 8*SW2*Sub418 + (4 - 8*SW2)*Sub419 + 
     (3 - 4*SW2)*Sub424 + MT*(8*SW2*Sub415 + (-4 + 8*SW2)*Sub422);

    

  Sub5123 = (4 - 8*SW2)*Sub5090 - 8*SW2*Sub5101 + 
     (3 - 4*SW2)*Sub5122 + 
     MT2*((4 - 8*SW2)*Sub5111 - 8*SW2*Sub5113) + 
     MT*(-(8*SW2*Sub5118) + (4 - 8*SW2)*Sub5121);

  Sub5355 = 8*SW2*Sub5351 + (-4 + 8*SW2)*Sub5352 + 
     (-3 + 4*SW2)*Sub5354;

  Sub6236 = 48*SW2*Sub6198 + 2*Power(1 - 2*SW2,2)*Sub6233 + 
     (3 - 4*SW2)*Sub6235;

  Sub9595 = (-4 + 8*SW2)*Sub9591 + 8*SW2*Sub9592 + 
     (-3 + 4*SW2)*Sub9594;

  Sub1393 = 1/(CW2*MW2)*
     (MT2*MW2*SW2*(-192 + 256*SW2)*(F12*F8) + 
       CW2*(-9*Sub1392 + 2*MW2*(F7*Sub1390)));

  Sub11009 = 64*(SW2*SW2)*Sub10871 + 
     32*Power(1 - 2*SW2,2)*Sub10881 + Power(3 - 4*SW2,2)*Sub11008;

    

  Sub13945 = -(32*(SW2*SW2)*Sub13390) + 8*SW2*Sub13941 - 
     Power(1 - 2*SW2,3)*Sub13944;

  Sub14170 = -(8*(3 - 4*SW2)*SW2*Sub13502) + 
     32*(SW2*SW2)*Sub13504 + Power(1 - 2*SW2,3)*Sub14169;

  Sub14194 = -(8*(3 - 4*SW2)*SW2*Sub13512) + 
     32*(SW2*SW2)*Sub13514 + Power(1 - 2*SW2,3)*Sub14193;

  Sub14202 = 8*(3 - 4*SW2)*SW2*Sub13554 - 
     32*(SW2*SW2)*Sub13556 + Power(1 - 2*SW2,3)*Sub14201;

  Sub13968 = Power(1 - 2*SW2,3)*Sub13965 + 8*SW2*Sub13967 + 
     32*(SW2*SW2)*(Sub13411 + MT*(F5*F6*Sub150));

  Sub13874 = Power(1 - 2*SW2,3)*Sub13871 + 8*SW2*Sub13873 + 
     32*(SW2*SW2)*(Sub13344 + MT*(F5*F6*Sub151));

  Sub3264 = 32*(SW2*SW2)*Sub3215 + 8*(3 - 4*SW2)*SW2*Sub3216 - 
     Power(1 - 2*SW2,3)*Sub3263;

  Sub6535 = Power(1 - 2*SW2,2)*Sub6534 + 
     64*(SW2*SW2)*(Sub6516 + MT*(Sub28*Sub538)) + 
     2*Power(3 - 4*SW2,2)*(Sub6509 + MT*Sub6513);

  Sub5548 = 1/(CW2*MW2)*
     (SW2*(F29*((MB2*MT2 - MT2*MT2)*F21 + 
            (-(MB2*MT2) + MT2*MT2)*F22)) + 
       CW2*(F29*((-(MB2*MT2) + MT2*MT2)*F21 + 
             (MB2*MT2 - MT2*MT2)*F22) + MW2*(2*Sub5546 + 4*Sub5547)
          ));

  Sub9810 = 1/(CW2*MW2)*
     ((-(MB2*MT*SW2) - MT*MT2*SW2)*(F29*(F37 + F38 + F39 + F40)) + 
       CW2*(MT*(MB2 + MT2)*(F29*(F37 + F38 + F39 + F40)) + 
          MW2*(4*MT2*Sub9792 + 2*(Sub9805 + MT*Sub9797))));

  Sub5662 = 1/(CW2*MW2)*
     (MT2*SW2*((F18 + F19)*F29*Pair3) + 
       CW2*(-(MT2*(F18*F29*Pair3)) - MT2*(F19*F29*Pair3) + 
          MW2*(Sub5639 + MB2*MT*(F10*F11))));

  Sub9720 = 1/(CW2*MW2)*
     (MB2*SW2*((F16 + F17)*F26*(-Pair3 + Pair4)) + 
       CW2*(MB2*((F16 + F17)*F26*(Pair3 - Pair4)) + 
          MW2*(Sub9714 + MT2*Sub9708)));

  Sub1122 = 1/(CW2*MW2*SW2)*
     (-(SW2*SW2*Sub1119) + 
       CW2*(SW2*(Sub1119 + 8*MW2*(F7*Sub1113)) + 
          MW2*(8*SW2*(F12*Sub1112) + (1 - 2*SW2)*Sub1121)));

  Sub1133 = 1/(CW2*MW2)*
     ((-(MB2*SW2) - MT2*SW2)*(F45*(F12 + F7)) - 
       MT2*SW2*(F9*Sub1130) + 
       CW2*((MB2 + MT2)*(F45*(F12 + F7)) + 4*MW2*Sub1128 + 
          MT2*(F9*Sub1130)));

  Sub1134 = 1/(CW2*MW2*SW2)*
     (-(SW2*SW2*Sub1132) + 
       CW2*(SW2*Sub1132 + MW2*
           (8*SW2*Sub1126 + (-1 + 2*SW2)*Sub1133)));

  Sub8250 = 2*Sub8249 - MT2*(-CW2 + SW2)*Sub8248 + 
     (1 - 2*SW2)/SW2*(Sub4001*(-(F16*F20) - F17*F20 + MT*Sub4209));

    

  Sub9432 = 1/MW2*((CW2 - SW2)*Sub9429 + 
       MW2*(4*MT2*Sub6752 + MT*Sub9431));

  Sub9764 = 1/MW2*((-CW2 + SW2)*Sub9761 + 
       MW2*(4*MT2*Sub6752 - MT*Sub9763));

  Sub9956 = 1/MW2*(2*(MT*MW2*Sub9952 + CW2*Sub9954) - 
       2*SW2*Sub9954 - MT2*MW2*Sub9955);

  Sub9294 = 1/SW2*(MT2*
        ((-12 - 16*SW2)*(F28*F3) + (12 + 16*SW2)*(F17*F9)) + 
       SW2*(16*Sub9209 - MT*Sub9293));

  Sub12048 = -(2*MT*((F20 + F26 + F29 + F30)*Sub12047)) + 
     1/SW2*(1/MW2*Sub12042 + 
        2/CW2*(Sub12043 + 16*(SW2*SW2)*Sub12040));

  Sub3478 = (F12 + F7)*Sub3475 + 
     1/SW2*(1/MW2*Sub3476 + 2/CW2*(Sub3477 + 16*(SW2*SW2)*Sub3473))
    ;

  Sub6656 = -(16*(3 - 8*SW2)*(3 - 4*SW2)*
        ((F12 + F7)*Sub6653)) + 2/SW2*Sub6654 + 
     (1 - 2*SW2)/(SW2*SW2)*(-Sub6655 - 128*Power(SW2,3)*Sub6621);

  Sub10081 = 2/SW2*Sub10078 - 
     128*(SW2*SW2)*(Sub10000 + 2*MT*((F26 + F30)*Sub10822)) - 
     (1 - 2*SW2)/(SW2*SW2)*(Sub10080 - 64*Power(SW2,3)*Sub9998);

  Sub10983 = -(18*MT*(3 + SW2*(-12 + 16*SW2))*Sub10934) + 
     2*Power(3 - 4*SW2,3)*Sub10957 + 1/MW2*Sub10982;

  Sub10980 = -(18*MT*(3 + SW2*(-12 + 16*SW2))*Sub10935) + 
     2*Power(3 - 4*SW2,3)*Sub10961 + 1/MW2*Sub10979;

  Sub10267 = -(2*Power(3 - 4*SW2,3)*Sub10246) + 
     1/MW2*Sub10266 + 18*MT*(3 + SW2*(-12 + 16*SW2))*
      ((F1*F2 - F5*F6)*Sub8347);

  Sub10348 = -(2*Power(3 - 4*SW2,3)*Sub10331) + 
     1/MW2*Sub10347 + 18*MT*(3 + SW2*(-12 + 16*SW2))*(Sub28*Sub924)
    ;

  Sub7608 = -(2*Power(3 - 4*SW2,3)*Sub7558) + 
     9/MW2*(Sub7416*Sub858) - 
     18*(-MT2 + MZ2)*(3 + SW2*(-12 + 16*SW2))*Sub968;

  Sub14881 = 2*Sub14880 + 
     SW2*(-4*pave23*Sub219 + 
        (-(8*MW2*Sub719) - MT*Sub721)*pave11(bb0));

  Sub14887 = 1/(CW2*SW2)*
     (SW2*Sub14886 + CW2*(8*SW2*(Sub576*pave25(bb1)) + 
          4*Sub582*pave24(bb1)));

  Sub14899 = MW2*(Finite*Sub314 + MT*(Sub291*pave15(bb1))) - 
     Sub38*Sub649*pave15(bb0) + Sub298*pave15(bb1);

  Sub14914 = -(1/CW2*(Sub624 - 2*Sub619*pave19(bb1))) + 
     4/SW2*(Sub652*pave30(bb1)) - 8*Sub637*pave31(bb1);

  Sub14884 = 1/SW2*(SW2*
        (10*Sub188*pave11(bb0) + Sub220*pave11(bb1)) + 
       MT*((-6*F12 + 6*F7)*(F8 + F9)*Sub159*pave11(bb11)));

  Sub15256 = Sub15255 + 
     MW2*SW2*(3*Sub15251 + 32*Sub1624*pave75(cc0));

  Sub15330 = MT*Sub15329 - 2*Sub1493*pave10(bb0) + 
     2*Sub1342*pave80(cc00);

  Sub15378 = MT*Sub15377 + 2*Sub3293*pave10(bb0) - 
     2*Sub3283*pave80(cc00);

  Sub15304 = 1/(CW2*MW2*SW2)*
     (MT*MT2*(F7*(-(Sub15302*Sub3365) - Sub15303*Sub3411) + 
          F12*(Sub15302*Sub3365 + Sub15303*Sub3411)) + 
       CW2*MW2*SW2*(MB2*(Sub1055*pave44(cc0)) + 
          Sub3111*pave44(cc1)));

  Sub15306 = 1/MW2*(MT2*(Sub1328*pave57(cc00)) + 
       MW2*(MT*(Sub1221*pave79(cc1)) + Sub1171*pave79(cc0)));

  Sub15013 = 3*Sub15012 + 
     SW2*(32*(F12 + F7)*Sub15011 + Sub3814*pave80(cc1));

  Sub15505 = 1/(CW2*SW2)*
     (Sub15504 + CW2*SW2*(Sub13361*pave162(cc0) + 
          Sub13224*pave163(cc1)));

  Sub15017 = Sub15016*Sub3557 + Sub3670*pave37(cc1) + 
     (F17 + F19)*F9*Sub536*pave64(cc12);

  Sub15349 = 1/(CW2*MW2)*
     (Sub15348 + CW2*MW2*(12*Sub15347 - 12*Sub1122*pave44(cc12)));

    

  Sub15135 = 3*MT2*Sub15134 + 4*Sub1324*pave49(cc00) - 
     2*Sub1847*pave49(cc12);

  Sub15115 = MT2*Sub15114 + 
     MW2*(2*Sub2598*pave32(cc2) + Sub2578*pave49(cc2)) - 
     Sub2601*pave32(cc2);

  Sub15019 = MT*(Sub3765*pave79(cc1)) + Sub3394*pave79(cc0) - 
     Sub3419*pave79(cc2);

  Sub15050 = -(MT*(Sub3434*pave79(cc1))) + 
     Sub3467*pave79(cc0) + Sub3617*pave79(cc2);

  Sub15038 = MT*((F12 + F7)*Sub967*pave56(cc12)) + 
     (MT*Sub3493 - 2*MT2*Sub736)*pave56(cc0) + Sub3560*pave56(cc2);

    

  Sub15125 = Pair3*(Sub3809*pave38(cc11) + 
       Sub1068*pave38(cc12) + Sub1061*pave38(cc22));

  Sub15228 = Sub1629*pave65(cc00) + Sub2189*pave65(cc11) + 
     Sub1521*pave65(cc22);

  Sub15300 = Sub3267*pave44(cc11) - Sub1134*pave44(cc12) - 
     Sub3355*pave44(cc22);

  Sub15225 = 2*Sub15222 - 2*Sub15224 + 
     (F20 + F26)*Sub2799*pave76(cc22);

  Sub15313 = MT*((F12 - F7)*Sub228*Sub536*Sub819*
         pave79(cc11) + Sub3284*pave79(cc22)) + Sub1314*pave9(bb0);

    

  Sub15726 = Sub10277*Sub15725 + 
     (Sub10362*Sub306 + 2*Sub10361*Sub8622)*pave110(dd0) + 
     Sub10364*pave111(dd0);

  Sub15702 = Sub9969*pave136(dd0) + Sub4096*pave137(dd0) + 
     Sub10026*pave137(dd00);

  Sub15688 = (F20 + F29)*Sub15686 + Pair1*Sub15687 + 
     1/SW2*((Sub13996 - 4*SW2*Sub13994)*pave120(dd002));

  Sub15623 = Sub14379*pave119(dd1) + Sub4182*pave53(cc0) + 
     Sub4118*pave63(cc1);

  Sub15586 = 3*MT*(Sub15584*Sub4194) + 
     SW2*(Sub15585 + Sub4293*pave126(dd122));

  Sub15435 = 1/(CW2*MW2*SW2)*
     (CW2*MW2*SW2*(Sub14336*pave128(dd12) + 
          Sub14277*pave3(dd12)) + Sub13368*pave3(dd23));

  Sub15737 = Sub9791*pave164(dd11) + Sub10061*pave164(dd13) + 
     Sub10536*pave164(dd23);

  Sub15766 = Sub8201*pave135(dd1) + Sub8539*pave135(dd2) + 
     Sub8784*pave135(dd3);

  Sub15796 = Sub5293*pave140(dd11) + Sub5671*pave140(dd12) + 
     Sub7041*pave140(dd33);

  Sub14854 = -(Sub14853/(-MZ2 + S)) + 120*Sub138*pave8(bb0) + 
     48*Sub137*pave8(bb1);

  Sub15393 = (2*Sub15390)/S + 
     SW2*(-((Sub152*Sub15391)/(-ME2 + Sub14828)) + 
        (Sub15392*Sub538)/(-ME2 + Sub14834));

  Sub10299 = Sub10369 + MT2*(F10*F14) + MT*Sub10295;

  Sub11809 = MB2*(Abb67*(F1*F23 + F15*F3)) + 
     MT2*(Sub11804 + MT*((F1*F42 + F3*F43)*(-Pair3 - Pair4))) + 
     MT*((F29 + F30)*F7*(MB2*(-Pair3 - 2*Pair4) + 
          MW2*(Pair3 + 2*Pair4)));

  Sub11905 = -(4*MW2*Sub11895) + MB2*(2*Sub11895 + Sub11898) + 
     MT2*Sub11901 + 2*MT*Sub11904;

  Sub11919 = (-2*MB2 + 4*MW2)*Sub11895 + MB2*(F21*Sub11896) - 
     2*MT*Sub11904 - MT2*Sub11918;

  Sub12165 = -(2*MW2*Sub12159) + MB2*(Sub12146 + Sub12159) + 
     MT2*Sub12162 - MT*Sub12164;

  Sub12786 = (F20 + F26 + F29 + F30)*Sub12785 + MT2*Sub12781 - 
     2*MW2*Sub12784 + MB2*(-Sub12764 + Sub12784 - MT*Sub12767);

  Sub13163 = Sub13159 + (F29 + F30)*Sub13161 - 
     MT2*(F21*(3*F29 + 3*F30) - 2*Sub13144) - MT*Sub13162;

  Sub14073 = -2*(F15*F3*Pair2*Sub14069 + Sub14070) + 
     4*F15*F3*Sub14072 + F17*F9*(Sub14069 + Sub2703);

  Sub14075 = F10*F13*(-2*Pair2*Sub14069 + 4*Sub14072) - 
     2*Sub14074 + F19*F9*(Sub14069 + Sub2703);

  Sub2381 = 1/MW2*(MT2*Sub2380 + 
       MB2*(Sub2375 - 2*Sub2372*Sub327) + 
       MW2*(2*Sub2377 + 4*Sub2372*Sub327));

  Sub427 = MT2*(Sub408 - Sub426) + MB2*(-Sub410 + MT*Sub405) + 
     MW2*(-2*Sub410 + 2*MT*Sub405);

  Sub13138 = -Sub13135 - Pair4*Sub13137 + 2*MT2*Sub13130 - 
     MB2*MT*Sub430 + MT*(Sub13132 + MW2*Sub430);

  Sub13296 = Sub13295 - MT2*Sub13286 + MT*Sub13293 - 
     MB2*MT*Sub431;

  Sub4877 = (F29 + F30)*Sub4869 + 2*Sub4871 - 1/MW2*Sub4873 - 
     MT/MW2*(Sub4875 - 2*MW2*Sub4876);

  Sub6266 = F18*Sub6260 - F13*Sub6262 + 2*F10*Sub6264 - 
     F22*Sub6265;

  Sub6272 = F16*Sub6267 - F23*Sub6269 + 2*F1*Sub6270 - 
     F21*Sub6271;

  Sub6483 = -Sub6448 + MT2*Sub6394 + 
     MT*(-Sub6414 + MZ2*(F1*F2));

  Sub7497 = -2*Sub7024 + 2*Sub7027 + 
     F22*(-Sub7025 + (-MT2 + MZ2)*F30);

  Sub12682 = -2*Sub7024 - F22*Sub7025 + 2*Sub7027 + MT*Sub12673
   ;

  Sub7411 = -2*Sub7366 - MZ2*Sub7129 + MT2*Sub7327 - MT*Sub7355
   ;

  Sub7715 = F10*Sub7679 + 2*Sub7680 + MT2*Sub7654 + 
     MT*((MT2 - MZ2)*(F3*F4) + (-MT2 + MZ2)*(F12*F9));

  Sub15535 = 2*((Pair1 + Pair2)*Sub15529 + Sub15530) + 
     9*CW2*Sub15534 + 18*MT*
      ((Pair1 + Pair2)*Sub15487*Sub4194*Sub815);

  Sub15547 = Sub12858*Sub15489 + Sub12960*Sub15491 - 
     Pair4*Sub15492*Sub7112 - Pair1*Sub15480*Sub4194*Sub819 - 
     Pair2*Sub15480*Sub4194*Sub819;

  Sub8861 = F19*Sub8847 + F5*Sub8852 + MT2*Sub8831 + MT*Sub8837
   ;

  Sub9003 = 1/MW2*(8*(MT2*MT2)*(F25*F5*Pair4) - 
       MT2*MW2*Sub8966 - MT*MW2*Sub8972 - MB2*MW2*Sub9002 + 
       MW2*MW2*Sub9002);

  Sub9237 = Sub9209 - MT*Sub9234 + MT2*(-Sub9230 + MT*(F7*F9))
   ;

  Sub932 = -2*Abb7*Sub148 + (F21 + F22)*(F20 + F26)*Sub326 + 
     Sub327*(-Sub929 - 2*Sub930) + Sub402*Sub931;

  Sub9851 = 2*Abb144*F15 + Sub9850 + MT*Sub9848 + 
     MT2*(F28 + MT*F4);

  Sub3538 = 1/MW2*(F45*(-(MB2*F7) - MT2*F7) + 
       F7*(2*MW2*Sub3509 + MT2*(-F46 + Sub3535) + 
          MB2*(-F46 + Sub3537)) + 
       F12*((-MB2 - MT2)*F45 + MB2*(-F46 + Sub3535) + 
          MT2*(-F46 + Sub3537) - 2*MW2*Sub992));

  Sub1021 = MT*(-32*Sub1002 + Sub1009) + (3 - 4*SW2)*Sub1013 + 
     MT2*(2*Sub1020 - 32*Sub994);

  Sub8363 = -2*F25*F5*(Pair1 + Pair2)*Sub3986 + MT2*Sub8360 + 
     MT*Sub8361 + (3 - 4*SW2)*Sub8362;

  Sub8370 = -2*(Pair1 + Pair2)*Sub8369 + MT2*Sub8366 + 
     MT*Sub8367 + (3 - 4*SW2)*Sub8368;

  Sub1429 = 16*Sub1422 - 1/MW2*Sub1427 + 
     2*(Power(3 - 4*SW2,3)*Sub1423 + (1 - 2*SW2)*Sub1428);

  Sub3061 = 1/MW2*(2*Sub3058 + 
       MW2*(-8*Sub3059 + 16*MT2*(F5*F6) + (1 - 2*SW2)*Sub3060));

  Sub12289 = -2*Sub12279*Sub814 + MT*Sub12283 + 
     2*MB2*Sub12287 + MT2*(-3 + 2*SW2)*Sub12288;

  Sub4279 = -2*(Pair1 + Pair2)*Sub4274 + 4*Sub4275 + 
     MT*Sub4277 + MT2*((-3 + 2*SW2)*(F29*Sub1687) + 
        (3 - 2*SW2)*(F10*Sub4278));

  Sub4473 = 1/MW2*(-Sub4472 + 
       MW2*(2*Sub4450*Sub882 + MB2*Sub4460 + (-6 + 4*SW2)*Sub4463))
    ;

  Sub6866 = 1/MW2*(2*Sub6864 + 
       MW2*(Sub3948*Sub6850 + MB2*Sub6856 + (3 - 2*SW2)*Sub6865));

    

  Sub8069 = -4*F15*F3*Sub5794*Sub814 + 
     F29*(Sub8068 + 2*Sub5792*Sub814) + 
     MT2*(-3 + 2*SW2)*(Sub8052 + MT*Sub8055);

  Sub8808 = -2*F15*F3*(Pair1 + Pair2)*Sub3993 + MT2*Sub8805 - 
     MT*Sub8806 + (-3 + 2*SW2)*(F22*Sub8807);

  Sub8817 = Sub8812 - MT2*Sub8810 - MW2*Sub8810 + 
     MB2*(Sub8810 - Sub8814) + (-3 + 2*SW2)*Sub8816;

  Sub10638 = 16*Sub10556 - 
     (MT2*Power(3 - 4*SW2,2))/(SW2*SW2)*(F17*F9 + F3*Sub10557) - 
     Power(3 - 4*SW2,2)/(SW2*SW2)*Sub10570 + MT*Sub10637;

  Sub9140 = 2*Sub9076 - Power(1 - 2*SW2,2)/(SW2*SW2)*Sub9069 - 
     MT2*Sub9138 - MT*Sub9139;

  Sub10265 = 1/SW2*(-2*Sub10263 + 
       SW2*(2*(Pair1 + Pair2)*Sub10261 + 4*Sub10262 + 
          (-1 + 2*SW2)*((F20 + F29)*Sub10264)));

  Sub10990 = 1/(SW2*SW2)*
     ((1 - 2*SW2)*Sub10985 - 2*SW2*Sub10986 + 
       SW2*SW2*(8*Sub10943 - MT*Sub10989));

  Sub12226 = 1/(CW2*(SW2*SW2))*
     (SW2*SW2*(Pair4*Sub12225) + 
       CW2*(2*SW2*Sub12217 + (-1 + 2*SW2)*Sub12219 + 
          MT2*(SW2*SW2)*Sub12222));

  Sub12704 = 1/(SW2*SW2)*
     ((1 - 2*SW2)*Sub12701 - 2*SW2*Sub12703 + 
       SW2*SW2*(2*Sub12699*Sub814 + 
          MB2*(2*MT*Sub12697 - 6*MT2*(Pair4*Sub6752))));

  Sub12928 = 1/SW2*(2*Sub12927 + 
       SW2*(8*Sub12911 - MT*Sub12924 + (1 - 2*SW2)*Sub12926));

  Sub776 = 1/SW2*(Alfa2*
        (Finite*(-4*Sub167 + SW2*(-32*F31*F5 + 32*F19*F8))) + 
       SW2*(Alfa*Pi*(3*Sub768 + (48*F31*F5 - 48*F19*F8)*Sub769) + 
          MT*Sub775));

  Sub2305 = 1/(CW2*(SW2*SW2))*
     (SW2*SW2*Sub2304 + CW2*
        ((-2 + 4*SW2)*Sub2293 + 2*MT2*(SW2*SW2)*Sub2295 + 
          SW2*(4*Sub2290 - 2*MT*Sub2297)));

  Sub286 = 1/SW2*(-2*Sub282 + 
       SW2*(2*MT2*Sub278 - 8*(Sub263 + MT*Sub279) + 
          (1 - 2*SW2)*Sub285));

  Sub3062 = 1/(CW2*(SW2*SW2))*
     (SW2*SW2*(-(8*MT2*Sub3055) - MT*Sub3061) + 
       CW2*(12*MT2*(SW2*SW2)*Sub3010 + (8 - 16*SW2)*Sub3030 - 
          16*SW2*Sub3033 + 
          MT*(2*SW2*Sub3053 + (-1 + 2*SW2)*Sub3054)));

  Sub3088 = 1/(CW2*(SW2*SW2))*
     (-(SW2*SW2*Sub3087) + 
       CW2*(12*MT2*(SW2*SW2)*Sub3010 + (8 - 16*SW2)*Sub3030 - 
          16*SW2*Sub3033 + MT*((1 - 2*SW2)*Sub3079 - 2*SW2*Sub3081)
          ));

  Sub3832 = 1/SW2*(2*Sub3828 + 
       SW2*(8*Sub3824 + (3 - 4*SW2)*Sub3827 + (-1 + 2*SW2)*Sub3831)
       );

  Sub439 = 1/SW2*(-(Sub410*Sub42) + 16*SW2*Sub408 - 
       MT2*SW2*Sub436 - MT*SW2*Sub438);

  Sub4544 = 1/(MW2*(SW2*SW2))*
     (SW2*SW2*(2*Pair4*Sub4530 + MB2*MW2*Sub4537) + 
       MW2*((1 - 2*SW2)*Sub4540 - 2*SW2*Sub4543));

  Sub5867 = 1/SW2*(-2*(Sub5861 + SW2*Sub5857) + 
       SW2*(4*Sub5852 + (1 - 2*SW2)*Sub5866));

  Sub5907 = 1/(CW2*(SW2*SW2))*
     (SW2*SW2*Sub5898 + CW2*
        (-(MT*(SW2*SW2)*Sub5902) + (-1 + 2*SW2)*Sub5903 - 
          2*SW2*Sub5906));

  Sub5996 = 1/SW2*(Sub5992 + 
       SW2*(F7*Sub5990 - 2*Sub5991 - Sub5995));

  Sub6530 = 1/(MW2*SW2)*
     (2*Sub6529 + MW2*SW2*(4*Sub6527 + MT*Sub6525 + 
          (1 - 2*SW2)*Sub6528));

  Sub7233 = 4*(-(F1*F24) - F16*F8 - F17*F8) + 8/MW2*Sub7225 + 
     (1 - 2*SW2)*Sub7230 - 2/SW2*Sub7232;

  Sub7383 = -72*(Sub6442 + (-MT2 + MZ2)*Sub7306) + 
     2/CW2*Sub7377 - (9*(1 - 2*SW2))/(SW2*SW2)*Sub7378 + 
     18/SW2*(Sub7380 + 2*Sub7382);

  Sub7410 = -(4*Power(3 - 4*SW2,2)*Sub7405) - 
     Power(3 - 4*SW2,3)*Sub7406 + 6/SW2*Sub7407 + 
     8*(3 - 4*SW2)*Sub7409;

  Sub7762 = 1/SW2*(2*Sub7761 + 
       SW2*(-(4*MW2*Sub7306) + MT2*(4*Sub7306 + Sub7758) + 
          (1 - 2*SW2)*Sub7760));

  Sub7766 = 1/(MW2*SW2)*
     (SW2*Sub7762 + MW2*(-4*Sub7765 + 
          SW2*(-8*F1*F24 + 8*F21*F30 + (2 - 4*SW2)*Sub7764)));

  Sub8021 = 1/(CW2*(SW2*SW2))*
     (2*(SW2*SW2)*(Pair2*Sub7374) + 
       CW2*(-(3*MT*(SW2*SW2)*Sub8018) + (-3 + 6*SW2)*Sub8019 - 
          6*SW2*Sub8020));

  Sub2171 = 1/SW2*(4*Sub2110*Sub814 + 
       SW2*(MT2*Sub2161 + MT*Sub2163 + MB2*Sub2170));

  Sub8657 = MT2*Sub8646 - 2/SW2*Sub8649 + MT*Sub8656 - 
     (1 - 2*SW2)/(SW2*SW2)*(Sub8650 + SW2*SW2*(F3*Sub8651));

  Sub9126 = 1/(SW2*SW2)*
     (-(2*SW2*Sub9112) + (1 - 2*SW2)*Sub9117 + 
       SW2*SW2*(2*Pair4*Sub9107 - MB2*Sub9125));

  Sub9590 = 1/(CW2*(SW2*SW2))*
     (SW2*SW2*(Pair3*Sub9589) + 
       CW2*(-(2*SW2*Sub9581) + (1 - 2*SW2)*Sub9583 + 
          MT2*(SW2*SW2)*Sub9586));

  Sub9734 = 1/(CW2*(SW2*SW2))*
     (SW2*SW2*Sub9733 + CW2*
        (2*SW2*Sub9720 + (-1 + 2*SW2)*Sub9722 + 
          MT*(SW2*SW2)*Sub9726));

  Sub990 = 1/(MW2*SW2)*
     (SW2*(16*Pair4*Sub973 + 2*MT2*MW2*Sub979) + 
       MW2*(2*Sub989 + (1 - 2*SW2)*SW2*Sub981));

  Sub9957 = 1/(CW2*(SW2*SW2))*
     (SW2*SW2*(Pair3*Sub9956) + 
       CW2*(-(2*MT2*SW2*Sub9938) + (-1 + 2*SW2)*Sub9945 + 
          2*(SW2*SW2)*Sub9949 + (1 - 2*SW2)*Sub9951 + 
          MT*((-1 + 2*SW2)*Sub9937 - 2*SW2*Sub9950)));

  Sub1950 = 1/SW2*(MT2*MT2*(8 - 16*SW2)*
        (F10*F13*(Pair1 + Pair2)) + 
       SW2*(-(MT2*Sub1940) + (-6 + 8*SW2)*Sub1943 + MT*Sub1949));

  Sub10259 = 1/SW2*((4 - 8*SW2)*Sub10250 + 
       SW2*(-8*Sub10257 + MT*Sub10256 + (3 - 4*SW2)*Sub10258));

  Sub10817 = 1/SW2*((4 - 8*SW2)*Sub10807 + 
       SW2*(-8*Sub10815 + MT*Sub10814 + (-3 + 4*SW2)*Sub10816));

  Sub10933 = 1/SW2*((4 - 8*SW2)*Sub10923 + 
       SW2*(-8*Sub10931 + MT*Sub10930 + (-3 + 4*SW2)*Sub10932));

  Sub12730 = 1/SW2*((-4 + 8*SW2)*Sub12721 + 
       SW2*(8*Sub12725 + (3 - 4*SW2)*Sub12288 + MT*Sub12729));

  Sub483 = 1/SW2*((4 - 8*SW2)*Sub419 + 
       SW2*(8*Sub418 + (MB2 - MT2 + 2*MW2)*Sub481 - MT*Sub482));

  Sub5773 = 1/SW2*((1 - 2*SW2)*Sub5760 - SW2*Sub5772 + 
       MT*(SW2*Sub5747 + (1 - 2*SW2)*Sub5748));

  Sub8460 = 1/SW2*((1 - 2*SW2)*Sub6443 + 
       SW2*(F21*F30*(-MH2 + MT2) + MT*Sub8458 + MT2*Sub8459));

  Sub7033 = 1/SW2*(Abb40*
        (-(4*SW2*(F1*F23)) + (2 - 4*SW2)*(F15*F3)) + 
       F21*(-(2*SW2*Sub6597) + (1 - 2*SW2)*Sub6600) + 
       SW2*(-(3*MT2*((Pair3 + Pair4)*Sub1066)) + MT*Sub7032));

  Sub9037 = -4*(F21*Sub7582 + 2*Sub7583) + MT2*Sub9032 + 
     MT*Sub9036 + (2*(1 - 2*SW2))/SW2*
      (Sub7586 + (-MB2 + MW2)*(F20*F21));

  Sub8127 = 1/SW2*((1 - 2*SW2)*Sub8120 + 
       SW2*(F26*Sub8122 + 2*Sub8123 + MT*Sub8126));

  Sub9084 = 1/SW2*((1 - 2*SW2)*Sub9069 + 
       SW2*(Sub9076 + MT2*Sub9082 - MT*Sub9083));

  Sub10203 = -(48*SW2*(F47*F5 - F46*F7)) + 
     (3 - 4*SW2)*Sub10200 + Power(3 - 4*SW2,2)*Sub10201 + 
     4*Power(1 - 2*SW2,2)*Sub10202;

  Sub9781 = -(48*SW2*(F26*F39 - F54*F8)) + 
     (3 - 4*SW2)*Sub9779 - Power(3 - 4*SW2,2)*Sub9780 - 
     (4*Power(1 - 2*SW2,2))/SW2*(-3*Sub9767 + 4*SW2*Sub9772);

  Sub11694 = 6*Sub6440 - 16*MT2*SW2*(2*F1*F2 - F12*F8) + 
     (-3 + 4*SW2)*Sub11693 + 
     (1 - 2*SW2)/SW2*(-3*Sub6439 - 4*SW2*Sub11689);

  Sub10055 = (-3 + 4*SW2)*Sub10050 + (-4 + 8*SW2)*Sub10052 + 
     8*(SW2*Sub10043 + F5*(MT*SW2*(F6*Sub10027) + 
           MT2*(F25*Sub10054)));

  Sub10185 = 6*Sub10174 - 8*SW2*Sub10165 + 
     (3 - 4*SW2)*Sub10184 - 
     (1 - 2*SW2)/SW2*(3*Sub10176 - 4*SW2*Sub10170);

  Sub10374 = (-4 + 8*SW2)*(F22*F29*Sub10296 + F10*Sub10367) + 
     8*SW2*Sub10371 + 3*MT*Sub10372 + (3 - 4*SW2)*Sub10373;

  Sub10548 = (4 - 8*SW2)*Sub10541 - 8*SW2*Sub10546 + 
     (3 - 4*SW2)*Sub10547 + 3*MT*(S*Sub5281) + 
     MT2*(F22*((-4 + 8*SW2)*F29 + 8*SW2*F30));

  Sub10666 = 1/SW2*(8*(SW2*SW2)*Sub10655 + 
       (3 + SW2*(-10 + 8*SW2))*Sub10659 + 
       SW2*(2*MT2*Sub10663 - MT*Sub10665));

  Sub10787 = 6*Sub10785 - 8*SW2*Sub10778 + 
     (-3 + 4*SW2)*Sub10786 - 
     (1 - 2*SW2)/SW2*(3*Sub10771 + 4*SW2*Sub10780);

  Sub10830 = (4 - 8*SW2)*Sub10808 + 8*SW2*Sub10811 + 
     (3 - 4*SW2)*Sub10827 - MT*Sub10829;

  Sub10888 = 1/SW2*((3 + SW2*(-10 + 8*SW2))*Sub10877 + 
       8*(SW2*SW2)*Sub10879 + SW2*(-(MT2*Sub10885) + MT*Sub10887));

    

  Sub11042 = (4 - 8*SW2)*Sub10924 - 8*SW2*Sub10927 + 
     (3 - 4*SW2)*Sub11040 - MT*Sub11041;

  Sub11070 = (4 - 8*SW2)*Sub11059 - 8*SW2*Sub11066 + 
     (3 - 4*SW2)*Sub11067 + MT*Sub11069;

  Sub11089 = 1/SW2*((1 - 2*SW2)*Sub11088 + 
       SW2*SW2*(8*Sub11081 - 8*MT*(F30*F39)) + 
       SW2*(MT2*Sub11084 - MT*Sub11086));

  Sub11114 = (-4 + 8*SW2)*Sub11101 - 8*SW2*Sub11110 + 
     (-3 + 4*SW2)*Sub11111 + MT*Sub11113;

  Sub11204 = 8*SW2*Sub11195 + (4 - 8*SW2)*Sub11197 + 
     (3 - 4*SW2)*Sub11200 + MT*Sub11203;

  Sub11260 = -(8*SW2*Sub11245) + (3 - 4*SW2)*Sub11256 - 
     MT*Sub11258 + (1 - 2*SW2)*Sub11259;

  Sub11284 = 8*SW2*Sub11271 + (4 - 8*SW2)*Sub11272 + 
     (-3 + 4*SW2)*Sub11283 + (-6 + 16*SW2)*((F12 + F7)*Sub6653);

  Sub11341 = 1/SW2*(8*(SW2*SW2)*Sub11316 + 
       (-6 + (28 - 32*SW2)*SW2)*((F12 + F7)*Sub6603) + 
       SW2*(4*Sub11339 + (3 - 4*SW2)*Sub11340));

  Sub11376 = (3 - 4*SW2)*Sub11371 + (-4 + 8*SW2)*Sub11372 + 
     8*SW2*Sub11373 + MT*Sub11375;

  Sub11518 = 6*Sub11493 - 8*SW2*Sub11507 + 
     (-3 + 4*SW2)*Sub11517 - 
     (1 - 2*SW2)/SW2*(-3*Sub11495 - 4*SW2*Sub11511);

  Sub11556 = 8*SW2*Sub11533 + (-3 + 4*SW2)*Sub11555 - 
     2*(3 - 8*SW2)*((F12 + F7)*Pair4*Sub2479) + 
     (1 - 2*SW2)/SW2*(-3*Sub10934 - 4*SW2*Sub11534);

  Sub13353 = -(8*SW2*Sub13344) + (-4 + 8*SW2)*Sub13348 + 
     (3 - 4*SW2)*Sub13350 + MT*Sub13352;

  Sub13394 = (-4 + 8*SW2)*Sub13389 + 8*SW2*Sub13390 + 
     (-3 + 4*SW2)*Sub13393 + MT*((3*F12 - 3*F7)*Sub150*Sub228);

  Sub13419 = 8*SW2*Sub13411 + (4 - 8*SW2)*Sub13414 + 
     (3 - 4*SW2)*Sub13416 + MT*Sub13418;

  Sub1804 = (4 - 8*SW2)*(F10*Sub1798) - 8*SW2*Sub1802 + 
     (-3 + 4*SW2)*Sub1803 + S*((4 - 8*SW2)*(F22*F29) + 3*MT*Sub960)
    ;

  Sub2153 = 8*SW2*Sub2149 + (-4 + 8*SW2)*Sub2150 + 
     (-3 + 4*SW2)*Sub2152 + 3*MT*(S*Sub34);

  Sub15236 = 4*S*Sub15230 + 3*SW2*Sub15231 + 
     Sub15130*(2*Sub1614 - 8*SW2*Sub30);

  Sub3070 = (-4 + 8*SW2)*Sub3064 - 8*SW2*Sub3067 + 
     (3 - 4*SW2)*Sub3068 - MT*Sub3069;

  Sub4740 = 1/SW2*(Sub4732 + 16*(SW2*SW2)*Sub4734 + 
       SW2*(MT2*Sub4728 - MT*Sub4739));

  Sub4789 = 1/SW2*(Sub4786 - 16*(SW2*SW2)*Sub4787 + 
       SW2*(MT2*(24 - 32*SW2)*Sub4700 + 
          MT*(Sub4788 + (12 - 16*SW2)*Sub4752)));

  Sub5242 = (8 - 16*SW2)*Sub5221 - 8*SW2*Sub5235 + 
     (3 - 4*SW2)*Sub5237 + 2*MT2*Sub5241 + 
     MT*(-(8*SW2*Sub5212) + (-8 + 16*SW2)*Sub5216);

  Sub5284 = (3 - 4*SW2)*Sub5278 + (-2 + 4*SW2)*Sub5279 - 
     MT2*Sub5283 + 8*SW2*(Sub5267 + MT*Sub5259);

  Sub5519 = (8 - 16*SW2)*Sub5506 + 
     SW2*(8*F18*Sub5495 - 16*Sub5514) + (3 - 4*SW2)*Sub5516 + 
     2*MT2*Sub5518 + MT*((-8 + 16*SW2)*Sub5485 + 8*SW2*Sub5491);

  Sub5776 = -(8*SW2*Sub5763) + (-2 + 4*SW2)*Sub5769 + 
     (3 - 4*SW2)*Sub5773 + MT2*Sub5775 + 
     MT*(8*SW2*Sub5740 + (-2 + 4*SW2)*Sub5755);

  Sub5915 = 8*Sub5913 - 8*SW2*Sub5910 + (3 - 4*SW2)*Sub5912 - 
     MT*Sub5914;

  Sub6191 = (4 - 8*SW2)*Sub6119 + 8*SW2*Sub6137 + 
     (3 - 4*SW2)*Sub6158 + MT*Sub6190;

  Sub6160 = 6*Sub6110 - 8*SW2*Sub6153 + (3 - 4*SW2)*Sub6159 + 
     (1 - 2*SW2)/SW2*(-3*Sub6111 + 4*SW2*Sub6142);

  Sub6283 = 12*Sub6238 + 8*SW2*Sub6249 + (3 - 4*SW2)*Sub6282 + 
     (2*(1 - 2*SW2))/SW2*(-3*Sub6241 + 2*SW2*Sub6253);

  Sub6722 = 6*Sub6665 - 8*SW2*Sub6714 + (3 - 4*SW2)*Sub6721 + 
     (1 - 2*SW2)/SW2*(-3*Sub6666 + 4*SW2*Sub6703);

  Sub6814 = (3*F12 - 3*F7)*Sub6812 + (-4 + 8*SW2)*Sub6803 + 
     8*SW2*Sub6807 + (3 - 4*SW2)*Sub6813;

  Sub8132 = -(8*SW2*Sub8121) + (2 - 4*SW2)*(F20*Sub8124) + 
     (4 - 8*SW2)*Sub8125 + (3 - 4*SW2)*Sub8127 + MT2*Sub8131 + 
     MT*(8*SW2*Sub8115 + (2 - 4*SW2)*Sub8118);

  Sub8165 = (4 - 8*SW2)*Sub8161 + (3 - 4*SW2)*Sub8162 - 
     MT*Sub8163 + (2 - 4*SW2)*(F20*(Sub8159 + Sub8164)) + 
     SW2*(8*Sub8155 - 16*MT2*(F22*F26));

  Sub8174 = (2 - 4*SW2)*Sub8168 - 8*SW2*Sub8170 + 
     (3 - 4*SW2)*Sub8171 + 3*MT*Sub8173;

  Sub8290 = (-3 + 4*SW2)*Sub8285 - 8*SW2*Sub8286 + 
     MT*Sub8289 + (-4 + 8*SW2)*(Sub8280 + MT2*Sub8253);

  Sub8340 = -2*Sub8339 + (-1 + 2*SW2)*Sub8334 + MT*Sub8338 + 
     8*SW2*(Sub8284 + MT2*Sub8325);

  Sub8440 = MT*(-2 + 4*SW2)*Sub8423 + (2 - 4*SW2)*Sub8429 + 
     (3 - 4*SW2)*Sub8436 - 8*SW2*Sub8437 - MT2*Sub8439;

  Sub8569 = (-3 + 4*SW2)*Sub8566 + 8*SW2*Sub8568 + 
     6*MT*(Sub8556 - MT2*(F12*F8) + MT2*(F7*F8)) + 
     (-1 + 2*SW2)*(4*Sub8559 - MT*Sub8567);

  Sub8730 = (3 - 4*SW2)*Sub8727 + (1 - 2*SW2)*Sub8729 - 
     8*SW2*(-Sub8721 + MT2*(F22*F26)) + 
     6*MT*(Sub8714 + MT2*((-F12 + F7)*F8));

  Sub8867 = (-3 + 4*SW2)*Sub8860 + 8*SW2*Sub8861 + 
     MT2*Sub8866 + (4 - 8*SW2)*
      (F19*Sub8839 + F13*Sub8841 + MT*Sub8856);

  Sub8909 = 8*SW2*Sub8871 + (-4 + 8*SW2)*Sub8875 + 
     (-3 + 4*SW2)*Sub8906 + MT*Sub8908;

  Sub9240 = (3 - 4*SW2)*Sub9236 + (4 - 8*SW2)*Sub9237 + 
     8*SW2*Sub9238 + MT2*Sub9239;

  Sub9331 = (3 - 4*SW2)*Sub9326 + 8*(Sub9330 + SW2*Sub9327) - 
     MT2*Sub9329;

  Sub9363 = (3 - 4*SW2)*Sub9358 + 
     SW2*(-8*F19*Sub9353 + 8*F5*Sub9359) + MT2*Sub9362 + 
     (-2 + 4*SW2)*(Sub9352 + MT*Sub9356);

  Sub9547 = 6*F5*Sub9541 + (1 - 2*SW2)*Sub9543 - 
     8*SW2*Sub9544 + (3 - 4*SW2)*Sub9546;

  Sub9642 = (-3 + 4*SW2)*Sub9637 + (-8 + 16*SW2)*Sub9638 - 
     8*SW2*Sub9639 + MT2*Sub9641;

  Sub10287 = -(12*(3 - 8*SW2)*(F5*Sub10278)) + 
     2*Power(3 - 4*SW2,2)*Sub10279 + Power(1 - 2*SW2,2)*Sub10284 + 
     64*(SW2*SW2)*Sub10286;

  Sub10592 = Power(3 - 4*SW2,2)*Sub10591 + 
     3*MT*(3 - 8*SW2)*(S*Sub5288) - 
     16*Power(1 - 2*SW2,2)*(-Sub10541 + MT2*(F22*F29)) - 
     64*(SW2*SW2)*(-Sub10546 + MT2*(F22*F30));

  Sub10679 = -(64*(SW2*SW2)*Sub10655) - 
     (Power(3 - 4*SW2,2)*Power(1 - 2*SW2,2))/(SW2*SW2)*Sub10659 + 
     2*MT2*Sub10676 - MT*Sub10678;

  Sub11014 = -(64*(SW2*SW2)*Sub10879) + MT*Sub11009 + 
     2*MT2*Sub11012 - Power(1 - 2*SW2,2)/(SW2*SW2)*Sub11013;

  Sub11120 = -(MT2*Sub11117) - MT*Sub11119 + 
     (Power(3 - 4*SW2,2)*Power(1 - 2*SW2,2))/(SW2*SW2)*
      (-Sub11078 + MT*(F29*F37)) + 
     64*(SW2*SW2)*(-Sub11081 + MT*(F30*F39));

  Sub2096 = -(128*(1 - 2*SW2)*SW2*(F10*F14*Sub2082)) + 
     256*(SW2*SW2)*(F5*Sub2084) - 2*Power(3 - 4*SW2,3)*Sub2092 + 
     1/MW2*Sub2095;

  Sub3175 = Power(1 - 2*SW2,3)*Sub3172 + MT*Sub3174 + 
     8*(3 - 4*SW2)*SW2*(-Sub3065 + MT*(F23*F33*Sub150)) + 
     32*(SW2*SW2)*(Sub3067 + MT*(F5*F6*Sub150));

  Sub5249 = -(Power(3 - 4*SW2,2)*Sub5244) + 2*MT2*Sub5248 - 
     64*(SW2*SW2)*(Sub5235 + MT*Sub5212) + 
     32*Power(1 - 2*SW2,2)*(-Sub5221 + MT*Sub5216);

  Sub5291 = -(8*Power(1 - 2*SW2,2)*Sub5279) - 
     Power(3 - 4*SW2,2)*Sub5286 + MT2*Sub5290 - 
     64*(SW2*SW2)*(Sub5267 + MT*Sub5259);

  Sub5578 = Power(3 - 4*SW2,2)*Sub5574 - 2*MT2*Sub5577 - 
     32*Power(1 - 2*SW2,2)*(-Sub5506 + MT*Sub5485) - 
     64*(SW2*SW2)*(F18*Sub5495 - 2*Sub5514 + MT*Sub5491);

  Sub5831 = Power(3 - 4*SW2,2)*Sub5828 + MT2*Sub5830 + 
     64*(SW2*SW2)*(-Sub5763 + MT*Sub5740) + 
     8*Power(1 - 2*SW2,2)*(Sub5769 + MT*Sub5755);

  Sub3141 = (-3 + 4*SW2)*Sub3136 + MT*Sub3140 + 
     (4*Power(1 - 2*SW2,3))/SW2*(-Sub2831 + MZ2*Sub11) - 
     32*(SW2*SW2)*(Sub2834 - MT*MZ2*Sub2046 - MZ2*Sub706);

  Sub8145 = Power(3 - 4*SW2,2)*Sub8138 + 2*MT2*Sub8141 + 
     Power(1 - 2*SW2,2)*Sub8144 - 
     64*(SW2*SW2)*(-Sub8139 + MT*Sub8115);

  Sub8196 = Power(3 - 4*SW2,2)*Sub8189 + 
     2*Power(1 - 2*SW2,2)*Sub8191 + MT*Sub8195 + 
     64*(SW2*SW2)*(-Sub8155 + 2*MT2*(F22*F26));

  Sub8184 = 64*(SW2*SW2)*Sub8170 + 
     Power(3 - 4*SW2,2)*Sub8180 + 2*Power(1 - 2*SW2,2)*Sub8181 + 
     6*MT*Sub8183;

  Sub8523 = -(64*(SW2*SW2)*Sub8437) - 
     Power(1 - 2*SW2,2)*Sub8520 + MT2*Sub8522 - 
     2*Power(3 - 4*SW2,2)*(Sub8434 + MT*Sub8420);

  Sub8757 = Power(3 - 4*SW2,2)*Sub8754 + 
     Power(1 - 2*SW2,2)*Sub8756 + 
     64*(SW2*SW2)*(-Sub8721 + MT2*(F22*F26)) + 
     12*MT*(3 - 8*SW2)*(Sub8714 + MT2*((-F12 + F7)*F8));

  Sub9346 = -(Power(3 - 4*SW2,2)*Sub9341) - 
     64*(SW2*SW2)*Sub9343 + MT2*Sub9345 + 
     32*Power(1 - 2*SW2,2)*(Sub9313 + MT*Sub9305);

  Sub9439 = 64*(SW2*SW2)*(-(F19*Sub9353) + F5*Sub9359) + 
     Power(3 - 4*SW2,2)*Sub9435 + MT2*Sub9438 + 
     8*Power(1 - 2*SW2,2)*(Sub9352 + MT*Sub9356);

  Sub9653 = -(32*Power(1 - 2*SW2,2)*Sub9638) + 
     64*(SW2*SW2)*Sub9639 - Power(3 - 4*SW2,2)*Sub9650 + 
     MT2*Sub9652;

  Sub1713 = 1/(CW2*MW2)*
     (-(2*(MT2*MT2)*SW2*(F20*F22)) + 
       CW2*(2*(MT2*MT2)*(F20*F22) + 
          MW2*(Sub1706 - MT2*Sub1700 - MT*Sub1712)));

  Sub12136 = 1/(CW2*MW2*(SW2*SW2))*
     (Power(SW2,3)*Sub12130 + 
       CW2*(-(SW2*SW2*Sub12130) - MT*MW2*(SW2*SW2)*Sub12135 + 
          MW2*((1 - 2*SW2)*Sub12131 + 2*SW2*Sub12133)));

  Sub11859 = 1/(CW2*MW2*(SW2*SW2))*
     (-(MT2*Power(SW2,3)*(F22*Sub1279)) + 
       CW2*(MW2*((1 - 2*SW2)*Sub11857 - 2*SW2*Sub11858) + 
          SW2*SW2*(2*MT*MW2*Sub11856 + MT2*(F22*Sub1279))));

  Sub5473 = 1/MW2*((CW2 - SW2)*Sub5467 + 
       MW2*(4*Pair4*Sub5463 + MT*Sub5470 + 2*MT2*Sub5472));

  Sub5565 = 1/MW2*(-(CW2*Sub5556) + SW2*Sub5556 + 
       MT2*MW2*Sub5560 - MT*MW2*Sub5562 + 2*MW2*(Pair3*Sub5564));

  Sub11463 = 2*Sub11460 + 4*Sub11462 - 2/SW2*Sub11458 + 
     ((1 - 2*SW2)*(-CW2 + SW2))/(CW2*MW2*(SW2*SW2))*
      (F29*(-(2*MT2*(F21 + F22)) - MT*Sub4750));

  Sub10270 = -(256*(SW2*SW2)*Sub10260) + MT*Sub10265 + 
     2/SW2*Sub10267 - (1 - 2*SW2)/(SW2*SW2)*
      (-Sub10269 + 128*Power(SW2,3)*Sub10245);

  Sub10359 = -(256*(SW2*SW2)*Sub10346) - 2/SW2*Sub10348 + 
     MT*Sub10358 + (1 - 2*SW2)/(SW2*SW2)*
      (Sub10350 + 128*Power(SW2,3)*Sub10329);

  Sub10577 = (3 - 4*SW2)*Sub10573 + (-1 + 2*SW2)*Sub10575 + 
     SW2*(8*Sub10567 - 8*MT*Sub10562) + 
     MT2*(-6*Sub19 - 8*SW2*Sub10576);

  Sub10984 = MT*Sub10977 + 2/SW2*Sub10980 - 
     256*(SW2*SW2)*(Sub10962 + MT*Sub10950) + 
     (1 - 2*SW2)/(SW2*SW2)*(-Sub10983 + 128*Power(SW2,3)*Sub10958);

    

  Sub8247 = -(MT*Sub8243) + MT2*Sub8246 + 
     1/SW2*(Sub8237 + 2/CW2*(Sub8238 + 16*(SW2*SW2)*Sub8239));

  Sub5959 = -(8*MT*(9 + SW2*(-24 + 8*SW2))*
        (-(F1*F2) + F12*F8)) + Power(3 - 4*SW2,2)*Sub5956 + 
     64*(SW2*SW2)*Sub5957 + Power(1 - 2*SW2,2)*Sub5958;

  Sub1590 = 256*(SW2*SW2)*Sub1572 + 
     18*MT*(3 + SW2*(-12 + 16*SW2))*(S*Sub1585) + 2/SW2*Sub1587 - 
     (1 - 2*SW2)/(SW2*SW2)*(Sub1589 - 128*Power(SW2,3)*Sub1576);

  Sub2935 = -8*(MT2 + Sub2913)*Sub2931 - 
     (72*(3 + SW2*(-12 + 16*SW2)))/SW2*
      (F30*(-F12 + F7)*(Pair1 + Pair2)) - 
     2*Power(3 - 4*SW2,3)*Sub2930 + 1/MW2*Sub2934;

  Sub371 = (-1 + 2*SW2)*Sub245 - 2/SW2*Sub246 + 
     1/(CW2*CW2)*(Sub370 - 8*(-(CW2*CW2) + SW2*SW2)*Sub241);

  Sub14871 = 1/SW2*(MT*
        ((-12*F12 + 12*F7)*Sub14841*Sub228*Sub538) + 
       SW2*(6*Sub14870 - 2*Sub14869*Sub392 + Sub784*pave22(bb0)));

    

  Sub14863 = 8*Finite*Pair2*S*Sub161 + 
     6/SW2*((Sub249 + 8*SW2*(Sub159*Sub241))*
        (pave23 - 2*pave8(bb00))) - 
     12*(5*S*Sub273 - MW2*Sub274)*pave8(bb0) + 3*Sub444*pave8(bb1);

    

  Sub14896 = Sub14895 + 
     CW2*(9*Sub14893 + MW2*SW2*
         (Sub14892*Sub777 + 32*Sub515*pave158(bb1)));

  Sub15154 = Sub15148 + 2*Sub15153 + MT2*Sub15152 - 
     2*MB2*(Sub1471*pave49(cc0));

  Sub15344 = -4*Sub15343 + MT*MT2*((3*F12 - 3*F7)*Sub15342) - 
     8*Sub3352*pave79(cc00);

  Sub15103 = Sub15102 - 2*Sub15101*Sub2 + 
     2*Pair3*Sub148*Sub287*pave33(cc12) - Sub942*pave50(cc1);

  Sub15309 = 1/MW2*(9*MT2*(Sub1103*pave57(cc12)) + 
       MW2*((-12*F12 + 12*F7)*Sub15308*Sub536 + 
          32*Sub1503*pave56(cc1) + Sub1309*pave80(cc1)));

  Sub15001 = Sub26*pave161(bb0) + Sub964*pave83(cc0) + 
     Sub3601*pave83(cc1) + 
     (F17 + F19)*(F8 + F9)*Sub153*pave83(cc12);

  Sub15205 = 2*MT2*(Sub3578*pave36(cc0)) + 
     MT*(Sub2602*pave35(cc1) + Sub327*Sub383*pave35(cc2) - 
        Sub3579*pave36(cc0)) - 
     2*(Sub148*Sub2603*pave35(cc1) + Sub2735*pave35(cc2)) + 
     Sub3889*pave76(cc0);

  Sub15290 = 1/(CW2*SW2)*
     (SW2*(CW2*(Sub3092*pave64(cc1) - Sub3157*pave64(cc2)) - 
          F9*Sub3142*Sub536*pave81(cc12)) + 
       (Sub3185 + 4*SW2*Sub3183)*pave81(cc1));

  Sub15018 = Sub3650*pave11(bb0) + Sub586*pave37(cc2) + 
     Sub3661*pave64(cc1) + Sub3505*pave64(cc2);

  Sub15062 = Sub3421*pave167(bb0) + Sub3675*pave55(cc0) + 
     Sub3691*pave55(cc1) + Sub3747*pave55(cc2);

  Sub15200 = Sub2752*pave65(cc1) + Sub2697*pave68(cc1) + 
     Sub2763*pave68(cc2) + Sub3604*pave89(cc2);

  Sub15051 = Sub3446*pave11(bb0) + Sub3597*pave62(cc2) + 
     Sub3502*pave86(cc1) + Sub3590*pave86(cc2);

  Sub15246 = MB2*(Sub1442*pave88(cc0)) + 
     Sub1629*pave34(cc00) + Sub2312*pave34(cc12) + 
     Sub2189*pave34(cc22);

  Sub15162 = Sub1270*pave33(cc2) + Sub1682*pave50(cc1) + 
     Sub1845*pave50(cc22) + 
     (-(2*MT2*Sub3684) + MT*Sub3687)*pave61(cc0);

  Sub15215 = -(MT*(Sub15214*Sub3579)) + 
     MT2*(2*Sub15214*Sub3578 + Sub945*pave51(cc1)) + 
     MB2*(Sub3889*pave88(cc0)) + (F20 + F26)*Sub2776*pave88(cc22);

    

  Sub15259 = Sub1791*pave74(cc1) + Sub2217*pave75(cc12) + 
     Sub2371*pave75(cc2) + Sub1228*pave75(cc22);

  Sub15767 = 2*Sub15764 - 2*Sub15765 + Sub15766 + 
     4*Sub8146*pave135(dd00);

  Sub15685 = 1/CW2*(Sub15684 + 
       CW2*(Sub13976*pave119(dd00) - Sub14124*pave119(dd11) + 
          Sub13952*pave120(dd00)));

  Sub15786 = Sub15785*Sub8757 + Sub8145*pave142(dd11) + 
     Sub8196*pave142(dd12) + Sub8523*pave142(dd13);

  Sub15792 = MT*(Sub5181*pave170(dd0)) + 
     Sub5291*pave170(dd11) + Sub5395*pave170(dd12) + 
     Sub5831*pave170(dd13);

  Sub15703 = -(Sub8660*pave114(dd0)) - Sub9439*pave114(dd13) + 
     Sub10471*pave138(dd0) + Sub6868*pave171(cc0);

  Sub15440 = 1/MW2*(MW2*
        (Sub14273*pave123(dd12) + Sub14600*pave123(dd2) + 
          Sub14333*pave124(dd12)) + 
       (F29 + F30)*Sub1310*pave123(dd23));

  Sub15540 = 1/(CW2*MW2)*
     (Sub15539 + CW2*MW2*(Sub9340*pave134(dd123) + 
          Sub6379*pave134(dd223) + Sub9892*pave134(dd233)));

  Sub15527 = MT2*(Sub1347*(F21*Sub15526 - F22*Sub15526) + 
       Sub11529*pave118(dd13) - Sub11728*pave118(dd23) - 
       Sub11791*pave118(dd3));

  Sub15572 = -(Pair3*Sub8148*pave121(dd333)) + 
     Pair4*Sub4217*pave122(dd133) - Sub8321*pave122(dd223) + 
     Sub12071*pave122(dd233);

  Sub12493 = 1/MW2*(Sub12492 + 
       MW2*(Sub12471 + MT2*Sub12439 + (-MB2 + MW2)*Sub12442 + 
          MT*Sub12491));

  Sub12984 = (F21 + F22)*F26 - 4*(F15*F3 + F25*F5)*Pair2 - 
     2*Sub12981 + 2*Sub12982 - Sub12983;

  Sub14044 = -(F29*Sub14039) - F30*Sub14039 - Sub14043 + 
     F15*F3*(MW2*(2*Pair1 - 2*Pair3 - 2*Pair4) + 
        MB2*(-2*Pair1 + 2*Pair3 + 2*Pair4)) + MB2*Sub14041 - 
     MT*Sub14042;

  Sub1455 = 1/MW2*(-(Pair4*Sub1451) + 
       MW2*(Sub1449 + F1*F23*Sub1454 + 
          F15*F3*(Sub1448 + Sub1454) + MT2*Sub1450));

  Sub15025 = 2*Sub15024 + MT*((F12 + F7)*Sub15021) - 
     2*(Sub15020*Sub3469 + MT2*Sub15022);

  Sub13537 = 2*Sub13536 + MT2*(Sub13533 - Sub13534) + 
     MH2*(Sub13534 + MT*Sub509) + MT*(Sub13535 - 2*MT2*Sub509);

  Sub4503 = 1/MW2*((F29 + F30)*(-(MT2*Sub4500) - MT*Sub4501) + 
       MW2*(-2*Sub4499 + 2*Sub4502 - MT2*Sub4483 + 
          MT*(Sub4492 - MT2*Sub509)));

  Sub14097 = 2*Sub14094 + F5*Sub14095 - 2*Sub14096 + 
     F10*Sub7679 + MT2*(2*F22*F30 + 4*F5*Sub14093);

  Sub8713 = -2*Sub8707 + 
     2*(Pair4*Sub8705 + 1/MW2*
         (Sub8708 + MW2*(Sub8225 + MT2*Sub8204))) + 
     1/MW2*(Sub8712 + MT*(Sub8709 + 2*MW2*Sub8231));

  Sub411 = 1/MW2*(Sub39*Sub408 - Sub37*Sub410 + 
       MT2*MW2*(-18 + 48*SW2)*Sub401 + 
       MT*(Sub37*Sub405 + Sub39*Sub406));

  Sub1758 = 16*Sub1739 - 16*Sub1749 - 2*MT2*Sub1747 - 
     MT*Sub1754 + (6 - 8*SW2)*Sub1757;

  Sub9682 = 18*(-Pair1 + Pair3)*Sub9676 + 12*F5*Sub9681 + 
     2*(3 - 4*SW2)*Sub9678 - Power(3 - 4*SW2,2)*Sub9679 + 
     4*Power(1 - 2*SW2,2)*Sub9680;

  Sub2952 = Sub13*Sub899 + 
     MT*(-(Sub12*Sub900) + MT2*MT2*(-3 + 2*SW2)*Sub2892 + 
        MB2*(3 - 2*SW2)*Sub2942 + 
        (MB2*(3 - 2*SW2) + MT2*(-3 + 2*SW2))*(F9*Sub2943));

  Sub1779 = 1/SW2*(2*Sub1772 + 
       SW2*(8*Sub1769 + (3 - 4*SW2)*Sub1771 + MT2*Sub1778 + 
          MT*(-(Sub287*Sub648) + 6*MT2*Sub1770)));

  Sub2074 = 1/(CW2*MW2*SW2)*
     (SW2*Sub2073 + CW2*MW2*
        (-4*Sub2059 + SW2*(4*Sub2061 - 2*Sub2068 + 
             (1 - 2*SW2)*Sub2065)));

  Sub3787 = 1/(MW2*SW2)*
     (SW2*(-2*Sub3784 + 16*MT2*MW2*Sub596) + 
       MW2*(-4*Sub3783 + SW2*(16*Sub3777 + (1 - 2*SW2)*Sub3786)));

    

  Sub8688 = 1/SW2*(-4*Sub8682 + 
       SW2*(8*(F30*Sub1686 + F1*Sub8674) + 2*Sub8680 + 
          MT*Sub8678 + (1 - 2*SW2)*Sub8687));

  Sub10788 = (4 - 8*SW2)*Sub10724 + 
     SW2*(-8*F30*Sub10733 + 8*F5*Sub10736) + 
     (3 - 4*SW2)*Sub10782 - MT*Sub10787 + 
     MT2*(-2*Sub10784 + (4 - 8*SW2)*Sub10766);

  Sub11285 = (4 - 8*SW2)*Sub11276 + 8*SW2*Sub11281 + 
     (3 - 4*SW2)*Sub11282 + MT*Sub11284 + 
     MT2*((3*F21 - 3*F22)*Sub2479);

  Sub11342 = (4 - 8*SW2)*Sub11329 - 8*SW2*Sub11337 + 
     (3 - 4*SW2)*Sub11338 + MT*Sub11341 + 
     MT2*((-3*F21 + 3*F22)*Sub2479);

  Sub11557 = 6*Sub11552 - 8*SW2*Sub11551 + 
     (-3 + 4*SW2)*Sub11553 + (1 - 2*SW2)*Sub11554 + MT*Sub11556;

  Sub11778 = 6*Sub11776 - 8*SW2*Sub11759 + 
     (-3 + 4*SW2)*Sub11777 + 12*MT2*Sub6359 - 
     (1 - 2*SW2)/SW2*(-3*Sub11747 + 4*SW2*Sub11764);

  Sub12261 = 32*SW2*Sub12254 - 
     32*(3 - 4*SW2)*((F12 + F7)*Sub4192) + 
     1/SW2*(-(2*Power(3 - 4*SW2,2)*Sub12149) + 
        1/MW2*(Sub12144*Sub801 + Sub12251*Sub802));

  Sub12409 = 32*SW2*Sub12407 - 
     32*(3 - 4*SW2)*((F12 + F7)*Sub4192) + 
     1/SW2*(2*Power(3 - 4*SW2,2)*Sub12348 + 
        1/MW2*(Sub12144*Sub801 + Sub12251*Sub802));

  Sub1898 = MT2*Sub1889 + (3 - 4*SW2)*Sub1891 + 
     8*SW2*Sub1892 + 2*MT*Sub1894 + (1 - 2*SW2)*Sub1897;

  Sub3000 = (-4 + 8*SW2)*Sub2983 + 8*SW2*Sub2986 + 
     3*MT2*Sub2996 + (-3 + 4*SW2)*Sub2997 + 
     MT*(Sub2999 + (-4 + 8*SW2)*Sub2993);

  Sub5109 = (4 - 8*SW2)*Sub5090 - 8*SW2*Sub5101 + 
     (3 - 4*SW2)*Sub5102 + MT2*Sub5105 + MT*Sub5108;

  Sub5350 = 3*MT2*Sub5344 - MT*Sub5346 - 8*SW2*Sub5347 + 
     (3 - 4*SW2)*Sub5348 + (4 - 8*SW2)*Sub5349;

  Sub6163 = (4 - 8*SW2)*Sub6119 + 8*SW2*Sub6137 + 
     (3 - 4*SW2)*Sub6158 + MT*Sub6160 - MT2*Sub6162;

  Sub6911 = 12*Sub6907 + 48*SW2*Sub6192 + 9*MT2*Sub6226 + 
     Power(3 - 4*SW2,2)*Sub6908 + Power(1 - 2*SW2,2)*Sub6910;

  Sub11671 = (3 - 4*SW2)*Sub11663 + MT*Sub11665 - 
     MT2*Sub11670 + 8*SW2*Sub6448 + (4 - 8*SW2)*Sub6454;

  Sub6723 = -(MT2*Sub6162) + (4 - 8*SW2)*Sub6675 - 
     8*SW2*Sub6697 + (3 - 4*SW2)*Sub6720 + MT*Sub6722;

  Sub11521 = (3 - 4*SW2)*Sub11516 - MT*Sub11518 - 
     2*MT2*Sub11520 - 8*SW2*Sub7434 + (4 - 8*SW2)*Sub7488;

  Sub11779 = 4*Sub11771 + (-3 + 4*SW2)*Sub11772 - 
     2*MT2*Sub11775 - MT*Sub11778 + 8*SW2*Sub7576;

  Sub11699 = (3 - 4*SW2)*Sub11692 - MT2*Sub11698 + 
     8*SW2*Sub7677 + (4 - 8*SW2)*(F10*Sub7679) + 
     (8 - 16*SW2)*Sub7680 + MT*(Sub11694 + 8*SW2*Sub11688);

  Sub11397 = (3 - 4*SW2)*Sub11390 + 2*MT2*Sub11394 - 
     MT*Sub11396 + 8*SW2*Sub7819 + (4 - 8*SW2)*Sub7834;

  Sub7864 = -(4*(3 - 4*SW2)*Sub7855) + 
     Power(3 - 4*SW2,2)*Sub7856 + 2/SW2*Sub7859 + 
     (-1 + 2*SW2)*Sub7863 + 96*SW2*(F7*F8*Sub924);

  Sub9865 = 6*Sub9861 - 3*MT2*((-F12 + F7)*Sub228) - 
     8*SW2*Sub9859 + (-3 + 4*SW2)*Sub9864 + 
     (1 - 2*SW2)/SW2*(-3*Sub9862 + 4*SW2*Sub9855);

  Sub10213 = 16*Sub10204 + Power(3 - 4*SW2,2)*Sub10198 - 
     MT*Sub10203 + MT2*Sub10212 + 
     64*(SW2*SW2)*(Sub10043 - MT*Sub10190);

  Sub10480 = -(16*Power(1 - 2*SW2,2)*
        (-(F22*F29*Sub10296) - F10*Sub10367)) + 
     64*(SW2*SW2)*Sub10371 + 9*MT2*Sub10476 + 
     Power(3 - 4*SW2,2)*Sub10477 + 3*MT*Sub10479;

  Sub10639 = 4*Sub10636 + 12*MT2*Sub10635 - 
     Power(1 - 2*SW2,2)*Sub10638 - 
     64*(SW2*SW2)*(-Sub10567 + MT*Sub10562 + MT2*Sub10576) + 
     16*(3 - 4*SW2)*SW2*(MT2*Sub10549 - MT*Sub10633);

  Sub11237 = 9*MT2*Sub10476 + MT*Sub11233 - 
     Power(3 - 4*SW2,2)*Sub11234 + 
     64*(SW2*SW2)*(Sub11195 + MT*Sub11229) - 
     4*Power(1 - 2*SW2,2)*(4*Sub11197 - MT*Sub11236);

  Sub11312 = 9*MT2*Sub10682 - 64*(SW2*SW2)*Sub11304 - 
     Power(1 - 2*SW2,2)*Sub11305 - Power(3 - 4*SW2,2)*Sub11307 + 
     MT*Sub11311;

  Sub13713 = (3 - 4*SW2)*Sub13707 + 8*MZ2*Sub13708 + 
     Power(1 - 2*SW2,3)*Sub13710 + MT*Sub13712 - 
     32*(SW2*SW2)*(Sub13676 + MT*Sub13677);

  Sub2021 = 2*Power(3 - 4*SW2,3)*Sub1932 - 
     256*(SW2*SW2)*Sub2003 + 128*(1 - 2*SW2)*SW2*Sub2004 + 
     1/MW2*Sub2015 - MT*Sub2020;

  Sub5164 = 16*Sub5153 + Power(3 - 4*SW2,2)*Sub5152 - 
     2*MT*Sub5155 - MT2*Sub5163 + 
     64*(SW2*SW2)*(Sub5101 + MT2*Sub5131);

  Sub6918 = 16*Sub6912 + Power(3 - 4*SW2,2)*Sub6906 + 
     MT*Sub6911 + MT2*Sub6917 + 64*(SW2*SW2)*(Sub6697 + MT*Sub6905)
    ;

  Sub7865 = 1/MW2*Sub7847 + Power(3 - 4*SW2,3)*Sub7850 - 
     64*SW2*Sub7853 - MT*Sub7864 - 
     128*(SW2*SW2)*(-Sub7854 + MT*Sub7815);

  Sub8407 = 16*Sub8394 + Power(3 - 4*SW2,2)*Sub8393 + 
     MT2*Sub8400 - MT*Sub8406 + 
     64*(SW2*SW2)*(Sub8284 + MT2*Sub8384);

  Sub8948 = 64*(SW2*SW2)*Sub8871 + 
     16*Power(1 - 2*SW2,2)*Sub8875 + Power(3 - 4*SW2,2)*Sub8939 - 
     3*MT2*Sub8942 + MT*Sub8947;

  Sub8961 = 64*(SW2*SW2)*(F5*Sub8916) + 
     Power(3 - 4*SW2,2)*Sub8957 + MT2*(3 - 4*SW2)*Sub8959 + 
     16*SW2*Sub8960 - 16*Power(1 - 2*SW2,2)*
      (Sub8856 + MT2*(F13*F35));

  Sub9295 = Power(3 - 4*SW2,2)*Sub9283 - MT2*Sub9288 - 
     4*MT*Sub9291 + Power(1 - 2*SW2,2)*Sub9294 - 
     64*(SW2*SW2)*(-Sub9202 + MT2*Sub9257);

  Sub4595 = 1/MW2*(-(2*SW2*Sub4592) + 
       CW2*(2*Sub4592 - MT2*MW2*Sub1056) + 
       MW2*(4*Sub4589 - 2*MT2*SW2*Sub1056 + (-2 + 4*SW2)*Sub4590 - 
          MT*Sub4594));

  Sub10131 = 6*Sub10124 + (-3 + 4*SW2)*Sub10126 + 
     (-1 + 2*SW2)*Sub10129 - 
     8*(MT2*(F25*F5*Sub10053) + SW2*(Sub10130 + MT*Sub10116));

  Sub15548 = 2*Sub15547 + 
     18*(Sub13048*Sub15490 + Pair3*Sub1347*Sub15485*Sub8135) + 
     3*MT2*Sub15546 + MB2*(9*CW2 - 9*SW2)*
      ((F12 + F7)*Sub228*pave44(cc0));

  Sub15136 = 1/(CW2*MW2)*
     (-Sub15135 + CW2*MW2*(8*S*Sub15131 - 4*Sub15130*Sub966 - 
          12*Sub963*pave66(cc00) - 6*Sub1904*pave66(cc11)));

  Sub15108 = (F29 + F30)*Sub15107 + Sub1485*pave38(cc2) + 
     (MT2*Sub3605 + MT*Sub3606)*pave58(cc1) + 
     Sub2410*pave66(cc0) + Sub2420*pave66(cc1);

  Sub15472 = 1/MW2*(MW2*
        (Sub13093*pave173(cc0) + Sub13216*pave173(cc1) + 
          2*Sub4611*pave173(cc2) - 2*Sub4613*pave174(cc0) + 
          Sub13204*pave174(cc1)) - Sub4612*pave173(cc2) - 
       Sub4616*pave174(cc0));

  Sub15037 = 1/SW2*(Sub15036 + 
       SW2*(Sub27*pave175(bb0) + Sub3488*pave54(cc0) + 
          Sub3495*pave54(cc1) + Sub3556*pave54(cc2)));

  Sub15310 = -(Sub3226*pave82(cc2)) + Sub3148*pave83(cc0) - 
     Sub3182*pave83(cc1) - Sub3194*Sub536*pave83(cc12) + 
     Sub3219*pave83(cc2);

  Sub15099 = MB2*(-(MT*(Sub2352*pave58(cc0))) - 
        Sub689*pave58(cc0)) + Sub2354*pave38(cc0) + 
     Sub2451*pave38(cc1) + Sub3653*pave58(cc2) + 
     Sub2542*pave66(cc2);

  Sub15264 = Sub1797*pave35(cc1) + Sub1653*pave35(cc2) + 
     Sub1661*pave51(cc1) + Sub1558*pave51(cc2) + 
     Sub1564*pave51(cc22);

  Sub15346 = 1/(MW2*SW2)*
     (SW2*(Sub15344 - 32*MW2*(F18*F9*Sub538*pave91(cc22))) + 
       MW2*(SW2*(-8*Sub15341*Sub3131 + (4 - 8*SW2)*Sub15345) + 
          8*F9*Sub2764*Sub538*pave91(cc22)));

  Sub15619 = 1/SW2*(SW2*
        (Sub14766*pave130(dd1) + Sub14806*Sub150*pave130(dd11) + 
          Sub14373*pave130(dd12) + 
          4*(Sub14652*pave178(cc1) + Sub14448*pave179(cc2))) + 
       Sub14653*pave178(cc1) + Sub14447*pave179(cc2));

  Sub15612 = Sub14422*pave119(dd12) + Sub14341*pave120(dd1) + 
     Sub4134*pave120(dd11) + Sub4177*pave120(dd22) + 
     Sub4120*pave63(cc2);

  Sub15620 = Sub4166*pave119(dd13) + Sub14597*pave119(dd3) + 
     Sub4187*pave119(dd33) + Sub14463*pave120(dd2) + 
     Sub14480*pave120(dd23);

  Sub2794 = -4*Sub2793 + 
     3*(-Sub222 - Sub223 + 2*Sub2372)*Sub327 + 
     4*(2*F15*F3*Pair2 + Sub222 + Sub223)*Sub385 + MT*Sub2786 + 
     2/MW2*(Sub2788 + MT2*(Sub2791 + MW2*Sub2781));

  Sub4572 = -2*Sub4569 + (F29 + F30)*Sub4570 + 2*Sub4571 + 
     MT2*Sub4549 + MT*(Sub4559 + MT2*Sub509);

  Sub7794 = 1/(SW2*SW2)*
     (-4*(SW2*SW2*Sub7775 + SW2*Sub7789) + (1 - 2*SW2)*Sub7793 + 
       SW2*SW2*(2*Sub7780 - 2*Sub7786 + MB2*MB2*Sub7772));

  Sub8619 = 1/SW2*(-2*Sub8608 + 
       SW2*(16*F1*F23*Sub8601 + 8*Sub8603 - 8*Sub8604 + 
          (1 - 2*SW2)*Sub8612 + MT*Sub8618));

  Sub6474 = 1/(CW2*SW2)*
     (2*SW2*Sub6468 + CW2*((-24 + 48*SW2)*Sub6443 + 
          SW2*(48*Sub6442 + (-3*MT2 + 3*MZ2)*Sub6466 + 
             MT*(48*Sub6396 + 3*Sub6472) + (-18 + 24*SW2)*Sub6473))
       );

  Sub7283 = 1/(MW2*(SW2*SW2))*
     (-(2*(SW2*SW2)*Sub7282) + 
       MW2*((-3 + (8 - 4*SW2)*SW2)*Sub7277 + 
          SW2*(-6 + 4*SW2)*Sub7280 + 8*(SW2*SW2)*Sub7281 + 
          MT*(F12*Sub7268*(SW2*(-6 + 4*SW2)*F8 + 
                (3 + SW2*(-8 + 4*SW2))*F9) + 
             (12 - 8*SW2)*SW2*Sub7269 + 
             (-6 + (16 - 8*SW2)*SW2)*Sub7270)));

  Sub10857 = 18*(-Pair1 + Pair4)*Sub10852 + 48*SW2*Sub10839 + 
     3*MT*Sub10851 + (3 - 4*SW2)*Sub10854 + 
     Power(3 - 4*SW2,2)*Sub10855 + 8*Power(1 - 2*SW2,2)*Sub10856;

  Sub12119 = 1/(CW2*MW2*SW2)*
     (-(Sub12080*Sub801) - Sub12116*Sub802 + 
       32*MW2*(SW2*SW2)*Sub12112 + MT*MW2*(18 - 48*SW2)*Sub12113 + 
       CW2*(2*MW2*SW2*Sub12117 - 2*MW2*SW2*(F20*Sub12118) - 
          2*MW2*SW2*(F26*Sub12118) - 2*MW2*SW2*(F29*Sub12118) - 
          2*MW2*SW2*(F30*Sub12118)));

  Sub14573 = Power(1 - 2*SW2,2)/SW2*
      (Sub14569 + MZ2*((F17 + F19)*F9) + 
        MT*((-(F13*F35) + F3*F4)*S)) + 
     4*SW2*(Sub14572 + MZ2*((F17 + F19)*F8) + 
        MT*((-(F23*F33) + F5*F6)*S));

  Sub9675 = 48*SW2*(-2*F5*Sub9476 + F1*F2*Sub9556) + 
     64*(SW2*SW2)*Sub9659 + 3*MT2*Sub9670 + 
     Power(3 - 4*SW2,2)*Sub9671 + 4*Power(1 - 2*SW2,2)*Sub9672 + 
     (3 - 4*SW2)*Sub9674;

  Sub6491 = Pair4*Sub6481 - Power(3 - 4*SW2,3)*Sub6482 + 
     128*(SW2*SW2)*Sub6483 - MT*Sub6490 - 
     (12*MT2)/(MW2*SW2)*(F25*F5*Pair2*
        (6*CW2*MT2*SW2 - MW2*Sub4029)) - 
     64*(1 - 2*SW2)*SW2*(Sub6454 + MT*MZ2*(F3*F4) + MT*Sub6420);

  Sub14872 = 8*Finite*Sub609 + 
     (36*MT)/SW2*((F12 - F7)*Sub537*Sub538*pave11(bb11)) + 
     3*(1/(CW2*CW2)*Sub14871 + Sub563*pave11(bb0)) - 
     12*Sub520*(pave23 - 2*pave11(bb00)) + 6*Sub548*pave11(bb1);

  Sub15270 = MT2*(Sub3842*pave177(cc0) - 
        Sub3862*pave43(cc1)) + MZ2*(Sub1668*pave47(cc0)) - 
     Sub3853*pave177(cc1) + Sub1809*pave46(bb0) + 
     S*Sub1684*pave47(cc2);

  Sub15353 = (1 - 2*SW2)*(Sub3351*pave62(cc0)) - 
     1/SW2*(F9*Sub538*(-Sub2769 + 4*SW2*F18)*pave91(cc12)) + 
     Sub3131*pave21(bb0) + Sub3134*pave91(cc0) - 
     Sub3164*pave91(cc1) + Sub2826*pave91(cc2);

  Sub15553 = MT2*(Sub11240*Sub15551 - 
        Pair3*Sub11297*Sub15552) + 
     MW2*(SW2*(Sub6883*pave139(dd00)) - 
        MB2*SW2*(Sub11645*pave99(dd0))) - 
     Sub11091*pave139(dd001) - Sub7068*pave139(dd122);

  Sub15675 = Sub11044*Sub15603 + Sub13746*Sub15604 + 
     (Pair1 + Pair2)*Sub15673 + Pair2*Sub15674 + 
     Sub5567*pave1(dd113) + Sub13364*pave1(dd123);

  Sub15571 = MT2*(Sub11263*Sub15568 + 
        Pair4*Sub11297*Sub15569 + Sub11465*Sub15570) + 
     MT*(Pair4*Sub7112*pave139(dd222)) + 
     (Pair3 + Pair4)*Sub12660*pave139(dd113) + 
     Sub12693*pave139(dd123);

  Sub15516 = MT2*(Sub11783*Sub15514 + Sub11815*Sub15515) + 
     Sub11913*pave139(dd003) + 
     (Pair3 + Pair4)*Sub11453*pave139(dd112) + 
     Sub12734*pave139(dd133) + Pair4*Sub7065*pave139(dd223);

  Sub15797 = 2*Sub15795 - 2*Sub15796 + 
     4*Sub5185*pave140(dd00) + Sub5254*pave140(dd1) - 
     Sub6969*pave140(dd2) - Sub7008*pave140(dd3);

  Sub15781 = -3*Sub15770*Sub5915 - Sub15775*Sub8132 - 
     Sub15776*Sub8165 + 2*Sub15769*Sub8174 + Sub15772*Sub8440 - 
     Sub15777*Sub8730 + Sub15771*Sub9149;

  Sub12497 = 2*Sub12496 + MT2*MT2*Sub12441 + 
     MB2*(Sub12479 + Sub12495) + 
     MT2*(Sub12484 + (-MB2 + MW2)*Sub12444) + 
     MT*(-MB2 + MT2)*(-Sub12452 + (-MB2 + MT2 + MW2)*Sub149);

  Sub1505 = 1/(SW2*SW2)*
     ((F19*Sub901 + F17*Sub902)*(-(2*SW2*F8) + (1 - 2*SW2)*F9) + 
       MT*(SW2*SW2)*Sub1504 + 
       (-1 + 2*SW2)*(F13*F36*Sub901 + F3*F32*Sub902) + 
       2*SW2*(F31*F5*Sub901 + F23*F34*Sub902) + 
       MT2*((-3 + (14 - 16*SW2)*SW2)*Sub1151 + 
          SW2*(-6 + 16*SW2)*Sub1152));

  Sub10183 = 2*Sub10179 + 12*(Sub10178 + Pair3*Sub5238) - 
     (12*Power(1 - 2*SW2,2))/SW2*(F15*F3*Pair2) - 8*SW2*Sub10161 - 
     2*MT*Sub10181 + (1 - 2*SW2)*Sub10182;

  Sub7518 = 128*F22*Sub7505 + 2*Power(3 - 4*SW2,3)*Sub7504 + 
     4/SW2*Sub7507 - 2*((1 - 2*SW2)*Sub7508 + 1/MW2*Sub7512) + 
     MT*Sub7517 - 256*(SW2*SW2)*(Sub7434 - MT*Sub7472);

  Sub14861 = 3*Sub14860*Sub247 + 
     CW2*(CW2*CW2*(-(24*MW2*(Sub371*pave8(bb0))) + 
           S*(-8*Finite*Sub362 - 60*Sub368*pave8(bb0)) + 
           Sub340*(6*pave23 - 12*pave8(bb00)) + 6*Sub377*pave8(bb1)
           ) + 9*Sub335*pave20(bb1));

  Sub15335 = CW2*MW2*(-(SW2*(Sub3088*pave44(cc1))) - 
        SW2*(Sub3062*pave44(cc2))) + 
     MT*MT2*(F12*(Sub15302*Sub2866 + Sub15317*Sub2869 - 
           Sub228*Sub538*pave57(cc11)) + 
        F7*(-(Sub15302*Sub2866) - Sub15317*Sub2869 + 
           Sub228*Sub538*pave57(cc11)));

  Sub15226 = Sub15221 - Sub15225 + 
     Finite*(Sub1621 - 68*SW2*Sub33) + 
     SW2*(-18*Sub15220 + 36*Sub1759*pave47(cc00) - 
        36*S*Sub2681*pave47(cc2));

  Sub15331 = Sub1254*pave167(bb0) + Sub1317*pave26(bb0) - 
     Sub3268*pave84(cc2) + Sub3171*pave85(cc0) + 
     Sub3200*pave85(cc1) + Sub3248*Sub536*pave85(cc12) - 
     Sub3264*pave85(cc2);

  Sub15550 = Sub6080*pave162(cc0) + Sub6021*pave162(cc1) + 
     Sub7111*pave162(cc2) - Sub7138*pave163(cc0) - 
     Sub7103*pave163(cc1) - Sub7169*pave163(cc2) - 
     Sub5719*pave3(dd00);

  Sub15459 = 1/(CW2*SW2)*
     (Sub15458 + CW2*SW2*(Sub11479*pave128(dd00) + 
          Sub13260*pave162(cc1) + Sub4639*pave162(cc2) + 
          Sub4644*pave163(cc0) + Sub13366*pave163(cc2) + 
          Sub11881*pave3(dd00)));

  Sub15692 = -(1/SW2*((Sub11787 - 4*SW2*Sub2556)*
          pave81(cc1))) - Sub13726*pave133(dd12) - 
     Sub13765*pave133(dd13) - Sub13807*pave133(dd22) - 
     Sub13867*pave133(dd3) + Sub13567*pave81(cc0) - 
     Sub13594*pave81(cc2);

  Sub15708 = Sub8518*pave136(dd3) + Sub10135*pave137(dd1) + 
     Sub10411*pave137(dd12) + Sub10605*pave137(dd13) + 
     Sub10672*pave137(dd2) + Sub8554*pave137(dd3) + 
     Sub8586*pave137(dd33);

  Sub15520 = Sub15519 + Sub8179*pave121(dd113) + 
     Sub1888*Sub9895*pave121(dd133) + 
     Pair3*(Sub8250*pave121(dd223) + Sub4300*pave121(dd233)) + 
     Sub12004*pave122(dd123) + Pair4*Sub8187*pave122(dd333);

  Sub4635 = -2*Sub4626 + 2*F15*F3*Sub4631 + 2*Sub4633 + 
     MW2*Sub4619 - MT2*Sub4624 - MT*Sub4629 + 
     2/MW2*(Pair4*Sub4630) - 
     MB2/MW2*(2*Pair4*Sub4634 + MW2*Sub4621);

  Sub7235 = (-(F28*F3) + (F16 + F17)*F9)*Sub3983 + 
     (3 - 2*SW2)*(Sub7221 + MW2*(F20*F21 + (F16 + F17)*F9) + 
        MT2*Sub7190 - MT*Sub7207) + 
     1/MW2*(2*Sub7234 - 2*(3 - 2*SW2)*
         (MT*(-MT2 + MW2)*(F10*F41*Pair4) + MT2*Sub7208));

  Sub11593 = 1/SW2*((-3 + (10 - 8*SW2)*SW2)*Sub11576 + 
       8*(SW2*SW2)*Sub11580 + 
       SW2*(2*(F30*Sub11589 + Sub11590) + 4*Sub11591 - 
          F29*Sub11592) + MT*
        (-(8*(SW2*SW2)*Sub5801) + (-3 + (10 - 8*SW2)*SW2)*Sub5804))
    ;

  Sub6517 = 1/SW2*((-3 + (10 - 8*SW2)*SW2)*Sub6514 + 
       8*(SW2*SW2)*Sub6516 + 
       SW2*((-2 + 4*SW2)*Sub6506 + (-3 + 4*SW2)*Sub6509) + 
       MT*(Sub538*((3 + SW2*(-10 + 8*SW2))*Sub243 + 
             8*(SW2*SW2)*Sub28) + 
          SW2*((2 - 4*SW2)*Sub6511 + (-3 + 4*SW2)*Sub6513)));

  Sub10720 = Opt27 + F17*Sub10717 + F19*Sub10718 - 2*Sub10719
   ;

  Sub8488 = Opt27 + F17*Sub8478 - 2*Sub8483 + F19*Sub8487;

  Sub15122 = 2*Sub15119 - 2*Sub15120 - Sub15121 + 
     Finite*(-Sub2182 - 68*SW2*Sub378) + 
     SW2*(-18*Sub15118 + 36*Sub1630*pave47(cc00) - 
        36*Pair2*S*Sub1290*pave47(cc2));

  Sub15600 = (Pair1 + Pair2)*Sub15598 + Sub15599 + 
     MW2*SW2*(18*(Sub14675*Sub15596 + Sub15597) + 
        MT*(9*Sub14716*pave95(dd2) - 9*Sub14691*pave95(dd3)) + 
        MT2*(-9*Sub14714*pave95(dd2) + 9*Sub14696*pave95(dd3)) - 
        18*Pair4*Sub14633*pave95(dd33));

  Sub15694 = 1/SW2*((Sub14268 + 4*SW2*Sub14266)*
        pave120(dd22)) - 1/SW2*
      ((Sub14313 + 4*SW2*Sub14311)*pave120(dd23)) + 
     1/CW2*(Sub13646*pave133(dd00)) - Sub14211*pave119(dd13) - 
     Sub13559*pave119(dd33) - Sub14082*pave120(dd11) - 
     Sub14144*pave120(dd12) + Sub13701*pave63(cc1);

  Sub4852 = 2*Sub4850 - MB2*MT*(-MB2 + MT2 + MW2)*Sub383 + 
     MB2*MB2*Sub4828 - MB2*(-MT2 + MW2)*Sub4828 + 
     MB2*MT2*Sub4830 - MB2*MT*Sub4833 - MB2*Sub4835 - 
     MT*(-MB2 + MT2)*(Sub403*Sub413 + 2*F29*Sub4837 + 
        2*F30*Sub4837) - MT2*Sub4851;

  Sub15562 = Sub11301*Sub15450 + (Pair1 + Pair2)*Sub15561 + 
     MT*(Sub12845*Sub15464 + Sub12930*Sub15468) + 
     Sub7284*pave125(dd002) + Sub11187*pave125(dd123) + 
     Sub11044*pave2(dd002) + Pair3*Sub11443*pave2(dd223) + 
     Pair4*(Sub4196*pave125(dd223) + Sub11443*pave2(dd223)) + 
     Sub4391*pave2(dd233);

  Sub15768 = Sub7149*pave105(dd1) + Sub7529*pave105(dd12) + 
     Sub7734*pave105(dd13) + Sub7798*pave105(dd2) + 
     Sub7304*pave141(dd11) + Sub7646*pave141(dd12) + 
     Sub7745*pave141(dd13) + Sub7975*pave141(dd2) + 
     Sub8134*pave141(dd3);

  Sub15705 = Sub10097*pave136(dd1) + Sub10221*pave136(dd11) + 
     Sub10308*pave136(dd12) + Sub10467*pave136(dd13) + 
     Sub10631*pave136(dd2) + Sub10720*pave136(dd23) + 
     Sub8581*pave136(dd33) + Sub10294*pave137(dd11) + 
     Sub8488*pave137(dd23);

  Sub11992 = Opt31 - 2*Sub11990;

  Sub12033 = Opt31 - 2*Sub12032;

  Sub15611 = 1/SW2*((F20 + F29)*Sub15610 + Sub15609*Sub4118) + 
     Sub14420*pave1(dd1) + 
     (2*Abb85*Sub148 + Sub14464*Sub153)*pave1(dd11) + 
     Sub14475*pave1(dd12) + Sub4174*pave1(dd2) + 
     Sub4147*pave1(dd23) + Sub4113*pave129(dd0) + 
     Sub14516*pave129(dd13) + Sub4142*pave129(dd22) + 
     Sub4151*pave129(dd23);

  Sub15636 = 1/SW2*((F20 + F29)*Sub15635 + 
       SW2*(Sub14501*pave1(dd13) + Sub4138*pave1(dd22) + 
          Sub14001*pave1(dd3) + 
          (F17 + F19)*(F8 + F9)*S*pave1(dd33) + 
          Sub14446*pave129(dd1) + 
          Sub150*(Sub14468 - MT*Sub25)*pave129(dd11) + 
          Sub14485*pave129(dd12) + Sub4130*pave129(dd2) + 
          Sub14112*pave129(dd3)));

  Sub13117 = 2*(F1*F23 + F15*F3)*(Pair1 + Pair2)*Sub4089 - 
     MB2*(-MB2 + MW2)*(F21*(F29 + F30)) + 
     MT2*MT2*(F22*(2*F20 + 2*F26 + F29 + F30)) + 
     MT*(-MB2 + MT2 + 2*MW2)*
      ((F20 + F26 + F29 + F30)*(F37 + F38 - F39 - F40)) - 
     2*MT2*(-MB2 + MT2 + MW2)*
      ((F10*F13 + F25*F5)*(Pair1 + Pair2 - Pair4)) - 
     2*(-MB2 + MT2 + MW2)*(-MB2 + 2*MW2)*
      ((F1*F23 + F15*F3)*Pair4) - MT2*Sub12162 - 
     MB2*MT2*Sub13100 - MB2*MT*Sub13101 - MB2*Sub13107 - 
     MT*(-MB2 + MT2)*Sub13108;

  Sub15613 = 1/SW2*(SW2*
        (Sub14631*pave130(dd0) + Sub14396*pave130(dd13) + 
          Sub14457*pave130(dd2) + Sub14511*pave130(dd22) + 
          Sub14556*pave130(dd23) + Sub14584*pave130(dd3) + 
          (2*Sub3573*Sub4117 + MZ2*Sub14621)*pave131(dd0) + 
          Sub14611*pave178(cc0) - 4*Sub14424*pave178(cc2) + 
          Sub14618*pave179(cc0) + Sub14679*pave179(cc1)) - 
       Sub14423*pave178(cc2));

  Sub10154 = 1/SW2*((3 + SW2*(-10 + 8*SW2))*Sub10145 + 
       F5*(8*MT*(SW2*SW2)*Sub10142 + 6*SW2*Sub10153) + 
       8*(SW2*SW2)*(Sub10144 + MT*(F30*F38)) + 
       MT2*(F21*((-6 + (20 - 16*SW2)*SW2)*F29 + 
             (9 - 12*SW2)*SW2*F30) + 
          F22*((6 - 12*SW2)*SW2*F29 - 16*(SW2*SW2)*F30) + 
          6*SW2*(F27*F5) + 
          F3*((3 - 6*SW2)*F28 + (-6 + 12*SW2)*(F15*Pair2))) + 
       SW2*((2 - 4*SW2)*Sub10149 + (3 - 4*SW2)*Sub10152) + 
       MT*((3 + SW2*(-10 + 8*SW2))*(F29*F40) + 
          F3*(MT2*(3 - 6*SW2)*F4 + (-6 + 12*SW2)*Sub10137 + 
             (3 + SW2*(-10 + 8*SW2))*Sub9142) + 
          SW2*((3 - 4*SW2)*Sub10139 + (-2 + 4*SW2)*Sub10141)));

  Sub5617 = 1/(CW2*MW2*(SW2*SW2))*
     (Pair4*(MT2*((F18 + F19)*
             (SW2*(-2 + 4*SW2)*F20 + 4*(SW2*SW2)*F26)) + 
          MB2*MT*(F12*((6 - 12*SW2)*SW2*F20 - 12*(SW2*SW2)*F26)))+
         SW2*SW2*(MW2*Sub5615 + 
          F26*(-(2*(MB2 + MT2)*MW2*F21) + 
             4*MB2*((F16 + F17)*Pair4) + 
             MT*(-(8*MB2*(F7*Pair4)) + 2*MW2*Sub1222))) + 
       SW2*(MW2*MW2*(4 - 8*SW2)*(F15*F3*Pair1) + 
          MT*(F20*(MB2*(4 - 8*SW2)*(F7*Pair4) + 
               MW2*(-1 + 2*SW2)*Sub1222))) + 
       CW2*(MT2*((F18 + F19)*Pair4*
             ((2 - 4*SW2)*F20 - 4*SW2*F26)) + 
          MT*(F20*(MB2*(-4 + 8*SW2)*(F7*Pair4) + 
               MW2*(1 - 2*SW2)*(Sub1222 + Sub5587))) + 
          SW2*(F26*(2*(MB2 + MT2)*MW2*F21 + 
               MT*(8*MB2*(F7*Pair4) - 2*MW2*Sub1222))) + 
          MW2*(4*SW2*Sub5609 + (2 - 4*SW2)*Sub5614 + 
             MT2*((1 - 2*SW2)*Sub5582 + 2*SW2*Sub5585) + 
             MT*(-(2*SW2*Sub5592) + (2 - 4*SW2)*Sub5601)) + 
          MB2*(Pair4*(-(4*SW2*((F16 + F17)*F26)) + 
                MT*(F12*((-6 + 12*SW2)*F20 + 12*SW2*F26))) + 
             MW2*((4 - 8*SW2)*(F15*F3*Pair1) + SW2*SW2*Sub5616))));

    

  Sub13431 = -Sub4760 + MT*Sub13430;

  Sub13429 = -Sub13228 + MT*Sub13428;

  Sub7635 = F29*Sub7631 - 2*(F30*Sub7632 + Sub7634) + 
     (4*MT*(-MB2 + MT2 + MW2)*(3 - 2*SW2))/SW2*(F5*F6) + 
     (2*MT*MT2*(-MB2 + MT2 + MW2)*(3 - 2*SW2))/(MW2*SW2)*
      (-(F1*F2) + F12*F8) - 
     (MT*MT2*(-MB2 + MT2 + MW2)*(1 - 2*SW2)*(3 - 2*SW2))/
       (MW2*(SW2*SW2))*(-(F3*F4) + F12*F9) - 
     (4*MT2*(3*MB2 + MT2*(3 - 2*SW2)))/(MW2*SW2)*(F25*F5*Pair4) + 
     (8*MT2)/(MW2*SW2)*(F25*F5*Pair2*Sub4005) + 
     (4*MT2)/(MW2*SW2)*((F1*F23 - F25*F5)*(Pair1 + Pair2)*
        Sub4007) + 4/(MW2*SW2)*(F1*F23*Pair4*Sub4045) + 
     (2*MT*(-MB2 + MT2)*(3 - 2*SW2))/(MW2*SW2)*
      ((-(F1*F2) + F12*F8)*Sub413) - 
     (MT*(-MB2 + MT2)*(1 - 2*SW2)*(3 - 2*SW2))/(MW2*(SW2*SW2))*
      ((-(F3*F4) + F12*F9)*Sub413) + 
     (2*MT2*(1 - 2*SW2)*(3 - 2*SW2))/(SW2*SW2)*Sub6387 - 
     (4*MT2*(3 - 2*SW2))/SW2*Sub6390 + 
     (4*MT*(3 - 2*SW2))/SW2*Sub6410 + 
     (2*MT*(1 - 2*SW2)*(3 - 2*SW2))/(SW2*SW2)*Sub6417 + 
     (2*(1 - 2*SW2)*(3 - 2*SW2))/(SW2*SW2)*Sub6426 + 
     (2*MT2*(1 - 2*SW2)*(3 - 2*SW2))/(MW2*(SW2*SW2))*Sub6441 - 
     (4*MT2*(3 - 2*SW2))/(MW2*SW2)*Sub6444 + 
     (4*(3 - 2*SW2))/SW2*Sub6458 - 
     (MT2*MT2*(1 - 2*SW2)*(3 - 2*SW2))/(MW2*(SW2*SW2))*Sub7624 - 
     (4*MT*MT2*(3 - 2*SW2))/(MW2*SW2)*Sub7628 + 
     (2*MT*MT2*(1 - 2*SW2)*(3 - 2*SW2))/(MW2*(SW2*SW2))*Sub7630 + 
     MB2*Sub7633;

  Sub3638 = (4*MT2 - S34)*Sub593 + MT*Sub3637;

  Sub6652 = F22*(F26 + F30)*(-4*MT2 + S34) + MT*Sub6617;

  Sub9161 = F17*(F45 + F9*(MT2 - S34)) - 
     F3*(2*Abb142*F15 - Sub9144);

  Sub9873 = F17*(F45 + F9*(MT2 - S34)) - 
     F3*(2*Abb144*F15 + Sub9850);

  Sub9852 = F17*(F45 + F9*(MT2 - S34)) - F3*Sub9851;

  Sub14292 = 1/SW2*(Sub14291 + 
       4*SW2*(Sub14288 + MT*(S34*Sub13757)));

  Sub6056 = (1 - 2*SW2)/SW2*Sub6055 - 
     2*(Sub6032 + MT*(Sub200*(MT2 - T)));

  Sub11218 = Sub11197 + 
     MT*(F10*F11*(MT2 - T) + F3*F4*(-MT2 + T));

  Sub11216 = Sub11199 + MT*(F1*F2*(MT2 - T) + F5*F6*(-MT2 + T))
   ;

  Sub3315 = -Sub3314 + 
     F8*(F12*(3*(MT2 + S34) - 3*T) + F7*(-3*(MT2 + S34) + 3*T));

  Sub5323 = -(F3*Sub5322) + F21*F29*(MT2 - T14);

  Sub5327 = F5*(2*Abb160*F25 - Sub5326) + F22*F30*(MT2 - T14)
   ;

  Sub5720 = Sub5677 + MT*(F3*F4*(MT2 - T14));

  Sub5418 = Sub5411 + MT*(F3*F4*(2*MT2 - 2*T14));

  Sub2716 = 1/(SW2*SW2)*
     (4*SW2*Sub2715 + MT*(F9*
          (F7*(6*MT2 - 3*(T + T14)) + F12*(-6*MT2 + 3*(T + T14)))))
    ;

  Sub10700 = F5*Sub10699 + F19*F8*(MT2 - T24);

  Sub8879 = Sub8869 + MT*(Sub243*(-MT2 + S + T24));

  Sub8882 = Sub8875 + MT*(Sub243*(MT2 - S - T24));

  Sub8883 = Sub8871 + MT*(Sub28*(-MT2 + S + T24));

  Sub8880 = Sub8878 + MT*(Sub28*(MT2 - S - T24));

  Sub10896 = 2*F25*Sub10891 + F31*(-3*MT2 + T24);

  Sub10892 = 2*F15*Sub10891 + F32*(-3*MT2 + T24);

  Sub10711 = Sub10700 + MT*(F5*F6*(-MT2 + T24));

  Sub480 = (3 - 4*SW2)*Sub479 + 
     MT*((8*F1*F2 - 8*F12*F8)*(T14 + T24));

  Sub502 = 1/SW2*(Sub501 + 
       MT*SW2*((16*F5*F6 - 16*F7*F8)*(T14 + T24)));

  Sub471 = (3 - 4*SW2)*Sub469 - 4*MT*(Sub470*(T14 + T24));

  Sub503 = 1/(SW2*SW2)*
     ((3 - 4*SW2)*Sub417 + 
       MT*SW2*((4*F3*F4 - 4*F12*F9)*(T14 + T24)));

  Sub10794 = Sub10792 + MT*(F3*F4*(-8*MT2 + 2*T24 + 4*U));

  Sub2328 = 2*F15*Sub2327 + F28*(Sub2324 - T - U);

  Sub8070 = 1/(SW2*SW2)*
     (Sub8069 - 2*MB2*SW2*((F21*F29 + F28*F3)*(T + U)));

  Sub14540 = Sub14538 + MT*(F13*F35*(2*MT2 - T24 - U));

  Sub14542 = Sub14535 + MT*(F3*F4*(-2*MT2 + T24 + U));

  Sub3376 = Sub3375 + MT*
      (F13*F35*(2*MT2 - T24 - U) + F3*F4*(-2*MT2 + T24 + U));

  Sub14541 = Sub14530 + MT*(F5*F6*(-2*MT2 + T24 + U));

  Sub3377 = Sub3373 + MT*
      (F23*F33*(2*MT2 - T24 - U) + F5*F6*(-2*MT2 + T24 + U));

  Sub13821 = Sub13817 + MT*(Sub13757*(-2*MT2 + T24 + U));

  Sub13822 = Sub13820 + MT*(Sub13758*(2*MT2 - T24 - U));

  Sub9165 = Sub9161 + MT*(F3*F4*(3*MT2 - 2*U));

  Sub11165 = -2*F3*(2*Abb185*F15 - Sub11164) + 
     F29*(F53 + F21*(2*MT2 + U));

  Sub11167 = -2*F5*(2*Abb185*F25 - Sub11166) + 
     F30*(F56 + F22*(2*MT2 + U));

  Sub13823 = (3 - 4*SW2)*Sub13822 + 
     3*MT*((-F12 + F7)*F9*(-4*MT2 - S + 2*(T24 + U)));

  Sub15068 = 1/MW2*(Sub15067 + 
       MT*MW2*((F8 + F9)*(F12*
             (MT2*(-36 + 96*SW2) + (18 - 48*SW2)*(T + T14)) + 
            F7*(MT2*(36 - 96*SW2) + (-18 + 48*SW2)*(T + T14)))*
          pave80(cc11)));

  Sub15066 = (F16 + F18)*Sub1141*Sub15065*(-2*MT2 + T + T14) + 
     Sub3754*pave78(cc2);

  Sub14883 = (4*Sub14881)/S34 + 
     3*MT*((F12 + F7)*(Sub14882*Sub230 + 8*Finite*Sub228*Sub644))/
       (-MH2 + S34);

  Sub14890 = (8*Sub14887)/S34 + 
     1/(CW2*CW2)*(Sub14889 + 4*CW2*Sub14888)/(-MZ2 + S34);

}
