#if 0
* self.c
* form factors for {-F[2, {1}], F[2, {1}]} -> {-F[3, {3, Col3}], F[3, {3, Col4}], V[1]}
* generated by FormCalc 8.1 on 6-Apr-2013 23:49
#endif

#include "vars.h"
#include "inline.h"


void self() {

#include "vars.h"

#include "inline.h"

  Cloop(1) = Cloop(1) + 
     EL*(1/108.*Sub14855/(-MT2 + Sub14830) - 
        1/108.*Sub14865/(-MT2 + Sub14832) - 
        1/144.*Sub14878/(-ME2 + Sub14834) + 
        1/144.*(Sub14845/(-ME2 + Sub14828) + 
           Sub14885/(-MZ2 + S34)) + 
        Alfa2/(648.*(CW2*CW2)*MW2*SW2)*Sub14918 - 
        MT/2.*((F12 + F7)*Sub14920)/(-MH2 + S34));

#ifdef DEBUG
  DEB("self: Cloop(1) =", Cloop(1));
#endif

}
