#if 0
* abbr1h10.c
* abbreviations for {-F[2, {1}], F[2, {1}]} -> {-F[3, {3, Col3}], F[3, {3, Col4}], V[1]}
* generated by FormCalc 8.2 on 11-Apr-2013 14:53
#endif

#include "vars.h"
#include "inline.h"


void abbr1h10() {

#include "vars.h"

#include "inline.h"

  Sub7914 = 4*F12*F26*Pair4 + 
     F9*(-4*F30*Pair3 + 2*F26*Pair4) + F11*Sub7910 - 
     2*(Pair1*Sub7911 + Sub7912) + 2*Sub7913 + F5*F6*(T + T14);

  Sub5862 = -(F23*F50) - F14*F52 + 2*F24*F50*Pair1 + 
     2*F13*F52*Pair1 + F5*F6*T14 + F2*F3*(-MT2 + T14) - MT2*(F5*F6)
    ;

  Sub7022 = F30*(F39 - 2*F12*Pair1) + 
     F50*(-2*F23 + 4*F24*Pair1) - F26*Sub7019 + F42*Sub7021 - 
     F11*F12*T14 + 2*F5*F6*T14 + 
     MT2*(-(F24*F33) - 2*F5*F6 + F11*F9);

  Sub6146 = (F10 + F11)*(F12 + F9)*Sub387 - 4*Sub6143 + 
     4*Sub6144 + 2*(Sub6145 + F2*F3*T14 + F5*F6*(T + T14));

  Sub7025 = F52*(-2*F14 + 4*F13*Pair1) + 
     F29*(F37 - 2*F9*Pair1) - F19*Sub7023 + F41*Sub7024 + 
     2*F2*F3*T14 + F10*(-(F9*T14) + MT2*F12) + 
     MT2*(-2*F2*F3 - F13*F35);

  Sub9675 = F42*(-2*F34 + 4*F1*Pair3) - F26*Sub9674 + 
     F11*(-F55 - F9*T14) + F5*(-2*F44*Pair1 + F6*(-MT2 + S + T14));

    

  Sub8619 = F26*(-F37 + 2*F12*Pair1) - F30*Sub8618 - 
     2*F1*F4*T + F12*(F46 + F11*(-MT2 + T)) + 
     F5*(-2*F48*Pair1 + F6*(-T - T14)) + F11*F9*T14 + 
     MT2*(2*F1*F4 + F5*F6);

  Sub6510 = S34*Sub6507 + 4*Sub6508 + 
     F12*(F46 + F11*(-3*T - 6*T14)) + F9*(-F46 + F11*T14) - 
     2*(F23*F50 + MT2*(F24*F33)) + 
     2*(Sub6509 + F5*F6*T + MT2*Sub6506);

  Sub6502 = 2*F14*F52 + S34*Sub6499 - 4*Sub6500 + 
     F12*(F45 + F10*(2*MT2 - T14)) + 
     F9*(-F45 + F10*(3*T + 6*T14)) - 
     2*(Sub6501 + F7*F8*T + MT2*Sub6498);

  Sub6671 = F22*Sub6668 + F21*(-Sub6670 + F30*T14) + 
     F5*(-Sub6669 + F31*T14 + 
        F25*(Pair2*(-2*T - 4*T14) - 4*Pair1*T14));

  Sub6663 = -(F26*F37) - F30*F37 + Opt23 - 2*Pair1*Sub6662 + 
     F5*F6*(2*MT2 - T - T14);

  Sub8214 = (3*F10*F22 + 2*F14*F7)*S34 - 4*Sub8213 - 
     2*((F19*F21 + F13*F36)*(MT2 - T) + F21*F29*(MT2 + S34 - T)) + 
     (4*F13*F7*(-Pair1 + Pair4) + Sub6395)*(-2*MT2 + T + T14) + 
     2*(F22*Sub8212 + (F21*(F19 + F29) + F13*F36)*
         (-MT2 + S34 + T14));

  Sub9018 = F56 + 2*F22*Pair2 + 
     F18*(2*Pair2 - 2*(Pair3 + Pair4)) + F21*(-MT2 - S + T24);

  Sub4614 = 2*(F41*F7 + F29*F9)*Pair4 - F12*Sub4612 + 
     F2*Sub4613 + F7*F8*(-S - T14 - T24) + F10*F9*(S + T14 + T24);

    

  Sub9011 = -(F19*Sub7019) + F2*Sub9009 - 2*Sub9010 + 
     F7*(4*F41*Pair3 + F8*(T14 - T24)) + F10*(Sub9008 + F9*T24) + 
     MT2*Sub9007;

  Sub4617 = 2*(F44*F5 + F30*F9)*Pair4 - F12*Sub4615 + 
     F1*Sub4616 + F5*F6*(-S - T14 - T24) + F11*F9*(S + T14 + T24);

    

  Sub14122 = Sub14181 + 
     Pair1*((F1*F24 + F25*F5)*S + F15*F2*(S + T24));

  Sub8557 = F2*(6*F15*Pair2*S - F27*T14) + 
     F19*F20*(-S - T24) + F10*(Sub8381 - F16*T24) + 
     F15*(-2*Sub8521 - 4*F2*Pair2*T24) + MT2*Sub8556;

  Sub8569 = -(F10*Sub8566) + S*Sub8567 + F19*F21*(MT2 - T24) + 
     F7*(-Sub8568 - F14*T24 + 
        F13*(2*Pair1*T24 - 2*Pair2*T24 - 2*MT2*Pair1));

  Sub2857 = -(F26*Sub2853) - 2*Sub2855 - 4*Sub2856 + 
     F19*(-Sub2853 + F20*(-2*MT2 + S - T14 - T24)) + 
     F1*F23*(2*MT2 - 2*T14 - 2*T24) + 
     F20*F26*(-2*MT2 + S - T14 - T24) + 
     F2*F27*(-2*MT2 + 2*T14 + 2*T24) + MT*Sub2852 - MT2*Sub2854;

  Sub5404 = Sub4584 + Pair4*(-6*F29*F9 - 2*Sub5403) + 
     F2*(F43*(2*Pair3 + 4*Pair4) + F3*(-2*S - T14 - T24)) + 
     F7*F8*(S + T14 + T24) + 
     F10*(F9*(-S - T14 - T24) + F12*(2*S + T14 + T24));

  Sub13840 = Power(1 - 2*SW2,2)/SW2*
      (Sub13836 + MT*((F2*F3 - F13*F35)*(2*MT2 - T24 - U)) + 
        MZ2*(Sub3677 + MT*(F2*F3 - F13*F35))) + 
     SW2*(-(4*MT*((F24*F33 - F5*F6)*(2*MT2 - T24 - U))) + 
        4*(Sub13839 + MZ2*(Sub7586 + MT*(-(F24*F33) + F5*F6))));

  Sub9828 = -F45 - 2*F46 + 
     F10*(8*MT2 - S34 - 2*(S + T + T24) - 3*U);

  Sub12561 = -4*Sub12559 - 8*Sub12560 + (F10 + F11)*(S - T - U)
   ;

  Sub7188 = F19*(F39 + F40 + 2*F12*Pair4) + F7*F8*S + 
     F29*Sub6189 + 4*Sub7187 - 
     2*(F41*F7*Pair3 + F2*(F43*Pair4 + F3*(S + T + U)));

  Sub7190 = F26*(-F39 - F40 - 2*F12*Pair4) + 
     2*(F44*F5*Pair3 + F1*F42*Pair4) - F5*F6*S - F30*Sub6189 - 
     4*Sub7189 + F1*F4*(2*S + 2*T + 2*U);

  Sub12630 = F26*(-F39 - F40 - 2*F12*Pair4) + 
     F30*(F37 + F38 - 2*Sub12507) + 
     F1*(F42*(-2*Pair3 - 4*Pair4) + F4*(S - T - U)) + 
     F5*(2*F44*Pair4 + F6*(T + U));

  Sub12631 = F19*(F39 + F40 + 2*F12*Pair4) + 
     F29*(-F37 - F38 + 2*Sub12507) + 
     F7*(-2*F41*Pair4 - F8*T - F8*U) + 
     F2*(F43*(2*Pair3 + 4*Pair4) + F3*(-S + T + U));

  Sub12791 = 2*(Pair3*Sub12785 + Sub12787) - 2*Sub12790 - 
     4*((F41*F7 - 2*(F29 + F30)*F9)*Pair4 + Sub4396) - 
     Sub12786*(T + U) + 10*F9*(F29*Pair3 + MT2*(F10 + F11)) + 
     3*MT2*(F5*F6 + F7*F8);

  Sub13624 = 2*(Sub13619 + Pair3*Sub13620) - 
     4*(F30*F9*(Pair1 + Pair2) + Sub13621) - 2*Sub13623 + 
     4*(Sub13622 + Pair4*Sub4358) + 
     F7*(4*F41*(Pair1 + Pair2) + F8*(3*MT2 - T - U)) + 
     F5*F6*(3*MT2 - T - U);

  Sub11612 = F30*(S34 - Sub262 - Sub4257) + 
     F29*(S34 - Sub262 - Sub388 - Sub4257) + F26*(S34 + T + U) + 
     F19*(-4*MT2 + S34 + T + U) + MT2*(-4*F26 - 2*(F29 + F30));

  Sub5442 = -(F7*F8*Sub4169) + F5*F6*(-Sub4169 - Sub4170) - 
     F7*F8*Sub4170 + F2*F3*Sub5248 + F1*F4*Sub5248 - 2*Sub5440 - 
     F9*Sub5441 - F10*F12*Sub921 + 
     F11*(-(F12*Sub921) + F9*(2*MT2 - T - U));

  Sub4343 = F2*(-4*F15*(Pair2 + Pair4)*Sub3913 - 
        MT*(F3*Sub3933)) + MB2*MT*(-3 + 2*SW2)*Sub4320 + 
     F7*(2*Sub4342 + MT2*MT2*(-12 + 8*SW2)*(F13*Pair4) + 
        MT*(F8*(Sub3933 + Sub3924*(2*MT2 - T - U)))) + 
     MT2*(F21*F29*(-Sub879 + MT2*(3 - 2*SW2)) + 
        F14*F7*(Sub879 + MT2*(-3 + 2*SW2)) + MT*(3 - 2*SW2)*Sub4320
        );

  Sub12519 = -2*Sub12517 + 2*Sub12518 + 
     F20*(F26*(T + U) + F19*(-2*MT2 + T + U) + 
        (F29 + F30)*(S + T + U) + MT2*(-2*F26 - 4*(F29 + F30))) + 
     F1*F24*(-2*(Pair3*(T + U) + Pair4*(S + T + U)) + 
        MT2*(4*Pair3 + 8*Pair4));

  Sub12522 = -2*Sub12520 + 2*Sub12521 + 
     F21*(F26*(T + U) + F19*(-2*MT2 + T + U) + 
        (F29 + F30)*(S + T + U) + MT2*(-2*F26 - 4*(F29 + F30))) + 
     F13*F7*(-2*(Pair3*(T + U) + Pair4*(S + T + U)) + 
        MT2*(4*Pair3 + 8*Pair4));

  Sub10675 = -2*Sub10673 + 2*Sub10674 + 
     F1*(F23*S + F24*(-2*Pair4*Sub262 + 
           2*(Pair1 + Pair2)*Sub388)) + 
     F20*(F30*(Sub262 + T - T14 - T24 + U) + 
        F26*(Sub4257 + T - T14 - T24 + U));

  Sub5822 = Abb155*(F1*F24 + F13*F7) + F16*(F19 + F30)*Pair1 + 
     F22*F29*(Pair1 + Pair2) + F25*F5*Pair3*S34 + 
     MT2*(F1*F24*(Pair3 + Pair4));

  Sub7139 = F1*(F42*Pair3 + F4*S34) + Sub5290 + 
     F2*(F43*Pair3 + F3*(S34 + T));

  Sub1105 = -4*(F29 + F30)*Pair3 + 4*(F19 + F26)*Pair4 + 
     F11*(S34 - T + T14) + F10*(-2*MT2 + S34 - T + T14) - 
     2*(F45 + F46 + MT2*F11);

  Sub6977 = F50*(F23 - 2*F24*Pair1) + 
     F42*(F34 + F1*(-2*Pair1 - 2*Pair2)) - F30*Sub6974 + 
     F26*(-F39 + 2*Sub6975) + F11*F12*(-S34 - T) + 
     F1*(F4*S34 + F4*T) - F24*F33*T14 + MT2*Sub6976;

  Sub6981 = F52*(F14 - 2*F13*Pair1) + 
     F41*(F36 - 2*F7*Pair1 - 2*F7*Pair2) - F10*F9*S34 + 
     F19*(-F37 - 2*Sub6978) - F29*Sub6979 - F10*F9*T + 
     F7*F8*(S34 + T) - F13*F35*T14 + MT2*Sub6980;

  Sub8692 = 2*(F23*F50 + F48*F5*Pair1) + 
     F26*(-F37 + 2*F9*Pair1) - 4*(F24*F50*Pair1 + F1*F42*Pair4) + 
     F30*(F37 - 2*Sub8687) + F5*F6*(T - T14) + 
     (-2*F24*F33 + F11*F9)*T14 + MT2*Sub8691;

  Sub8971 = F42*(F34 - 2*F1*Pair3) + F41*(F36 - 2*F7*Pair3) + 
     (-(F2*F3) - F1*F4 - F5*F6 - F7*F8 + F10*(F12 + F9) + 
        F11*(F12 + F9))*T14;

  Sub7104 = F42*(-F34 + F1*(-2*Pair1 - 2*Pair2 + 4*Pair3)) + 
     F26*(F37 + F39 - 2*Sub7101) - F30*Sub7102 - F11*Sub7103 + 
     F12*(F46 + F11*(3*MT2 - 2*T14)) + 2*F1*F4*T14 + 
     F5*(-2*F48*Pair1 + F6*(-T + T14));

  Sub13810 = -(F10*F12*S) - F11*F12*S + 2*Sub13809 + 
     4*F19*Sub5705 + 4*F26*Sub5705 + 
     F2*(-4*F43*Pair4 + F3*(-2*MT2 + T14 + T24)) + 
     F1*(-4*F42*Pair4 + F4*(T14 + T24) - 2*MT2*F4);

  Sub9236 = -(F26*Sub9232) + F11*Sub9233 - F24*F34*T14 + 
     F1*(-Sub9235 - F23*T24 + 
        F24*((4*Pair1 - 2*Pair4)*T14 + 2*Pair1*T24)) + MT2*Sub9234;

    

  Sub9241 = -(F19*Sub9237) - F10*Sub9238 - F13*F36*T14 + 
     F7*(Sub9240 - F14*T24 + 
        F13*((4*Pair1 - 2*Pair4)*T14 + 2*Pair1*T24)) + MT2*Sub9239;

    

  Sub7782 = (4*F12*F30 - 4*F2*F43)*Pair2 + 
     (-4*F2*F43 + 4*F41*F7)*Pair4 - 4*Sub7775 + 4*Sub7777 - 
     2*Sub7778 + F11*Sub7779 + 2*Sub7781 + Sub7780*(T14 + T24) + 
     3*MT2*Sub2200;

  Sub11362 = F29*(-2*F9*Pair1 - 2*F9*Pair2) + 
     F12*(F29*(8*Pair1 + 8*Pair2 - 2*Pair3 - 4*Pair4) + 
        F19*(4*Pair3 + 6*Pair4)) - F7*F8*S - Sub4584 + 
     2*Pair4*Sub4597 + F7*F8*(-T14 - T24) + 
     F2*(-2*F43*Pair3 - 4*F43*Pair4 + F3*(2*S + T14 + T24));

  Sub11363 = F30*(-2*F9*Pair1 - 2*F9*Pair2) + 
     F12*(F30*(8*Pair1 + 8*Pair2 - 2*Pair3 - 4*Pair4) + 
        F26*(4*Pair3 + 6*Pair4)) - F5*F6*S - Sub4586 + 
     2*Pair4*Sub4601 + F5*F6*(-T14 - T24) + 
     F1*(-2*F42*Pair3 - 4*F42*Pair4 + F4*(2*S + T14 + T24));

  Sub14248 = -(F16*S) + F18*(-4*MT2 + T + T14) + 
     F17*(-4*MT2 + S + S34 + T + T14 + T24 + U);

  Sub8804 = -2*F54 - F56 + 
     F21*(S + S34 + T + T14 + T24 + 2*U) + MT2*(-6*F20 - 8*F21);

  Sub4072 = F16*Sub153 + F17*Sub407 + 
     F22*(2*MT2 - S - T24 - U) + F18*(2*MT2 - S34 - T24 - U);

  Sub13010 = Abb67 + Pair4*(-S34 - 2*T - T14 - T24 - 2*U) + 
     Pair3*(-T - U) + MT2*(2*Pair3 + 6*Pair4);

  Sub11032 = -2*Sub11030 + F20*F30*Sub1765 + 
     F1*(Sub11031 + F23*U + 
        F24*Pair4*(2*(T14 + T24) + 4*(T + U))) + 
     Pair3*(2*F17*F30 - 4*MT2*(F1*F24));

  Sub8750 = 2*Sub8748 + F28*(-S34 - U) + F31*(-T24 + U) + 
     F25*(6*Pair2*U - 2*(Sub8749 + Pair4*(T24 + U)));

  Sub12807 = (F29 + F30)*
      ((F18 + F22)*(Pair3 + 2*Pair4) + (F20 + F21)*(MT2 - S)) + 
     Sub12142 + F15*F2*(Pair1*(-T - U) + Pair4*(T + U));

  Sub4401 = (F29 + F30)*(F39 + F40) + 
     4*((F41*F7 - 2*(F29 + F30)*F9)*Pair4 + Sub4396) + 
     2*(Sub4399 + (-(F7*F8) + F11*F9)*(T14 + T24)) - 
     2*(Pair3*Sub4395 + Sub4400 + Sub4397*(T + U) + MT2*Sub4394);

  Sub12405 = F18*(F29 + F30)*(Pair1 + Pair2) + 
     F22*(F30*Pair2 + F29*(Pair1 + Pair2)) + Sub12141 + Sub5244 + 
     F15*F2*Pair2*(-2*MT2 + T + U) + 
     Pair1*(F22*F30 + F15*F2*(-2*MT2 + T + U));

  Sub12476 = -2*Sub12474 + 2*Sub12475 + 
     F15*F2*(2*Pair3 + 4*Pair4)*(T + U) + 
     F1*F24*(2*Pair3*(T + U) + 
        Pair4*(2*(T14 + T24) + 4*(S + T + U))) + 
     F20*(F26*(-T - U) + F19*(2*MT2 - T - U) + 
        (F29 + F30)*(-T14 - T24 - 2*(S + T + U)) + 
        MT2*(2*F26 + 4*(F29 + F30))) + 
     MT2*((F15*F2 + F1*F24)*(-4*Pair3 - 8*Pair4));

  Sub12496 = -2*Sub12494 + 2*Sub12495 + 
     F25*F5*(2*Pair3 + 4*Pair4)*(T + U) + 
     F13*F7*(2*Pair3*(T + U) + 
        Pair4*(2*(T14 + T24) + 4*(S + T + U))) + 
     F21*(F26*(-T - U) + F19*(2*MT2 - T - U) + 
        (F29 + F30)*(-T14 - T24 - 2*(S + T + U)) + 
        MT2*(2*F26 + 4*(F29 + F30))) + 
     MT2*((F25*F5 + F13*F7)*(-4*Pair3 - 8*Pair4));

  Sub9767 = F17*(F45 + F10*(-Sub9761 - Sub9762)) + 
     F18*(F46 + F11*(-Sub9761 - Sub9762)) + 
     2*((F2*F27 + F28*F5)*Sub9762 + Sub9765) + 4*Sub9766 + 
     F5*(F31*(-2*MT2 + 2*T24) + 
        F25*((-4*Pair1 + 4*Pair4)*(T24 + U) + 
           MT2*(12*Pair1 - 12*Pair4))) - MT*Sub9764;

  Sub4064 = (F18*F26 + F17*(F26 + F30))*(Pair1 + Pair2) + 
     Sub14103 + Sub14338 + 
     Pair1*(F18*F30 + F15*F2*(-2*MT2 + T24 + U)) + 
     Pair2*(F18*F30 + F13*F7*S34 + F15*F2*(-2*MT2 + S34 + T24 + U))
    ;

  Sub14162 = -2*Sub14160 + 2*Sub14161 + 
     F25*F5*(Pair1 + Pair2)*(-4*MT2 + 2*(T24 + U)) + 
     F11*((F16 + F22)*Sub153 + 
        (F17 + F18)*(-2*MT2 - S34 + 2*Sub153 + T24 + U));

  Sub14159 = -2*Sub14157 + 2*Sub14158 + 
     F13*F7*(Pair1 + Pair2)*(-4*MT2 + 2*(T24 + U)) + 
     F10*((F16 + F22)*Sub153 + 
        (F17 + F18)*(-2*MT2 - S34 + 2*Sub153 + T24 + U));

  Sub5823 = (-2*F29 - 4*F30)*Pair4 + 
     F26*(2*(Pair1 + Pair2) - 2*(Pair3 + Pair4)) + 
     F10*(5*MT2 - S34 - 2*T) + 3*MT2*F11;

  Sub14183 = (F22*(F26 + F29 + F30) + 
        F16*(F19 + F26 + F29 + F30))*Pair1 + 
     F19*(F22*Pair1 + F17*Pair2) + F15*F2*Pair2*T;

  Sub12817 = Sub12339 + F15*F2*Pair4*(S + T);

  Sub9081 = F1*F23*S + F11*((F16 + F22)*S + MT2*(F17 + F18)) + 
     F10*(F22*S + F16*(S + T14) + MT2*(F17 + F18));

  Sub13241 = F12*F29*(Pair1 + Pair2) + 
     (F1*F42 + F2*F43)*Pair3 + Sub3369 + F2*F3*T14 + 
     MT2*((F10 + F11)*F9);

  Sub6848 = F52*(-2*F14 + 4*F13*Pair1) + 
     F29*(F39 - 2*F12*Pair1 + 2*F9*Pair3) + F19*Sub6847 + 
     F9*(F45 + F10*(3*MT2 - S34 - 3*T14)) + 
     (F10*F12 + 2*F7*F8)*T14 + 
     F2*(2*F51*Pair1 + F3*(-2*MT2 + T + T14)) - MT2*(F13*F35);

  Sub8203 = -(F22*Sub6664) + F19*F21*(MT2 - T14) - 
     F21*F29*T14 - F13*F36*T14 + 
     F7*(Sub8202 - F14*T14 + 
        F13*(2*Pair2*T14 + Pair1*(2*T + 4*T14))) + MT2*Sub8201;

  Sub9724 = F47 + F48*
      (2*(Pair1 + Pair2) - 2*(Pair3 + Pair4)) + 
     F44*(-4*(Pair1 + Pair2) + 4*(Pair3 + Pair4)) - F6*T24;

  Sub13465 = F2*F3*(-2*MT2 + S) + 4*Sub13463 - 
     4*(Pair3*Sub13462 + Sub13464) - F7*F8*T14 + 
     F5*F6*(-T14 - T24) - F7*F8*T24 + F1*(F4*S - 2*MT2*F4);

  Sub14178 = (F17 + F18)*(F19 + F26 + F29 + F30)*Pair2 + 
     Abb86*Sub138 + F15*F2*Pair1*T24;

  Sub7786 = -(F10*(F16 + F17)*Sub4541) - 
     F11*(F16 + F17)*Sub4541 + F20*F29*Sub4542 + F20*F30*Sub4542 - 
     4*Sub7783 + Sub4538*Sub7784 + 4*Sub7785 + 
     4*F1*F24*(Pair3 + Pair4)*(T14 + T24) - 
     2*F19*F20*(S + 2*T14 + 2*T24) - 2*F20*F26*(S + 2*T14 + 2*T24);

    

  Sub9853 = F45 + F46 + F10*(2*MT2 - S34 - U) + 
     F11*(-4*MT2 + S + S34 + T + T14 + 2*T24 + U);

  Sub14005 = F16*Sub1724 + F17*Sub407 + 
     F18*(2*MT2 - S34 - T24 - U) + 
     F22*(4*MT2 - S34 - T - T14 - T24 - U);

  Sub12965 = -2*Sub12961 - 4*Sub12962 + 2*Sub12963 + 
     F19*(2*F16*Pair4 + 2*F17*Pair4 - F20*Sub1976) - F20*F29*T14 - 
     F20*F30*T14 - F20*F29*T24 - F20*F30*T24 + 
     F26*(Sub12964 + F20*U);

  Sub12970 = -2*Sub12966 - 4*Sub12967 + 2*Sub12968 - 
     F26*Sub12969 + F19*(2*F18*Pair4 + 2*F22*Pair4 - 
        F21*Sub1976) - F21*F29*T14 - F21*F30*T14 - F21*F29*T24 - 
     F21*F30*T24 + F21*F26*U;

  Sub12171 = -2*(F2*F43*Pair4 + Sub12170) + 4*Sub3368 + 
     F12*(4*F30*Pair4 + (F10 + F11)*Sub921) + 
     (F2*F3 + F1*F4)*(2*S + T + U);

  Sub11416 = F19*Sub11414 + F29*(-F37 - F38 + 2*Sub11415) + 
     F2*(-Sub10846 + F3*U) + F7*(-2*F41*Pair4 - F8*T - F8*U) + 
     F10*(F12*(S - T - U) + F9*(T + U));

  Sub5294 = (F15*F2 + F1*F24)*
      (Abb50 + Pair4*(T14 + T24) + Pair3*(-T - U)) + MT2*Sub5293;

  Sub8829 = -(F28*Sub1049) + F31*(MT2 - S34 - 2*U) + 
     F25*(2*Abb141 + Pair3*(2*(T + T14) - 2*U) + 
        Pair1*(-4*(T + T14) + 4*U) + MT2*(-4*Pair1 + 2*Pair3));

  Sub4065 = -2*Sub4063 + 
     F11*((F17 + F18)*Sub407 + F22*(-T24 - U) + 
        F16*(2*MT2 - T24 - U)) + 
     F10*((F17 + F18)*Sub407 + (F16 + F22)*(2*MT2 - T24 - U)) + 
     2*(Sub4064 + (F1*F24 + F25*F5 + F13*F7)*(Pair1 + Pair2)*
         (T24 + U)) + MT2*(2*F11*F22 - 
        4*(F1*F24 + F25*F5 + F13*F7)*(Pair1 + Pair2));

  Sub2228 = Abb15*(F25*F5 + F13*F7) - F13*F7*Pair4*S34 + 
     MT2*((F10 + F11)*(F18 + F22) + F21*(F19 + F26) - F28*F5 + 
        F14*F7) + F25*F5*(-(Pair4*S34) + 2*MT2*Pair2);

  Sub3436 = -4*Sub3433 + 4*Sub3434 - 2*(Sub3435 + F11*F12*T) + 
     F9*(8*(F19 + F26)*Pair4 + (F10 + F11)*(S34 - 3*T + T14));

  Sub8900 = -(F10*Sub8899) - F11*Sub8899 + 
     F1*(2*F42*Pair2 + F4*(-S - T24)) + 
     F2*(-2*F43*Pair1 - F3*T24) + F5*(-2*F44*Pair1 - F6*T24) + 
     F7*(2*F41*Pair2 - F8*S - F8*T24) + MT2*Sub523;

  Sub4365 = 6*F12*F29*Pair3 + 
     F30*(-4*F9*(Pair1 + Pair2) + 6*F12*Pair3) + 
     F7*(4*F41*(Pair1 + Pair2) - 4*F8*S) + 
     4*(Pair4*Sub4358 + Sub4359) + 2*(F1*F4*S + Sub4360) - 
     S34*Sub4361 - 2*Sub4363 + Sub4362*(T14 + T24) - 
     4*(Sub4364 + MT2*Sub4357);

  Sub5406 = F26*(F39 + F40) + 
     F30*(-F37 - F38 + 2*F39 + 2*F40 - 6*F9*Pair4) - 
     2*Pair4*Sub5405 + F1*(F42*(2*Pair3 + 4*Pair4) + 
        F4*(-2*S - T14 - T24)) + F5*F6*(S + T14 + T24) + 
     F11*(F9*(-S - T14 - T24) + F12*(2*S + T14 + T24));

  Sub13869 = F17*Sub13850 + F16*Sub13868 + 
     F22*(6*MT2 - T - T14 - 2*(S + T24) - 2*U) + 
     F18*(6*MT2 - S34 - T - T14 - 2*(S + T24) - 2*U);

  Sub6578 = F19*(F37 + F38) - 
     F29*(F37 + F38 + F9*(-2*Pair3 - 2*Pair4)) + F10*F9*S + 
     F7*(2*F41*(Pair1 + Pair2) - 4*F41*Pair4 - F8*S) - F7*F8*S34 + 
     F10*F12*T - 2*F2*F3*T + F10*F12*U - 2*F2*F3*U + 2*MT2*Sub6577;

    

  Sub6580 = F26*(F37 + F38) - 
     F30*(F37 + F38 + F9*(-2*Pair3 - 2*Pair4)) + F11*F9*S + 
     F5*(2*F44*(Pair1 + Pair2) - 4*F44*Pair4 - F6*S) - F5*F6*S34 + 
     F11*F12*T - 2*F1*F4*T + F11*F12*U - 2*F1*F4*U + 2*MT2*Sub6579;

    

  Sub10237 = -(F11*Sub10229) + F1*Sub10234 + 
     F12*(F30*(-4*(Pair1 + Pair2) + 10*Pair4) + 2*Sub10235) - 
     2*Sub10236 + F5*(F44*(4*(Pair1 + Pair2) + 2*Pair4) + 
        F6*(-S34 + T - T14 - T24 + U));

  Sub8267 = -(F5*F6*S34) + F10*F9*Sub152 + F10*F12*Sub8265 + 
     F11*(F12*Sub152 + F9*Sub8265) - F13*F35*T24 + 
     F24*F33*(-T24 - 2*U) - 2*F13*F35*U + F5*F6*U + 
     F2*F3*(-S34 + U) + MT2*Sub8266;

  Sub10233 = Opt28 + F7*
      (F41*(-4*(Pair1 + Pair2) - 2*Pair4) + F8*S34) + 
     F10*Sub10229 - F2*Sub10230 + 
     F12*(F29*(4*(Pair1 + Pair2) - 10*Pair4) - 2*Sub10231) + 
     2*Sub10232;

  Sub6582 = F19*(F39 + F40) - 
     F29*(F39 + F40 + F12*(-2*Pair3 - 2*Pair4)) + F10*F12*S + 
     F2*(2*F43*(Pair1 + Pair2) - 4*F43*Pair4 - F3*S) - F2*F3*S34 - 
     2*F7*F8*T + F10*F9*T - 2*F7*F8*U + F10*F9*U - 2*MT2*Sub6581;

  Sub6584 = F26*(F39 + F40) - 
     F30*(F39 + F40 + F12*(-2*Pair3 - 2*Pair4)) + F11*F12*S + 
     F1*(2*F42*(Pair1 + Pair2) - 4*F42*Pair4 - F4*S) - F1*F4*S34 - 
     2*F5*F6*T + F11*F9*T - 2*F5*F6*U + F11*F9*U + 2*MT2*Sub6583;

  Sub9833 = F17*Sub9821 - 4*Sub9825 - F18*Sub9828 - 
     2*(S34*Sub9824 + Sub9830) + 4*Pair4*Sub9831 + 
     Pair2*(-8*Sub9826 - 12*F15*F2*U) + 
     F5*(2*F28*U - 2*(Sub9829*T24 + Sub9827*U)) + 
     2*(Sub9832 + MT2*Sub9823);

  Sub13292 = (F2*F3 + F1*F4)*Sub5369 + 
     S34*(-Sub4324 - Sub595) + S*(F7*F8 - Sub4324 - Sub595) + 
     F7*F8*(2*S34 + Sub6074) + F5*F6*(S + 2*S34 + Sub6074) - 
     2*(Sub13291 + (Pair1 + Pair2)*Sub6086 + 
        Pair4*(Sub6083 + Sub6087));

  Sub9082 = F18*F26*Pair1 + F10*(F17*T14 + MT2*(F16 + F22)) + 
     MT2*(F11*(F16 + F22) + F1*F23 + F2*F27 + F24*F34 + F13*F36 + 
        F28*F5 + F14*F7);

  Sub7100 = F52*(-2*F14 + 4*F13*Pair1) + 
     F9*(F45 + 2*F29*Pair3 + F10*(3*MT2 - S34 - 3*T14)) + 
     2*(F19*Sub7099 + (F2*F3 + F7*F8)*T14) + 
     MT2*(F10*F12 - 2*F2*F3 - F13*F35);

  Sub12707 = F26*Sub12693 - F30*Sub12694 + S*Sub12705 + 
     F1*(-Sub12706 + F4*(-2*S - T24)) + 
     F11*(-(F9*T14) - F9*T24 + F12*(T14 + T24)) + 
     F5*(-2*F44*Pair4 + F6*(T14 + T24));

  Sub12704 = F26*Sub12699 - F30*Sub12701 - S*Sub12702 + 
     F1*(Sub12703 + F4*T24) + 
     F5*(F44*(2*Pair3 + 4*Pair4) - F6*T14 - F6*T24) + 
     F11*(F9*T14 + F12*(-T14 - T24) + F9*T24);

  Sub14066 = 2*Sub14064 - 2*Sub14065 + F2*F32*Sub153 + 
     F13*(F36*Sub153 + F7*(Pair2*(2*Sub152 - 2*Sub153) - 
           2*Pair1*Sub153)) + 
     F10*((F16 + F22)*Sub153 + 
        (F17 + F18)*(Sub14063 - T - T14 + T24 + U));

  Sub14069 = 2*Sub14067 - 2*Sub14068 + 
     (F24*F34 + F31*F5)*Sub153 + 
     F25*F5*(Pair2*(2*Sub152 - 2*Sub153) - 2*Pair1*Sub153) + 
     F11*((F16 + F22)*Sub153 + 
        (F17 + F18)*(Sub14063 - T - T14 + T24 + U));

  Sub5291 = Opt32 - 2*Sub5290 + 
     F5*(F44*(2*Pair3 - 4*Pair4) + F6*(T14 + T24)) + 
     F7*(F41*(2*Pair3 - 4*Pair4) + F8*(T14 + T24)) + 
     4*MT2*(F2*F3 + F1*F4);

  Sub11419 = F19*Sub11417 - F29*Sub11418 + 
     F2*(-2*F43*Pair4 - F3*T - F3*U) + 
     F10*(F9*(S - T - U) + F12*(T + U)) + 
     F7*(F41*(2*Pair3 + 4*Pair4) + F8*(-S + T + U));

  Sub11421 = F26*Sub11414 + F30*(-F37 - F38 + 2*Sub11415) + 
     F5*(-2*F44*Pair4 - F6*T - F6*U) + 
     F1*(-Sub11420 + F4*(T + U)) + 
     F11*(F12*(S - T - U) + F9*(T + U));

  Sub5245 = Sub13974 + (F25*F5 + F13*F7)*Pair4*Sub388 + 
     F1*F24*(Pair4*Sub388 + Pair3*(-2*MT2 + T + U));

  Sub9649 = Abb40*(F15*F2 + F1*F24 + F25*F5 + F13*F7) + 
     (F29 + F30)*((F18 + F22)*(Pair3 + 2*Pair4) + 
        (F20 + F21)*(MT2 - S34)) + Sub12142 + 
     MH2*(Pair1 + Pair2 - Pair4)*Sub138;

  Sub4082 = (F17 + F18)*(F19 + F26 + F29 + F30)*Pair1 + 
     Abb87*Sub138 + Pair2*((F25*F5 + F13*F7)*S34 + 
        F15*F2*(S34 + T));

  Sub7821 = Sub13449 + Sub5816 + 
     MT2*(F10*F22 + F2*F32 + F24*F34 + F13*F36) + 
     MT*(Sub14061*(-MT2 + T14));

  Sub13814 = 8*Sub13174 - 4*Sub13175 + 
     4*(F19 + F26)*Sub13811 + (F16 + F17)*Sub13812 - 2*Sub13813 + 
     F1*F23*Sub278 - F2*F27*Sub278 - 
     2*F1*F24*(Pair1 + Pair2)*Sub278 + 
     2*F15*F2*Pair4*(S + T14 + T24) + 
     2*F1*F24*Pair4*(S + T14 + T24) - 
     F19*F20*(2*MT2 - S + 2*T14 + 2*T24) - 
     F20*F26*(2*MT2 - S + 2*T14 + 2*T24) - MT*Sub13810;

  Sub2881 = (F29 + F30)*(F39 + F40) + 
     (F5*F6 + F7*F8)*(-S34 - T14 - T24) + F2*F3*(-6*MT2 + 2*U) + 
     2*(Sub2880 + F1*F4*(T + U)) + 
     MT2*(-6*F1*F4 + 10*(F5*F6 + F7*F8));

  Sub12074 = F19*(F39 + F40) - F29*Sub12071 + 
     F2*(Sub12073 + F3*(-4*MT2 + 3*T24)) + 
     F7*F8*(-4*MT2 + T + U) + 
     F10*(-Sub12072 - F9*T - F9*U + F12*(-T14 - T24 + U));

  Sub5509 = F19*(-F39 - F40 + 2*F9*Pair4) + F29*Sub5506 + 
     F10*F12*(T14 + T24) + 
     F2*(-Sub5508 + F3*(-4*(T14 + T24) - 2*U)) + 
     F9*(-(F10*T) - F10*U) + F7*(2*F41*Pair4 + F8*(T + U)) - 
     2*MT2*Sub5507;

  Sub12079 = F26*(F39 + F40) - F30*Sub12071 + 
     F1*(Sub12078 + F4*(-4*MT2 + 3*T24)) + 
     F5*F6*(-4*MT2 + T + U) + 
     F11*(-Sub12072 - F9*T - F9*U + F12*(-T14 - T24 + U));

  Sub8436 = F9*(F46 + F11*(2*MT2 - S34 - U)) + 
     F5*(F47 + F48*(2*(Pair1 + Pair2) - 2*(Pair3 + Pair4)) + 
        F6*(-8*MT2 + 2*S34 + T24 + 5*U));

  Sub5512 = F26*(F39 + F40 - 2*F9*Pair4) - F30*Sub5506 + 
     F5*F6*(-T - U) + F11*(F12*(-T14 - T24) + F9*(T + U)) + 
     F1*(Sub5511 + F4*(4*(T14 + T24) + 2*U)) - 
     2*(F44*F5*Pair4 + MT2*Sub5510);

  Sub9379 = S34*Sub9375 + F10*F17*T24 + 
     F15*(-2*Sub9378 + F2*(-2*Pair1*U + Pair2*(4*T24 + 8*U))) - 
     MT*(F12*Sub1145) + F2*
      (2*Sub9377 + F32*(-2*T14 - T24) + F27*(-2*T24 - 2*U) - 
        MT*Sub9374) - MT2*Sub9376;

  Sub4037 = Abb136*(F1*F24 + F13*F7) + Abb115*Sub138 - 
     2*Sub4036 + Pair2*(-(F25*F5*S34) + F13*F7*(-2*S34 - U) - 
        F1*F24*U + F25*F5*(2*T24 + U) + F15*F2*(-S34 + 2*T24 + U))+
       4*MT2*Sub4035;

  Sub420 = 1/(SW2*SW2)*
     (F5*F6*(MB2*(-(12*SW2*Sub318) + 8*(SW2*SW2)*Sub388) + 
          MW2*(-(24*SW2*Sub318) + 16*(SW2*SW2)*Sub388) + 
          MT2*(-(8*(SW2*SW2)*Sub388) + 2*SW2*Sub48)) + 
       F2*F3*((MW2*(-6 + (20 - 16*SW2)*SW2) + 
             MB2*(-3 + (10 - 8*SW2)*SW2))*Sub388 + 
          MT2*((-6 + 12*SW2)*Sub318 + 
             (3 + SW2*(-10 + 8*SW2))*Sub388 + (-1 + 2*SW2)*Sub49))+
         SW2*(F1*F4*((MW2*(12 - 16*SW2) + MB2*(6 - 8*SW2))*
             Sub388 + MT2*(12*Sub318 + 2*Sub49 + 
               (-6 + 8*SW2)*Sub388))) + 
       F7*F8*(MT2*((4 - 8*SW2)*SW2*Sub388 + (-1 + 2*SW2)*Sub48) + 
          MW2*(-6*(T + U) + (-6 + (20 - 16*SW2)*SW2)*S + 
             (12 - 24*SW2)*Sub318 + 
             SW2*((-8 + 16*SW2)*Sub388 + (20 - 16*SW2)*(T + U))) + 
          MB2*(-3*(T + U) + (-3 + (10 - 8*SW2)*SW2)*S + 
             (6 - 12*SW2)*Sub318 + 
             SW2*((-4 + 8*SW2)*Sub388 + (10 - 8*SW2)*(T + U)))));

  Sub13288 = (F26 + F29 + F30)*F37 + (F29 + F30)*F38 + 
     F26*(F38 - F39 - F40) + F19*(F37 + F38 - F39 - F40) - 
     Sub13061 - F11*F9*T + Sub5359*(-T - U) + 
     F11*F9*(T14 + T24 - U) + Sub5360*(T + U) + 
     F12*(F11*T + F11*(-T14 - T24 + U)) + 
     F10*(-(F9*T) + F9*(T14 + T24 - U) + 
        F12*(T - T14 - T24 + U)) + MT2*(2*Sub5359 - 2*Sub5360);

  Sub13290 = (F5*F6 + F7*F8)*Sub5369 + 
     S34*(-Sub594 - Sub6073) + S*(F1*F4 - Sub594 - Sub6073) + 
     F1*F4*(2*S34 + Sub6074) + F2*F3*(S + 2*S34 + Sub6074) - 
     2*(Sub13289 + (Pair1 + Pair2)*Sub6077) + 
     2*(Pair3*(Sub6071 + Sub6078) + Pair4*(Sub6072 + Sub6079));

  Sub7710 = F41*(F36 + F7*(-2*Pair1 - 2*Pair2)) - 
     F19*(F37 + F9*(2*Pair2 - 2*Pair3)) - 2*F2*F51*Pair3 - 
     2*F2*F51*Pair4 + F9*(F45 + F10*(2*MT2 - S34)) + F10*F12*S34 - 
     F2*F3*S34 + F29*(-F37 + 2*Sub7708) + 2*Sub7709 + F10*F12*T - 
     F2*F3*T - 2*F2*F3*T14 - F10*F9*T14 - 3*MT2*(F10*F12 - F2*F3);

    

  Sub6846 = -(F36*F41) - F45*F9 + 2*F41*F7*Pair1 + 
     2*F41*F7*Pair2 + F29*(F37 + F9*(-2*Pair1 - 2*Pair3)) + 
     F10*F9*S34 + F19*(F37 - 2*Sub6845) - 2*F10*F12*T14 + 
     2*F2*F3*T14 - 2*F7*F8*T14 + 2*F10*F9*T14 + MT2*(F10*F12) - 
     MT2*(F2*F3) - 2*MT2*(F10*F9);

  Sub7451 = F22*Sub7450 + 
     F7*(F14*(S34 + T) - 2*(Abb153*F13 + MT2*F14)) + 
     F21*(F29*T14 + MT2*(F19 - 2*F29)) + 
     F13*(MT2*F36 + F7*(-2*Pair1*T + Pair4*(2*T - 2*(S34 + T14)) + 
           MT2*(-2*Pair2 + 4*Pair4)));

  Sub3536 = 2*(Pair1 + Pair2)*(Sub1032 + Sub1036) + 
     F12*(-2*(F19 + F26 + F29 + F30)*Pair4 + F11*T) + 
     F9*((F19 + F26 + F29 + F30)*(2*Pair3 + 4*Pair4) + 
        F11*(2*MT2 - S34 - 2*T - T14)) + 
     F10*(F12*T + F9*(2*MT2 - S34 - 2*T - T14));

  Sub9159 = F26*(-F39 + 2*F12*Pair1) + Sub9110 + 
     F1*(F42*(-2*Pair1 + 2*Pair4) + F4*(-S - T14 - T24)) + 
     F11*(-F53 + F12*(-2*MT2 + S + T24));

  Sub9160 = F19*(F37 - 2*F9*Pair1) - Sub9101 + 
     F10*(F55 + F9*(2*MT2 - S - T24)) + 
     F7*(F41*(2*Pair1 - 2*Pair4) + F8*(S + T14 + T24));

  Sub2948 = (F19 + F26)*(F39 + F40) + 
     (-(F5*F6) - F7*F8 + F11*F9)*Sub1409 - 2*Sub2947 + 
     F10*(F9*Sub1409 + F12*(-Sub1409 - 3*Sub262 - T14 - T24)) + 
     F11*F12*(-Sub1409 - 3*Sub262 - T14 - T24) + 
     (F2*F3 + F1*F4)*(3*Sub262 + 2*(Sub278 + T14 + T24));

  Sub13382 = Opt41 + F2*F43*(-8*Pair3 + 8*Pair4) + 
     (F19 + F26)*Sub13381 + F11*F12*(-2*MT2 - T - U) + 
     F1*(F42*(-8*Pair3 + 8*Pair4) + F4*(T + U)) + 
     MT2*(-2*F10*F12 + 2*(F2*F3 + F1*F4));

  Sub5502 = F26*(-F37 - F38 + 2*F12*Pair4) + F30*Sub5499 + 
     F5*(F44*(-2*Pair3 + 2*Pair4) - Sub5501 + 
        F6*(-4*(T14 + T24) - 2*U)) + 
     F11*(F9*(T14 + T24) + F12*(-T - U)) + 
     F1*(2*F42*Pair4 + F4*(T + U)) - 2*MT2*Sub5500;

  Sub12512 = -Opt32 - 4*(F9*Sub12509 + Sub12510) - 
     2*Sub12511 + Sub2880 + F2*(2*F43*Pair4 + F3*U) + 
     F1*(2*F42*Pair4 + F4*(T + U));

  Sub12866 = (F29 + F30)*(F37 + F38 + F39 + F40) + Opt40 + 
     2*(F1*F42 + F2*F43 + F44*F5 + F41*F7)*Pair4 + F2*F3*T;

  Sub5505 = F19*(F37 + F38 - 2*F12*Pair4) - F29*Sub5499 + 
     F2*(-(F3*T) - F3*U) + 
     F10*(-(F9*T14) - F9*T24 + F12*(T + U)) + 
     F7*(F41*(2*Pair3 - 2*Pair4) + Sub5504 + 
        F8*(4*(T14 + T24) + 2*U)) - 2*(F2*F43*Pair4 + MT2*Sub5503);

    

  Sub11967 = Opt35 + F41*F7*(2*Pair3 - 4*Pair4) - 
     F29*Sub11966 - F2*F3*T;

  Sub6327 = Opt35 + F41*F7*(2*Pair3 - 2*Pair4) - F29*Sub6326 + 
     F2*(-2*F43*Pair4 - F3*T);

  Sub12565 = -Opt32 + F1*Sub10905 + F12*Sub12561 + 
     2*(Pair3*Sub12562 + Pair4*Sub12563) + F2*F3*(-S + T + U) + 
     F9*(Sub12564 + F10*U + F11*(T + U));

  Sub2961 = Sub1722 - Sub1723 + 
     (-(F21*F29) - F20*F30)*Sub388 - F21*F29*Sub400 - 
     F20*F30*Sub400 + F1*F23*(-2*MT2 - Sub388 + T + U) + 
     F14*(F7*(-Sub388 + T + U) - 2*MT2*F7);

  Sub11903 = F20*(F29 + F30)*(-MT2 + S) + Sub12141 - 
     Sub12517 + F15*F2*(Pair4*(-2*S + Sub388 - T - U) + 
        Pair1*(T + U)) + F1*F24*Pair4*(Sub388 - 2*(S + T + U)) + 
     MT2*(2*F15*F2*Pair4 + F1*F24*(2*Pair3 + 6*Pair4));

  Sub12169 = (F29 + F30)*
      ((F18 + F22)*(Pair1 + Pair2) + F21*(-MT2 + S)) - Sub12520 + 
     F25*F5*Pair1*(T + U) + 
     Pair4*(F25*F5*(-2*S + Sub388 - T - U) + 
        F13*F7*(Sub388 - 2*(S + T + U))) + 
     MT2*(2*F25*F5*Pair4 + F13*F7*(2*Pair3 + 6*Pair4));

  Sub14341 = 4*Sub14338 + 2*Sub14339 - 2*Sub14340 + 
     F10*(F17 + F18)*(-2*MT2 - 4*Sub3478 + T + T14) + 
     F13*(Sub153*(-F36 + MT*F35) + 
        F7*(Pair2*(2*Sub153 - 2*(T + T14) - 8*(T24 + U)) + 
           Pair1*(2*Sub153 + 8*(T24 + U)) + 
           MT2*(-16*Pair1 + 20*Pair2))) + 
     F2*(-(F32*Sub153) + F15*
         (Pair2*(-8*T24 - 8*U) + Pair1*(8*T24 + 8*U) + 
           MT2*(-16*Pair1 + 16*Pair2)) - MT*(F3*Sub153));

  Sub7098 = F41*(-F36 + F7*(-2*(Pair1 + Pair2) + 4*Pair3)) + 
     F19*(F37 + F39 - 2*Sub7096) - F29*Sub7097 + 
     F9*(F45 + F10*(3*MT2 - S34 - 2*T14)) + F10*F12*(MT2 - T14) + 
     2*F7*F8*T14 + F2*(-2*F51*Pair1 + F3*(-T + T14));

  Sub9699 = F41*(-2*F36 + F7*(-2*Pair2 + 4*Pair3)) + 
     F19*Sub9698 + F10*(F53 + F55 + (F12 + F9)*(2*MT2 - T14)) + 
     F7*F8*T14 + F2*(2*F43*Pair1 + F3*(-S + T14)) + 
     MT2*(-(F2*F3) - F7*F8);

  Sub9702 = F42*(2*F34 + F1*(2*Pair2 - 4*Pair3)) - 
     F26*Sub9701 + F5*(-2*F44*Pair1 + F6*(S - T14)) - F1*F4*T14 + 
     MT2*(F1*F4 + F5*F6) + 
     F11*(-F53 - F55 + F9*T14 + F12*(-2*MT2 + T14) - 2*MT2*F9);

  Sub6521 = -(F19*F21*Sub6518) - 2*Sub6520 + 
     F14*F7*(S34 + T + 2*T14) + 
     F13*(F36*(S34 + T + 2*T14) + 
        F7*((-2*Pair2 + 2*Pair4)*S34 + Pair1*(-2*T - 8*T14) + 
           (-4*Pair2 + 4*Pair4)*T14)) + MT2*Sub6519;

  Sub6047 = Opt30 + F19*(F37 + F38 + 2*F12*Pair4) + 
     F10*(2*F12 - F9)*S + F7*(-2*F41*Pair4 + F8*S) + 
     F29*(F39 + F40 + 2*Sub6046) + 
     F2*(F43*(2*Pair3 + 4*Pair4) + F3*(-2*S - T14));

  Sub6052 = F26*(F39 + F40 + 2*F9*Pair4) + 
     F30*(F37 + F38 + 2*Sub6048) + 
     F5*(F44*(2*Pair3 + 4*Pair4) + F6*(-2*S - T14 - T24)) + 
     F1*(-2*F42*Pair4 + F4*(S + T14 + T24)) + 
     F11*(F12*(-S - T14 - T24) + F9*(2*S + T14 + T24));

  Sub12122 = F26*(F37 + F38) + Opt37 + 
     F44*F5*(2*Pair3 - 2*Pair4) - 
     F30*(F37 + F38 - 2*F9*(Pair3 + Pair4)) + 
     (-2*F1*F4 + F5*F6)*(T + U) + 
     MT2*(4*F1*F4 - 2*(F11*F12 + F5*F6));

  Sub14092 = (F16 + F22)*(F19 + F29) + 
     (F15*F2 + F13*F7)*(4*MT2 - S34 - T - T14 - T24 - U);

  Sub12123 = Opt39 + F29*
      (F37 + F38 + F9*(-2*Pair3 - 2*Pair4)) - F10*F12*T - 
     F7*F8*T - F7*F8*T14 - F7*F8*T24 - F10*F12*U + 2*F2*F3*U - 
     F7*F8*U + 2*(F2*F3*T + MT2*(F7*F8));

  Sub8159 = -Opt28 + Opt39 + F29*Sub6326 - F10*F9*T - 
     F10*F9*U + F2*(2*F43*Pair4 + F3*(T + U));

  Sub12124 = -(F19*(F39 + F40)) - 2*F2*F43*Pair3 + 
     F29*(F39 + F40 + F12*(-2*Pair3 - 2*Pair4)) + 2*F2*F43*Pair4 - 
     F2*F3*T + 2*F7*F8*T - F10*F9*T - F2*F3*T14 - F2*F3*T24 - 
     F2*F3*U + 2*F7*F8*U - F10*F9*U + 2*MT2*(F2*F3) - 
     4*MT2*(F7*F8) + 2*MT2*(F10*F9);

  Sub12125 = -(F26*(F39 + F40)) - 2*F1*F42*Pair3 + 
     F30*(F39 + F40 + F12*(-2*Pair3 - 2*Pair4)) + 2*F1*F42*Pair4 - 
     F1*F4*T + 2*F5*F6*T - F11*F9*T - F1*F4*T14 - F1*F4*T24 - 
     F1*F4*U + 2*F5*F6*U - F11*F9*U + 2*MT2*(F1*F4) - 
     4*MT2*(F5*F6) + 2*MT2*(F11*F9);

  Sub8160 = F26*(F37 + F38) + Opt36 - F30*Sub6326 + 
     F1*(-2*F42*Pair4 - F4*T) + 
     F5*(F44*(2*Pair3 - 2*Pair4) + F6*(T14 + T24)) + 
     MT2*(-2*F11*F12 + 4*F1*F4);

  Sub7246 = -(F29*(F37 + F38)) - F19*(F39 + F40) - 
     2*F2*F43*(Pair1 + Pair2) + 2*F12*F29*Pair3 - 
     2*F29*F9*(Pair3 - Pair4) + 2*F2*F43*Pair4 - 
     2*(F41*F7 + F19*F9 + F29*F9)*Pair4 + 
     2*F41*F7*(Pair3 + 2*Pair4) - 2*(F10*F12 - F2*F3)*(S + S34) - 
     2*(-(F7*F8) + F10*F9)*Sub262 - 2*(Pair1 + Pair2)*Sub7244 + 
     2*Pair4*Sub7245 - (F10*F12 - F2*F3)*(S + T14 + T24) + 
     (-(F7*F8) + F10*F9)*(2*S + T14 + T24) - 
     2*(F10*F12 - F2*F3)*(-2*MT2 + T + U);

  Sub7243 = -(F26*(F37 + F38)) - F30*(F39 + F40) - 
     2*F44*F5*(Pair1 + Pair2) + 2*F30*F9*Pair3 - 
     2*F12*F30*(Pair3 - Pair4) - 
     2*(F12*(F26 + F30) + F1*F42)*Pair4 + 2*F44*F5*Pair4 + 
     2*F1*F42*(Pair3 + 2*Pair4) + 2*(F5*F6 - F11*F9)*(S + S34) - 
     2*(F11*F12 - F1*F4)*Sub262 - 2*(Pair1 + Pair2)*Sub7241 - 
     2*Pair4*Sub7242 + (F5*F6 - F11*F9)*(S + T14 + T24) + 
     (F11*F12 - F1*F4)*(2*S + T14 + T24) - 
     2*(-(F5*F6) + F11*F9)*(-2*MT2 + T + U);

  Sub5247 = -4*Sub5242 + 4*Sub5244 - 2*Sub5245 + 
     2*((F18 + F22)*Sub5243 + Sub5246) + 
     (F20 + F21)*(F29 + F30)*(-T - U) + 
     F7*(F14 + 4*F13*Pair4)*(T + U) + 
     F2*(F27*(-T - U) + F15*(2*Pair3 + 4*Pair4)*(T + U)) + 
     F5*(F28*(-T - U) + F25*(-2*Pair1 + 2*Pair3 + 6*Pair4)*
         (T + U)) + F1*(F23*(-2*MT2 + T + U) + 
        F24*((2*Pair3 + 4*Pair4)*(T + U) + 
           MT2*(-4*Pair3 - 8*Pair4))) + 
     MT2*(2*((F20 + F21)*(F29 + F30) + F28*F5) + 
        F2*(2*F27 + F15*(-4*Pair3 - 8*Pair4)) + 
        F25*F5*(4*Pair1 - 4*Pair3 - 12*Pair4) + 
        F7*(-2*F14 - 8*F13*Pair4));

  Sub5378 = -(F2*F3*(-4*MT2 + S + 2*S34)) - 
     F1*F4*(-4*MT2 + S + 2*S34) + F2*F3*Sub5369 + F1*F4*Sub5369 + 
     F12*Sub5371 + 2*(Pair1 + Pair2)*Sub5373 + 
     2*(Pair1 + Pair2)*Sub5374 - 2*Pair4*Sub5376 - 2*Sub5377 + 
     F5*F6*(4*MT2 - 3*T - 3*U) + F7*F8*(4*MT2 - 3*T - 3*U) + 
     2*F10*F9*(-MT2 + T + U) + 2*F11*F9*(-MT2 + T + U) - 
     F10*F12*(T - T14 - T24 + U) - F11*F12*(T - T14 - T24 + U);

  Sub3351 = F45 + F46 + 2*(F29 + F30)*Pair3 + 
     (F19 + F26)*(-2*(Pair1 + Pair2) + 2*Pair3) + 
     (F10 + F11)*(2*MT2 - S34 - T14);

  Sub7359 = -2*Sub7356 + F24*F34*T + F11*F16*(S34 + 3*T14) + 
     2*(Sub7357 + F24*F34*T14) + 
     F20*(F30*(-S34 + T14) + F26*(T + 2*T14)) + 
     F1*(F24*(-8*Pair1 - 4*Pair2)*(T + T14) + 
        2*(Sub7358 + F23*T14)) + MT2*Sub7355;

  Sub8879 = 2*(F2*F43*Pair1 + F44*F5*Pair1) - 
     2*(F1*F42*Pair2 + F41*F7*Pair2) - F2*F3*S - F5*F6*S + 
     Sub2693 - F2*F3*T14 - F1*F4*T14 - F5*F6*T14 - F7*F8*T14 + 
     F10*(F53 + F55 + F12*T14 + F9*T14) + 
     F11*(F53 + F55 + F12*T14 + F9*T14);

  Sub7664 = (-(F7*F8) + (F10 + F11)*F9)*S + 
     (F29 + F30)*Sub5489 + Pair4*(F12*(F19 + F26) + Sub7663) + 
     F7*F8*(-T14 - T24) + F5*F6*(-S - T14 - T24) + 
     (F10 + F11)*F9*(T14 + T24);

  Sub3705 = (2*F2*F3 - 2*F24*F33)*S34 + 
     F9*(F45 + F46 + (F10 + F11)*T24) + 
     (F10 + F11)*F12*(4*MT2 - T24 - 2*(S34 + U)) + 
     MT2*(-8*F2*F3 + 8*F24*F33);

  Sub12756 = Opt40 + (F1*F4 + F7*F8)*S34 + 2*Sub12754 - 
     2*Sub12755 + (F10 + F11)*(F12 + F9)*Sub262 + Sub6145;

  Sub12824 = Opt40 - 4*Sub12819 - 2*Sub12822 + 
     2*(Pair3*Sub12820 + Pair4*Sub12821 + Sub12823) + 8*Sub3368 + 
     (F10 + F11)*(F12 + F9)*Sub921 + F2*F3*T;

  Sub9725 = F2*Sub9722 + 
     (F11*F12 + F10*F9)*(-S - S34 - T - T14 - T24 - U) + 
     F5*(Sub9724 + F6*U) + MT2*Sub9723;

  Sub12077 = F19*(F37 + F38) + Opt41 - F10*F9*S34 - 
     F29*Sub12075 + F7*(F41*(2*Pair3 - 2*Pair4) + 
        F8*(2*S + 2*S34 + 3*T14 + 3*T24)) + 
     F10*F9*(T - T14 - T24 + U) + 4*MT2*Sub12076;

  Sub11965 = F19*(F39 + F40) - Opt41 - F29*Sub11964 + 
     F2*(F43*(2*Pair3 - 4*Pair4) + F3*(T14 + T24)) + 
     F7*F8*(4*MT2 - T - U) + F10*(F9*(T + U) - 2*MT2*F9);

  Sub11968 = F26*(-F39 - F40) - Opt36 + F30*Sub11964 + 
     F1*(F42*(-2*Pair3 + 4*Pair4) + F4*(T - T14 - T24)) + 
     F11*F12*(-T - U) + MT2*(-4*F5*F6 + 2*F11*F9);

  Sub12081 = F26*(F37 + F38) - F11*F9*S34 - F30*Sub12075 + 
     F1*F4*T + F5*(F44*(2*Pair3 - 2*Pair4) + 
        F6*(2*S + 2*S34 + 3*T14 + 3*T24)) + F1*F4*U + 
     F11*(F12*(-T - U) + F9*(T - T14 - T24 + U)) - 4*MT2*Sub12080;

    

  Sub9092 = -(S*Sub9089) - 2*Sub9091 - F2*F27*T - F28*F5*T - 
     F1*F23*U + (F21*F29 + F21*F30 + F20*(F29 + F30))*U - 
     F14*F7*U + Pair2*(2*Sub9090 + 
        (2*F1*F24 + 4*F25*F5 + 2*F13*F7)*T - 2*F25*F5*U) + 
     MT2*Sub9088;

  Sub5364 = F30*(Sub5362 + F21*(-S - T - T14 - T24 - U)) + 
     F29*(Sub5362 + F21*(2*MT2 - S - T - T14 - T24 - U)) + 
     F20*(F29 + F30)*(2*MT2 - T - U) + 
     2*(Sub5363 + Pair4*(F15*F2*(T + U) + 
           (F1*F24 + F25*F5 + F13*F7)*(S + T + T14 + T24 + U))) + 
     MT2*(2*F21*F30 - 4*(F15*F2 + F1*F24 + F25*F5 + F13*F7)*Pair4);

    

  Sub13133 = Abb17*(4*F15*F2 + 4*F1*F24) + 8*Sub13131 - 
     4*Sub13132 + (-Sub4256 - Sub4264)*T - Sub4256*U - Sub4264*U + 
     F20*(F29*(S - 2*S34 - Sub5714) + F30*(S - 2*S34 - Sub5714) + 
        F26*(-2*S34 - 3*T - 3*U) + F19*(4*MT2 - 2*S34 + T + U) + 
        MT2*(12*F26 + 2*F29 + 2*F30)) + 
     F15*F2*(-2*Pair4*S + 2*Pair1*T + 2*Pair1*U + 4*MT2*Pair4) + 
     F1*F24*(2*Pair3*T + 2*Pair3*U + Pair4*(-2*S + 2*T + 2*U) + 
        4*MT2*Pair4);

  Sub14312 = 4*Sub14311 + 2*(F20 + F21)*(F19 + F29)*Sub153 + 
     Pair2*(2*Sub14310 - 4*F15*F2*(T24 + U)) + 
     F10*(2*(F16 + F22)*Sub153 + 
        (F17 + F18)*(-4*MT2 - Sub14309 - Sub2561 + 2*T24 + 2*U)) + 
     F13*F7*(4*Pair1*(T24 + U) + 
        Pair2*(2*Sub14309 - 4*(T24 + U))) + 
     MT2*(8*F15*F2*Pair2 + F13*F7*(-8*Pair1 + 8*Pair2));

  Sub14372 = -4*Abb32*(F15*F2 + F13*F7) - 8*Sub14338 + 
     4*Sub14371 + (-(F10*F18) - 6*F15*F2*Pair2 - 6*F13*F7*Pair2)*
      Sub933 - 2*F15*F2*Pair1*(-2*MT2 + T24 + U) - 
     2*F13*F7*Pair1*(-2*MT2 + T24 + U) + 
     Sub14194*(-2*MT2 + T24 + U) + Sub14200*(-2*MT2 + T24 + U) - 
     F10*(F18 + F22)*(-2*MT2 - 2*S + T24 + U) + 
     F10*(F17*Sub14195 + F18*Sub14195 - F17*Sub933 - 
        (F16 + F17)*(-2*MT2 - 2*S + T24 + U)) - 
     MT*((F2*F3 - F13*F35)*(2*MT2 - T24 - U));

  Sub5372 = -(F5*F6*(-4*MT2 + S + 2*S34)) - 
     F7*F8*(-4*MT2 + S + 2*S34) + 2*(Pair1 + Pair2)*Sub5365 + 
     2*(Pair1 + Pair2)*Sub5366 + 2*Pair4*Sub5367 + 
     2*Pair4*Sub5368 + F5*F6*Sub5369 + F7*F8*Sub5369 - 2*Sub5370 + 
     F9*Sub5371 + F2*F3*(4*MT2 - 3*T - 3*U) + 
     F1*F4*(4*MT2 - 3*T - 3*U) + 2*F10*F12*(-MT2 + T + U) + 
     2*F11*F12*(-MT2 + T + U) - F10*F9*(T - T14 - T24 + U) - 
     F11*F9*(T - T14 - T24 + U);

  Sub12894 = (F1*F42 + F2*F43 + F44*F5 + F41*F7 + F30*F9)*
      Pair3 + F12*(F29*Pair3 + F30*(Pair2 + Pair3)) + F2*F3*S34 + 
     Sub13498 + Sub3440;

  Sub8993 = 2*Sub8992 - F21*F29*T - F21*F30*T - F28*F5*T + 
     F7*(F13*Pair1*(-2*S - 2*T) + F14*T) + 
     F2*(F15*Pair1*(-2*S - 2*T) - F27*T) + 
     F20*(-(F29*T) - F30*T) + 
     F5*(F25*Pair1*(-2*S - 2*T) + 2*F25*Pair2*T) + 
     F1*(F24*Pair1*(-2*S - 2*T) + F23*(-MT2 + T) + 
        2*MT2*(F24*Pair1)) + 
     MT2*(F21*F29 + F21*F30 + F20*(F29 + F30) + F28*F5 - F14*F7 + 
        2*F13*F7*Pair1 + F2*(F27 + 2*F15*Pair1) + 
        F5*(2*F25*Pair1 - 2*F25*Pair2));

  Sub8729 = F19*(F37 + F39) + 
     F41*(-F36 + F7*(2*(Pair1 + Pair2) - 4*Pair4)) - F29*Sub8728 + 
     F7*F8*(2*MT2 - 2*T) + F9*(F45 + F10*(MT2 + T - T14)) + 
     F10*F12*(MT2 - T14) + F2*(-2*F51*Pair1 + F3*(-T + T14));

  Sub8731 = F26*(F37 + F39) + 
     F42*(-F34 + F1*(2*(Pair1 + Pair2) - 4*Pair4)) - F30*Sub8730 + 
     F1*F4*(2*MT2 - 2*T) + F12*(F46 + F11*(MT2 + T - T14)) + 
     F11*F9*(MT2 - T14) + F5*(-2*F48*Pair1 + F6*(-T + T14));

  Sub7723 = 2*Sub7712 - 2*Sub7713 + (F20*F29 + F2*F32)*T14 + 
     F19*F20*(S34 + T + 2*T14) + 
     F10*F16*(-3*MT2 + S34 + T + 2*T14) + 
     F15*(-2*Sub7711 - 6*F2*(Pair1 + Pair2)*(T + T14)) + 
     MT2*(-3*F19*F20 - Sub7722);

  Sub8393 = -(F19*F21*Sub387) - 2*Sub8392 + 
     F10*F22*(S34 + T + T14) + F13*(Sub8391 + F36*(T + T14)) + 
     F7*((F14 - 2*F13*Pair2)*S34 + F14*(T + T14) + 
        F13*((-2*Pair1 + 2*Pair4)*T + 
           (-4*Pair1 - 2*Pair2 + 2*Pair4)*T14));

  Sub12473 = -(F12*Sub12467) + 2*Pair4*Sub12468 + S*Sub12469 - 
     2*Sub12470 + 2*Sub12471 + (F1*F4 - F5*F6 - F7*F8)*T14 + 
     F1*F4*T24 - F5*F6*T24 - F7*F8*T24 + F2*F3*(T14 + T24) + 
     F9*(Sub12472 + F11*T14 + F10*T24 + F11*T24);

  Sub14105 = Sub13449 + Abb84*Sub138 + Sub14176 + Sub14181 + 
     Sub5816 + F15*F2*Pair1*T24;

  Sub12811 = (F29 + F30)*(F37 + F38 + F39 + F40) - Opt40 - 
     F1*F4*S34 - F7*F8*S34 + F19*Sub12809 + F26*Sub12809 - 
     2*Sub12810 + 2*Sub2693 - Sub6145;

  Sub11931 = Opt41 + F19*(-F37 - F38 - 2*F9*Pair4) + 
     F29*Sub11928 + F7*(Sub11930 + 
        F8*(10*MT2 - 4*(T14 + T24) - 2*U)) + 
     F10*(F12*S34 + F9*(T + T14 + T24 + U)) - 
     2*(Sub11929 + MT2*(F10*F9));

  Sub6325 = F19*(F39 + F40) - Opt41 - F29*Sub6324 + 
     F2*(F43*(2*Pair3 - 2*Pair4) + F3*(T14 + T24)) + 
     F7*(-2*F41*Pair4 + F8*(4*MT2 - T - U)) + 
     F10*(F9*(T + U) - 2*MT2*F9);

  Sub6328 = F26*(-F39 - F40) - Opt36 + F30*Sub6324 + 
     F1*(F42*(-2*Pair3 + 2*Pair4) + F4*(T - T14 - T24)) + 
     F5*(2*F44*Pair4 - 4*MT2*F6) + F11*(F12*(-T - U) + 2*MT2*F9);

  Sub11936 = F26*(-F37 - F38 - 2*F9*Pair4) + F30*Sub11928 + 
     F5*(Sub11935 + F6*(10*MT2 - 4*(T14 + T24) - 2*U)) + 
     F1*F4*(T + U) + F11*(F12*(S34 - T - U) + 
        F9*(T + T14 + T24 + U)) - 2*(Sub11934 + MT2*(F11*F9));

  Sub7507 = F20*(F26*Sub258 + F30*Sub4250) + 
     F11*(F16 + F17)*(S + T14 + T24) + 
     F1*(F23*(S + T14 + T24) + 
        F24*(2*Abb11 - 2*Pair3*(S + T14 + T24) + 
           Pair4*(-2*(T14 + T24) + 2*(T + U))));

  Sub6990 = Opt42 + F12*(F45 + F10*(2*MT2 - 2*S34)) + 
     F2*(-4*F51*Pair1 + 2*F3*S34) - 
     2*(F29*Sub6988 + F19*Sub6989) + F9*(F45 + 2*F10*T) + 
     F7*F8*(8*MT2 - 4*(S34 + T) - 2*T14);

  Sub6463 = -(F36*F41) - F45*F9 + Opt42 + 2*F41*F7*Pair1 + 
     2*F41*F7*Pair2 + F29*(F37 + F9*(-2*Pair1 - 2*Pair3)) + 
     F19*(F37 + F9*(2*Pair2 - 2*Pair3)) - F10*F12*S34 + 
     F2*F3*S34 + F2*F3*T - 2*F10*F12*T14 + 2*F2*F3*T14 - 
     F7*F8*T14 + 3*MT2*(F10*F12);

  Sub6503 = F42*(F34 - 2*F1*Pair1 - 2*F1*Pair2) - 
     F30*(F39 + F12*(-2*Pair1 - 2*Pair3)) - 
     F26*(F39 + F12*(2*Pair2 - 2*Pair3)) - F5*F6*S34 + 
     F11*F9*S34 - F5*F6*T + F11*F9*T - F11*F12*T14 + F1*F4*T14 - 
     2*F5*F6*T14 + 2*F11*F9*T14 + 
     F12*(F46 - F11*S34 + 2*MT2*F11) + MT2*(2*F5*F6 - 3*F11*F9);

  Sub13684 = -Opt40 - 2*F1*F42*Pair4 - 2*F2*F43*Pair4 - 
     2*F44*F5*Pair4 - 2*F41*F7*Pair4 - 
     F29*(F37 + F38 + F39 + F40 + F12*Pair4 + F9*Pair4) - 
     F30*(F37 + F38 + F39 + F40 + F12*Pair4 + F9*Pair4) + 
     Sub2693 - F2*F3*T;

  Sub5295 = Abb50*(F25*F5 + F13*F7) + 
     F13*F7*(Pair4*(T14 + T24) + Pair3*(2*MT2 - T - U)) + 
     MT2*(F21*(-F19 - F26 + F29 + F30) - F28*F5 + F14*F7) + 
     F25*F5*(Pair4*(T14 + T24) + Pair3*(-T - U) + 
        2*MT2*(Pair2 + Pair3));

  Sub12953 = Opt43 + 2*Sub12952 - F21*F29*Sub1971 - 
     F21*F30*Sub1971 + (2*F1*F24 + 2*F25*F5 + 2*F13*F7)*Pair4*
      Sub1971 + F20*(-(F29*Sub1971) - F30*Sub1971) - 4*Sub5242 - 
     2*Sub9648 + F15*F2*(Pair3*(2*T + 2*U) + Pair4*(4*T + 4*U) + 
        MT2*(-4*Pair3 - 8*Pair4));

  Sub12816 = F18*(F29 + F30)*(Pair1 + Pair2) + 
     F30*(F22*(Pair1 + Pair2) + F21*S) + Sub13148 + 
     F29*(F22*(Pair1 + Pair2) + F21*(S34 + T));

  Sub12463 = -(F26*F39) + F19*(-F39 - F40) - F26*F40 - 
     2*F2*F43*Pair3 + F29*(F37 + F38 - 2*F39 - 2*F40 + 
        6*F9*Pair4) + F30*(F37 + F38 - 2*F39 - 2*F40 + 
        6*F9*Pair4) + (-(F5*F6) - F7*F8)*S + 
     Pair4*(-2*Sub12462 + 2*Sub5403) + 
     F12*(-2*F11*S + F11*(-T14 - T24)) + F5*F6*(-T14 - T24) + 
     F7*F8*(-T14 - T24) + F10*F12*(-2*S - T14 - T24) + 
     F2*(-4*F43*Pair4 + 2*F3*S + F3*(T14 + T24)) + 
     F1*(F42*(-2*Pair3 - 4*Pair4) + 2*F4*S + F4*(T14 + T24)) + 
     F9*(F11*S + F11*(T14 + T24) + F10*(S + T14 + T24));

  Sub2972 = (F10 + F11)*(4*F9*Sub278 + F12*Sub2968) - 
     6*Sub2969 + 6*Sub2970 + 2*Sub2971 + 
     (F5*F6 + F7*F8)*(8*S + 4*(T14 + T24)) + 
     F1*F4*(-4*S + S34 + T + U) + 
     F2*F3*(-2*MT2 - 4*S + S34 + T + U) + 
     MT2*(-2*F1*F4 - 8*(F5*F6 + F7*F8));

  Sub11927 = F19*(-F39 - F40 - 2*F12*Pair4) + F29*Sub11925 + 
     F7*F8*(T + U) + F10*(F9*(S34 - T - U) + 
        F12*(T + T14 + T24 + U)) + 
     F2*(F43*(-2*Pair3 + 4*Pair4) + 
        F3*(-3*S - 4*(T14 + T24) - 2*(S34 + T + U))) - 
     2*MT2*Sub11926;

  Sub11933 = F26*(F39 + F40 + 2*F12*Pair4) - F11*F9*S34 - 
     F30*Sub11925 - F5*F6*T + F11*F12*(-T - T14 - T24 - U) - 
     F5*F6*U + F11*F9*(T + U) + 
     F1*(F42*(2*Pair3 - 4*Pair4) + 
        F4*(3*S + 2*S34 + 2*T + 4*T14 + 4*T24 + 2*U)) - 
     2*MT2*Sub11932;

  Sub14171 = F30*(-(F16*Pair2) - F22*Pair2) + 
     F26*(F18*Pair1 - F16*Pair2 - F22*Pair2) + Sub14103 - 
     2*Sub14170 + Pair1*(F18*F30 + F17*(F26 + F30) + 
        (F1*F24 + F25*F5)*(T24 + U)) + 
     Pair2*(F1*F24*(-S + T24 + U) + F25*F5*(-2*MT2 - S + T24 + U));

    

  Sub14173 = F29*(-(F16*Pair2) - F22*Pair2) + 
     F19*(F18*Pair1 - F16*Pair2 - F22*Pair2) - 2*Sub14172 + 
     Pair1*(F18*F29 + F17*(F19 + F29) + 
        (F15*F2 + F13*F7)*(T24 + U)) + 
     Pair2*(F15*F2*(-S + S34 + T24 + U) + 
        F13*F7*(-2*MT2 - S + S34 + T24 + U));

  Sub13326 = 2*Sub13325 + Abb50*Sub138 + 
     (F1*F24 + F25*F5 + F13*F7)*Pair4*(T14 + T24) + 
     F15*F2*(Pair4*(T14 + T24) + Pair3*(-T - U)) + 
     Pair3*((-(F1*F24) - F25*F5 - F13*F7)*T - F1*F24*U - 
        F25*F5*U - F13*F7*U) + MT2*Sub13324;

  Sub12808 = 4*Sub12804 - 4*Sub12805 + 2*Sub12806 - 
     2*Sub12807 + (F20 + F21)*(F29 + F30)*(T + U) + 
     F2*(F27*(T + U) + F15*
         ((-2*Pair3 - 4*Pair4)*(T + U) + MT2*(4*Pair3 + 8*Pair4)))+
       F5*(F28*(T + U) + F25*
         ((2*Pair1 - 2*Pair3)*(T + U) + 
           Pair4*(2*Sub388 - 6*(T + U)) + MT2*(4*Pair3 + 8*Pair4)))
       + F7*(F14*(-T - U) + 
        F13*(Pair4*(2*Sub388 - 4*(T + U)) + 
           MT2*(4*Pair3 + 8*Pair4))) + 
     F1*(F23*(-T - U) + F24*
         (Pair4*(2*Sub388 - 4*(T + U)) + MT2*(4*Pair3 + 8*Pair4)))+
       MT*Sub12803;

  Sub9801 = Sub8543*Sub9798 - 4*Sub9800 + 
     F18*(-F45 - 2*F46 + F10*(-MT2 - S + S34 - T - T14)) + 
     F17*(-2*F45 - F46 + F11*(-MT2 - S + S34 - T - T14)) + 
     (F1*F24*(-4*Pair1 + 4*Pair3) + 
        F13*(2*F36 + F7*(-4*(Pair1 + Pair2) + 4*(Pair3 + Pair4))))*
      U + 2*(Sub9799 + F24*F34*U) + 
     F2*(F27*(-2*MT2 + 2*(T24 + U)) + 
        F15*(Pair1*(4*(S + T + T14) - 4*U) + 
           Pair3*(-4*(S + T + T14) + 4*U) + MT2*(4*Pair1 - 4*Pair3)
           )) + F5*(F31*(2*(S + T + T14) - 2*T24) + 
        F28*(-2*MT2 + 2*(T24 + U)) + 
        F25*(Pair1*(4*(S + T + T14) - 4*U) + 
           Pair3*(-4*(S + T + T14) + 4*U) + MT2*(4*Pair1 - 4*Pair3)
           )) - 2*MT2*Sub8319 - MT*Sub9797;

  Sub3474 = F45 + F46 + F30*(2*Pair2 - 2*Pair4) + 
     F29*(2*(Pair1 + Pair2) - 2*Pair4) - 2*(F19 + F26)*Pair4 + 
     F11*(-S + T - T24 - U) + F10*(2*MT2 - S + T - T24 - U) + 
     2*(F30*Pair1 + MT2*F11);

  Sub12960 = 4*Sub12954 - 4*Sub12957 + S*Sub12958 - 
     2*(F9*Sub12956 + Sub2693) + (F10 + F11)*Sub6206 + 
     2*((Pair3 + Pair4)*Sub12955 + Sub12959 + Pair2*Sub6411) + 
     (F2*F3 + F1*F4)*(S34 + T + T14 + T24 + U);

  Sub5250 = Opt46 + (F2*F3 + F1*F4)*Sub5248 + 2*Sub5249 + 
     F5*(F44*(-2*Pair3 + 4*Pair4) + 
        F6*(-6*MT2 + 3*S + S34 + T14 + T24 + 2*U)) + 
     F7*(F41*(-2*Pair3 + 4*Pair4) + 
        F8*(-6*MT2 + 3*S + S34 + T14 + T24 + 2*(T + U)));

  Sub13130 = Opt41 + Opt45 - F5*F6*S + F10*F9*(-2*MT2 + S) + 
     F7*(8*F41*Pair4 - F8*S) - 4*F19*Sub13126 - 4*F26*Sub13126 + 
     8*F30*Sub13127 + 8*Sub13128 + 4*Sub13129 - 8*Sub3389 - 
     F11*F12*T + F9*(4*F30*Pair4 + F11*S - 2*MT2*F11);

  Sub13504 = Opt45 - 16*Sub12954 + 
     8*(F30*F9*Pair3 + Sub13498 + F30*Sub13500) + 4*Sub13501 + 
     S*Sub13502 - 2*Sub13503 - 
     4*(Pair4*Sub13499 + F19*Sub5704 + F26*Sub5704) - F7*F8*T14 + 
     F5*F6*(-T14 - T24) - F7*F8*T24 + 
     F12*(-8*F29*Pair3 - F11*T + F10*(-T - U)) + F2*(F3*T + F3*U);

    

  Sub13355 = -6*Sub13351 - 2*Sub13353 + 2*Sub13354 + 
     F2*(Sub13352 + 3*F32*(T24 + U) + 
        F15*(Pair1 + Pair2)*(4*(T + T14) - 4*(T24 + U))) + 
     F20*(F19*(T + T14 + 2*U) + F29*(T + T14 + 2*(T24 + U)));

  Sub13360 = 6*Sub13356 + 2*Sub13357 - 2*Sub13359 + 
     F21*(F19*(-T - T14 - 2*U) + F29*(-T - T14 - 2*T24 - 2*U)) + 
     F13*(-Sub13358 + F36*(2*T14 - 3*(T24 + U)) + 
        F7*(-4*(Pair2*T + Pair1*T14) + 4*Pair1*(T24 + U) + 
           Pair2*(-4*T14 + 4*(T24 + U))));

  Sub4944 = F20*(F29*(-S - S34 - T - T14 - T24 - U) + 
        MT2*(-2*F19 + 6*F29)) + 
     F2*(MT2*F27 + F15*(Abb82 - 2*Pair3*(T + U) + 
           Pair4*(3*S + 2*S34 + 4*(T + T14 + T24 + U)) + 
           MT2*(-2*Pair2 + 4*Pair3 - 16*Pair4)));

  Sub5238 = -Opt32 - 4*(F5*F6 + F7*F8)*S - 2*Pair3*Sub5235 + 
     2*(Pair4*Sub5236 + Sub5237) + 
     (F10 + F11)*F12*(2*MT2 - T - U) + 
     F2*F3*(3*S + S34 + T14 + T24 + 2*U) + 
     F1*F4*(3*S + S34 + T14 + T24 + 2*(T + U)) - 
     6*MT2*(F2*F3 + F1*F4);

  Sub7156 = (F26 - F29 - F30)*F37 + F26*F38 + 
     F19*(F37 + F38) + (F44*F5 + F41*F7)*(2*Pair3 - 6*Pair4) + 
     (F29 + F30)*(-F38 + (-2*F12 + 6*F9)*Pair3 + 4*F9*Pair4) - 
     Sub13061 - 2*Pair4*(Sub7152 + Sub7153) + 
     (Sub7154 + Sub7155)*(2*MT2 - T - U) + 
     (F5*F6 + F7*F8)*(S34 - Sub7147 - T - U) + 
     (F10 + F11)*F9*(T - T14 - T24 + U);

  Sub4273 = F19*Sub4269 + S*Sub4270 + 2*S34*Sub4271 + 
     F20*F29*(-20*MT2 + 5*(T14 + T24) + 4*(T + U)) + 
     F2*(-Sub4272 + F15*(Pair1*(-8*MT2 + 6*(T14 + T24)) - 
           2*(Pair2*T + (Pair3 + Pair4)*(T14 + T24)) + 
           Pair2*(2*(T14 + T24) - 2*U)) + F27*(2*(T14 + T24) + U));

    

  Sub7502 = F10*(F16 + F17)*(S + T14 + T24) + 
     F20*(F19*Sub258 + F29*
         (10*MT2 - 2*(S + T14 + T24) - 3*(S34 + T + U))) + 
     F2*(F27*(-S - T14 - T24) + 
        F15*((-2*Pair1 + 2*Pair4)*S - 2*Pair1*(T14 + T24) + 
           2*(Abb11 + Pair4*(T + U))));

  Sub13153 = 2*Abb61*(F15*F2 + F1*F24) + 20*Sub12962 + 
     F20*(F29 + F30)*Sub13147 - 4*Sub13148 + 16*Sub13149 + 
     8*Sub13150 + S*Sub13151 - 8*Sub13152 + 
     F2*(-(F27*T14) - F27*T24 + 
        F15*((-2*Pair1 - 6*Pair4)*T14 - 2*Pair1*T24 - 
           6*Pair4*T24 - 8*Pair3*U)) + 
     F1*(F23*(T14 + T24) + 
        F24*(-8*Pair4*(T14 + T24) + 
           Pair3*(-2*(T14 + T24) - 8*(T + U))));

  Sub6308 = -2*(F36*F41 + F34*F42 + F23*F50 + F14*F52) + 
     4*((F24*F50 + F13*F52)*Pair1 + (F1*F42 + F41*F7)*Pair3) + 
     (4*(F2*F3 + F5*F6) + 2*F7*F8)*T14 + 
     F12*(F46 + 2*F30*Pair3 + F11*(2*MT2 - S34 - 3*T14) - 
        2*F10*T14) + 2*(F26*Sub6306 + F19*Sub6307 + F1*F4*T14) + 
     F9*(F45 + F10*(-S34 - 3*T14) - 2*F11*T14 + 
        2*(F29*Pair3 + MT2*F10));

  Sub9186 = (F19 + F26)*(F38 + F40 - 2*(F12 + F9)*Pair2) + 
     F2*(4*F43*Pair1 + 2*F3*T24) + F5*(4*F44*Pair1 + 2*F6*T24) + 
     F1*(-4*F42*Pair2 + 2*F4*(S + T24)) + 
     F7*(-4*F41*Pair2 + 2*F8*(S + T24)) + 
     (F10 + F11)*(2*(F53 + F55) + 
        (F12 + F9)*(4*MT2 - 2*(S + T24))) - 
     2*MT2*(F2*F3 + F1*F4 + F5*F6 + F7*F8);

  Sub12508 = Opt32 + 2*(F44*F5 + F41*F7)*Pair4 + 
     (F19 + F26)*(-F39 - F40 - 2*F12*Pair4) + 
     (F29 + F30)*(F37 + F38 - 2*Sub12507) + 
     F2*(F43*(-2*Pair3 - 4*Pair4) + F3*(S - T - U)) + 
     F1*(F42*(-2*Pair3 - 4*Pair4) + F4*(S - T - U));

  Sub12951 = -Opt32 + Opt46 - F11*F12*S - 2*F7*F8*S + 
     2*Sub12945 - 4*Sub12946 + 2*Pair4*Sub12947 + 4*Sub12948 - 
     F12*Sub12949 - 2*Sub12950 + 6*Sub3368 + F2*Sub6194 + 
     F1*Sub6200 + F5*F6*(-S34 - T14 - T24) + 
     F7*F8*(-S34 - T14 - T24);

  Sub13064 = Opt40 + Opt46 - 8*(F44*F5 + F41*F7)*Pair3 + 
     4*(Sub13061 + Pair4*Sub13062) - 4*Sub13063 + Sub2880 + 
     (F10 + F11)*(-(F9*S) + F12*(-T - U));

  Sub11576 = 2*S34*Sub11575 + F19*Sub4269 + S*Sub4270 + 
     F20*F29*(5*(T14 + T24) + 4*(T + U)) + 
     F2*(-Sub4272 + F27*(2*(T14 + T24) + U) + 
        F15*((6*Pair1 - 2*Pair3)*(T14 + T24) + 
           Pair2*(2*(T14 + T24) - 2*U) - 
           2*((Pair2 + Pair4)*T + Pair4*(T14 + T24 + U)))) - 
     4*MT2*Sub11574;

  Sub13535 = -Sub13312 - Sub13827 + Sub2891 + 
     F2*(-2*F43*Pair4 + F3*(-2*S34 - 2*T - 2*U)) + 
     F1*(-2*F42*Pair4 + F4*(-2*S34 - 2*T - 2*U)) + 
     F5*(-2*F44*Pair4 + F6*(-S - 2*S34 - 2*T - T14 - T24 - 2*U)) + 
     F7*(-2*F41*Pair4 + F8*(-S - 2*S34 - 2*T - T14 - T24 - 2*U)) + 
     F9*(2*F29*Pair3 + 2*F30*Pair3 - 2*F19*Pair4 - 2*F26*Pair4 + 
        F11*(S + 2*S34 + 2*T + T14 + T24 + 2*U)) + 
     F12*(2*F29*Pair3 + 2*F30*Pair3 - 2*F19*Pair4 - 2*F26*Pair4 + 
        F11*(2*S34 + 2*T + 2*U) - 8*MT2*F11) + 
     F10*(F12*(-8*MT2 + 2*S34 + 2*T + 2*U) + 
        F9*(S + 2*S34 + 2*T + T14 + T24 + 2*U) - 8*MT2*F9) + 
     MT2*(8*F2*F3 + 8*F1*F4 + 8*F5*F6 + 8*F7*F8 - 8*F11*F9);

  Sub13035 = -(F5*F6*S) - F7*F8*S + 2*Pair4*Sub13030 + 
     2*Sub13033 - 4*Sub13034 - 8*Sub3369 + 6*Sub3389 + 
     F9*(-2*Sub13031 - F10*Sub435 - F11*Sub435) + 
     F12*(2*Sub13032 + F10*Sub435 + F11*Sub435) + 
     2*Pair2*Sub6411 + F1*F4*
      (4*S + 3*S34 + 3*T + 3*T14 + 3*T24 + 3*U) + 
     F2*F3*(-10*MT2 + 4*S + 3*S34 + 3*T + 3*T14 + 3*T24 + 3*U) + 
     MT2*(-10*F1*F4 - 2*F5*F6 - 2*F7*F8);

  Sub14234 = 2*Sub14232 - 
     2*((F26 + F30)*Sub14231 + Sub14233) + 
     (F1*F24 + F25*F5)*(Pair2*(2*Sub152 - 2*Sub153) - 
        2*Pair1*Sub153) + F13*
      (F36*Sub153 + F7*(Pair2*(2*Sub152 - 2*Sub153) - 
           2*Pair1*Sub153)) + 
     (F10 + F11)*((F16 + F22)*Sub153 + 
        (F17 + F18)*(Sub14063 - T - T14 + T24 + U)) + 
     Sub153*(F2*F32 + F24*F34 + F31*F5 - MT*Sub14061);

  Sub12338 = -Opt32 + 6*F26*F9*Pair4 - F11*F12*S + 
     F2*Sub12328 + F1*Sub12329 - 2*Pair2*Sub12330 - 4*Sub12331 + 
     2*Sub12332 + 2*Pair3*Sub12333 - 2*Sub12334 + 8*Sub12335 + 
     F9*(-(F11*S) - Sub12336) - F12*Sub12337 + 
     F5*F6*(4*MT2 - S - S34 - T14 - T24) + 
     F7*(-2*F41*Pair4 + F8*(-S - S34 - T14 - T24) + 4*MT2*F8);

  Sub7140 = (F19 + F26)*(F39 + F40) - Opt32 - Opt46 - 
     F29*Sub5506 - F30*Sub5506 - 2*Sub7138 + 2*Sub7139 + 
     F10*F12*(-T14 - T24) + F12*(-(F11*T14) - F11*T24) + 
     F2*F3*(-10*MT2 + 3*S + 4*T14 + 4*T24 + 2*U) + 
     F1*(F4*(3*S + 2*T + 4*T14 + 4*T24 + 2*U) - 10*MT2*F4);

  Sub13050 = -4*(F44*F5*Pair3 + F41*F7*Pair3) - 
     F19*(2*F37 + 2*F38 + F12*Pair4) - 
     F26*(2*F37 + 2*F38 + F12*Pair4) + 
     4*(F44*F5*Pair4 + F41*F7*Pair4) - 2*F11*F9*S - 2*F5*F6*S34 - 
     2*F7*F8*S34 + 2*F11*F9*S34 + 2*Sub13049 - F5*F6*T14 - 
     F7*F8*T14 - F10*F9*T14 - F11*F9*T14 - F5*F6*T24 - F7*F8*T24 - 
     F10*F9*T24 - F11*F9*T24 + 
     F9*(-4*F29*Pair1 - 4*F30*Pair1 - 4*F29*Pair2 - 4*F30*Pair2 - 
        2*F10*S + MT2*F10 + MT2*F11) + 
     3*(MT2*(F5*F6) + MT2*(F7*F8));

  Sub13882 = -(F11*Sub13869) + 4*Sub13877 - 2*Sub13880 + 
     6*Sub13881 - 16*Sub9079 + 
     F24*(Sub13879 + F34*(-T14 - 2*U) + 
        F1*(Pair1*(2*(T + T14) + 6*U) + 
           Pair2*(-4*(T + T14) + 2*(T24 + U)))) + 
     F5*(Sub13878 + F31*(-T14 - 2*(T24 + U)) + 
        F25*(Pair2*(-4*(T + T14) + 2*(T24 + U)) + 
           Pair1*(2*(T + T14) + 6*(T24 + U))));

  Sub13876 = F10*Sub13869 + 16*Sub13870 - 4*Sub13871 + 
     2*Sub13874 - 6*Sub13875 + 
     F2*(-Sub13872 + F32*(T14 + 2*U) + 
        F15*(Pair1*(-2*(T + T14) - 6*U) + 
           Pair2*(4*(T + T14) - 2*(T24 + U)))) + 
     F13*(Sub13873 + F36*(T14 + 2*(T24 + U)) + 
        F7*(Pair1*(-2*(T + T14) - 6*(T24 + U)) + 
           Pair2*(4*(T + T14) - 2*(T24 + U))));

  Sub12718 = Opt40 + Opt48 + (F1*F4 + F7*F8)*S34 + 
     (-2*Pair2 + 2*(Pair3 + Pair4))*Sub12715 - 2*Sub12717 - 
     4*Sub2693 - S*Sub523 + Sub6145 + 
     F11*(F9*(-T - U) + F12*(2*MT2 - T - U)) + 
     F10*(F12 + F9)*(2*MT2 - T - U) + 2*(Sub12716 + MT2*(F11*F9));

    

  Sub2695 = Opt48 + Sub12823 + 
     (F10 + F11)*(F12 + F9)*Sub2692 - 6*Sub2693 - 2*Sub2694 + 
     2*(F2*F3 + F1*F4 + F5*F6 + F7*F8)*(S34 + T + U);

  Sub12772 = (F29 + F30)*(F37 + F38 + F39 + F40) - Opt40 - 
     Opt46 + (-(F1*F4) - F7*F8 + F11*F9)*S34 + F19*Sub12770 + 
     F26*Sub12770 - 2*Sub12771 + 2*Sub2693 - Sub6145 + 
     F12*(F11*S34 + F11*(T + U)) + F10*(F9*S34 + F12*(S34 + T + U))
    ;

  Sub9951 = Abb145*(2*F1*F24 + 2*F13*F7) + Opt49 + Sub14181 - 
     2*Sub9950 - F2*F32*T24 - F31*F5*T24 + 
     F10*(F17*(-MT2 + T24) + F18*(-MT2 + T24)) + 
     F11*(-(MT2*F17) - MT2*F18) + 
     F13*(-(F36*T24) + F7*(-2*Pair2*S34 + 4*MT2*Pair2)) + 
     F15*F2*(Pair2*(6*T24 + 8*U) - 24*MT2*Pair2) + 
     F25*F5*(Pair2*(6*T24 + 8*U) - 24*MT2*Pair2) + 
     F24*(-(F34*T24) + 4*MT2*(F1*Pair2)) + 
     MT*(Sub14061*T24 - MT2*Sub14061);

  Sub4083 = -Opt49 + 2*F1*F24*Pair2*S34 - F10*Sub4078 - 
     2*Sub4079 - 8*Sub4080 + 2*Sub4082 + 
     F1*F24*Pair2*(2*T + 2*T14 + 2*U) + 
     F11*(-Sub4081 + F16*T14 + F22*(T + T14) + F18*(-S34 - U) - 
        F17*U) + Pair2*((2*F25*F5 + 2*F13*F7)*T + 2*F15*F2*T14 + 
        F13*F7*(2*T14 + 2*U) + F15*F2*(2*T24 + 2*U) + 
        F25*F5*(2*T14 + 2*T24 + 2*U));

  Sub3475 = Opt50 + F2*F3*(4*MT2 - S34) + 
     (F24*F33 + F13*F35 - F5*F6)*S34 + F12*Sub3474 + 
     F9*((F29 + F30)*(2*(Pair1 + Pair2) - 2*Pair4) - 
        2*(F19 + F26)*Pair4 + F11*(-S + T - T24) + 
        F10*(-S - T24 - U)) + 
     MT2*(-4*(F24*F33 + F13*F35) + 4*F5*F6 + 2*F10*F9);

  Sub9854 = -Opt50 + F11*F9*S34 + F2*(2*F49 + 2*F3*Sub9852) - 
     F12*Sub9853 + F10*F9*(-S - S34 - T14 - 2*T24 - U) + 
     F13*F35*(2*S34 + 2*T24 + 2*U) + 
     F24*F33*(-6*MT2 + 2*S34 + 2*T24 + 2*U) + 
     F5*(2*F47 + F6*(-4*S - 6*S34 - 4*T - 4*T14 - 6*T24 - 4*U) + 
        18*MT2*F6) + MT2*(-6*F13*F35 + 4*F10*F9);

  Sub13026 = -Opt30 + 2*F41*F7*Pair3 + 
     F29*(F37 + F38 + F39 + F40 + 4*F12*Pair4) + 
     F30*(F37 + F38 + F39 + F40 - 2*F9*Pair3 + 4*F12*Pair4) + 
     (F2*F3 + F1*F4)*S - 2*F7*F8*S - 2*Pair2*Sub13023 - 
     2*Sub13024 + 2*Sub13025 + F19*Sub9643 + F26*Sub9643 + 
     F2*F3*T14 - F5*F6*T14 + 
     F12*(-(F10*S) - F11*S + F11*(-T14 - T24)) - F5*F6*T24 + 
     F1*F4*(T14 + T24) + F9*(2*F11*S + F11*(T14 + T24));

  Sub2497 = Sub13312 + 
     F1*F4*(-3*(S34 + T14 + T24) - 2*(S + T + U)) + 
     F2*F3*(8*MT2 - 3*(S34 + T14 + T24) - 2*(S + T + U)) + 
     (F5*F6 + F7*F8)*(S34 + T14 + T24 + 4*(S + T + U)) + 
     MT2*(8*F1*F4 - 2*(F5*F6 + F7*F8));

  Sub5358 = -Sub7143 + 
     F21*(F29*(-T - T14 - T24 - U) + 
        F30*(-S34 - T - T14 - T24 - U)) + 
     (F25*F5 + F13*F7)*(Abb41 - Pair3*T - Pair3*U + 
        Pair4*(2*S + S34 + 2*T + 3*T14 + 3*T24 + 2*U)) + 
     MT2*Sub5357;

  Sub9591 = Opt40 + Opt48 + (F5*F6 + F7*F8)*S34 + 
     (F2*F3 + F1*F4)*(S + S34) - 4*Sub2693 + Sub2880 + 
     (F12 + F9)*((F29 + F30)*Pair4 + (F10 + F11)*Sub435);

  Sub5356 = -Sub11622 + 
     F20*(F29*(-S34 - T - T24 - U) + 
        F30*(-S34 - T - T14 - T24 - U)) + 
     (F15*F2 + F1*F24)*(Abb41 - Pair3*T - Pair3*U + 
        Pair4*(2*S + S34 + 2*T + 3*T14 + 3*T24 + 2*U)) + 
     MT2*(F11*(F16 + F17) + Sub5355);

  Sub12590 = (F29 + F30)*
      (F9*(2*(Pair1 + Pair2) - 2*(Pair3 + Pair4)) + 
        F12*(-2*(Pair1 + Pair2) + 2*(Pair3 + Pair4))) + 
     F5*(F44*(-2*(Pair1 + Pair2) + 2*(Pair3 + Pair4)) + 
        F6*(-MT2 - S + S34)) + 
     F7*(F41*(-2*(Pair1 + Pair2) + 2*(Pair3 + Pair4)) + 
        F8*(-MT2 - S + S34)) + F2*Sub11554 + F1*Sub11558;

  Sub13448 = (2*F29*F9 + 2*F30*F9)*Pair3 + 
     (F19 + F26)*(-F37 - F38 - F39 - F40 + 2*F12*Pair3 + 
        2*F9*Pair3) + (-2*F2*F3 - 2*F1*F4 - 2*F5*F6 - 2*F7*F8)*S - 
     Sub12892 - Sub2890 + F9*
      (2*F11*S + F11*(-2*S34 - 2*Sub388) + 
        F10*(2*S - 2*S34 - 2*Sub388)) + 
     F12*((2*F29 + 2*F30)*Pair3 + 2*F11*S + 
        F11*(-2*S34 - Sub262 - 2*Sub388) + 
        F10*(2*S - 2*S34 - Sub262 - 2*Sub388)) + 
     F5*F6*(2*S34 + 2*Sub388) + F7*F8*(2*S34 + 2*Sub388) + 
     F2*F3*(2*S34 + Sub262 + 2*Sub388) + 
     F1*F4*(2*S34 + Sub262 + 2*Sub388);

  Sub12988 = F12*(-2*F29*Pair4 - 2*F30*Pair4) - 
     2*(F29*F9*Pair4 + F30*F9*Pair4) - Sub12892 - F19*Sub9643 - 
     F26*Sub9643 + F5*(F44*(-2*Pair3 - 2*Pair4) + 
        F6*(S - 2*T - 2*U)) + 
     F7*(-2*F41*Pair3 - 2*F41*Pair4 + F8*(S - 2*T - 2*U)) + 
     F1*F4*(-T - U) + F2*F3*(2*MT2 - T - U) + 
     MT2*(2*F1*F4 + 4*F5*F6 + 4*F7*F8);

  Sub8288 = -(S34*Sub8282) + 2*(S*Sub8281 + Sub8283) + 
     F17*Sub8284 - F18*Sub8285 - 2*Pair1*Sub8286 - 4*Sub8287 + 
     F31*F5*(2*T + 2*T14 + T24) + F11*F17*U + F10*F18*U - 
     F24*F34*U + F28*F5*(2*T24 + 2*U) + 
     F15*F2*(2*Pair1*U - 8*Pair2*U) + 
     F1*F24*(-2*Pair1*U - 4*Pair2*U) + 
     F2*(F32*(2*T14 + T24) + F27*(2*T24 + 2*U)) + 
     F25*F5*(Pair2*(-4*T24 - 8*U) + Pair1*(4*T24 + 2*U)) + 
     F13*(-(F36*U) + F7*(-2*Pair1*U - 4*Pair2*U)) + MT*Sub8279 + 
     MT2*Sub8280;

  Sub6168 = 2*(F23*F50 + F14*F52) + Opt55 - 
     4*((F24*F50 + F13*F52)*Pair1 + (F1*F42 + F41*F7)*Pair4) + 
     F2*(-4*F51*Pair1 - 2*F3*T) + F5*(-4*F48*Pair1 - 2*F6*T) - 
     2*((F1*F4 + F7*F8)*S34 + F30*Sub6166 + F29*Sub6167 + 
        (F24*F33 + F13*F35)*T14) + 
     F9*(F45 + F10*(-2*MT2 + T) - 2*(F19*Pair4 + MT2*F11)) + 
     F12*(F46 + F11*T - 2*(F26*Pair4 + MT2*(F10 + F11))) + 
     4*MT2*(F2*F3 + F24*F33 + F13*F35 + F5*F6);

  Sub13242 = (F10 + F11)*F12*(6*MT2 - 3*S) + 
     (-2*F1*F4 + 5*(F5*F6 + F7*F8))*S34 + Sub12823 + 
     4*((F1*F42 + F2*F43)*Pair4 + (Pair1 + Pair2)*Sub13239) + 
     2*(F11*F9*S + Sub13240 + 
        (F19 + F26)*(-2*(F37 + F38) + Sub6415)) + 
     (-2*F11*F12 + 5*(F5*F6 + F7*F8))*T + 
     (-4*F1*F4 + 5*F7*F8)*T24 - 
     4*(Sub13241 + F1*F4*T14 + F2*F3*T24) + 
     (-2*F11*F12 + 5*F7*F8)*U - 
     2*((-(F41*F7) + 2*F30*F9)*Pair4 + F2*F3*S34 + 
        F10*F12*(T + U)) + 
     5*((F5*F6 + F7*F8)*T14 + F5*F6*(T24 + U)) - 
     12*MT2*(F5*F6 + F7*F8);

  Sub14180 = -(F10*Sub13946) - 4*Sub14118 + 2*F19*Sub14175 + 
     (2*F26 + 2*F29 + 2*F30)*Sub14175 - 2*Sub14176 - 
     S34*Sub14177 + 2*Sub14178 + 4*Sub14179 - 8*Sub4080 + 
     ((2*F25*F5 + 2*F13*F7)*Pair1 + 4*F25*F5*Pair2 + 
        4*F13*F7*Pair2 + F1*F24*(2*Pair1 + 4*Pair2))*T24 + 
     F11*((F17 + F18 + F22)*T + F22*T14 + F16*(T + T14) + 
        F17*(T14 - T24 - U) + F18*(T14 - T24 - U)) + 
     4*F15*F2*Pair2*U + 4*F25*F5*Pair2*U + 4*F13*F7*Pair2*U + 
     Pair1*(2*F15*F2*U + 2*F25*F5*U + 2*F13*F7*U) + 
     F1*F24*(2*Pair1*U + 4*Pair2*U);

  Sub6026 = (F29 + F30)*(F37 + F39) - F36*F41 - F34*F42 - 
     2*F23*F50 - 2*F14*F52 - 2*F12*F29*Pair1 - 2*F12*F30*Pair1 + 
     2*F1*F42*Pair1 + 2*F48*F5*Pair1 + 4*F24*F50*Pair1 + 
     2*F2*F51*Pair1 + 4*F13*F52*Pair1 + 2*F41*F7*Pair1 - 
     2*F29*F9*Pair1 - 2*F30*F9*Pair1 + 
     F19*(F37 + F39 - 2*F12*Pair1 - 2*F9*Pair1) + 
     F26*(F37 + F39 - 2*F12*Pair1 - 2*F9*Pair1) + 2*F1*F42*Pair2 + 
     2*F41*F7*Pair2 + F2*F3*T + F5*F6*T - F10*F12*T14 - 
     F11*F12*T14 + 3*F2*F3*T14 + 3*F5*F6*T14 - F10*F9*T14 - 
     F11*F9*T14 + MT2*(F10*F12) + MT2*(F11*F12) - 3*MT2*(F2*F3) - 
     MT2*(F24*F33) - MT2*(F13*F35) - 3*MT2*(F5*F6) + 
     MT2*(F10*F9) + MT2*(F11*F9);

  Sub7146 = -(F11*F18*S34) - F11*F22*S34 + 
     (F28*F5 - F14*F7 - 2*F25*F5*Pair2 + 2*F13*F7*Pair4)*S34 + 
     4*Sub7141 - 3*Sub7143 + 2*Sub7144 + 6*Sub7145 + 
     F21*((-F19 - F26)*S34 + F29*(-3*T - 3*T14 - 3*T24 - 3*U) + 
        F30*(-3*S34 - 3*T - 3*T14 - 3*T24 - 3*U)) + 
     F25*F5*(-2*Pair3*T - 2*Pair3*U + 
        Pair4*(8*T14 + 8*T24 + 6*U)) + 
     F13*F7*(-2*Pair3*T - 2*Pair3*U + 
        Pair4*(6*T + 8*T14 + 8*T24 + 6*U)) + 
     F10*(F18*(4*MT2 - S34) - F22*S34 + 4*MT2*F22) + 
     MT2*(F21*(18*F29 + 18*F30) + 4*Sub7142);

  Sub13685 = -(F26*F39) + F19*(-F39 - F40) - F26*F40 + Opt40 + 
     Opt46 - 2*F2*F43*Pair3 + 2*F41*F7*Pair4 + F29*Sub6324 + 
     F30*Sub6324 + F2*(2*F43*Pair4 + F3*T + F3*(-T14 - T24)) + 
     F1*(F42*(-2*Pair3 + 2*Pair4) - F4*T14 - F4*T24) + 
     F10*F12*(-T - U) + F11*F12*(-T - U) + 
     F5*(2*F44*Pair4 - 4*MT2*F6) + 
     MT2*(-4*F7*F8 + 2*F10*F9 + 2*F11*F9);

  Sub9087 = -(F19*Sub9078) - 8*Sub9079 + 2*S*Sub9080 - 
     2*Sub9081 + 2*Sub9082 - 4*Pair1*Sub9083 + F26*Sub9084 + 
     4*Sub9085 - 4*Sub9086 - 2*F11*F16*T14 + 2*F11*F17*T14 + 
     2*F10*F18*T14 + 2*F11*F18*T14 - 2*F10*F22*T14 - 
     2*F11*F22*T14 - 2*F1*F23*T14 - F21*F26*T14 - 2*F2*F27*T14 - 
     2*F24*F34*T14 - 2*F13*F36*T14 - 2*F28*F5*T14 - 2*F14*F7*T14 + 
     8*F1*F24*Pair1*T14 + 8*F25*F5*Pair1*T14 + 
     8*F13*F7*Pair1*T14 + 4*F25*F5*Pair2*T14 - 
     4*F13*F7*Pair4*T14 - 2*F10*F16*T24 - 2*F11*F16*T24 - 
     2*F10*F22*T24 - 2*F11*F22*T24 - 2*F1*F23*T24 - 2*F14*F7*T24 + 
     4*F1*F24*Pair1*T24 + 4*F13*F7*Pair1*T24 + 
     MT*((F19 + F26)*(F37 + F39 - 2*F12*Pair1 - 2*F9*Pair1)) - 
     MT2*Sub8967;

  Sub11623 = -(F19*Sub11615) + S34*Sub11617 + 2*Sub11618 - 
     5*Sub11622 + (-(F2*F27) - 4*F20*(F29 + F30))*T + 
     Pair3*(2*Sub11620 - 4*F1*F24*(T14 + T24)) + 
     F2*F27*(-2*T24 - U) + 
     F1*(-4*F24*Pair4*(T14 + T24) + F23*(T + 2*(T14 + T24) + U)) + 
     F20*(F29*(-5*T24 - 4*U) + F30*(-5*(T14 + T24) - 4*U) + 
        F26*(T14 + T24 + 2*U)) + 
     F15*(-2*Sub11619 + F2*
         ((-6*Pair1 - 2*Pair2 + 2*Pair4)*T14 + 
           (-6*Pair1 + 2*(Pair3 + Pair4))*T24 + 
           Pair2*(-2*T24 + 2*U))) - 2*(Sub11621 + MT2*Sub11616);

}
