#if 0
* abbr1h11.c
* abbreviations for {-F[2, {1}], F[2, {1}]} -> {-F[3, {3, Col3}], F[3, {3, Col4}], V[1]}
* generated by FormCalc 8.2 on 11-Apr-2013 14:53
#endif

#include "vars.h"
#include "inline.h"


void abbr1h11() {

#include "vars.h"

#include "inline.h"

  Sub4074 = Sub14179 - 2*Sub4073 - Sub4079 + 
     Pair1*((F17 + F18)*(F19 + F26 + F29 + F30) + 
        (F15*F2 + F1*F24 + F25*F5 + F13*F7)*(T24 + U)) + 
     Pair2*(F15*F2*(-S + S34 + U) + F25*F5*(-S + T24 + U) + 
        F1*F24*(-2*MT2 - S + T24 + U) + 
        F13*F7*(-S + S34 + T24 + U) - 2*MT2*(F25*F5 + F13*F7));

  Sub12896 = Opt40 + (2*(F1*F4 + F5*F6 + F7*F8) - F11*F9)*
      S34 + 3*Sub12823 - 2*Sub12892 - 4*Pair4*Sub12893 + 
     2*Sub12894 - 8*Sub2693 + (F19 + F26)*Sub9643 + 
     F11*(F9*(-T14 - T24) + F12*(-S34 - T14 - T24)) + 
     F10*(F12 + F9)*(-S34 - T14 - T24) + F2*F3*(T + 4*T24) + 
     4*(Sub12895 + (F1*F4 + F5*F6 + F7*F8)*(T14 + T24));

  Sub5292 = (F19 + F26)*(-F37 - F38 - F39 - F40) + Opt46 - 
     Opt53 + 4*(F2*F43 + F44*F5 + F41*F7)*Pair4 + Sub12892 + 
     2*(F2*F3 + F5*F6 + F7*F8)*(T + U) + 
     F12*(-(F11*T) + F10*(-T - U) - F11*U) + 
     F1*(4*F42*Pair4 + 2*F4*(T + U));

  Sub12610 = F19*Sub12601 + S*Sub12603 + S34*Sub12604 - 
     2*Sub12605 + 4*Sub12607 + 2*Sub12609 + 
     Pair3*(4*F13*F7*(T14 + T24) - 2*(Sub12608 + F25*F5*T24)) + 
     F7*(4*F13*Pair4*(T14 + T24) + F14*(-T - 2*T14 - 2*T24 - U)) + 
     F5*(F25*((6*Pair1 - 2*Pair4)*T14 + 6*Pair1*T24 - 
           2*(Pair2*T + Pair4*T24) + Pair2*(2*(T14 + T24) - 2*U))+
          F28*(T + 2*T24 + U)) + 
     F21*(Sub12606 + F26*(-T14 - T24 - 2*U) + 
        (F29 + F30)*(5*(T14 + T24) + 4*U)) - 4*MT2*Sub12602;

  Sub4048 = Opt49 + (-4*F1*F24*Pair2 + 
        (-4*F25*F5 - 4*F13*F7)*Pair2)*S + 2*Abb97*Sub138 + 
     4*Sub4046 - 4*Sub4047 - F10*F17*Sub435 - F10*F18*Sub435 + 
     F1*F24*(Pair2*(-2*S34 - 2*U) + Pair1*(-2*T24 - 2*U)) + 
     Pair2*(-2*F15*F2*S34 + F13*F7*(-2*S34 - 2*U) + 
        F15*F2*(-2*T24 - 2*U) + F25*F5*(-2*S34 - 2*T24 - 2*U)) + 
     F15*F2*Pair1*(-2*T24 - 2*U) + F25*F5*Pair1*(-2*T24 - 2*U) + 
     F13*F7*Pair1*(-2*T24 - 2*U) + 
     F11*(F18*S + F18*(S34 + T + T14 + U) + 
        F17*(S + S34 + T + T14 + U));

  Sub5185 = Abb82*(F15*F2 + F1*F24) - Sub11622 + 
     MT2*(-2*F19*F20 + F2*F27) + 
     F20*(F29*(-S34 - T - T24 - U) + 
        F30*(-S34 - T - T14 - T24 - U) + 
        MT2*(-2*F26 + 6*(F29 + F30))) + 
     F1*(-(MT2*F23) + F24*(-2*Pair3*(T + U) + 
           Pair4*(3*S + 2*S34 + 4*(T + T14 + T24 + U)) + 
           MT2*(4*Pair3 - 16*Pair4))) + 
     F15*F2*(-2*Pair3*(T + U) + 
        Pair4*(3*S + 2*S34 + 4*(T + T14 + T24 + U)) + 
        MT2*(-2*Pair2 + 4*Pair3 - 16*Pair4));

  Sub9746 = -(F47*F5) + Opt51 + 2*F30*F9*Pair1 + 
     F12*(2*F29*Pair1 + F29*(2*Pair2 - 2*Pair3 - 2*Pair4) + 
        F19*(2*Pair1 + 2*Pair2 - 2*Pair3 - 2*Pair4)) + 
     F30*F9*(2*Pair2 - 2*Pair4) - 2*F26*F9*Pair4 + F2*Sub9745 + 
     F13*(-2*F52*Pair1 + F52*(-2*Pair2 + 2*Pair3 + 2*Pair4) + 
        2*F35*U) + F24*(-2*F50*Pair1 + 
        F50*(-2*Pair2 + 2*Pair3 + 2*Pair4) + F33*(-MT2 + 2*U)) - 
     MT2*(F13*F35) + F5*((4*F44 - 6*F48)*Pair1 + 
        F44*(4*Pair2 - 4*Pair3 - 4*Pair4) + 
        F48*(-6*Pair2 + 6*Pair3 + 6*Pair4) + F6*(T24 - 3*U) + 
        2*MT2*F6);

  Sub3462 = Opt51 + (-2*F2*F3 + 2*F24*F33)*S34 + 
     F12*((-4*F26 - 2*(F29 + F30))*Pair1 + 
        (F29 + F30)*(-2*Pair2 + 2*Pair4) + 
        F26*(-4*Pair2 + 4*Pair3 + 6*Pair4) + 
        F19*(-4*(Pair1 + Pair2) + 4*Pair3 + 6*Pair4) + 
        (F10 + F11)*(2*MT2 + S34 - 2*T - T14)) + 
     F9*(-F45 - F46 + F19*(2*Pair1 + 2*Pair2 - 2*Pair3) - 
        2*F29*Pair3 + F11*(-S34 + 2*T14) + 
        F10*(-3*MT2 - S34 + 2*T14) - 3*MT2*F11) + 
     MT2*(8*F2*F3 - 8*F24*F33);

  Sub9372 = Opt52 - Sub14117 - Sub5816 + 2*Abb126*Sub9056 + 
     F11*F16*T24 + F11*F17*T24 + F11*F18*T24 + F11*F22*T24 + 
     (F19*(F20 + F21) + F20*F26 + F21*F26)*T24 - F28*F5*T24 + 
     F25*F5*Pair2*(-4*S + 4*T24) + 
     F7*(-2*F13*Pair2*S - 2*F13*Pair1*T24) + 
     F1*(-2*F24*Pair2*S - 2*F24*Pair1*T24) + 
     F2*(-(F27*T24) + F15*Pair2*(-4*S + 4*T24)) + 
     F10*(F17*T24 + F18*T24 + F22*T24 + F16*(-MT2 + T24) + 
        MT2*(-F17 - F18 - F22)) + 
     MT2*(F28*F5 - F14*F7 + 2*F13*F7*Pair1 + 
        F1*(-F23 + 2*F24*Pair1) + 
        F2*(F27 + F15*(2*Pair1 - 4*Pair2)) + 
        F5*(2*F25*Pair1 - 4*F25*Pair2));

  Sub12818 = Opt52 + F19*Sub12812 - 4*Sub12813 + S*Sub12814 - 
     F20*(-2*F29*Sub11841 - 2*F30*Sub11841 - F26*Sub1976) + 
     2*F25*F5*Pair4*T + 2*F13*F7*Pair4*T + 
     F21*(Sub12815 - 2*F30*T) + 2*(Sub12817 + F1*F24*Pair4*T) + 
     F1*F23*T14 - F2*F27*T14 - 2*F21*F30*T14 - F28*F5*T14 + 
     F14*F7*T14 - 2*F15*F2*Pair1*T14 - 2*F25*F5*Pair1*T14 - 
     2*F1*F24*Pair3*T14 - 2*F13*F7*Pair3*T14 - 
     2*F1*F24*Pair4*T14 - 2*F13*F7*Pair4*T14 - 
     2*(Sub12816 + F21*F29*T14) - F2*F27*T24 - 2*F21*F29*T24 - 
     2*F21*F30*T24 - F28*F5*T24 - 2*F1*F24*Pair3*T24 - 
     2*F13*F7*Pair3*T24 - 2*F1*F24*Pair4*T24 - 
     2*F13*F7*Pair4*T24 - F21*F26*U - 2*F21*F29*U - 2*F21*F30*U + 
     2*F15*F2*Pair4*U + 2*F1*F24*Pair4*U + 2*F25*F5*Pair4*U + 
     2*F13*F7*Pair4*U + MT*Sub12811;

  Sub14184 = Opt56 + F16*
      (-4*F26*Pair2 - 4*F29*Pair2 - 4*F30*Pair2) + 
     F22*(-4*F19*Pair2 - 4*F26*Pair2 - 4*F29*Pair2 - 
        4*F30*Pair2) + F17*
      (-2*F26*Pair2 - 2*F29*Pair2 - 2*F30*Pair2) + 
     F18*(-2*F19*Pair2 - 2*F26*Pair2 - 2*F29*Pair2 - 
        2*F30*Pair2) + (F10 + F11)*Sub14005 + 4*Sub14181 - 
     4*Sub14182 - 2*Sub14183 - S*Sub9998 + F2*F32*(-T - T24 - U) + 
     F31*F5*(-T - T24 - U) + F24*F34*(-T14 - T24 - U) + 
     F15*F2*(Pair1*(2*T24 + 2*U) + Pair2*(-2*T14 + 2*T24 + 2*U)) + 
     F1*F24*(Pair1*(2*T24 + 2*U) + 
        Pair2*(-2*T - 2*T14 + 2*T24 + 2*U)) + 
     F25*F5*(Pair1*(2*T24 + 2*U) + 
        Pair2*(-2*T - 2*T14 + 2*T24 + 2*U)) + 
     F13*(F36*(-T14 - T24 - U) + 
        F7*(Pair1*(2*T24 + 2*U) + 
           Pair2*(-2*T - 2*T14 + 2*T24 + 2*U))) - 
     MT*(Sub14061*Sub151);

  Sub5651 = (-F29 - F30)*F37 + F26*(F37 + F38) + Opt28 + 
     Opt36 - Opt39 + 2*F44*F5*Pair3 - 2*F2*F43*Pair4 - 
     2*F44*F5*Pair4 + F29*(-F38 - 4*F9*Pair1 + 
        F12*(2*Pair1 + 2*Pair2 - 2*Pair3 - 2*Pair4) + 
        F9*(-4*Pair2 + 6*Pair3 + 6*Pair4)) + 
     F30*(-F38 - 4*F9*Pair1 + 
        F12*(2*Pair1 + 2*Pair2 - 2*Pair3 - 2*Pair4) + 
        F9*(-4*Pair2 + 6*Pair3 + 6*Pair4)) - Sub13061 + 
     F1*(-2*F42*Pair4 - F4*T) + F5*F6*(T14 + T24) + 
     F2*F3*(-T - U) + F9*(F10*T + F10*U) + 
     MT2*(-2*F11*F12 + 4*F1*F4);

  Sub13323 = (F26 - F29 - F30)*F37 + 
     (F29 + F30)*(-F38 - F39 - F40) + F26*(F38 + F39 + F40) + 
     F19*(F37 + F38 + F39 + F40) + Opt28 + Opt36 + Opt37 - Opt41 + 
     Opt53 + (F44*F5 + F41*F7)*(2*Pair3 - 2*Pair4) + 
     F2*(F43*(2*Pair3 - 2*Pair4) + F3*(T14 + T24)) + 
     F1*(F42*(2*Pair3 - 2*Pair4) + F4*(-T + T14 + T24)) + 
     F10*(F9*(T + U) - 2*MT2*(F12 + F9)) + 
     MT2*(2*(F2*F3 + F1*F4 + F5*F6 + F7*F8) - 2*F11*(F12 + F9));

  Sub5896 = (F29 + F30)*(F37 + F39) - F36*F41 - F34*F42 - 
     2*F23*F50 - 2*F14*F52 + Opt53 - 4*F12*F29*Pair1 - 
     4*F12*F30*Pair1 + 2*F1*F42*Pair1 + 2*F48*F5*Pair1 + 
     4*F24*F50*Pair1 + 2*F2*F51*Pair1 + 4*F13*F52*Pair1 + 
     2*F41*F7*Pair1 - 4*F29*F9*Pair1 - 4*F30*F9*Pair1 + 
     F19*(F37 + F39 - 2*F12*Pair1 - 2*F9*Pair1) + 
     F26*(F37 + F39 - 2*F12*Pair1 - 2*F9*Pair1) - 
     2*F12*F29*Pair2 - 2*F12*F30*Pair2 + 2*F1*F42*Pair2 + 
     2*F41*F7*Pair2 - 2*F29*F9*Pair2 - 2*F30*F9*Pair2 + F2*F3*T + 
     F5*F6*T - F10*F12*T14 - F11*F12*T14 + F2*F3*T14 + 
     2*F24*F33*T14 + 2*F13*F35*T14 + F5*F6*T14 - F10*F9*T14 - 
     F11*F9*T14 + MT2*(F10*F12) + MT2*(F11*F12) - MT2*(F2*F3) - 
     3*MT2*(F24*F33) - 3*MT2*(F13*F35) - MT2*(F5*F6) + 
     MT2*(F10*F9) + MT2*(F11*F9);

  Sub13686 = F26*(F37 + F38) + Opt28 + Opt36 + Opt37 - Opt39 - 
     Opt41 - 4*F30*F9*Pair1 + 2*F44*F5*Pair3 + 
     F12*(2*F30*Pair1 + F30*(2*Pair2 - 2*Pair3 - 2*Pair4) + 
        F29*(2*Pair1 + 2*Pair2 - 2*Pair3 - 2*Pair4)) - 
     2*F2*F43*Pair4 - 2*F44*F5*Pair4 + 
     F30*F9*(-4*Pair2 + 6*Pair3 + 6*Pair4) + 
     F29*(-4*F9*Pair1 + F9*(-4*Pair2 + 6*Pair3 + 6*Pair4)) - 
     Sub12892 + F1*(-2*F42*Pair4 - F4*T) + F9*(F10*T + F10*U) + 
     MT2*(-2*F11*F12 + 4*F1*F4);

  Sub14106 = Opt54 + F10*Sub13832 - 2*S34*Sub14102 - 
     4*Sub14103 + 2*Sub14105 + 4*Sub4080 + 
     ((F20 + F21)*(F19 + F26 + F29 + F30) + F2*F32 + F24*F34 + 
        F31*F5)*(-T24 - U) + 
     F11*(-Sub14104 + F22*(-T24 - U) - F16*U) + 
     F15*F2*(-2*Pair2*(T + T14) + Pair1*(-2*T + 2*U)) + 
     (F1*F24 + F25*F5)*(-2*Pair2*(T + T14) + 
        Pair1*(-2*T + 2*(T24 + U))) + 
     F13*(F36*(-T24 - U) + 
        F7*(-2*Pair2*(T + T14) + Pair1*(-2*T + 2*(T24 + U)))) + 
     MT*(Sub14061*(-2*MT2 + T24 + U));

  Sub12911 = (F19 + F26)*(F37 + F38 + F39 + F40) + Opt48 + 
     Opt55 + 2*(F1*F42 + F41*F7)*Pair3 - 2*Sub12892 + 
     F1*(-4*F42*Pair4 - 2*F4*U) + F7*(-4*F41*Pair4 - 2*F8*U) + 
     F10*(F12 + F9)*(-2*MT2 + 2*(T + U)) + 
     F9*((F29 + F30)*(-2*(Pair1 + Pair2) + 8*(Pair3 + Pair4)) + 
        2*F11*(T + U)) + F2*
      (F43*(2*Pair3 - 4*Pair4) - 2*F3*(T + U)) + 
     F5*(F44*(2*Pair3 - 4*Pair4) - 2*F6*(T + U)) + 
     F12*(F30*(-2*Pair2 + 8*(Pair3 + Pair4)) + 
        F29*(-2*(Pair1 + Pair2) + 8*(Pair3 + Pair4)) + 
        2*F11*(T + U) - 2*(F30*Pair1 + MT2*F11)) + 
     MT2*(4*(F2*F3 + F5*F6) - 2*F11*F9);

  Sub6280 = 2*(F36*F41 + F34*F42 + F23*F50 + F14*F52) + 
     Opt55 - 4*((F24*F50 + F13*F52)*Pair1 + 
        (F1*F42 + F41*F7)*(Pair1 + Pair2)) + 
     F2*(-4*F51*Pair1 + F3*(-2*S34 - 4*T - 6*T14)) + 
     F5*(-4*F48*Pair1 + F6*(-2*S34 - 4*T - 6*T14)) - 
     2*(F26*Sub6277 + F19*Sub6278 + Sub6279 + 
        (F1*F4 + F7*F8)*(S34 + T14)) + 
     F9*(F45 + F46 + F30*(4*Pair1 + 2*Pair3) + 
        F29*(6*Pair1 + 2*Pair2 - 2*Pair4) + 
        F11*(-4*MT2 + S34 + 2*T + 3*T14) + 
        F10*(-6*MT2 + 2*S34 + 3*T + 4*T14)) + 
     F12*(F45 + F46 + F30*(6*Pair1 + 2*Pair2) + 
        F29*(4*Pair1 + 2*Pair3) + 
        F10*(-4*MT2 + S34 + 2*T + 3*T14) + 
        F11*(-6*MT2 + 2*S34 + 3*T + 4*T14)) + 
     MT2*(2*(F24*F33 + F13*F35) + 8*(F2*F3 + F5*F6));

  Sub13276 = -(F21*F30*S34) - Sub11622 + Sub12294 - 
     8*Sub12898 + 2*Sub13275 + Abb41*Sub138 - Sub7143 - 
     F15*F2*Pair3*T + F20*(-(F30*S34) + F29*(-S34 - T - T24 - U) + 
        F30*(-T - T14 - T24 - U)) + F21*F29*(-T - T14 - T24 - U) + 
     F21*F30*(-T - T14 - T24 - U) - F15*F2*Pair3*U + 
     F25*F5*(-(Pair3*T) - Pair3*U) + 
     F13*F7*(-(Pair3*T) - Pair3*U) + 
     Pair4*((2*F25*F5 + 2*F13*F7)*S + 2*F15*F2*T + 
        F15*F2*(3*T14 + 3*T24 + 2*U) + 
        F25*F5*(2*T + 3*T14 + 3*T24 + 2*U) + 
        F13*F7*(2*T + 3*T14 + 3*T24 + 2*U)) + 
     F1*F24*(-(Pair3*T) - Pair3*U + 
        Pair4*(2*S + 2*T + 3*T14 + 3*T24 + 2*U)) + 
     F11*(MT2*F16 + MT2*F17) + MT2*Sub13274;

  Sub5354 = (F10 + F11)*(F12*S + F9*S) + 
     F2*(2*F43*Pair1 + 2*F43*Pair2 + F3*(4*MT2 - S34)) + 
     F1*(F42*(2*Pair1 + 2*Pair2) - F4*S34) + 
     F5*(2*F44*Pair1 + 2*F44*Pair2 - F6*S34) + 
     F7*(2*F41*Pair1 + 2*F41*Pair2 - F8*S34) - Sub12823 - 
     Sub5292 + MT2*(4*F1*F4 + 4*F5*F6 + 4*F7*F8);

  Sub13273 = (F19 + F26)*(-F37 - F38 - F39 - F40) - Opt40 - 
     Opt53 + Sub13049 + Sub13061 + 
     F1*(F42*(-2*Pair3 + 2*Pair4) + 
        F4*(-2*S - 2*S34 - 3*T14 - 3*T24)) + 
     F5*(-2*F44*Pair3 + 2*F44*Pair4 + 
        F6*(-2*S - 2*S34 - 3*T14 - 3*T24)) + 
     F7*(-2*F41*Pair3 + 2*F41*Pair4 + 
        F8*(-2*S - 2*S34 - 3*T14 - 3*T24)) + 
     F2*(-2*F43*Pair3 + 2*F43*Pair4 + 
        F3*(-2*S - 2*S34 - T - 3*T14 - 3*T24)) + 
     F11*F9*(S34 + T14 + T24) + 
     F12*(F11*(S34 + T14 + T24) - 4*MT2*F11) + 
     F10*(F9*(T14 + T24) + F12*(-4*MT2 + S34 + T14 + T24) - 
        4*MT2*F9) + MT2*(8*F2*F3 + 8*F1*F4 + 8*F5*F6 + 8*F7*F8 - 
        4*F11*F9);

  Sub13450 = Opt52 + Opt59 + MH2*(-Sub11664 + 2*Sub13447) + 
     10*Sub13449 + 2*Abb11*Sub138 + 
     (F2*F27 + F28*F5)*(-S - T14 - T24) + 
     (F10*(F16 + F17 + F22) + F11*(F16 + F18 + F22))*
      (S + T14 + T24) + (F15*F2 + F25*F5)*
      (-2*Pair1*(S + T14) + 2*Pair4*(S + T + U)) + 
     (F20 + F21)*(F19*Sub258 + F26*(4*MT2 - S34 - T - U) + 
        (F29 + F30)*(-2*(S + T14 + T24) - 3*(S34 + T + U))) + 
     F7*(F14*(S + T14) + F13*
         (-2*Pair3*(S + T14 + T24) + 
           Pair4*(-2*(T14 + T24) + 2*(T + U)))) + 
     F1*(F23*(S + T14) + F24*
         (-2*Pair3*(S + T14 + T24) + 
           Pair4*(-2*(T14 + T24) + 2*(T + U)))) + 
     MT2*(Sub11664 - Sub13446) + MT*Sub13448;

  Sub9747 = -4*Abb140*(F15*F2 + F25*F5) + 
     2*Abb137*(F1*F24 + F13*F7) + Opt59 + 
     F18*(F45 + 2*F46 + (F29 + F30)*
         (4*(Pair1 + Pair2) - 4*(Pair3 + Pair4)) + 
        F19*(2*(Pair1 + Pair2) - 2*(Pair3 + Pair4))) + 
     F17*(2*F45 + F46 + (F29 + F30)*
         (4*(Pair1 + Pair2) - 4*(Pair3 + Pair4)) + 
        F26*(2*(Pair1 + Pair2) - 2*(Pair3 + Pair4))) - 
     2*Abb116*Sub138 + F11*
      (F18*(3*MT2 - 2*S34) + F17*(-3*MT2 + T + 2*U)) + 
     F10*(F17*(3*MT2 - 2*S34) + F18*(-3*MT2 + T + 2*U)) + 
     F24*(F34*(MT2 - 2*U) + 
        F1*(Pair1*(-4*S34 - 2*U) - 4*Pair2*U + 
           Pair3*(4*S34 + 2*U) + MT2*(8*Pair1 - 8*Pair3))) + 
     F13*(F36*(MT2 - 2*U) + 
        F7*(Pair1*(-4*S34 - 2*U) - 4*Pair2*U + 
           Pair3*(4*S34 + 2*U) + MT2*(8*Pair1 - 8*Pair3))) + 
     MT*Sub9746 + F2*(F32*(-MT2 + 2*T24 - 2*U) + 
        F27*(-4*MT2 + 2*(S34 + U)) + 
        F15*(Pair2*(-4*S34 - 8*(S + T24) - 12*U) + 
           (-2*Pair1 + 2*Pair3)*(S34 + U) + 
           4*Pair4*(S + T24 + U) + 
           MT2*(4*Pair1 + 32*Pair2 - 4*Pair3 - 12*Pair4)) + 
        MT2*(Sub8478 - MT*F3)) + 
     F5*(F31*(-MT2 + 2*T24 - 2*U) + F28*(-4*MT2 + 2*(S34 + U)) + 
        F25*(Pair2*(-4*S34 - 8*(S + T24) - 12*U) + 
           (-2*Pair1 + 2*Pair3)*(S34 + U) + 
           4*Pair4*(S + T24 + U) + 
           MT2*(4*Pair1 + 32*Pair2 - 4*Pair3 - 12*Pair4)) + 
        MT2*(Sub8477 - MT*F6));

  Opt27 = -(F36*F41) + F12*F45 - F45*F9 + F19*Sub7346 + 
     F29*Sub7346;

  Opt31 = Opt30 + F41*F7*(-2*Pair3 - 4*Pair4) + S*Sub6049 - 
     F2*Sub6050;

  Opt33 = F1*F42*(-Pair1 - Pair2) + 
     (-(F2*F43) + F44*F5 + F41*F7 + (F19 + F26 + F29 + F30)*F9)*
      Pair2 + Pair1*(-(F2*F43) + (F26 + F29)*F9 + Sub12239);

  Opt34 = (F10 + F11)*(F12 + F9)*S - Sub12823;

  Opt38 = F26*(F37 + F38) + Opt36 + Opt37 + 
     MT2*(-2*F11*F12 + 4*F1*F4);

  Sub9254 = Abb174*(F15*F2 + F25*F5) + Abb168*(F1*F24 + F13*F7)
   ;

  Sub5931 = Abb26*(F15*F2 + F25*F5) + MT2*(F1*F23);

  Sub8817 = Abb183*(F15*F2 + F25*F5) + MT2*(F20*F30);

  Sub8775 = Abb190*(F15*F2 + F25*F5) + MT2*(F2*F32);

  Sub8880 = Abb171*(F15*F2 + F25*F5) + MT2*(F24*F34);

  Sub2883 = 1/MW2*(MW2*(Abb11*(F15*F2 + F1*F24)) + 
       MB2*MT*((F29 + F30)*(F37 + F38)));

  Sub2875 = 1/MW2*(MW2*(Abb11*(F15*F2 + F1*F24)) + 
       MB2*MT2*(F20*(F29 + F30)));

  Sub8766 = Abb184*(F15*F2 + F25*F5) + MT2*(F15*F2*Pair2);

  Sub14267 = Abb101*F15*F2 + F16*(F19 + F29)*(2*Pair1 + Pair2)
   ;

  Sub14273 = Abb101*F13*F7 + F22*(F19 + F29)*(2*Pair1 + Pair2)
   ;

  Sub10076 = MT2*F27 + F15*(4*Abb135 - 2*MT2*Pair2);

  Sub7986 = MT2*(F19*F20) + F15*F2*(Abb173 + MT2*Pair2);

  Sub6091 = Abb42*F15*F2 + (F16 + F17)*F29*Pair3;

  Sub6094 = Abb42*F13*F7 + (F18 + F22)*F29*Pair3;

  Sub6057 = Abb42*F1*F24 + (F16 + F17)*F30*Pair3;

  Sub9052 = Abb173*(F15*F2 + F25*F5) + 
     MT2*(F15*F2*Pair2 + F13*F7*Pair3);

  Sub11160 = Abb14*F15*F2 + (F16 + F17)*F29*(Pair3 - Pair4);

  Sub11164 = Abb14*F1*F24 + (F16 + F17)*F30*(Pair3 - Pair4);

  Sub5701 = Abb70*F15*F2 + (F16 + F17)*(-F19 + F29)*Pair4;

  Sub11304 = Abb11*F15*F2 + (F16 + F17)*F29*Pair4;

  Sub11307 = Abb11*F13*F7 + (F18 + F22)*F29*Pair4;

  Sub5697 = Abb70*F1*F24 + (F16 + F17)*(-F26 + F30)*Pair4;

  Sub13497 = Abb70*(F15*F2 + F1*F24) + 
     (F16 + F17)*(-F19 - F26 + F29 + F30)*Pair4;

  Sub11309 = Abb11*F1*F24 + (F16 + F17)*F30*Pair4;

  Sub11312 = Abb11*F25*F5 + (F18 + F22)*F30*Pair4;

  Sub12723 = Abb11*(F15*F2 + F1*F24) + 
     (F16 + F17)*(F29 + F30)*Pair4;

  Sub9726 = Abb148*(F15*F2 + F25*F5) + MT2*(F1*F24*Pair4);

  Sub10615 = Abb52*F15*F2 + 
     (F16 + F17)*(F19 + F29)*(2*Pair3 + Pair4);

  Sub10617 = Abb52*F13*F7 + 
     (F18 + F22)*(F19 + F29)*(2*Pair3 + Pair4);

  Sub10619 = Abb52*F1*F24 + 
     (F16 + F17)*(F26 + F30)*(2*Pair3 + Pair4);

  Sub10621 = Abb52*F25*F5 + 
     (F18 + F22)*(F26 + F30)*(2*Pair3 + Pair4);

  Sub13171 = Abb69*(F25*F5 + F13*F7) + 
     (F18 + F22)*(F19 + F26)*(-Pair3 - 2*Pair4);

  Sub9313 = Abb175*(F15*F2 + F25*F5) + F15*F2*Pair1*S;

  Sub9806 = Abb148 + (2*Pair2 - Pair3)*S;

  Sub10721 = F25*F5*(Abb10 + (Pair1 - Pair4)*S);

  Sub11605 = Abb11*(F25*F5 + F13*F7) + F25*F5*Pair4*S;

  Sub13777 = Abb66*(F15*F2 + F1*F24) + 
     F1*F24*Pair3*(-2*MT2 + S);

  Sub10827 = F23*S - F24*(Abb55 + 2*(Pair1 + Pair2)*S);

  Sub2444 = MT*(MB2 + 2*MW2)*((F12*F26 + F1*F42)*Pair4) + 
     MT2*(F25*F5*(Abb18 - Pair4*S));

  Sub10087 = F2*F49 + (-F12 + F9)*Sub10086;

  Sub10315 = F19*(F12*(Pair1 + Pair2) + F9*(-Pair3 - Pair4)) + 
     F29*F9*(Pair2 - Pair3 - Pair4) + Pair2*Sub10280 + 
     Pair1*(F29*F9 + Sub10280);

  Sub10282 = (Pair1 + Pair2)*Sub10280 + (F19 + F29)*Sub10281;

  Sub10286 = (F26 + F30)*Sub10281 + (Pair1 + Pair2)*Sub10285;

  Sub10308 = F26*(F12*(Pair1 + Pair2) + F9*(-Pair3 - Pair4)) + 
     F30*F9*(Pair2 - Pair3 - Pair4) + Pair2*Sub10285 + 
     Pair1*(F30*F9 + Sub10285);

  Sub12366 = 2*MW2*((Pair1 + Pair2)*Sub10397) + 
     MT2*(F12*(F19 + F29)*(Pair3 + Pair4) + 
        (Pair1 + Pair2)*Sub10397);

  Sub12369 = 2*MW2*((Pair1 + Pair2)*Sub10399) + 
     MT2*(F12*(F26 + F30)*(Pair3 + Pair4) + 
        (Pair1 + Pair2)*Sub10399);

  Sub3682 = (-3*MB2 - 6*MW2)*Sub1043 + 4*MT*Sub1045;

  Sub3521 = MT2*Sub1050 + (-MB2 - 2*MW2)*Sub1051;

  Sub10519 = -4*F1*F23 + F20*(-8*F30 + Sub10518);

  Sub10527 = 2*(F26 + F30)*F9*Pair4 + 
     F12*(-(F26*Pair4) - F30*Pair4) + (Pair1 + Pair2)*Sub10526;

  Sub10532 = -(F26*F9*Pair4) - F30*F9*Pair4 + 
     F12*(2*F26*Pair4 + 2*F30*Pair4) + Pair1*Sub10531 + 
     Pair2*Sub10531;

  Sub10535 = 2*(F19 + F29)*F9*Pair4 + 
     F12*(-(F19*Pair4) - F29*Pair4) + (Pair1 + Pair2)*Sub10534;

  Sub1061 = -8*F10*F17 + 8*F2*F32 + MT*Sub1060;

  Sub10733 = F9*(-(F29*Pair3) + F19*(-Pair3 - Pair4) - 
        F29*Pair4) + (Pair1 + Pair2)*Sub10605;

  Sub10730 = F9*(-(F30*Pair3) + F26*(-Pair3 - Pair4) - 
        F30*Pair4) + (Pair1 + Pair2)*Sub10609;

  Sub10660 = (Pair1 + Pair2)*Sub10280 + (F19 + F29)*Sub10659;

  Sub10662 = (Pair1 + Pair2)*Sub10285 + (F26 + F30)*Sub10659;

  Sub1068 = (MB2 + 2*MW2)*Sub1066 - MT2*Sub1067;

  Sub10696 = -8*F1*F23 + F20*(-16*F30 + Sub10695);

  Sub10703 = (F26 + F30)*Sub10701 + (Pair1 + Pair2)*Sub10993;

  Sub10709 = (F19 + F29)*Sub10701 + (Pair1 + Pair2)*Sub10991;

  Sub3771 = F19*Sub1071 + MT2*(-2*F10*F12 + 2*F2*F3);

  Sub1377 = (MB2*MT2 - MT2*MT2)*F20 + 
     (-3*MB2*MT2 + 3*(MT2*MT2))*F21 + 2*MB2*MT*Sub1071;

  Sub10794 = F29*Sub10792 + F13*F7*(-2*Abb181 + 2*Sub10793);

  Sub10799 = F17*F30*(Pair1 + Pair2 - Pair3 - Pair4) + 
     F1*F24*Sub10798;

  Sub10800 = 2*(Abb181*F1*F24 + Sub10799) + MT2*(F20*F30);

  Sub10974 = 2*F1*F24*(Abb59 + Pair4*Sub10972) - 
     F20*F30*Sub10973;

  Sub12905 = -2*(F15*F2 + F1*F24)*(Abb59 + Pair4*Sub10972) + 
     F20*(F29 + F30)*Sub10975;

  Sub10977 = F20*F29*Sub10975 - 
     2*F15*F2*(Abb59 + Pair4*Sub10976);

  Sub13263 = 4*Abb47*(F15*F2 + F1*F24) + 
     F20*(F19 + F26)*Sub11078;

  Sub1123 = -2*F12*Sub1120 + F10*Sub1122 + 2*F9*Sub1257;

  Sub1126 = F11*Sub1122 - 2*F12*Sub1124 + 2*F9*Sub1259;

  Sub1132 = -2*F9*Sub1120 + F10*Sub1131 + 2*F12*Sub1257;

  Sub1133 = -2*F9*Sub1124 + F11*Sub1131 + 2*F12*Sub1259;

  Sub12670 = F30*(F12*(Pair3 - Pair4) + F9*(-Pair3 + Pair4)) + 
     Pair4*Sub11323;

  Sub11382 = F19*(F37 + F38 - 2*F12*Pair3) + F29*Sub11381;

  Sub11385 = F26*(F37 + F38 - 2*F12*Pair3) + F30*Sub11381;

  Sub13188 = (F19 + F26)*(F37 + F38 - 2*F12*Pair3) + 
     (F29 + F30)*Sub11381;

  Sub11384 = F29*(F39 + F40 - 6*F9*Pair3) + F19*Sub11383;

  Sub11386 = F30*(F39 + F40 - 6*F9*Pair3) + F26*Sub11383;

  Sub11390 = (F26 + F30)*(F39 + F40) + Pair3*Sub11389;

  Sub11393 = (F19 + F29)*(F39 + F40) + Pair3*Sub11392;

  Sub10830 = 2*Abb68*Sub1141 + 3*MT*((Pair1 + Pair2)*Sub10829)
   ;

  Sub11433 = (F16 + F17)*(F30*Pair3 - F26*Pair4) - 
     F1*F24*Sub11432;

  Sub11435 = (F18 + F22)*(F30*Pair3 - F26*Pair4) - 
     F25*F5*Sub11432;

  Sub11481 = F29*Sub11480 + MT2*(F19*(-2*F20 + 2*F21));

  Sub14558 = MT2*MT2*(F19*(2*F20 - 2*F21) + 2*F20*F29) + 
     MT2*(Sub11481 - 2*MT2*(F21*F29));

  Sub14559 = MT2*MT2*(-2*F21*F26 + 2*F20*(F26 + F30)) + 
     MT2*(Sub11482 - 2*MT2*(F21*F30));

  Sub11506 = (-(MB2*MT2) + MT2*MT2)*F20 + 
     (MB2*MT2 - MT2*MT2)*F21 + MB2*MT*Sub11499;

  Sub1151 = (MB2 + MT2)*(F46*(F12 + F9)) + 
     F11*(MB2*Sub1149 + MT2*Sub1150);

  Sub11534 = 1/CW2*(CW2*(MT2*MT2)*
        ((-54*F1*F24 + 54*F25*F5)*Pair4) + MT2*Sub11533);

  Sub11537 = 1/CW2*(Sub11536 + 
       CW2*(MT2*MT2)*((-54*F15*F2 + 54*F13*F7)*Pair4));

  Sub11585 = (F16 + F17 - F18 - F22)*Sub11220 + 
     MT*((F12*(Pair3 - Pair4) + F9*(-Pair3 + Pair4))*Sub11584);

  Sub12614 = MZ2*Sub11547 + MT2*(-Sub11547 + Sub11587);

  Sub1454 = Sub1161 + MT*(F24*F33 - F5*F6);

  Sub14542 = F19*(F37 + F38 - F39 - F40) + F29*Sub11630;

  Sub14543 = F26*(F37 + F38 - F39 - F40) + F30*Sub11630;

  Sub11635 = Sub11632 + MT*(F26*Sub11630 + F30*Sub11631);

  Sub14547 = MT2*MT2*(-2*F21*F26 + 2*F20*(F26 + F30)) + 
     MT2*(Sub11632 - 2*MT2*(F21*F30));

  Sub11634 = ((4*F17 - 4*(F18 + F22))*F29 + 
        F16*(2*F19 + 4*F29))*Pair3 + F29*Sub11633 + 
     F19*((2*F17 - 2*(F18 + F22))*Pair3 + Sub11633);

  Sub14546 = MT2*MT2*(F19*(2*F20 - 2*F21) + 2*F20*F29) + 
     MT2*(Sub11634 - 2*MT2*(F21*F29));

  Sub11700 = 1/MW2*((-2*MT2 + 3*MW2)*((F29 + F30)*F9*Pair3) + 
       MW2*Sub11698);

  Sub11737 = -(F16*Sub11736) - F17*Sub11736 + F18*Sub11736 + 
     F22*Sub11736 + MT*(F12*Sub11584 - F9*Sub11584);

  Sub11783 = 1/CW2*(-2*Sub11782 + 9*CW2*MT2*Sub11776);

  Sub14612 = Sub11802 + MT*((4*F12 - 4*F9)*Pair3);

  Sub11820 = -2*(F1*F42*Pair4 + F30*Sub11818) + F5*Sub11819;

  Sub11822 = -2*(F2*F43*Pair4 + F29*Sub11818) + F7*Sub11821;

  Sub1186 = Sub1184 + MT*(F24*F33 + F5*F6);

  Sub1227 = MT2*(Sub1184 + MT*(F24*F33 + F5*F6));

  Sub1201 = -Sub1185 + MT*(F2*F3 + F13*F35);

  Sub11911 = 1/MW2*(-(MB2*Sub11903) + 
       MW2*(Sub11902 + 2*Sub11903));

  Sub12010 = F27*(-2*MT2 + S) - 2*F15*Sub12009;

  Sub12011 = F20*F29*Sub12008 + F2*(2*Abb66*F15 + Sub12010);

  Sub12014 = F20*F30*Sub12008 + F1*(2*Abb66*F24 + Sub12013);

  Sub12061 = (F18 + F22)*Sub12060 + 
     MT*((Pair3 + Pair4)*Sub12059);

  Sub12224 = 1/CW2*(2*Sub12223 + 9*CW2*MT2*Sub12217);

  Sub12242 = (F15*F2 + F1*F24)*Sub10289 + (F16 + F17)*Sub12241
   ;

  Sub12268 = (F25*F5 + F13*F7)*Sub10289 + (F18 + F22)*Sub12241
   ;

  Sub12258 = (F25*F5 + F13*F7)*Pair4*S + 
     (Pair1 + Pair2)*Sub12257;

  Sub1238 = F12*(F19 + F29)*
      (2*(Pair1 + Pair2) - 2*(Pair3 + Pair4)) + F10*Sub1237;

  Sub1239 = F12*(F26 + F30)*
      (2*(Pair1 + Pair2) - 2*(Pair3 + Pair4)) + F11*Sub1237;

  Sub12400 = -(2*MW2*((Pair1 + Pair2)*Sub12387)) + 
     MT2*(-(Pair1*Sub12387) - Pair2*Sub12387) + MB2*Sub12388;

  Sub12461 = 2*Abb40*(F15*F2 + F1*F24) + F20*Sub12460;

  Sub12506 = 2*Abb53*(F15*F2 + F1*F24) + F20*Sub12460;

  Sub12558 = 2*Abb53*(F25*F5 + F13*F7) + F21*Sub12460;

  Sub12482 = (-MB2 + 2*MW2)*Sub12459 + MT2*Sub12463;

  Sub12523 = 2*MW2*Sub12459 + MB2*(-Sub12459 + Sub12512);

  Sub14429 = Abb94*(F15*F2 + F13*F7) + F15*F2*Pair1*Sub1253;

  Sub1255 = (F12*F29 + F19*F9)*
      (-2*(Pair1 + Pair2) + 2*(Pair3 + Pair4)) + F10*Sub1254;

  Sub1256 = (F12*F30 + F26*F9)*
      (-2*(Pair1 + Pair2) + 2*(Pair3 + Pair4)) + F11*Sub1254;

  Sub12640 = Sub12637 + MT*(F11*F12 - F5*F6);

  Sub9596 = F26*(2*F12 - 2*F9)*Pair3 - MT2*Sub1277;

  Sub10455 = (F26 + F30)*(2*F12 - 2*F9)*Pair4 + S*Sub1277;

  Sub2642 = (2*MB2*MT2 - 2*(MT2*MT2))*F21 + MB2*MT*Sub1279;

  Sub12972 = (F20 + F21)*(F19 + F26)*Sub12971 + 
     MT2*(-Sub12953 + MT*Sub12943);

  Sub13070 = 1/MW2*(-(2*MB2*(F12*Sub12918 + F9*Sub13060)) - 
       MW2*Sub13064);

  Sub13078 = F12*(F29 + F30)*(Pair1 + Pair2) + 
     (F19 + F26)*Sub13075;

  Sub13108 = Sub13104 + (F10 + F11)*(-(MT*F12) - MT*F9);

  Sub13136 = 1/MW2*(2*Pair4*(MB2*Sub13124 + MT2*Sub13125) + 
       MW2*Sub13130);

  Sub14603 = (MB2 + 2*MW2)*Sub13141 - MT2*Sub13143;

  Sub13157 = -(Pair4*Sub13156) + Pair3*(Sub13155 + Sub13156);

  Sub13158 = (F16 + F17)*
      (MB2*(-2*Pair3 + 2*Pair4) + MW2*(-8*Pair3 + 8*Pair4)) + 
     MT*Sub13157;

  Sub13159 = 1/MW2*(-Sub13158 + 2*MT2*MW2*Sub13154);

  Sub13220 = (F19 + F26)*(F37 + F38) + F9*Sub13219;

  Sub13408 = (F18 + 2*F22)*(F26 + F30)*Pair2 + F25*F5*Sub13405
   ;

  Sub13434 = F18*(F19 + F29)*Pair1 - Pair2*Sub13433;

  Sub13472 = 1/MW2*(Pair3*(2*MB2*Sub13460 - 2*MT2*Sub13461) - 
       MW2*Sub13465);

  Sub13493 = 1/MW2*(MB2*((F10 + F11)*(F12 + F9)) - 
       MW2*Sub13488);

  Sub13494 = 1/MW2*(MW2*Sub13490 + MB2*Sub13491 + MT2*Sub13492)
   ;

  Sub13601 = MW2*(-(F10*F18) + 2*F13*F7*Pair2) + MT*Sub13600;

  Sub13694 = Sub13693 + (-MT2 + MZ2)*(F21*(F29 + F30));

  Sub13733 = F17*(F19*Pair1 + F29*Pair1) - F16*F19*Pair2 - 
     F16*F29*Pair2 - F15*F2*Sub13732;

  Sub13735 = F17*(F26*Pair1 + F30*Pair1) - F16*F26*Pair2 - 
     F16*F30*Pair2 - F1*F24*Sub13732;

  Sub13737 = F18*(F26*Pair1 + F30*Pair1) - F22*F26*Pair2 - 
     F22*F30*Pair2 - F25*F5*Sub13732;

  Sub13739 = F18*(F19*Pair1 + F29*Pair1) - F19*F22*Pair2 - 
     F22*F29*Pair2 - F13*F7*Sub13732;

  Sub13752 = 1/MW2*(-(Pair4*Sub13750) + 2*MT2*MW2*Sub13751);

  Sub13782 = 1/MW2*(MB2*(Pair3*Sub13780) - 2*MT2*MW2*Sub13781)
   ;

  Sub13789 = F13*Sub13788 + MT2*(F10*F22 + F21*F29);

  Sub13816 = Sub13794 + MZ2*(F20*(F19 + F29) + F2*F32);

  Sub13822 = Sub13796 + MZ2*(F20*(F26 + F30) + F24*F34);

  Sub12752 = (F16 + F17 + F18 + F22)*(F29 + F30)*Pair4 + 
     Abb11*Sub138;

  Sub4052 = (F17 + F18)*(F19 + F26 + F29 + F30)*Pair1 + 
     Abb97*Sub138;

  Sub2975 = (-MB2 + MT2)*(F15*F2) + MT2*(F1*F24) + 
     MB2*(-(F1*F24) + Sub138);

  Sub1539 = (-MB2 - 3*MW2)*(F25*F5) - 3*MW2*(F13*F7) + 
     MB2*(-(F13*F7) + Sub138);

  Sub2569 = (2*MB2 - 8*MW2)*(F15*F2) - 8*MW2*(F1*F24) + 
     MB2*(2*F1*F24 + Sub138);

  Sub10498 = (F16 + F17 + F18 + F22)*
      (F19 + F26 + 2*(F29 + F30)) + (-MH2 + 2*MT2)*Sub138;

  Sub139 = (F1*F24 + F13*F7)*Pair2 + Pair1*Sub138;

  Sub4056 = (F10 + F11)*(F17 + F18) + 2*Pair2*Sub138;

  Sub12282 = (F20 + F21)*(F19 + F26 + F29 + F30) - 
     2*(Pair1 + Pair2)*Sub138;

  Sub935 = (F10 + F11)*(F16 + F17 + F18 + F22) + 
     2*(Pair1 + Pair2)*Sub138;

  Sub13182 = (F20 + F21)*(F29 + F30) + 2*(Pair1 + Pair2)*Sub138
   ;

  Sub923 = (F20 + F21)*(F19 + F26 + F29 + F30) + 
     2*(Pair1 + Pair2)*Sub138;

  Sub13187 = F19*(-F20 + F21) + F20*(-F26 - F29 - F30) + 
     F21*(F26 + F29 + F30) + Pair3*Sub138;

  Sub5864 = (F15*F2 + F25*F5)*(Pair1 + Pair2) + Pair3*Sub138;

  Sub13532 = (F1*F24 + F13*F7)*Pair2 + (Pair1 + Pair3)*Sub138
   ;

  Sub5279 = (F20 + F21)*(F29 + F30) - 2*Pair4*Sub138;

  Sub12326 = (F20 + F21)*(F19 + F26) + 
     (-2*(Pair1 + Pair2) + 2*Pair4)*Sub138;

  Sub13859 = F11*(F16 + F17)*Sub13856 - 
     F24*(F34*Sub13856 - 2*F1*(Abb98 + Sub13858));

  Sub13860 = F10*(F16 + F17)*Sub13856 - 
     F2*(F32*Sub13856 - 2*F15*(Abb98 + Sub13858));

  Sub13861 = F11*(F18 + F22)*Sub13856 - 
     F5*(F31*Sub13856 - 2*F25*(Abb98 + Sub13858));

  Sub13862 = F10*(F18 + F22)*Sub13856 - 
     F13*(F36*Sub13856 - 2*F7*(Abb98 + Sub13858));

  Sub14260 = Sub13867 + MT*(F24*F33 - F5*F6);

  Sub13911 = Sub13909 + MT*(F2*F3 - F13*F35);

  Sub13912 = Sub13910 + MT*(-(F24*F33) + F5*F6);

  Sub13953 = (F17 + F18)*(F19 + F29)*Pair1 + Pair2*Sub13952;

  Sub13960 = (F17 + F18)*(F26 + F30)*Pair1 + Pair2*Sub13959;

  Sub14090 = (F17 + F18)*(F26 + F30)*Pair1 - Pair2*Sub14089;

  Sub14091 = Abb87*(F1*F24 + F25*F5) + Sub14090;

  Sub14093 = (F17 + F18)*(F19 + F29)*Pair1 - Pair2*Sub14092;

  Sub14094 = Abb87*(F15*F2 + F13*F7) + Sub14093;

  Sub14112 = Abb97*(F15*F2 + F13*F7) + Sub14111;

  Sub14115 = Abb97*(F1*F24 + F25*F5) + Sub14114;

  Sub14537 = Sub14254 + MT*(-(F2*F3) + F13*F35);

  Sub14297 = Abb88*(F15*F2 + F13*F7) + Sub14296;

  Sub14304 = (F19 + F29)*(-4*F17*Pair1 + 4*F16*Pair2) + 
     F15*F2*Sub14303;

  Sub14306 = (F19 + F29)*(-4*F18*Pair1 + 4*F22*Pair2) + 
     F13*F7*Sub14303;

  Sub14320 = (F19 + F29)*(-4*F17*Pair1 + 4*F16*Pair2) + 
     F15*F2*Sub14319;

  Sub14322 = (F19 + F29)*(-4*F18*Pair1 + 4*F22*Pair2) + 
     F13*F7*Sub14319;

  Sub14458 = MT2*MT2*(F20 - F21) + MT*MT2*Sub14448;

  Sub1446 = -2*Sub1445 + MT2*((F20 - F21)*Sub1444);

  Sub14598 = Sub14493 - MT*(F2*F3) - MT*(F7*F8);

  Sub14600 = Sub14497 + MT2*(F1*F4 + F5*F6);

  Sub14552 = Sub14550 + MT*(-3*F2*F3 + 3*F13*F35);

  Sub14553 = Sub14551 + MT*(3*F24*F33 - 3*F5*F6);

  Sub14568 = Sub14566 + MT*(3*F2*F3 - 3*F13*F35);

  Sub14569 = Sub14567 + MT*(3*F24*F33 - 3*F5*F6);

  Sub14586 = -(F20*(F19 + F26 - 2*(F29 + F30))) + MT*Sub14571
   ;

  Sub14587 = -(F21*(F19 + F26 - 2*(F29 + F30))) + MT*Sub14585
   ;

  Sub14594 = MT2*MT2*(2*F20 - 2*F21) + 
     MT2*(-Sub11918 + MT*Sub14591);

  Sub14613 = 4*(MT2*MT2)*F20 + MT2*(-Sub14612 - 4*MT2*F21);

  Sub14828 = 6*Sub14827 + 
     CW2*((F10 + F11)*(72*(F17 + F18)*Sub14825 + MT*Sub14824));

  Sub4109 = Abb96*(F15*F2 + F13*F7) + F10*(F16 + F22)*Sub152;

  Sub4111 = 4*Abb96*(F15*F2 + F13*F7) + F10*(F16 + F22)*Sub152
   ;

  Sub14299 = Abb95*F15*F2 - (F10*F17 + F20*(F19 + F29))*Sub152
   ;

  Sub14300 = Abb95*F13*F7 - (F10*F18 + F21*(F19 + F29))*Sub152
   ;

  Sub3396 = -(F10*F17*Sub152) + F2*(Abb2*F15 + F32*Sub152);

  Sub3358 = -(F10*F17*Sub152) + F2*(2*Abb2*F15 + F32*Sub152);

  Sub3359 = -(F11*F17*Sub152) + F24*(2*Abb2*F1 + F34*Sub152);

  Sub3397 = -(F10*F18*Sub152) + F13*(Abb2*F7 + F36*Sub152);

  Sub3360 = -(F10*F18*Sub152) + F13*(2*Abb2*F7 + F36*Sub152);

  Sub3361 = -(F11*F18*Sub152) + F5*(2*Abb2*F25 + F31*Sub152);

  Sub3277 = 2*Abb24*F1 - (F34 + 2*F1*(Pair1 + Pair2))*Sub152;

  Sub3266 = 2*Abb24*F15 - (F32 + 2*F15*(Pair1 + Pair2))*Sub152
   ;

  Sub3278 = 2*Abb24*F25 - (F31 + 2*F25*(Pair1 + Pair2))*Sub152
   ;

  Sub3267 = 2*Abb24*F7 - (F36 + 2*F7*(Pair1 + Pair2))*Sub152;

  Sub3297 = 2*Abb2*(F1*F24 + F25*F5) - Sub1161*Sub152;

  Sub14444 = -(Sub14443*Sub152) + 
     (F15*F2 + F13*F7)*(Abb95 + MW2*Pair1);

  Sub547 = (-(F10*F17) + 2*F15*F2*Pair1)*Sub152 + 
     F2*(2*Abb2*F15 + F32*Sub152);

  Sub577 = (-(F11*F17) + 2*F1*F24*Pair1)*Sub152 + 
     F24*(2*Abb2*F1 + F34*Sub152);

  Sub578 = (-(F11*F18) + 2*F25*F5*Pair1)*Sub152 + 
     F5*(2*Abb2*F25 + F31*Sub152);

  Sub548 = -(F10*F18*Sub152) + 
     F13*(F36*Sub152 + 2*F7*(Abb2 + Pair1*Sub152));

  Sub15280 = (F16 + F17 + F18 + F22)*Sub15279 + 
     MT*((F12 + F9)*(Pair3 + Pair4)*Sub15277);

  Sub2562 = F15*F2*(Abb25 + (Pair1 + Pair2)*Sub153);

  Sub3676 = Abb25*(F15*F2 + F13*F7) + 
     F15*F2*(Pair1 + Pair2)*Sub153;

  Sub2579 = F1*F24*(Abb25 + (Pair1 + Pair2)*Sub153);

  Sub2581 = F25*F5*(Abb25 + (Pair1 + Pair2)*Sub153);

  Sub2940 = F7*(2*Abb3 - Pair1*Sub153 - Pair2*Sub153);

  Sub3453 = Abb25*Sub138 + 
     (F15*F2 + F25*F5 + F13*F7)*(Pair1 + Pair2)*Sub153;

  Sub4060 = (F17 + F18)*(F19 + F26 + F29 + F30) - Sub138*Sub153
   ;

  Sub14141 = F17*Sub14139 + F2*(2*F15*Sub14140 + F32*Sub153);

  Sub14142 = -(F18*Sub14139) + 
     F13*(-2*F7*Sub14140 - F36*Sub153);

  Sub13887 = 2*Abb85*(F1*F24 + F25*F5) + Sub13886*Sub154;

  Sub13889 = 2*Abb85*(F15*F2 + F13*F7) + Sub13888*Sub154;

  Sub1542 = 1/MW2*(Sub1541 + (MB2 + 3*MT2)*MW2*Pair3);

  Sub1543 = Sub1542 + (MB2 + 3*MT2 - 2*MW2)*(Pair1 + Pair2);

  Sub15431 = (F17 + F18)*Sub15429 + (F16 + F22)*Sub15430;

  Sub14629 = 1/(CW2*MW2)*
     (CW2*MT2*((3*F20 - 3*F21)*Sub1381) + 2*MT*MW2*Sub1565);

  Sub5446 = MT2*(-MB2 + MT2 + MW2)*(F13*F7) + 
     2*MT*MW2*Sub1577 + MB2*
      ((-MB2 + MT2 + MW2)*(F1*F24) + MT*Sub1577);

  Sub7667 = (-MB2 + 6*MW2)*(F25*F5*Pair2) + 
     (MT2 + 4*MW2)*((Pair1 + Pair2)*Sub1578) + 
     MB2*(-(Pair1*Sub1578) - Pair2*Sub1578);

  Sub2554 = (-MT2 + 2*MW2)*Sub1577 + MB2*(-Sub1577 + 2*Sub1579)
   ;

  Sub2905 = MT2*(F15*F2 + F1*F24) + MT*Sub1579;

  Sub14645 = MT2*(F25*F5 + F13*F7) + MT*Sub1579;

  Sub2666 = MT2*Sub1577 + (-MB2 - 2*MW2)*Sub1579;

  Sub2626 = Pair3*((-MB2 - 2*MW2)*Sub1577 + MT2*Sub1579);

  Sub333 = 2*F1*F24*(Pair1 + Pair2) - Sub159;

  Sub1513 = MT2*Sub158 + (-MB2 + 2*MW2)*Sub159;

  Sub1603 = 2*Abb6*F1*F24 - (F11*(F16 + F17) + F1*F23)*Sub1602
   ;

  Sub1609 = 2*Abb6*F13*F7 - (F10*(F18 + F22) + F14*F7)*Sub1602
   ;

  Sub334 = 2*F13*F7*(Pair1 + Pair2) - Sub161;

  Sub1510 = (-MB2 + 2*MW2)*Sub160 + MT2*Sub161;

  Sub1645 = (MB2 + 2*MW2)*Sub1643 + MT2*Sub1644;

  Sub1118 = 1/(CW2*MW2)*
     (CW2*MT*((-3*F12 + 3*F9)*Sub1117) + 8*MW2*Sub166);

  Sub1858 = (-F20 + F21)*Sub1749 + MT*Sub1748;

  Sub11025 = S*Sub11024 + (-3*F37 + 3*F39)*Sub1782;

  Sub10126 = 2*F5*F6*Sub10125 + (-3*F38 + 3*F40)*Sub1782;

  Sub2020 = Sub1828 + (-MB2 + 2*MW2)*(F25*F5*Pair3);

  Sub1862 = 2*Abb38*F15*F2 + (F19 + F29)*Sub1861;

  Sub1864 = 2*Abb38*F13*F7 - F19*Sub1863 - F29*Sub1863;

  Sub1866 = 2*Abb38*F1*F24 + (F26 + F30)*Sub1865;

  Sub1868 = 2*Abb38*F25*F5 - F26*Sub1867 - F30*Sub1867;

  Sub1922 = 1/MW2*(4*MB2*((F41*F7 + F19*F9)*Pair4) - 
       MW2*Sub1906);

  Sub1923 = 1/MW2*(4*MB2*((F44*F5 + F26*F9)*Pair4) - 
       MW2*Sub1907);

  Sub509 = 2*F25*F5*(Pair1 + Pair2) - Sub192;

  Sub470 = 2*F25*F5*(2*Abb3 - Pair1*Sub153 - Pair2*Sub153) - 
     Sub153*Sub192;

  Sub511 = 2*F1*F24*(Pair1 + Pair2) - Sub193;

  Sub469 = 2*F1*F24*(2*Abb3 - Pair1*Sub153 - Pair2*Sub153) - 
     Sub153*Sub193;

  Sub510 = 2*F15*F2*(Pair1 + Pair2) - Sub194;

  Sub3063 = F15*F2*(2*Abb33 - 3*Pair2*Sub153) - Sub153*Sub194
   ;

  Sub468 = 2*F15*F2*(2*Abb3 - Pair1*Sub153 - Pair2*Sub153) - 
     Sub153*Sub194;

  Sub512 = 2*F13*F7*(Pair1 + Pair2) - Sub195;

  Sub3064 = F13*F7*(2*Abb33 - 3*Pair2*Sub153) - Sub153*Sub195
   ;

  Sub471 = 2*F13*F7*(2*Abb3 - Pair1*Sub153 - Pair2*Sub153) - 
     Sub153*Sub195;

  Sub13713 = (F16 + F17 + F18 + F22)*(F19 + F26) + 
     Sub138*Sub1971;

  Sub6447 = -(Abb70*F15*F2) - F15*F2*Pair4*Sub1971 - 
     MT*(F12*F19*Pair4) + 2*MT*(F41*F7*Pair4);

  Sub6444 = -(Abb70*F1*F24) - F1*F24*Pair4*Sub1971 - 
     MT*(F12*F26*Pair4) + 2*MT*(F44*F5*Pair4);

  Sub1991 = MT2*MT2*(F13*F7*Pair4) + 
     F15*F2*(-(MT2*MT2*Pair4) + MB2*(Abb17 + Pair4*Sub1971));

  Sub1993 = MT2*MT2*(F25*F5*Pair4) + 
     F1*F24*(-(MT2*MT2*Pair4) + MB2*(Abb17 + Pair4*Sub1971));

  Sub2526 = Sub1298*(Abb17 + Pair4*Sub1971) + 
     MT*(-(MB2*(Pair4*Sub1534)) - MT2*(Pair4*Sub1534) - 
        2*MW2*(Pair4*Sub1534));

  Sub11502 = 2*F1*F24*Sub11501 - F20*F30*Sub1976;

  Sub12871 = -(F15*F2*Sub10936) - F1*F24*Sub10936 + 
     F20*(F29*Sub1976 + F30*Sub1976);

  Sub201 = 3*(F10 + F11)*Sub200 + 8*MW2*Sub199;

  Sub1322 = (F29 + F30)*Sub1143 + 
     MT*(-MB2 + MT2 - 2*MW2)*Sub216;

  Sub2180 = F20*F30*Sub2178 + F1*(-2*Abb11*F24 + 2*Sub2179);

  Sub2675 = -Sub2198 + 
     MT2*(2*(Pair1 + Pair2) - 2*(Pair3 + Pair4));

  Sub2204 = (F25*F5 + F13*F7)*Sub2198 + 
     Sub138*((-MT2 + 2*MW2)*Pair1 + MT2*(-Pair2 + Pair3 + Pair4) + 
        MB2*(-Pair1 - Pair2 + Pair3 + Pair4) + 
        MW2*(2*Pair2 - 2*(Pair3 + Pair4)));

  Sub2519 = -(F25*F5*Sub1536) - F13*F7*Sub1536 + 
     MT*(Pair4*Sub2199);

  Sub13695 = Sub13694 - MT*(Sub13685 + (-MT2 + MZ2)*Sub2200);

  Sub2202 = (2*(Pair1 + Pair2) - 2*(Pair3 + Pair4))*Sub2199 + 
     Sub2200*Sub2201;

  Sub2216 = 2*(F25*F5 + F13*F7)*Sub2198 + MT*Sub2202;

  Sub2205 = 2*F15*F2*Sub2198 + 2*F1*F24*Sub2198 - 
     MT*(F5*Sub1669) - MT*(F7*Sub1671) - MT*(F9*Sub2203);

  Sub2206 = (-MB2 + 2*MW2)*Sub2205 + 
     MT2*(-2*Sub2204 - MT*Sub2202);

  Sub2224 = Abb15*(F15*F2 + F1*F24) + MT2*Sub2223;

  Sub2630 = (MB2 + 2*MW2)*Sub2199 + MT2*Sub2261;

  Sub2973 = MT2*MT2*Sub1578 + MT*(MB2 + MT2 - 2*MW2)*Sub2261;

  Sub13095 = (F19 + F26 + F29 + F30)*(F37 + F38) + 
     Pair4*Sub2261;

  Sub2518 = -(F15*F2*Sub1536) - F1*F24*Sub1536 + 
     MT*(Pair4*Sub2261);

  Sub2295 = -(F29*Sub2291) + 
     F2*(-(F27*Sub2293) - 2*F15*(Abb12 + Sub2294));

  Sub2347 = (MB2 + 2*MW2)*Sub2309 + MT2*Sub2310;

  Sub10454 = (F19 + F29)*(2*F12 - 2*F9)*Pair4 - S*Sub243;

  Sub2446 = 3*(MT2*MT2)*(F13*F7) - MT2*Sub2445;

  Sub2449 = 3*(MT2*MT2)*(F25*F5) - MT2*Sub2448;

  Sub249 = 1/(CW2*MW2)*
     (2*MW2*Sub166 + CW2*MT*((3*F12 - 3*F9)*Sub152*Sub248));

  Sub12851 = 1/MW2*(-(MB2*MT2*Sub2505) + 
       MW2*(Sub12844 + 2*MT2*Sub2505));

  Sub2895 = MT*(MT2 - 2*MW2)*(Pair4*Sub2199) + 
     MB2*(2*Sub2518 + MT*(Pair4*Sub2199));

  Sub2521 = Abb38*(2*F15*F2 + 2*F13*F7) - F19*Sub2520 - 
     F29*Sub2520;

  Sub2523 = 2*Abb38*(F1*F24 + F25*F5) + (F26 + F30)*Sub2522;

  Sub2532 = (F20 + F21)*(F29 + F30)*Sub1765 + 2*MT2*Sub2531;

  Sub7666 = (F29 + F30)*F9*(2*Pair3 - 2*Pair4) - Sub2200*Sub258
   ;

  Sub11434 = -2*(Abb53*F1*F24 + Sub11433) + 
     F20*(-(F30*Sub11431) - F26*Sub258);

  Sub11436 = -2*(Abb53*F25*F5 + Sub11435) + 
     F21*(-(F30*Sub11431) - F26*Sub258);

  Sub2600 = Sub153*Sub194 + F15*F2*(2*Abb30 - 2*Pair2*Sub2599)
   ;

  Sub2601 = Sub153*Sub193 + F1*F24*(2*Abb30 - 2*Pair2*Sub2599)
   ;

  Sub2602 = Sub153*Sub192 + F25*F5*(2*Abb30 - 2*Pair2*Sub2599)
   ;

  Sub2603 = Sub153*Sub195 + F13*F7*(2*Abb30 - 2*Pair2*Sub2599)
   ;

  Sub3711 = Sub153*(Sub194 + Sub195) + 
     (F15*F2 + F13*F7)*(2*Abb30 - 2*Pair2*Sub2599);

  Sub3477 = Sub138*(2*Abb30 - 2*Pair2*Sub2599) + 
     Sub153*(Sub192 + Sub193 + Sub194 + Sub195 - MT*Sub14061);

  Sub11826 = F15*(2*Abb74 - 2*Sub11825) - F27*Sub262;

  Sub1072 = F19*Sub1071 + (F10*F12 - F2*F3)*Sub262;

  Sub11322 = -2*((Pair1 + Pair2)*Sub1029 + Pair4*Sub11321) + 
     F1*F4*Sub262;

  Sub11326 = 2*((Pair1 + Pair2)*Sub1032 + Pair4*Sub11325) + 
     F7*F8*Sub262;

  Sub12303 = (F19 + F26 + F29 + F30)*
      (F12*(-4*Pair3 - 2*Pair4) + F9*(8*Pair3 + 4*Pair4)) + 
     Sub216*Sub262;

  Sub11828 = -(F30*Sub11824) + 
     F1*(-2*F24*(Abb74 + Sub11827) - F23*Sub262);

  Sub11504 = 2*F30*Sub11503 + F5*(8*F44*Pair4 - F6*Sub262);

  Sub11505 = 2*F29*Sub11503 + F7*(8*F41*Pair4 - F8*Sub262);

  Sub265 = Sub159*(-2*Sub261 + Sub262) + 
     2*F1*F24*(2*Abb1 - Pair1*Sub262 - Pair2*Sub262);

  Sub266 = Sub161*(-2*Sub261 + Sub262) + 
     2*F13*F7*(2*Abb1 - Pair1*Sub262 - Pair2*Sub262);

  Sub969 = F1*F24*(-Abb20 - 3*Pair4*Sub262) - 2*MT2*Sub159;

  Sub968 = F15*F2*(-Abb20 - 3*Pair4*Sub262 - 4*MT2*Pair2) - 
     2*MT2*Sub160;

  Sub11627 = 1/MW2*(MW2*Sub11623 + 
       MT*((MT2 + 4*MW2)*((Pair1 + Pair2)*Sub2636) + 
          MB2*(-(Pair1*Sub2636) - Pair2*Sub2636)));

  Sub2643 = (-MB2 + 2*MT2)*Sub2200 + 2*MT2*Sub2640;

  Sub2833 = Sub2710 - MT*(F24*F33) - MT*(F5*F6);

  Sub2832 = Sub2711 + MT*(F2*F3 + F13*F35);

  Sub2777 = -(MB2*(F10*Sub2763)) + 
     MT2*(F10*Sub2763 + MT2*Sub2733);

  Sub1418 = F15*F2*Sub1417 + F19*F20*(S + Sub278);

  Sub2806 = Sub2790 + MT*(F24*F33 + F5*F6);

  Sub2807 = Sub2793 + MT*(F2*F3 + F13*F35);

  Sub2897 = 2*(F25*F5 + F13*F7)*Sub1536 + Pair4*Sub2896;

  Sub2906 = MT2*MT2*(F25*F5 + F13*F7) + MB2*Sub2905;

  Sub3002 = Sub2913 + MT*(-(F24*F33*Sub153) + MZ2*Sub14);

  Sub14126 = (3*F12 - 3*F9)*Sub14125 + Sub153*Sub2917;

  Sub13925 = (3*F12 - 3*F9)*Sub13924 + Sub154*Sub2917;

  Sub2974 = -(Pair4*Sub2973) + 
     MB2*((F15*F2 + F1*F24)*(Abb17 + Pair4*Sub1971));

  Sub2976 = Sub2975 + (-MB2 - MT2 - MW2)*(F25*F5 + F13*F7);

  Sub2977 = Abb17*(F25*F5 + F13*F7) + 
     Pair4*((F25*F5 + F13*F7)*Sub1971 + Sub2976);

  Sub3046 = Sub1114*(Abb31 + Pair2*Sub3043) + MW2*Sub3045;

  Sub3059 = F9*(F45 + 2*Sub1257) + F10*Sub3058;

  Sub3060 = F9*(F46 + 2*Sub1259) + F11*Sub3058;

  Sub3393 = (MB2*MT2)/MW2*(Sub3097 - MT*Sub14061);

  Sub3123 = Sub3122 + MT*(F13*F35 - F5*F6);

  Sub3130 = -2*(F12*Sub1120 + F9*Sub1257) + F10*Sub3129;

  Sub3131 = -2*(F12*Sub1124 + F9*Sub1259) + F11*Sub3129;

  Sub3133 = 2*(F9*Sub1120 + F12*Sub1257) + F10*Sub3132;

  Sub3134 = 2*(F9*Sub1124 + F12*Sub1259) + F11*Sub3132;

  Sub3143 = MT2*(F10*F12*Sub1058) + 
     MB2*(4*F45*F9 - F10*Sub3141);

  Sub3145 = F12*Sub3144 + MB2*(4*F46*F9 - F11*Sub3141);

  Sub3190 = MT2*(F9*Sub3162) + 
     MB2*(F11*Sub3187 - 4*F12*Sub3188);

  Sub3219 = 1/(CW2*MW2)*(-(F10*Sub3218) + 4*CW2*MW2*Sub3216);

  Sub3243 = 6*F15*(Abb2 + Pair1*Sub152) - F32*Sub3241;

  Sub3244 = -6*F7*(Abb2 + Pair1*Sub152) + F36*Sub3241;

  Sub3272 = Sub3271 + MT*(F2*F3 - F13*F35);

  Sub3273 = (F15*F2 + F13*F7)*(Abb31 + Pair2*Sub3043) + 
     MW2*Sub3272;

  Sub3299 = Sub3297 + MT*((-(F24*F33) + F5*F6)*Sub152);

  Sub3324 = (-MB2 - 2*MW2)*Sub3308 + MT2*Sub3309;

  Sub3312 = 1/MW2*((-MB2 - 2*MW2)*Sub3308 + MT2*Sub3309);

  Sub3403 = -(Sub152*Sub3400) + 
     F2*(2*Abb2*F15 + MT*(F3*Sub152));

  Sub3402 = Sub152*Sub3401 + F13*(-2*Abb2*F7 + MT*(F35*Sub152))
   ;

  Sub3422 = 2*Abb33*(F15*F2 + F13*F7) - Sub153*Sub3421;

  Sub3445 = 2*(MB2 + MT2)*(F12*(F45 + F46)) - MB2*Sub3436;

  Sub3446 = 1/MW2*(-Sub3445 + 
       MT2*(-(F12*Sub3444) + 2*MW2*Sub3424));

  Sub3465 = 1/MW2*(MT*(F9*Sub3444) + 2*MW2*Sub3460);

  Sub3467 = (F45 + F46)*Sub3466 + (-MB2 + MW2)*(F9*Sub3461);

  Sub3488 = F12*(F19 + F26 + F29 + F30)*
      (2*(Pair1 + Pair2) - 2*(Pair3 + Pair4)) + (F10 + F11)*Sub3487
    ;

  Sub3511 = (F15*F2 + F13*F7)*(4*Abb34 - 4*Pair2*Sub152) + 
     Sub153*Sub3510;

  Sub3514 = Sub3512 + MT*((-(F2*F3) + F13*F35)*Sub152);

  Sub3515 = Sub3513 + MT*((-(F24*F33) + F5*F6)*Sub152);

  Sub3519 = (MB2 + MT2)*(F12*(F45 + F46) + F45*F9) + 
     MB2*(F46*F9 + (F10 + F11)*Sub1149) + 
     MT2*(F46*F9 + (F10 + F11)*Sub3518);

  Sub3522 = (F10 + F11)*Sub3521 + 
     (F45 + F46)*((-MB2 + MT2 - 2*MW2)*F12 + 
        (MB2 - MT2 + 2*MW2)*F9);

  Sub3557 = (F10 + F11)*Sub1122 - 2*F12*Sub3555 + 2*F9*Sub3556
   ;

  Sub3575 = (F10 + F11)*Sub1254 + 
     (-2*(Pair1 + Pair2) + 2*(Pair3 + Pair4))*Sub3566;

  Sub3576 = 2*Sub3575 + 
     1/MW2*((F10 + F11)*Sub1265 - MB2*Sub3574);

  Sub3645 = 1/CW2*(2*Sub3644 + CW2*((-3*F20 + 3*F21)*Sub1931))
   ;

  Sub3646 = 1/CW2*(2*MT*Sub3641 + CW2*MT2*Sub3645);

  Sub3661 = 1/(CW2*MW2)*
     (CW2*MT*((3*(F37 + F38) - 3*(F39 + F40))*Sub11507) + 
       2*MW2*Sub3660);

  Sub14257 = Sub3677 + MT*(F2*F3 - F13*F35);

  Sub3691 = 4*(F45 + F46)*F9 + (F10 + F11)*Sub3690;

  Sub3693 = 1/MW2*(F12*Sub3692 - 2*MW2*Sub3689 + MB2*Sub3691)
   ;

  Sub3706 = MT2*(Sub3704 + MT*Sub3459) + 
     MT/MW2*((F45 + F46)*Sub3466 + MW2*Sub3705);

  Sub3712 = Sub3711 + MT*((F2*F3 - F13*F35)*Sub153);

  Sub14487 = (F20 + F21)*(F19 + F26 - 2*(F29 + F30)) + 
     2*MT*Sub381;

  Sub2878 = -(2*MT2*((F20 + F21)*(F19 + F26) + Sub2877)) + 
     MT*(Sub262*Sub381);

  Sub3584 = 2*MT2*Sub3583 - 
     MT*((F19 + F26)*Sub1279 + Sub262*Sub381);

  Sub385 = (Sub158 + Sub159 + Sub160 + Sub161)*Sub261 + 
     Sub262*Sub384;

  Sub2918 = Sub153*Sub2917 + (-3*F12 + 3*F9)*Sub207*Sub387;

  Sub2943 = Sub153*Sub2917 + (-6*F12 + 6*F9)*Sub207*Sub387;

  Sub2978 = 1/MW2*(MT*(MB2 + MW2)*Sub2199 + 
       MW2*((F15*F2 + F1*F24)*Sub388));

  Sub11391 = 2*Sub11390 + (-(F1*F4) + F5*F6)*Sub388;

  Sub11394 = 2*Sub11393 + (-(F2*F3) + F7*F8)*Sub388;

  Sub6432 = F2*(Abb81 + (-2*Pair3 + 4*Pair4)*Sub388);

  Sub13657 = (F16 + F17 + F18 + F22)*(F29 + F30) + 
     Sub138*Sub388;

  Sub2506 = 2*Abb11*(F15*F2 + F1*F24) - Sub2505*Sub388;

  Sub2528 = 2*Abb11*(F25*F5 + F13*F7) - Sub2527*Sub388;

  Sub1713 = F20*F29*S + F15*F2*(2*Abb10 - 2*Pair1*Sub388);

  Sub1714 = F21*F30*S + F25*F5*(2*Abb10 - 2*Pair1*Sub388);

  Sub1715 = F20*F30*S + 
     2*F1*F24*(Abb10 - Pair1*Sub388 - Pair2*Sub388);

  Sub1716 = F21*F29*S + 
     2*F13*F7*(Abb10 - Pair1*Sub388 - Pair2*Sub388);

  Sub2292 = F23*Sub2289 - 2*F24*(Abb12 + Pair3*Sub388);

  Sub5773 = (F16 + F17)*F29*(Pair3 - 2*Pair4) + 
     F15*F2*(Abb77 + (Pair3 - 2*Pair4)*Sub388);

  Sub2313 = -(MT2*(Abb14*F25*F5)) - 
     MT2*(F25*F5*Pair4*Sub388) + 
     F12*F26*(MB2*MT*Pair4 + MT*(-(MT2*Pair4) + 2*MW2*Pair4)) + 
     F1*F42*(MB2*MT*Pair4 + MT*(-(MT2*Pair4) + 2*MW2*Pair4));

  Sub1708 = F15*F2*(-2*(Abb13 + Pair3*Sub262) + 
        2*Pair4*Sub388) + MT*(F9*Sub1670 + F7*Sub1671);

  Sub1710 = F1*F24*(-2*(Abb13 + Pair3*Sub262) + 
        2*Pair4*Sub388) + MT*(F9*Sub1668 + F5*Sub1669);

  Sub1676 = F25*F5*(-2*(Abb13 + Pair3*Sub262) + 
        2*Pair4*Sub388) + MT*(-(F1*Sub1666) + F12*Sub1667);

  Sub1707 = Sub1022*(2*(Abb13 + Pair3*Sub262) - 
        2*Pair4*Sub388) + MT*Sub1706;

  Sub1674 = Sub1141*(-2*(Abb13 + Pair3*Sub262) + 
        2*Pair4*Sub388) + MT*Sub1673;

  Sub1801 = F13*(Abb11 + Pair4*Sub388) - MT2*F14;

  Sub2125 = F15*(Abb11 + Pair4*Sub388) + MT2*F27;

  Sub2141 = F20*F29*Sub2140 - 2*F15*F2*(Abb11 + Pair4*Sub388)
   ;

  Sub1757 = F20*F29*Sub388 - 2*F15*F2*(Abb11 + Pair4*Sub388);

  Sub4258 = (F16 + F17)*F29*(Pair3 - Pair4) + 
     F15*F2*(Abb11 + Pair4*Sub388);

  Sub10995 = (F16 + F17)*F29*Pair4 + 
     F15*F2*(Abb11 + Pair4*Sub388);

  Sub2127 = -(Abb11*F24) - F24*Pair4*Sub388 + MT2*F23;

  Sub2142 = F20*F30*Sub2140 - 2*F1*F24*(Abb11 + Pair4*Sub388)
   ;

  Sub1758 = F20*F30*Sub388 - 2*F1*F24*(Abb11 + Pair4*Sub388);

  Sub4265 = (F16 + F17)*F30*(Pair3 - Pair4) + 
     F1*F24*(Abb11 + Pair4*Sub388);

  Sub11000 = (F16 + F17)*F30*Pair4 + 
     F1*F24*(Abb11 + Pair4*Sub388);

  Sub1803 = F25*(Abb11 + Pair4*Sub388) + MT2*F28;

  Sub1759 = F21*F30*Sub388 - 2*F25*F5*(Abb11 + Pair4*Sub388);

  Sub11002 = (F18 + F22)*F30*Pair4 + 
     F25*F5*(Abb11 + Pair4*Sub388);

  Sub1760 = F21*F29*Sub388 - 2*F13*F7*(Abb11 + Pair4*Sub388);

  Sub4262 = (F18 + F22)*F29*(Pair3 - Pair4) + 
     F13*F7*(Abb11 + Pair4*Sub388);

  Sub10998 = (F18 + F22)*F29*Pair4 + 
     F13*F7*(Abb11 + Pair4*Sub388);

  Sub1974 = 3*(Pair1 + Pair2)*Sub262 - 2*(Abb22 + Pair4*Sub388)
   ;

  Sub11869 = (F16 + F17)*F29*(Pair1 + Pair2 + Pair4) + 
     F15*F2*(Abb56 + Pair4*Sub388);

  Sub11874 = (F18 + F22)*F30*(Pair1 + Pair2 + Pair4) + 
     F25*F5*(Abb56 + Pair4*Sub388);

  Sub13260 = 1/MW2*(2*(Sub13120*Sub3989 + Sub13258*Sub4027) + 
       MW2*(Sub13118*Sub3848));

  Sub13476 = 2*(Abb97*F15*F2 + Sub13475) + 
     F10*(-(F17*Sub152) - F16*Sub4049);

  Sub13479 = 2*(Abb97*F1*F24 + Sub13478) + 
     F11*(-(F17*Sub152) - F16*Sub4049);

  Sub13482 = 2*(Abb97*F13*F7 + Sub13481) + 
     F10*(-(F18*Sub152) - F22*Sub4049);

  Sub13485 = 2*(Abb97*F25*F5 + Sub13484) + 
     F11*(-(F18*Sub152) - F22*Sub4049);

  Sub13428 = -2*(Abb87*F15*F2 + Sub13427) + 
     F10*(F16*Sub387 - F17*Sub4058);

  Sub13430 = -2*(Abb87*F1*F24 + Sub13429) + 
     F11*(F16*Sub387 - F17*Sub4058);

  Sub13435 = 2*(Abb87*F13*F7 + Sub13434) + 
     F10*(-(F22*Sub387) + F18*Sub4058);

  Sub13432 = 2*(Abb87*F25*F5 + Sub13431) + 
     F11*(-(F22*Sub387) + F18*Sub4058);

  Sub3280 = -(F11*F17*Sub407) + F24*(Sub3277 + MT*(F33*Sub152))
   ;

  Sub3268 = -(F10*F18*Sub407) + F13*(Sub3267 + MT*(F35*Sub152))
   ;

  Sub3344 = Sub152*Sub2917 + (-3*F12 + 3*F9)*Sub207*Sub407;

  Sub1119 = 1/(CW2*MW2)*
     (8*MW2*Sub166 + CW2*MT*((-3*F12 + 3*F9)*Sub248*Sub407));

  Sub3252 = -2*F15*F2*(Abb23 + Pair2*Sub152) + 
     F10*F17*(Sub152 + Sub407);

  Sub3253 = -2*F13*F7*(Abb23 + Pair2*Sub152) + 
     F10*F18*(Sub152 + Sub407);

  Sub1054 = -(F11*F18*Sub152) + 
     2*(Abb23*Sub138 + Pair2*Sub138*Sub152) - F11*F18*Sub407 + 
     F17*(-(F11*Sub152) - F11*Sub407) + 
     F10*(-(F18*Sub152) + F17*(-Sub152 - Sub407) - F18*Sub407);

  Sub13734 = 2*Sub13733 + F10*(F16*Sub153 + F17*Sub407);

  Sub13736 = 2*Sub13735 + F11*(F16*Sub153 + F17*Sub407);

  Sub13740 = 2*Sub13739 + F10*(F22*Sub153 + F18*Sub407);

  Sub13738 = 2*Sub13737 + F11*(F22*Sub153 + F18*Sub407);

  Sub4077 = F10*(F17 + F18)*Sub153 - 
     2*(F15*F2 + F13*F7)*Sub4076;

  Sub4086 = F10*(F17*Sub153 + F18*Sub153) - F15*F2*Sub4085 - 
     F13*F7*Sub4085;

  Sub14305 = -2*(Abb91*F15*F2 + Sub14304) + 
     F10*(2*F16*Sub153 - F17*Sub4092);

  Sub14307 = -2*(Abb91*F13*F7 + Sub14306) + 
     F10*(2*F22*Sub153 - F18*Sub4092);

  Sub12349 = (Pair1 + Pair2)*(Sub12238*Sub37 - Sub12267*Sub41)
   ;

  Sub3698 = Sub3697*Sub37 + 
     Sub41*(3*MT2*Sub1023 - 4*MT*Sub1045);

  Sub3349 = Sub3310*Sub37 - Sub3311*Sub41 + 
     MT*(-(Sub3308*Sub37) + Sub3309*Sub41);

  Sub15315 = Sub14491*Sub15313 + 
     (F29 + F30)*Pair4*Sub15314*(F9*Sub37 + F12*Sub41);

  Sub4103 = (F15*F2 + F13*F7)*(2*Abb93 - 2*Pair1*Sub4101) + 
     F10*(F17 + F18)*Sub4102;

  Sub4724 = MB2*((F16 + F17)*(F19 + F29)) + 
     MT*(-MB2 + MT2)*Sub4110;

  Sub4150 = (2*F12*F30 - 2*F44*F5)*(Pair1 + Pair2) + F5*Sub4149
   ;

  Sub4152 = (2*F12*F29 - 2*F41*F7)*(Pair1 + Pair2) + F7*Sub4151
   ;

  Sub6728 = -Sub4156 + (-2*MT2 + MZ2)*(F28*F5);

  Sub7644 = F5*(F28*(-MH2 + 2*MT2) + 
        F25*(-2*MH2 + 4*MT2)*Pair1) + Sub4156;

  Sub7649 = F14*F7*(-MH2 + 2*MT2) - Sub4160;

  Sub4204 = Sub4160 + (-MB2 - MT2 + MW2)*(F14*F7);

  Sub7500 = (F26 + F30)*
      (F12*(Pair3 - Pair4) + F9*(-Pair3 + Pair4)) + Pair4*Sub4235;

    

  Sub4284 = Sub4245 + (-MB2 + MT2 + MW2)*(F1*F4) + 
     (MB2 - MT2 - MW2)*(F5*F6);

  Sub4283 = Sub4249 + (-MB2 + MT2 + MW2)*(F2*F3) + 
     (MB2 - MT2 - MW2)*(F7*F8);

  Sub4259 = F15*F2*(2*Pair1 - 2*Pair4) - Sub4256;

  Sub4300 = Sub4273 + (-MB2 + MW2)*(F19*F20) + 
     (MB2 - MW2)*(F2*F27);

  Sub6813 = Sub4273 + (-MT2 + MZ2)*(F19*F20) + 
     (MT2 - MZ2)*(F2*F27);

  Sub4301 = 1/MW2*(MT2*MT2*Sub4223 - 2*MW2*Sub4300);

  Sub4317 = F15*Sub4316 + MT2*(-F27 + 2*F15*Pair3);

  Sub4318 = F2*Sub4317 + MT2*(F20*(-F19 + F29));

  Sub6951 = -Sub4318 + 
     F15*F2*(MT2*(-Pair1 - Pair2) + 2*MZ2*(Pair1 + Pair2));

  Sub4327 = F1*(F24*(Abb50 + Sub4326) + MT2*F23) + 
     MT2*(F20*(-F26 + F30));

  Sub6935 = -Sub4327 + 
     F1*F24*(MT2*(-Pair1 - Pair2) + 2*MZ2*(Pair1 + Pair2));

  Sub13661 = -2*F15*F2*(Abb97 + Sub13660) + F10*F17*Sub435;

  Sub13662 = 2*F1*F24*(Abb97 + Sub13660) - F11*F17*Sub435;

  Sub3259 = 2*F1*F24*(Abb23 + Pair2*Sub152) - F11*F17*Sub435;

  Sub13664 = -2*F13*F7*(Abb97 + Sub13660) + F10*F18*Sub435;

  Sub13663 = -2*F25*F5*(Abb97 + Sub13660) + F11*F18*Sub435;

  Sub3260 = -2*F25*F5*(Abb23 + Pair2*Sub152) + F11*F18*Sub435
   ;

  Sub14536 = -2*(F15*F2 + F13*F7)*(Abb97 + Sub13660) + 
     F10*(F17 + F18)*Sub435;

  Sub3498 = -2*(F15*F2 + F13*F7)*(Abb23 + Pair2*Sub152) + 
     F10*(F17 + F18)*Sub435;

  Sub14535 = -2*(F1*F24 + F25*F5)*(Abb97 + Sub13660) + 
     F11*(F17 + F18)*Sub435;

  Sub3499 = -2*(F1*F24 + F25*F5)*(Abb23 + Pair2*Sub152) + 
     F11*(F17 + F18)*Sub435;

  Sub10863 = 2*F15*F2*(Abb13 + Sub10862) + F20*F29*Sub435;

  Sub10864 = 2*F1*F24*(Abb13 + Sub10862) + F20*F30*Sub435;

  Sub12862 = 2*(F15*F2 + F1*F24)*(Abb13 + Sub10862) + 
     F20*(F29 + F30)*Sub435;

  Sub440 = -2*S*Sub1559 + F19*F21*(Sub262 + Sub438);

  Sub4409 = (MB2 + MT2)*F39 + MT2*F40 + MB2*(F40 + 2*Sub4393)
   ;

  Sub442 = -2*S*Sub1278 + F20*F26*(Sub262 + Sub438);

  Sub4449 = MT*Sub4442 + MT2*(Sub4427 + MT*(F10*(F12 + F9)));

  Sub5193 = Pair4*Sub4467 + 
     MT*(-(Pair3*Sub1483) - Pair4*Sub1483);

  Sub4471 = 5*F10*(F16 + F17 + F18 + F22) + 4*Sub4470;

  Sub4480 = Pair3*Sub4479 + F2*(F15*Pair4*Sub388 + MT2*F27);

  Sub3761 = (F19 + F26)*(F37 + F38 - 2*F9*(Pair1 + Pair2)) - 
     2*MT2*Sub450;

  Sub4547 = (F16 + F17)*F19*(Pair1 + Pair2) + F15*F2*Sub4546;

  Sub4561 = F12*F29*(Pair3 + 2*Pair4) + Pair4*Sub4560;

  Sub4564 = F12*F30*(Pair3 + 2*Pair4) + Pair4*Sub4563;

  Sub12833 = F12*(F29 + F30)*(Pair3 + 2*Pair4) + 
     Pair4*(Sub4560 + Sub4563);

  Sub4579 = MT2/MW2*(Sub4556 + MT*Sub4573);

  Sub5538 = F20*F29*Sub435 + F15*F2*(2*Abb39 - 2*Pair4*Sub4578)
   ;

  Sub5539 = F20*F30*Sub435 + F1*F24*(2*Abb39 - 2*Pair4*Sub4578)
   ;

  Sub5610 = F20*(F29 + F30)*Sub435 + 
     (F15*F2 + F1*F24)*(2*Abb39 - 2*Pair4*Sub4578);

  Sub5324 = F21*F30*Sub435 + F25*F5*(2*Abb39 - 2*Pair4*Sub4578)
   ;

  Sub5323 = F21*F29*Sub435 + F13*F7*(2*Abb39 - 2*Pair4*Sub4578)
   ;

  Sub5611 = F21*(F29 + F30)*Sub435 + 
     (F25*F5 + F13*F7)*(2*Abb39 - 2*Pair4*Sub4578);

  Sub4599 = F12*F19*(2*Pair3 + 3*Pair4) + Pair4*Sub4597;

  Sub4603 = F12*F26*(2*Pair3 + 3*Pair4) + Pair4*Sub4601;

  Sub4607 = F26*F9*(2*Pair3 + 3*Pair4) + Pair4*Sub4605;

  Sub11366 = (F41*F7 + F29*F9)*(Pair3 + 2*Pair4) + 
     Pair4*Sub4609;

  Sub11243 = -(F18*Sub4635) - F22*Sub4635 + 
     MT*(Pair3*Sub11242 + Pair4*Sub11242);

  Sub4677 = -Sub4659 + MT2/CW2*(F10*(F12 + CW2*(F12 - 2*F9)))
   ;

  Sub4720 = -(F25*F5*Sub4718) + 2*F1*F24*Sub4719;

  Sub5639 = 1/MW2*(MT2*(-2*F2*F3 + F7*F8) - 2*MW2*Sub4733);

  Sub11730 = MT*MT2*Sub11714 + MB2*(Sub4783 + MT*Sub11713);

  Sub11729 = MB2*Sub4785 + MT2*(Sub4788 - MT*Sub11712);

  Sub4810 = Pair4*(2*MT2 - 2*S + Sub388) - Sub4809;

  Sub4887 = MT2*(F10*(-2*F12 + F9)) + 2*(Sub4876 + MB2*Sub4886)
   ;

  Sub4925 = 1/MW2*(2*MT2*Sub4900 - MW2*Sub4910);

  Sub4998 = 1/(CW2*MW2)*
     (F12*F19*Pair4*Sub3859 + CW2*MW2*Sub4985);

  Sub5022 = -Sub5018 + MB2*(F10*F12 - F2*F3);

  Sub5024 = Sub5021 + MB2*(-(F11*F12) + F1*F4);

  Sub5876 = F10*(2*MT2 - S) + 4*F19*Sub5052;

  Sub5879 = F11*(-2*MT2 + S) - 4*F26*Sub5052;

  Sub11288 = (-F26 - 2*F30)*Pair4 + F30*Sub5052;

  Sub5094 = Sub5070 + MT*(F10*(-F12 - 2*F9));

  Sub5208 = 1/MW2*(2*Pair1*(F15*F2*Sub3989 + F25*F5*Sub4027) - 
       MW2*(Sub3848*Sub5131));

  Sub5217 = 1/MW2*((-2*Pair1 + 2*Pair3)*
        (F15*F2*Sub3989 + F25*F5*Sub4027) + MW2*(Sub3848*Sub5162));

    

  Sub14532 = F20*(-F19 - F26 + F29 + F30) + MT*Sub5176;

  Sub5189 = 1/MW2*(Pair4*Sub5188 + 
       MT*((-MB2 + MT2)*MW2 + MW2*MW2)*Sub5176);

  Sub5191 = 1/MW2*(2*Pair4*Sub5190 - MW2*Sub5179);

  Sub5276 = (F10 + F11)*(F12 + F9) - 2*Sub523;

  Sub9584 = (F20 + F21)*(F29 + F30) + 2*MT*Sub523;

  Sub3805 = (F2*F3 + F1*F4)*Sub1958 - MT2*Sub523;

  Sub11602 = F12*(F19*Pair3 + F29*Pair4) + MT2*Sub523;

  Sub13700 = 2*Sub13684 + (-2*MT2 + MZ2)*Sub523;

  Sub2654 = (F29 + F30)*(F37 + F38 + F39 + F40) - Sub388*Sub523
   ;

  Sub3828 = MT2*Sub3827 + MT*(Sub3826 + MT2*Sub523);

  Sub5262 = (-2*MT2 + MZ2)*Sub148 + MT*Sub5241;

  Sub5271 = (Pair1 + Pair2)*
      (-(Sub1577*Sub37) + Sub1579*Sub41) + 3*Pair4*Sub5270;

  Sub12914 = (F20 + F21)*(F19 + F26) + MT*Sub5276;

  Sub5278 = (F10 + F11)*(F16 + F17 + F18 + F22) - 2*Sub5277;

  Sub13581 = (F1*F24 + F13*F7)*MH2*Pair4 + MT2*Sub5279;

  Sub5301 = (-MT2 + MZ2)*Sub147 + MT*Sub5289;

  Sub5311 = Sub5292 + (-MT2 + MZ2)*((F10 + F11)*(F12 + F9));

  Sub5302 = Sub5301 + MT*(2*MT2 - MZ2)*Sub523;

  Sub12864 = 1/MW2*(-(2*MW2*Sub12861) + 
       MB2*((F19 + F26 + F29 + F30)*Sub5351));

  Sub546 = 2*Abb2*Sub138 - Sub152*Sub545 - MT*(Sub14061*Sub152)
   ;

  Sub5455 = Sub5450 + MT*(F11*F12 - F1*F4);

  Sub5458 = MB2*MT*(-(F7*F8) + F10*F9) - MT2*Sub5452;

  Sub5459 = Sub5453 + MT*(-(F10*F12) + F2*F3);

  Sub5461 = MB2*MT*(F5*F6 - F11*F9) + MT2*Sub5454;

  Sub5472 = 1/MW2*(-(2*MW2*Sub4700) + MT2*Sub5463 - 
       MB2*Sub5706);

  Sub5475 = MB2*MT*Sub5709 + MT2*(Sub5468 - MT*Sub5466);

  Sub5552 = 2*Sub5538 + MT*MZ2*(F7*F8 - F10*F9);

  Sub1178 = -2*F11*F18 + 2*F31*F5 + MT*Sub560;

  Sub5662 = -(12*MW2*Sub5648) + MB2*(Sub5646 + 2*Sub5648);

  Sub13704 = Sub5656 + (-MT2 + MZ2)*(F20*(F29 + F30));

  Sub5666 = 1/MW2*((-(MB2*MW2) + MW2*MW2)*Sub450 + MT2*Sub5658)
   ;

  Sub5707 = (F2*F43 + F41*F7)*Pair4 + F29*Sub5705;

  Sub5710 = (F1*F42 + F44*F5)*Pair4 + F30*Sub5705;

  Sub5747 = F16*(F29*(Pair1 + Pair2) + F19*Pair4) + MT2*Sub5746
   ;

  Sub5749 = (F16 + F22)*(F29 + F30)*Pair3 + MT2*Sub5748;

  Sub5778 = (-F27 + 2*F15*Pair2)*Sub5769 - 2*F15*Sub5777;

  Sub5782 = F11*(F12 - F9)*Sub1765 - 2*Sub5781;

  Sub5785 = F10*(F12 - F9)*Sub1765 - 2*Sub5784;

  Sub583 = -Sub582 + MT*(F2*F3 - F13*F35);

  Sub590 = 2*Abb2*(F15*F2 + F13*F7) - Sub152*Sub582;

  Sub584 = 2*Abb2*(F15*F2 + F13*F7) + Sub152*Sub583;

  Sub589 = 2*Abb2*(F1*F24 + F25*F5) - Sub152*Sub588;

  Sub592 = Sub589 + MT*((-(F24*F33) + F5*F6)*Sub152);

  Sub591 = Sub590 + MT*((F2*F3 - F13*F35)*Sub152);

  Sub5919 = 1/CW2*(2*Pair1*Sub5916 - 9*CW2*MT2*Sub5918);

  Sub5922 = 1/(CW2*MW2)*(CW2*Sub5919 + MW2*Sub5921);

  Sub5953 = 1/(CW2*MW2)*
     (4*MW2*(Pair4*Sub1683) - 3*CW2*MT*(Sub11507*Sub5952));

  Sub5965 = Sub5955 + MT*(F10*(-2*F9 + F12*Sub5964));

  Sub5981 = (F1*F42 + F41*F7)*Pair2 + Pair1*Sub5980;

  Sub6019 = Sub6012 + MT*(F10*(2*F12 - F9*Sub5964));

  Sub6015 = Sub6013 + MT*(F11*(2*F12 - 3*F9));

  Sub6138 = Sub6069 + MZ2*(F1*F4 - F5*F6);

  Sub6130 = (-MT2 + MZ2)*(F19*F21) + MT*Sub6076;

  Sub7859 = (-2*MB2 + 2*MW2)*F30 + MT2*Sub6108;

  Sub6109 = MT2*(-2*MT2 + 2*MZ2)*F30 + MT2*MT2*Sub6108;

  Sub3573 = 2*Abb2*Sub138 - Sub152*Sub612 - 
     MT*(Sub14061*Sub152);

  Sub3233 = (-MT2 + MW2)*Sub3122 + MB2*(-Sub3122 + 2*Sub612);

  Sub620 = 4*Abb3*(F15*F2 + F13*F7) - Sub153*Sub619;

  Sub6232 = (F16 + F17)*F29*Pair3 - F15*F2*Sub6231;

  Sub6235 = (F16 + F17)*(F30*Pair3 - F26*Pair4) - 
     F1*F24*Sub6231;

  Sub6236 = (F18 + F22)*(F30*Pair3 - F26*Pair4) - 
     F25*F5*Sub6231;

  Sub6238 = (F18 + F22)*F29*Pair3 - F13*F7*Sub6231;

  Sub8124 = 2*Sub6236 + F21*(Sub6234 + (-MB2 + MW2)*F26);

  Sub6264 = 2*Sub6236 + F21*(Sub6234 + (-MT2 + MZ2)*F26);

  Sub8113 = (-2*MB2 + 2*MW2)*F26 + MT2*Sub6240;

  Sub6241 = MT2*(-2*MT2 + 2*MZ2)*F26 + MT2*MT2*Sub6240;

  Sub6309 = -2*(F15*F2 + F25*F5)*(Pair1 + Pair2) + Sub6305;

  Sub6366 = (-MT2 + MZ2)*(F20*F29) + MT2*Sub6318;

  Sub6369 = MT2*Sub6322 + 
     MT*((-MT2 + MZ2)*(F10*F12) + (MT2 - MZ2)*(F2*F3));

  Sub6370 = Sub6325 + MT2*(F10*F12 - 3*F2*F3);

  Sub6378 = Sub6327 + MT2*(-3*F7*F8 + F10*F9);

  Sub6372 = Sub6328 + (-MT2 + MZ2)*(F11*F12) + 
     (MT2 - MZ2)*(F1*F4);

  Sub6338 = F29*(F39 + F40 + F12*Pair4) + F2*Sub6337;

  Sub6340 = F30*(F39 + F40 + F12*Pair4) + F1*Sub6339;

  Sub6342 = F30*(F37 + F38 + F9*Pair4) + F5*Sub6341;

  Sub6344 = F29*(F37 + F38 + F9*Pair4) + F7*Sub6343;

  Sub6379 = Sub6378 + (-MT2 + MZ2)*(F7*F8) + 
     (MT2 - MZ2)*(F10*F9);

  Sub6406 = (Pair1 + Pair2)*Sub6405 + 
     (F1*F24 + F13*F7)*(Abb156 + MT2*(Pair1 + Pair2));

  Sub6424 = F19*(-2*(F37 + F38) + Sub6415) + 
     F29*(F39 + F40 - 2*Sub6416);

  Sub6418 = F26*(-2*(F37 + F38) + Sub6415) + 
     F30*(F39 + F40 - 2*Sub6416);

  Sub6471 = Abb69*F13*F7 + (-Pair3 - 2*Pair4)*Sub6470;

  Sub6474 = Abb69*F25*F5 + (-Pair3 - 2*Pair4)*Sub6473;

  Sub6483 = F27*Sub6480 + 2*F15*(Abb78 + Pair1*Sub6480);

  Sub6487 = F23*Sub6480 - 
     2*F24*(Abb78 + (Pair1 + Pair2)*Sub6480);

  Sub6512 = -2*F15*Sub6511 + MT2*(-F32 - 10*F15*Pair2);

  Sub6515 = 2*F25*Sub6511 + MT2*(F31 + 10*F25*Pair2);

  Sub7483 = (-MH2 + MT2)*Sub6558 + MT2*Sub6559;

  Sub7490 = (-MH2 + MT2)*Sub6561 + MT2*Sub6562;

  Sub6649 = MZ2*(F21*(F26 + F30) + F28*F5) + MT2*Sub6570;

  Sub6653 = -Sub6582 + (-MT2 + MZ2)*(F10*F9);

  Sub714 = 1/CW2*(8*MW2*Sub166 + 
       CW2*MT*((3*F12 - 3*F9)*Sub152*Sub660));

  Sub661 = 1/CW2*(8*MW2*Sub459 + 
       CW2*MT*((-3*F12 + 3*F9)*Sub153*Sub660));

  Sub6638 = F13*F7*(3*Pair4*Sub3879 + 
        (Pair1 + Pair2)*Sub3893) + F15*F2*Sub6637;

  Sub6691 = F26*(F12*(-Pair3 - Pair4) + F9*Pair4) - 
     Pair3*Sub6686;

  Sub6687 = F26*(-(F9*Pair4) + F12*(Pair3 + Pair4)) + 
     Pair3*Sub6686;

  Sub6690 = F19*(-(F9*Pair4) + F12*(Pair3 + Pair4)) - 
     Pair3*Sub6688;

  Sub6689 = F19*(F12*(-Pair3 - Pair4) + F9*Pair4) + 
     Pair3*Sub6688;

  Sub6700 = -2*F29*F9*(Pair1 + Pair2) + 
     F2*(2*F43*(Pair1 + Pair2) + Sub6699);

  Sub6702 = -2*F30*F9*(Pair1 + Pair2) + 
     F1*(2*F42*(Pair1 + Pair2) + Sub6701);

  Sub6792 = -(F14*Sub6791) + F13*(2*Abb43 + 8*MT2*Pair4);

  Sub6945 = -Sub6897 + (-MT2 + MZ2)*(F10*F12);

  Sub6912 = F5*(F25*(Abb50 + Sub6911) - MT2*F28) + 
     MT2*(F21*(-F26 + F30));

  Sub7050 = MW2*(F2*F27 + F20*(F19 + F29)) + MT2*Sub7032;

  Sub7051 = MW2*(-(F1*F23) + F20*(F26 + F30)) + MT2*Sub7034;

  Sub7058 = F1*F24*(Pair1 + Pair2)*Sub3937 + F25*F5*Sub7057;

  Sub2556 = (MT2 + 2*MW2)*Sub2552 + MB2*(-Sub2552 + 2*Sub708)
   ;

  Sub2708 = MT2*Sub2689 + (MB2 + 2*MW2)*Sub708;

  Sub7119 = -2*F13*F7*(Pair1 + Pair2) + MT*Sub7084;

  Sub7163 = -Sub7156 + MZ2*(F5*F6 + F7*F8);

  Sub7185 = F19*(-F37 - F38 + F39 + F40) - F29*Sub7184;

  Sub7186 = F26*(-F37 - F38 + F39 + F40) - F30*Sub7184;

  Sub7225 = -2*F21*F29 + 4*F13*F7*Pair4 + Sub7215;

  Sub7228 = 2*F21*F30 - 4*F25*F5*Pair4 + Sub7216;

  Sub7256 = (-6*F1*F24 + 6*F25*F5)*(Pair3 + Pair4) + Sub7255;

  Sub7985 = F41*(F36 - 2*F7*Pair3) - F19*Sub7273;

  Sub7807 = F19*(Pair2 - Pair3 - Pair4) - F29*Sub7334;

  Sub1453 = Sub734 + MT*(-(F2*F3) + F13*F35);

  Sub3296 = 2*Abb2*(F15*F2 + F13*F7) - Sub152*Sub734;

  Sub3124 = Sub735 + MT*(-(F2*F3) + F24*F33);

  Sub7459 = F21*Sub7457 + F5*(-2*Abb159*F25 + Sub7458);

  Sub14256 = Sub7586 + MT*(-(F24*F33) + F5*F6);

  Sub15337 = Pair3*Sub1441*Sub15298*Sub7631 + 
     Pair4*Sub15299*Sub1782*Sub7632;

  Sub7641 = F1*F23*(-MH2 + 2*MT2) + MT*(F5*Sub7635 - 2*Sub7636)
   ;

  Sub7670 = MT2*Sub5611 + MB2*(Sub5610 + MT*Sub7664);

  Sub7671 = MT2*(2*Sub7665 - MT2*Sub2200 - MW2*Sub2200) + 
     MB2*((-MB2 + MW2)*Sub450 + MT2*(Sub2200 + Sub450));

  Sub7668 = 1/MW2*(MT*((-MB2 + MT2)*MW2 + MW2*MW2)*
        (F5*F6 + F7*F8) + MT2*Sub7667);

  Sub7689 = F12*Sub7687 + 2*(F26*Sub7092 + Sub7688);

  Sub7789 = 1/MW2*(-2*Pair4*Sub7788 + (MB2 + MT2)*MW2*F20);

  Sub7864 = MT2*(Sub7842 - Sub7844) + MB2*Sub7844;

  Sub7866 = -(MB2*Sub7845) + MT2*(Sub7843 + Sub7845);

  Sub7869 = Sub7852 + (MB2 - MT2 - MW2)*(F2*F3) + 
     (-MB2 + MT2 + MW2)*(F7*F8);

  Sub7870 = Sub7858 + (-MB2 + MT2 + MW2)*(F1*F4) + 
     (MB2 - MT2 - MW2)*(F5*F6);

  Sub7946 = -Sub7939 + MT2*(F19*F21 + F13*F36);

  Sub7948 = Sub7940 + MT2*(F20*F26 + F24*F34);

  Sub12643 = 1/CW2*(-2*(Sub11550*Sub797 + Sub11591*Sub798) + 
       9*CW2*MT2*Sub12642);

  Sub3373 = MZ2*(-(Sub3308*Sub37) + Sub3309*Sub41) + 
     MT2*(Sub3308*Sub37 - Sub3309*Sub41 + Sub3364*Sub797 - 
        Sub3365*Sub798);

  Sub12690 = 1/CW2*(-2*(Sub2163*Sub797 + Sub416*Sub798) + 
       9*CW2*MT2*Sub148);

  Sub8065 = F1*(F23*Sub8063 + F24*(Abb79 + Sub8064)) - 
     F20*(-(F30*Sub8062) + 2*MT2*F26);

  Sub8069 = 1/MW2*(2*MT2*(Pair4*Sub8067) + 
       MT*(-4*Pair4*Sub8068 + 3*MW2*(F9*Sub248)));

  Sub8125 = Sub8124 + (-2*(MB2 + MT2) + 2*MW2)*(F25*F5*Pair4)
   ;

  Sub4920 = (F16 + F17)*F29*Pair4*Sub3944 + 
     F15*F2*Sub4898*Sub814;

  Sub4923 = (F16 + F17)*F30*Pair4*Sub3944 + 
     F1*F24*Sub4898*Sub814;

  Sub8181 = -4*F21*F29 + 8*F13*F7*Pair4 + Sub8154;

  Sub8168 = Sub8155 + MT*(-3*F7*F8 + F10*F9);

  Sub8166 = Sub8157 + MT*(-3*F5*F6 + F11*F9);

  Sub8176 = MT*(MB2 + MT2)*(F30*(F39 + F40)) + MT2*MT2*Sub8158
   ;

  Sub8165 = Sub8159 + (MB2 - MW2)*(F7*F8) + 
     (-MB2 + MW2)*(F10*F9);

  Sub8179 = -2*Sub8161 + (-MB2 - MT2 + MW2)*F3;

  Sub8174 = -2*Sub8162 + (-MB2 - MT2 + MW2)*F4;

  Sub8169 = (-MB2 + MW2)*(F20*F29) + MT2*Sub8168;

  Sub8177 = Sub8176 + MT2*MT2*(4*F21*F30 - 8*F25*F5*Pair4);

  Sub6163 = (F16 + F17)*(F19 + F29)*Sub809 + 
     MT*(Sub4110*Sub821);

  Sub6162 = (F16 + F17)*(F26 + F30)*Sub809 + 
     MT*(Sub4116*Sub821);

  Sub8237 = 2*F15*Sub8236 + MT2*(-F27 - 2*F15*Pair2);

  Sub8240 = 2*F25*Sub8236 + MT2*(-F28 - 2*F25*Pair2);

  Sub8315 = Sub8311 + MT*(2*F12*F26*Pair1 - 2*F1*F42*Pair2);

  Sub9585 = (F27 - F32)*Sub152 + 2*F15*Sub8321;

  Sub9638 = (F28 - F31)*Sub152 + 2*F25*Sub8321;

  Sub8322 = Sub152*Sub8320 + 4*(F15*F2 + F25*F5)*Sub8321;

  Sub8328 = (Abb115 - 2*Abb139 - Pair2*Sub4039)*Sub426 - 
     2*Sub8326*Sub8327;

  Sub8376 = Sub8338 + MT*(F34*F42 + F26*Sub7273);

  Sub8349 = 4*Sub8326*Sub8347 + 
     (Abb115 - 2*Abb139 - Pair2*Sub4039)*Sub8348;

  Sub8399 = F1*Sub8398 + MT2*(F20*F26 + F24*F34);

  Sub1473 = MT2*Sub1472 - 
     MT*((-F37 - F38 + F9*(2*Pair1 + 2*Pair2))*Sub840);

  Sub8404 = -(F19*F20*Sub387) + 2*F15*F2*Sub8403;

  Sub11354 = (F19 + F29)*Sub11353 + 
     (-2*F13*F7*Sub11340 - F21*Sub11342)*Sub842;

  Sub1407 = 1/MW2*(-(Sub35*Sub832) + Sub1387*Sub843 - 
       6*MT*MW2*Sub1406);

  Sub8500 = Sub8494 + MT*(F7*F8 - F10*F9);

  Sub8504 = F12*Sub1162 + F2*(F49 + F3*Sub8502);

  Sub8503 = F9*Sub1163 + F5*(F47 + F6*Sub8502);

  Sub10383 = Sub10382 + 
     2*F15*(Abb150 + (Pair1 - Pair4)*Sub8525);

  Sub10387 = Sub10386 + 
     2*F25*(Abb150 + (Pair1 - Pair4)*Sub8525);

  Sub8528 = F2*(4*Abb148*F15 - 2*Sub8526) + 
     F17*(F45 - F10*Sub8527);

  Sub8532 = Sub8528 + 2*F2*(MT2*F27 + MT*Sub8523);

  Sub8584 = F12*Sub1145 - 2*(F2*F3*Sub8433 + F13*F35*Sub8577)
   ;

  Sub10914 = Sub10851*Sub842 + 
     MT2*((9*F20 - 9*F21)*(F26 + F30)*Sub858);

  Sub6803 = (Pair1 + Pair2)*Sub3948*Sub4221 + 
     (Pair3 - Pair4)*Sub4110*Sub858;

  Sub6804 = (Pair1 + Pair2)*Sub3948*Sub4225 + 
     (-Pair3 + Pair4)*Sub4116*Sub858;

  Sub8590 = F18*Sub8575 + F5*(Sub8576 + MT*Sub8589);

  Sub4275 = (Pair1 + Pair2)*Sub3949*Sub4221 + 
     (Pair3 - Pair4)*Sub4110*Sub860;

  Sub8614 = F9*(Pair1 + Pair2 - Pair3 - Pair4) - F12*Sub8613;

  Sub8616 = F12*(Pair1 + Pair2 - Pair3 - Pair4) - F9*Sub8613;

  Sub2570 = 1/MW2*((F15*F2 + F1*F24)*Pair3*Sub875 + 
       (-(MB2*MW2) + MW2*MW2)*Sub708);

  Sub3617 = 1/CW2*(4*F45*(F9*Sub876 + F12*Sub877) + 
       CW2*(F10*Sub3616));

  Sub8885 = (F29 + F30)*(F38 + F40) + 2*Sub8774;

  Sub7426 = -4*(F16 + F17)*Pair4*Sub879 + MT*Sub7425;

  Sub2784 = Sub723*Sub878 + 
     MT*(-2*Sub2741*Sub814 + Sub1414*Sub879);

  Sub8822 = F17*Sub8796 + F2*(2*Abb141*F15 - Sub8797);

  Sub8864 = -Sub8822 + MT*(F2*(F49 - F3*Sub8798));

  Sub8832 = -Sub8829 + MT*(F47 - F6*Sub8798);

  Sub8914 = MT*Sub8913 + MT2*(F28 + MT*F6);

  Sub8134 = Sub6044*Sub860 + 
     Sub901*((-MB2 - MT2 + MW2)*(F1*F4) + 
        (MB2 + MT2 - MW2)*(F5*F6));

  Sub7420 = 2*F1*F24*Sub4812*Sub814 + 
     F30*(Sub4811*Sub814 + 
        MT*(F9*(Pair1 + Pair2)*Sub901 + 
           F12*(-(Pair1*Sub901) - Pair2*Sub901)));

  Sub12428 = Sub6044*Sub860 + (F1*F4 - F5*F6)*S*Sub901;

  Sub2730 = 4*Sub512*Sub903 - Sub719*Sub904 + 
     MT*(4*Sub16*Sub903 + Sub14*Sub904);

  Sub4844 = 2*F25*F5*Sub4814*Sub842 + 
     F30*(Sub4813*Sub842 + 4*(F18 + F22)*Pair4*Sub906);

  Sub3420 = -(Sub3311*Sub913) + Sub3310*Sub915 + 
     MT*(Sub3309*Sub913 - Sub3308*Sub915);

  Sub9177 = F10*(F53 + F12*Sub1749) + F2*Sub9176;

  Sub9179 = F11*(F55 + F9*Sub1749) + F5*Sub9178;

  Sub9182 = MT2*Sub9158 + MT*(-(F26*Sub7933) - 2*Sub9179);

  Sub9205 = 3*F20*F29 + F2*(F27 - 2*(F32 + F15*Sub9204));

  Sub10828 = 2*F1*Sub10827 + F11*(-(F16*Sub921) - F17*Sub921)
   ;

  Sub11252 = 2*Abb55*F1*F24 + (F11*(F16 + F17) + F1*F23)*Sub921
   ;

  Sub11253 = 2*Abb55*F15*F2 + (F10*(F16 + F17) - F2*F27)*Sub921
   ;

  Sub11254 = 2*Abb55*F25*F5 + (F11*(F18 + F22) - F28*F5)*Sub921
   ;

  Sub11255 = 2*Abb55*F13*F7 + (F10*(F18 + F22) + F14*F7)*Sub921
   ;

  Sub4903 = -2*(F29*Sub4901 + F7*Sub4902) + F10*F9*Sub921;

  Sub4905 = -2*(F30*Sub4901 + F5*Sub4904) + F11*F9*Sub921;

  Sub11258 = Sub11257*Sub921 - 6*MT*((Pair1 + Pair2)*Sub10829)
   ;

  Sub12647 = Sub12646*Sub921 - 3*MT*((Pair1 + Pair2)*Sub10829)
   ;

  Sub10736 = (F26 + F30)*(F37 + F38 - F39 - F40) - 
     Sub1277*Sub921;

  Sub10735 = (F19 + F29)*(F37 + F38 - F39 - F40) + 
     Sub243*Sub921;

  Sub2100 = 2*F13*(Abb10 - Pair1*Sub388 - Pair2*Sub388) + 
     F14*(Sub388 + Sub921);

  Sub2099 = 2*F24*(Abb10 - Pair1*Sub388 - Pair2*Sub388) + 
     F23*(Sub388 + Sub921);

  Sub11741 = (F11*(F16 + F17) + F1*F23)*Sub921 + 
     2*F1*F24*(Abb55 - Pair2*S + Pair1*(-S - Sub921) - 
        Pair2*Sub921);

  Sub11742 = (F10*(F18 + F22) + F14*F7)*Sub921 + 
     2*F13*F7*(Abb55 - Pair2*S + Pair1*(-S - Sub921) - 
        Pair2*Sub921);

  Sub9229 = F19*(F37 - F39 + 2*F12*Pair1) - 2*Sub9228;

  Sub9231 = F26*(-F37 + F39 + 2*F9*Pair1) - 2*Sub9230;

  Sub9262 = F20*F29 + F2*(2*F32 - 2*(F27 + F15*Sub9257));

  Sub9258 = F21*F30 + F5*(2*F31 - 2*(F28 + F25*Sub9257));

  Sub9270 = F30*(F54 - F20*Sub9265) + 
     F1*(-2*Abb133*F24 - Sub9269);

  Sub9277 = F29*(2*F54 - F20*Sub9209) + F2*Sub9276;

  Sub9281 = F30*(2*F56 - F21*Sub9209) + F5*Sub9280;

  Sub9362 = -Sub9281 + MT2*(F1*F23 + 4*F21*F30);

  Sub9340 = F19*(F38 + F40 - 2*(F12 + F9)*Pair2) - 
     2*(F10*Sub9327 + F2*Sub9339);

  Sub9342 = F26*(F38 + F40 - 2*(F12 + F9)*Pair2) - 
     2*(-(F11*Sub9329) - F5*Sub9341);

  Sub12714 = (F10 + F11)*(F16 + F17 + F18 + F22) + 2*Sub940;

  Sub14057 = 1/MW2*((-MB2 + MT2)*Sub216 + 2*MW2*Sub943);

  Sub2311 = MB2*MT*Sub943 + MT2*(Sub2310 - MT*Sub943);

  Sub14071 = 1/MW2*(2*MW2*Sub216 + (-MB2 + MT2)*Sub943);

  Sub1144 = (F19 + F26)*Sub1143 + 
     MT*(-MB2 + MT2 - 2*MW2)*Sub943;

  Sub2321 = 2*MT2*Sub2310 + MT*(MB2 - MT2 + 2*MW2)*Sub943;

  Sub12973 = (F19 + F26 + F29 + F30)*(F37 + F38 - F39 - F40) + 
     (-MT2 + MZ2)*Sub943;

  Sub5313 = MT2*(Sub5282 - Sub943) + MZ2*Sub943;

  Sub9498 = F29*F40 + F2*(F49 - 2*Sub9497);

  Sub9567 = F2*(-2*Abb191*F15 - Sub9499) + 
     F29*(F54 + 3*MT2*F20);

  Sub3405 = (-MH2 + 4*MT2)*Sub14061 + (F12 + F9)*Sub951;

  Sub3236 = Sub735*Sub909 - MB2*MT*(F12*Sub951) - 
     MB2*MT*(F9*Sub951);

  Sub3307 = Sub951*(MT2*F12 + (MB2 + 2*MW2)*F9);

  Sub9543 = Sub9524 + MT*(F24*F33 - 2*F5*F6);

  Sub9559 = F30*F38 + F5*(F47 - 2*Sub9558);

  Sub9572 = Sub9562 + MT*(F29*(F38 + F39) + 2*Sub9564);

  Sub9566 = F5*(-2*Abb191*F25 - Sub9565) + 
     F30*(F56 + 3*MT2*F21);

  Sub7486 = F29*(F12*(Pair1 + Pair2 - Pair3 - Pair4) + 
        F9*(-Pair1 - Pair2 + Pair3 + Pair4)) + MT2*Sub965;

  Sub10503 = (F19 + F29)*(F37 + F38 - F39 - F40) - S*Sub965;

  Sub6946 = 1/MW2*(F2*F43*Pair4*Sub3892 + MW2*(Sub3882*Sub965))
   ;

  Sub981 = 1/MW2*(2*(F44*F5 + F26*F9)*Pair4 + MW2*Sub966);

  Sub6257 = -(MZ2*Sub966) + MT2*(Sub4313 + Sub966);

  Sub10504 = (F26 + F30)*(F37 + F38 - F39 - F40) + S*Sub966;

  Sub6622 = 1/CW2*(Sub858*Sub966 + 
       CW2*(F30*(F9*(3*(Pair1 + Pair2) - 3*(Pair3 + Pair4)) + 
            F12*(-3*(Pair1 + Pair2) + 3*(Pair3 + Pair4)))));

  Sub1928 = 1/MW2*(-(MW2*Sub1910) + 2*MB2*(F1*F24*Sub967));

  Sub2211 = 4*Sub1022*Sub967 + 
     Pair4*(-(3*MT2*Sub1023) + 4*MT*Sub1979);

  Sub2197 = Sub1319*Sub967 + Pair4*(3*MT2*Sub1055 - MT*Sub2196)
   ;

  Sub2123 = -(Sub1142*Sub967) + 
     Pair4*(3*MT2*Sub2120 + MT*Sub2122);

  Sub9777 = F2*(-2*Abb194*F15 + Sub9758) + 
     F29*(-F54 - 2*MT2*F20);

  Sub9813 = Sub9777 + MT2*(-(F2*F27) + 2*F20*F29);

  Sub9779 = F5*(2*Abb194*F25 - Sub9778) + F30*(F56 + 2*MT2*F21)
   ;

  Sub9791 = Sub9779 + MT*(F30*F38 + F5*Sub9776);

  Sub9792 = -Sub9791 + MT2*(2*F21*F30 - F28*F5);

  Sub9873 = 2*F1*Sub9872 + MT2*(F34 - 4*F1*Pair4);

  Sub9876 = 2*F7*Sub9872 + MT2*(F36 - 4*F7*Pair4);

  Sub9882 = F9*(F46 - F11*Sub8527) + F5*Sub9881;

  Sub9884 = F12*(F45 - F10*Sub8527) + F2*Sub9883;

  Sub9889 = F2*(4*Abb148*F15 + Sub9887) + 
     F17*(F45 - F10*Sub9888);

  Sub9907 = MT*Sub9903 + MT2*(-Sub8477 + MT*F6);

  Sub13279 = Abb63*(F15*F2 + F1*F24) + F20*(F19 + F26)*Sub994
   ;

  Sub9961 = F18*(F46 - F11*Sub9851) + 2*F5*Sub9960;

  Sub9968 = -4*F10*F18 + 4*F13*F36 + F2*Sub9967;

  Sub998 = -(F20*F29*Sub994) + 
     F2*(-(F27*Sub994) + 2*F15*Sub997);

  Sub9978 = -(F7*Sub9977) + F29*(F56 + MT2*F21);

  Sub9980 = F1*Sub9979 + F30*(-F54 - MT2*F20);

  Sub9991 = -16*F10*F18 + 16*F13*F36 + F2*Sub9990;

  Sub10067 = 2*F5*Sub9293 + F18*(-2*F46 - F11*Sub9996);

  Sub764 = 1/CW*(MT*(Sub128*Sub16) + CW*(Sub763*SW))/SW;

  Sub648 = (-Sub647 + 32*Sub100*Sub33*SW)/SW;

  Sub790 = (-Sub789 + 16*F5*F6*Sub126*SW)/SW;

  Sub745 = 1/CW*(3*dZZA1*F5*F6*SW + CW*(F5*F6*Sub134 + Sub741))
   ;

  Sub767 = 1/CW*(3*dZZA1*Sub20*SW + CW*(Sub134*Sub20 + Sub759))
   ;

  Sub766 = (Sub765 + Sub21*(12*SW2*dZZA1 + 4*CW*(Sub134*SW)))/
     SW;

  Sub692 = 2*Sub691 + MT*(Sub150*(3*dZZA1 - 4*CW*(Sub61*SW)))
   ;

  Sub702 = 1/(CW2*SW2)*
     (SW2*Sub701 + CW2*(Sub701 + 8*SW2*(F5*F6)));

  Sub4669 = Sub4647 + MT/SW2*(F11*((1 + SW2)*F12 + 2*SW2*F9))
   ;

  Sub2440 = MT*Sub2439 + MT2/SW2*(Sub1268 - 8*SW2*F21);

  Sub2413 = MT*Sub2412 + MT2/SW2*(-Sub1339 + 8*SW2*F20);

  Sub12132 = 2*Sub12117 + MT/SW2*(3*Sub4933 + 4*SW2*Sub12115)
   ;

  Sub3497 = 1/MW2*((F10 + F11)*
        (-(Sub1051*Sub37) + Sub1050*Sub41) + 
       MW2*((F45 + F46)*((-18 + 48*SW2)*F12 + (18 - 48*SW2)*F9)));

    

  Sub14485 = MT2*(3 - 8*SW2)*Sub1019 + MT*Sub1056;

  Sub13184 = 1/MW2*(2*Pair4*Sub13183 + 
       MT*MW2*(9 - 24*SW2)*Sub216);

  Sub2848 = 1/MW2*(Sub2689*Sub41 + Sub37*Sub708 + 
       MT*MW2*(9 - 24*SW2)*Sub216);

  Sub2815 = 1/MW2*(Sub2689*Sub41 + Sub37*Sub708 + 
       MT*MW2*(18 - 48*SW2)*Sub216);

  Sub3012 = 1/MW2*(Sub2986*Sub873 + Sub2985*Sub874 + 
       MW2*(12 - 32*SW2)*Sub2989);

  Sub576 = 1/MW2*(Sub575 + MW2*(-18 + 48*SW2)*(Sub216*Sub388))
   ;

  Sub8868 = (9 - 24*SW2)*Sub8866 + MT*Sub8867;

  Sub220 = (3 - 8*SW2)*Sub193 + (5 - 8*SW2)*Sub194;

  Sub360 = Sub142*Sub359 + (-5 + 8*SW2)*Sub357;

  Sub726 = (5 - 8*SW2)*Sub510 + (3 - 8*SW2)*Sub511;

  Sub12129 = (1 - 4*SW2)*(F25*F5*Pair2) + MT*Sub4938;

  Sub12085 = (1 - 4*SW2)*(F25*F5*Pair2) + MT*Sub6575;

  Sub5037 = (-3 + 4*SW2)*((F16 + F17)*(F19 + F29)) + 
     3*MT*Sub4110;

  Sub5135 = (3 - 4*SW2)*((F16 + F17)*(F19 + F29)) + 
     3*MT*Sub4110;

  Sub4513 = (-3 + 4*SW2)*((F18 + F22)*(F19 + F29)) + 
     3*MT*Sub4110;

  Sub4518 = (3 - 4*SW2)*((F18 + F22)*(F19 + F29)) + 
     3*MT*Sub4110;

  Sub4692 = (3 - 4*SW2)*((F18 + F22)*(F19 + F29)) + 
     6*MT*Sub4110;

  Sub3763 = (-6 + 8*SW2)*(F10*F12) + (6 - 8*SW2)*(F2*F3) + 
     (-3 + 8*SW2)*Sub276;

  Sub5039 = (-3 + 4*SW2)*((F16 + F17)*(F26 + F30)) + 
     3*MT*Sub4116;

  Sub5137 = (3 - 4*SW2)*((F16 + F17)*(F26 + F30)) + 
     3*MT*Sub4116;

  Sub3764 = (6 - 8*SW2)*(F11*F12) + (-6 + 8*SW2)*(F1*F4) + 
     (3 - 8*SW2)*Sub277;

  Sub14576 = (6 - 8*SW2)*(F7*F8) + (-6 + 8*SW2)*(F10*F9) + 
     (-3 + 8*SW2)*Sub276;

  Sub14578 = (-6 + 8*SW2)*(F5*F6) + (6 - 8*SW2)*(F11*F9) + 
     (3 - 8*SW2)*Sub277;

  Sub985 = Pair4*Sub984 + MB2*(-3 + 4*SW2)*Abb16;

  Sub1014 = Sub1013 + MB2*(6 - 8*SW2)*(F1*F24);

  Sub7295 = 2*Sub7294 + 
     MH2*((-3 + 4*SW2)*(F10*F12) + (3 - 4*SW2)*(F2*F3));

  Sub5168 = (3 - 4*SW2)*(F17*(F19 + F29)*(Pair1 + Pair2)) + 
     3*MT*(Pair2*Sub4110);

  Sub5170 = (3 - 4*SW2)*(F17*(F26 + F30)*(Pair1 + Pair2)) + 
     3*MT*(Pair2*Sub4116);

  Sub7494 = F15*F2*Sub7493 + (3 - 4*SW2)*(F13*F7*MH2*Pair3);

  Sub6830 = F12*((3 - 4*SW2)*Pair1 + (6 - 8*SW2)*Pair3) + 
     F9*(3*Sub6829 + (3 - 4*SW2)*Pair1 + (6 - 8*SW2)*Pair3);

  Sub1396 = MT2*(3 - 4*SW2)*Sub1019 + MT*Sub1056;

  Sub1024 = 4*MT2*Sub1022 + 
     (MW2*(6 - 8*SW2) + MB2*(3 - 4*SW2))*Sub1023;

  Sub10316 = 3*Sub10309 + 
     2*(3 - 4*SW2)*(-(Pair1*Sub10310) - Pair2*Sub10310 + 
        F12*Sub10311);

  Sub10505 = 3*Sub10503 + 
     2*(3 - 4*SW2)*(-(Pair1*Sub10310) - Pair2*Sub10310 + 
        F12*Sub10311);

  Sub10317 = 3*Sub10312 + 
     2*(3 - 4*SW2)*(-(Pair1*Sub10313) - Pair2*Sub10313 + 
        F12*Sub10314);

  Sub10506 = 3*Sub10504 + 
     2*(3 - 4*SW2)*(-(Pair1*Sub10313) - Pair2*Sub10313 + 
        F12*Sub10314);

  Sub10410 = 3*S*Sub966 - 
     2*(3 - 4*SW2)*(F26*F9*(Pair1 + Pair2) + F12*Sub10395);

  Sub10408 = 3*S*Sub965 + 
     2*(3 - 4*SW2)*(F19*F9*(Pair1 + Pair2) + F12*Sub10396);

  Sub7198 = 8*F1*F24 + (-3 + 4*SW2)*Sub1043;

  Sub1110 = F45*(3*F12 - 3*F9) + (3 - 4*SW2)*(F10*Sub1050);

  Sub10559 = 3*Sub31*Sub7238 + (6 - 8*SW2)*Sub10529;

  Sub10560 = 3*Sub28*Sub7238 + (6 - 8*SW2)*Sub10532;

  Sub10628 = 3*(-(F2*F3) + F7*F8)*Sub921 + 
     2*(3 - 4*SW2)*(-(F12*Sub10396) - Pair1*Sub10602 - 
        Pair2*Sub10602);

  Sub10630 = 3*(F1*F4 - F5*F6)*Sub921 - 
     2*(3 - 4*SW2)*(-(F12*Sub10395) - Pair1*Sub10606 - 
        Pair2*Sub10606);

  Sub10857 = 3*MT2*Sub10837 + (-3 + 4*SW2)*Sub10851;

  Sub10855 = 3*MT2*Sub10836 + (-3 + 4*SW2)*Sub10852;

  Sub11041 = 3*F29*Sub11027 + (3 - 4*SW2)*Sub11034;

  Sub11043 = 3*F30*Sub11027 + (3 - 4*SW2)*Sub11036;

  Sub11137 = 3*F30*F39 + (3 - 4*SW2)*Sub11135;

  Sub11139 = 3*F29*F39 + (3 - 4*SW2)*Sub11136;

  Sub11210 = (-3 + 4*SW2)*Sub11199 + 3*MT*Sub965;

  Sub1171 = (F11*F18 - F31*F5)*Sub878 + MB2*(3 - 4*SW2)*Sub1161
   ;

  Sub11861 = 3*Sub11303 + (3 - 4*SW2)*Sub11840;

  Sub11975 = 3*Sub5498 + (3 - 4*SW2)*Sub11967;

  Sub12086 = (3 - 4*SW2)*Sub12064 + (3 - 8*SW2)*Sub6547;

  Sub4386 = MT*(F11*(3*F12 - 3*F9)) + (3 - 4*SW2)*Sub1214;

  Sub1218 = MT*(F10*(-3*F12 + 3*F9)) + (3 - 4*SW2)*Sub1215;

  Sub1220 = MT*(F11*(-3*F12 + 3*F9)) + (3 - 4*SW2)*Sub1216;

  Sub4384 = MT*(F10*(3*F12 - 3*F9)) + (3 - 4*SW2)*Sub1217;

  Sub13168 = MT*(F10*(-3*F12 + 3*F9)) + (3 - 4*SW2)*Sub13167;

  Sub1329 = F10*Sub1328 + (3 - 4*SW2)*Sub1324;

  Sub1327 = (3 - 4*SW2)*Sub1326 + 
     (3 - 8*SW2)*(F11*(F12 + F9)*Sub407);

  Sub13402 = (-3*F12 + 3*F9)*Sub13395 + (3 - 4*SW2)*Sub13392;

  Sub13403 = (-3 + 4*SW2)*Sub13398 + MT*Sub13402;

  Sub13527 = MT*(F10*(-3*F12 + 3*F9)) + (3 - 4*SW2)*Sub13511;

  Sub13602 = F10*(-6*F12 + 6*F9)*S + (3 - 4*SW2)*Sub13599;

  Sub13772 = (3 - 4*SW2)*
     (2*F1*(Abb83 + Sub13771) + S*(-F34 + MT*F33));

  Sub13818 = (-3*F12 + 3*F9)*Sub13784 + 
     (3 - 4*SW2)*(F2*F3*Sub13817);

  Sub13823 = (3*F12 - 3*F9)*Sub13785 + 
     (3 - 4*SW2)*(F24*F33*Sub13817);

  Sub13824 = (-3 + 4*SW2)*Sub13822 + MT*Sub13823;

  Sub13928 = (3 - 4*SW2)*Sub13919 + MT*Sub13927;

  Sub13931 = (-3 + 4*SW2)*Sub13920 + MT*Sub13930;

  Sub2998 = 1/(CW2*MW2)*
     (MW2*(24 - 32*SW2)*Sub14 + CW2*((3*F12 - 3*F9)*Sub2929));

  Sub14099 = (3 - 4*SW2)*Sub14074 + MT*Sub14098;

  Sub14097 = (3 - 4*SW2)*Sub14076 + MT*Sub14096;

}
