#if 0
* abbr1h6.c
* abbreviations for {-F[2, {1}], F[2, {1}]} -> {-F[3, {3, Col3}], F[3, {3, Col4}], V[1]}
* generated by FormCalc 8.2 on 11-Apr-2013 22:37
#endif

#include "vars.h"
#include "inline.h"


void abbr1h6() {

#include "vars.h"

#include "inline.h"

  Sub10727 = 12*(3 + SW2*(-8 + 8*SW2))*(F21*F30) + 
     64*(SW2*SW2)*Sub10656 - Power(3 - 4*SW2,2)*Sub10725 + 
     16*Power(1 - 2*SW2,2)*Sub10726;

  Sub9693 = -(Power(3 - 4*SW2,2)*Pair1) - 
     16*(SW2*SW2)*(Pair1 - 2*Pair2) + 
     (9 + SW2*(-24 + 32*SW2))*(Pair1 - Pair2) + 3*(3 - 8*SW2)*Pair2
    ;

  Sub15091 = 1/(CW2*SW2)*
     (-(SW2*(Sub1056*Sub15090)) + 
       CW2*(SW2*(2*Sub15089 + 8*F10*pave77(cc0)) + 
          F12*(8*SW2*pave77(cc0) - 2*pave86(cc1))));

  Sub724 = F5*F6*Sub692 - 2*Sub723 + 
     (-(F23*F33) + F7*F8)*Conjugate(dZfL1(3,3,3)) - 
     F13*F35*Conjugate(dZfR1(3,3,3));

  Sub13448 = F10*(F16 + F17 + F18 + F19) + Opt32;

  Sub11492 = F22*(F20 + F26) + Sub11920;

  Sub8714 = F23*F36 + Sub8806;

  Sub6366 = F1*F14 + F24*F3 + Sub6613;

  Sub12580 = F22*(-F29 - F30) + Sub2794;

  Sub8084 = F10*(-F16 + F17 + F18 - F19) - F24*F3 + 
     F21*(-F26 + F30) + F22*(F26 + F30) - F27*F5;

  Sub6614 = F21*(F26 + F30) + F22*(F20 + F26 + F29 + F30) + 
     F13*F34 + F23*F36 + F31*F5;

  Sub10619 = -(F24*F3) + F21*F30 + 2*F22*F30 - F27*F5 + 
     2*F31*F5;

  Sub8386 = F21*(-F26 - F30) + F22*(F26 + F30) - F23*F36 + 
     F33*F42 + F31*F5 - 2*F4*F51;

  Sub135 = (F10 + F12)*(F16 + F17 + F18 + F19) + Sub147;

  Sub3709 = F1*F14 + F12*(-F16 + F17 + F18 - F19) + 
     F20*(-F21 + F22) + F28*F7;

  Sub8082 = F1*F14 + F12*(-F16 + F17 + F18 - F19) + 
     F20*(-F21 + F22) + (F21 + F22)*F29 + F28*F7;

  Sub5477 = F1*F14 - F24*F3 + F22*(2*F29 + 2*F30) - F27*F5 + 
     F28*F7;

  Sub3352 = (F10 + F12)*(-F18 + F19) + F13*F34 - F23*F36 + 
     F31*F5 - F32*F7;

  Sub3467 = (F21 + F22)*(F20 + F26 + F29 + F30) + Sub13935;

  Sub8387 = (F21 - F22)*(F20 + F29) - F13*F34 + F35*F41 - 
     2*F2*F52 + F32*F7;

  Sub12192 = F11*(F20 + F26 + F29 + F30) + F1*F41 - Sub12193;

  Sub12104 = F11*(F20 + F26 + F29 + F30) - F1*F41 + Sub12193;

  Sub13255 = 2*(F1*F41 + F43*F5) - Sub12831;

  Sub2769 = F3*F4 + 4*(F1*F2 + F5*F6) + F7*F8 - 4*F12*F9;

  Sub3255 = -2*F12*F9 + Sub28;

  Sub12667 = -2*F12*F9 + Sub201;

  Sub2771 = 2*F1*F2 - 2*F12*F9 + Sub2712;

  Sub13017 = -2*F3*F4 + 2*F5*F6 + Sub11661;

  Sub3262 = -(F12*F9) + Sub28;

  Sub12669 = -(F12*F9) + Sub201;

  Sub5248 = 2*(F1*F2 + F5*F6) + 4*(F3*F4 + F7*F8) - F12*F9;

  Sub12402 = F3*F4 + F5*F6 + F7*F8 - F10*F9 - F12*F9;

  Sub12941 = F1*F41 - 2*F44*F7 + Sub5428;

  Sub13500 = F11*(2*F20 + 2*F26) - F3*F42 - F44*F7 + F20*F9 + 
     F26*F9;

  Sub4200 = F11*(F20 + 2*F29) - 2*F29*F9 + Sub10910;

  Sub7253 = (F20 - F29)*F9 + Sub10303;

  Sub6078 = -(F1*F41) - F20*F9 + F29*F9 + Sub12775;

  Sub4203 = F11*(F26 + 2*F30) - 2*F30*F9 - Sub10913;

  Sub7250 = (F26 - F30)*F9 + Sub10299;

  Sub6074 = -(F43*F5) - F26*F9 + F30*F9 + Sub12774;

  Sub13320 = (F29 + F30)*F9 + Sub12193;

  Sub12265 = -(F3*F42) + 2*F43*F5 - F44*F7 + 3*F20*F9 + 
     4*F30*F9;

  Sub3428 = -(F11*F12) + F13*F35 - F5*F6 + F12*F9 + 
     F10*(-F11 + F9);

  Sub3427 = -Sub2974 + Sub2988;

  Sub3429 = -Sub2976 + Sub2992;

  Sub3430 = -(F11*F12) - F23*F33 + F7*F8 + F12*F9 + 
     F10*(-F11 + F9);

  Sub11865 = -(F3*F4) + 2*(F1*F2 + F5*F6) - F7*F8 + 
     F10*(F11 + F9) + F12*(F11 + F9);

  Sub11917 = (F10 + F12)*(F11 + F9) + Sub400;

  Sub13435 = 2*(F10 + F12)*(F11 + F9) + Sub400;

  Sub1674 = (F20 + F26)*(F11 + F9) + Sub4427;

  Sub5646 = -(F3*F42) - F43*F5 - Sub13121;

  Sub9672 = Sub4763 + Sub4764 + MT*(F5*F6 + F7*F8);

  Sub8801 = F1*F14 + F24*F3 + F13*F34 + F23*F36 + 
     (F10 + F12)*(F16 + F17 + F18 + F19 + MT*(F11 + F9));

  Sub6130 = (F29 + F30)*(F37 + F39) + MT2*(F5*F6);

  Sub2275 = F12*(-F17 + F18) + Opt1;

  Sub13944 = F12*(F17 + 3*F18) + Opt1;

  Sub9543 = F10*(F16 + F19) - F21*F26 - 2*F23*F36 + 
     F3*(F24 - 2*F23*Pair1);

  Sub14501 = F31*F5 + F23*(F36 - 2*F3*Pair1) + Sub7105;

  Sub9307 = -(F21*F26) - F24*F3 + 2*F23*F3*Pair1 + Sub6796;

  Sub7596 = F26*F39 - F36*F42 + F10*(F53 - F55) - 
     2*F43*F5*Pair1;

  Sub14502 = -(F32*F7) + F13*(-F34 + 2*F1*Pair1) - Sub7103;

  Sub2273 = F12*(-F16 + F19) + Opt2;

  Sub13945 = F12*(F16 + 3*F19) + Opt2;

  Sub7597 = -(F20*F37) + F34*F41 + F12*(F53 - F55) + 
     2*F44*F7*Pair1;

  Sub9398 = F12*(-F16 + F17 - F19) - F20*F21 + 
     F1*(F14 - 2*F13*Pair1) + F7*(F28 + 2*F15*Pair1);

  Sub14398 = F12*(4*F16 + 4*F17) + F20*(-F21 - F22) - 
     F21*F29 - F22*F29 - F32*F7 - 8*F1*F13*Pair1 - 
     8*F15*F7*Pair1 + F13*(-F34 + MT*F35) - MT*(F7*F8);

  Sub13981 = (F21 + F22)*(F20 + F26 + F29 + F30) + F13*F34 + 
     F31*F5 + F32*F7 + F23*(F36 - 2*F3*Pair1);

  Sub14186 = (F10 + F12)*(F16 + F17) + 
     F13*(F34 - 2*F1*Pair1) + F7*(F32 - 2*F15*Pair1) + 
     F5*(F31 - 2*F25*Pair1) + F23*(F36 - 2*F3*Pair1);

  Sub8628 = F37 + 2*F39 + F40 - 2*F9*Pair1 + 
     F11*(-4*Pair1 - 2*Pair2);

  Sub12380 = (F29 + F30)*F9*Pair1 + Sub12930;

  Sub654 = F24*F3 - F21*F30 - Sub4;

  Sub2135 = (F21 - F22)*F30 - Sub2033;

  Sub2136 = (F21 - F22)*F29 + Sub2034;

  Sub4633 = (F21 + F22)*(F20 + F29) + 
     (F1*F13 + F15*F7)*(-Pair1 - 2*Pair2);

  Sub652 = F1*F14 - F22*F29 + Sub3;

  Sub428 = F24*F3 - F21*F30 + Sub3;

  Sub919 = F1*F14 - F27*F5 + Sub2459;

  Sub2515 = -(F27*F5) - F28*F7 + Sub2876;

  Sub8629 = 2*F37 + F38 + F39 + (-2*F11 - 4*F9)*Pair1 - 
     2*F9*Pair2;

  Sub4499 = Sub14359 + Sub14697;

  Sub2481 = F10*(F17 + F18) - F27*F5 - Sub411;

  Sub3103 = F10*(-F16 + F17) + F21*(-F26 - F30) + 
     F22*(F26 + F30) + F5*(F31 - 2*F25*(Pair1 + Pair2)) + 
     F23*(-F36 + 2*F3*(Pair1 + Pair2));

  Sub3106 = F12*(F16 - F17) + (F21 - F22)*(F20 + F29) + 
     F13*(-F34 + 2*F1*(Pair1 + Pair2)) + 
     F7*(F32 - 2*F15*(Pair1 + Pair2));

  Sub12533 = Opt10 + (2*F11 - 2*F9)*(Pair1 + Pair2);

  Sub1274 = Opt3 - 2*(F11 + F9)*(Pair1 + Pair2);

  Sub14364 = 2*F12*(F16 + F17 - 2*(F18 + F19)) + 
     4*(F21 + F22)*(F20 + F29) + 9*(F13*F34 + F32*F7) - 
     2*(F1*F13 + F15*F7)*(5*Pair1 + 2*Pair2) - 
     9*MT*(F13*F35 - F7*F8);

  Sub14399 = 5*(F21 + F22)*(F20 + F29) + 
     9*(F13*F34 + F32*F7) - 
     2*(F12*(-2*(F16 + F17) + F18 + F19) + 
        (F1*F13 + F15*F7)*(7*Pair1 + 4*Pair2)) - 
     9*MT*(F13*F35 - F7*F8);

  Sub14214 = 2*F12*F18 - F20*F22 - F22*F29 + 
     F13*(-3*F34 + F1*(4*Pair1 + 2*Pair2));

  Sub14374 = 4*F12*(F16 + F17) + (F21 + F22)*(F20 + F29) + 
     F13*(F34 + 8*F1*Pair2 - MT*F35) + 
     F7*(F32 + 8*F15*Pair2 + MT*F8);

  Sub9198 = (F21 + F22)*(F29 + F30) + 
     F1*(-F14 - 2*F13*Pair2) + F7*(F28 - 6*F15*Pair2) + 
     F3*(-F24 - 2*F23*Pair2) + F5*(F27 - 6*F25*Pair2);

  Sub9354 = F10*(F16 + F17 - F18 - F19) + 
     (4*F21 + 2*F22)*F26 + 4*F23*F36 + F5*(F27 - 2*F25*Pair1) + 
     F3*(F24 + 2*F23*(Pair1 + Pair2));

  Sub14215 = 2*F12*F19 - F20*F21 - F21*F29 - 3*F32*F7 + 
     F15*F7*(4*Pair1 + 2*Pair2);

  Sub2665 = F1*(-F14 + 2*F13*(Pair1 + Pair2)) + Sub2762;

  Sub9353 = F12*(-F16 - F17 + F18 + F19) - 
     2*F20*(F21 + 2*F22) - 4*F13*F34 + F7*(-F28 + 2*F15*Pair1) - 
     F1*(F14 + 2*F13*(Pair1 + Pair2));

  Sub3465 = (F21 + F22)*(F20 + F26 + F29 + F30) + F13*F34 + 
     F31*F5 + F32*F7 + F23*(F36 - 2*F3*(Pair1 + Pair2));

  Sub9362 = 2*F37 + F38 + F39 + F11*(2*Pair1 + 4*Pair3) + 
     F9*(-2*Pair2 + 4*Pair3);

  Sub13256 = F11*F29*Pair3 + Sub12830;

  Sub12643 = (2*F23*F3 - 2*F25*F5)*Pair3 - Sub2033;

  Sub13700 = (F10 + F12)*(F17 + F18) + F22*(-F29 - F30) + 
     2*(F1*F13 + F25*F5)*Pair3;

  Sub5848 = F10*(-F16 + F17 + F18 - F19) + F22*(F26 - F30) + 
     F21*(-F26 + F30) - 2*(F24*F3 + F27*F5) + 
     (4*F23*F3 - 4*F25*F5)*Pair3;

  Sub9818 = F7*(F32 + F15*(12*Pair2 - 6*Pair3)) + 
     F25*F5*(12*Pair2 - 6*Pair3);

  Sub5398 = F21*F29 - 2*F15*F7*Pair3 + Sub213;

  Sub13701 = (F10 + F12)*(F16 + F19) + F21*(-F29 - F30) + 
     2*(F23*F3 + F15*F7)*Pair3;

  Sub9360 = F37 + 2*F39 + F40 + F9*(2*Pair1 + 4*Pair3) + 
     F11*(-2*Pair2 + 4*Pair3);

  Sub12758 = F9*((F20 + F26 + F29 + F30)*Pair3 + MT2*F12);

  Sub5867 = Opt10 + (4*F11 - 4*F9)*Pair3;

  Sub5229 = Opt3 - 2*(F11 + F9)*Pair3;

  Sub6538 = MT2*(F12*(F16 + F19) + F21*(F20 + F26) + 
       F23*F3*Pair3);

  Sub11086 = F10*(-F16 + F17 + F18 - F19) + F22*(F26 - F30) + 
     F21*(-F26 + F30) - 2*(F24*F3 + F27*F5) + 
     F25*F5*(4*(Pair1 + Pair2) - 4*Pair3) + 
     F23*F3*(-4*(Pair1 + Pair2) + 4*Pair3);

  Sub5853 = F12*(-F16 + F17 + F18 - F19) + F20*(-F21 + F22) + 
     (F21 - F22)*F29 + F1*(2*F14 - 4*F13*Pair3) + 
     F7*(2*F28 + 4*F15*Pair3);

  Sub8576 = F24*F3 + F13*F34 + F23*F36 + F25*F5*Pair3 + 
     F1*(F14 - 2*F13*(Pair1 + Pair3));

  Sub5118 = F15*F7*(2*Pair1 - 2*Pair4) + Sub12733;

  Sub8070 = Pair1 + Pair2 - Pair3 - Pair4;

  Sub6459 = F37 + F39 + F9*(-Pair1 + Pair2 - Pair3) + 
     F11*(-2*Pair1 + Pair4);

  Sub12214 = -2*(F37 + F38) + F39 + F40 + 
     2*(F9*Pair3 + F11*Pair4);

  Sub2575 = F23*F3*(-Pair1 - Pair2) + F25*F5*Pair3 + 
     F15*F7*(-Pair1 - Pair2 + Pair4) + F1*F13*(Pair3 + Pair4);

  Sub5976 = F50*F7*Pair1 + F48*F5*(Pair1 + Pair2) + 
     F11*F20*(Pair3 + Pair4);

  Sub3437 = F11*F29*(Pair3 + Pair4) + Sub5249;

  Sub2576 = F1*F13*(Pair1 + Pair2) - F23*F3*Pair3 - 
     F15*F7*Pair3 + Sub1771;

  Sub6461 = F29*(F37 + F39) + F30*(F37 + F39 + F11*Pair4);

  Sub8826 = F3*F42*(Pair1 + Pair2) + 
     F30*(F9*Pair3 + F11*Pair4) + MT2*(F5*F6);

  Sub12531 = Sub12169 + 
     MT*((F20 + F26 + F29 + F30)*(F11 + F9)*
        (2*(Pair1 + Pair2) - Pair3 - Pair4));

  Sub3433 = F45 + F46 + 
     (F29 + F30)*(2*(Pair1 + Pair2) - 2*Pair4) - 
     2*(F20 + F26)*Pair4 + MT2*(F10 + F12);

  Sub13304 = (F29 + F30)*(F37 + F38) + F1*F41*Pair4;

  Sub7954 = F10*(F17 + F18) + F22*(F26 + 6*F30) + 
     F25*F5*(2*Pair2 - 8*Pair4);

  Sub13230 = (F10 + F12)*(F17 + F18) - F20*F22 - F22*F26 + 
     2*F1*F13*Pair4 + 2*F25*F5*Pair4;

  Sub7957 = F12*(F16 + F19) + F21*(F20 + 6*F29) + 
     F15*F7*(2*Pair2 - 8*Pair4);

  Sub4980 = F24*F3 + F21*(-F20 - F26 - F29 - F30) + 
     F7*(-F28 + 2*F15*Pair4);

  Sub13231 = (F10 + F12)*(F16 + F19) - F20*F21 - F21*F26 + 
     2*F23*F3*Pair4 + 2*F15*F7*Pair4;

  Sub13360 = F7*(-F28 + 8*F15*Pair4) + 
     F3*(F24 + F23*(-2*Pair3 + 6*Pair4));

  Sub4458 = F37 + F38 + 
     F11*(-2*(Pair1 + Pair2) + 2*Pair3 + Pair4) + 
     F9*(2*(Pair1 + Pair2) - 4*(Pair3 + Pair4));

  Sub10416 = -2*(F37 + F38) + F39 + F40 + 
     F11*(-4*Pair3 - 6*Pair4) + 8*F9*(Pair3 + Pair4);

  Sub12871 = F37 + F38 + F9*(-Pair3 - Pair4) + F11*Pair4;

  Sub6460 = F37 + F39 + F11*(-Pair1 + Pair2 - Pair3) + 
     F9*(-2*Pair1 + Pair4);

  Sub13437 = F37 + F38 + 
     F11*(2*(Pair1 + Pair2) - 2*Pair3 - 3*Pair4) + 
     F9*(-2*(Pair1 + Pair2) + Pair4);

  Sub13034 = F30*(F37 + F38) + F29*(F37 + F38 + F9*Pair4);

  Sub3439 = F29*F9*Pair4 + Sub13301;

  Sub7904 = F11*(F26*Pair2 + F30*(Pair1 + Pair3)) + 
     F30*F9*Pair4 + MT2*(F5*F6);

  Sub8954 = F11*(F26*Pair1 + F30*Pair4) + 
     F9*(F26*Pair3 + F30*Pair4) + MT2*(F5*F6);

  Sub12384 = F11*F29*Pair4 + Sub3627;

  Sub9629 = Opt3 + 2*(F11 + F9)*Pair4;

  Sub4288 = F37 + F38 + 
     F9*(-4*(Pair1 + Pair2) + 2*Pair3 + 3*Pair4) + 
     F11*(2*(Pair1 + Pair2) - 2*(Pair3 + Pair4));

  Sub8211 = -(F24*F3) + F21*F30 + F22*F30 - F27*F5 + 
     F25*F5*(Pair2 + Pair4);

  Sub6896 = F22*F30 + 2*F25*F5*(Pair2 + Pair4) + Sub212;

  Sub8212 = F1*F14 - F21*F29 - F22*F29 + F28*F7 + 
     F15*F7*(-Pair2 - Pair4);

  Sub6898 = F21*F29 + Sub8098;

  Sub12967 = Opt3 - 2*(F11 + F9)*(Pair1 + Pair2 + Pair4);

  Sub7219 = F10*(-2*(F17 + F18) + 2*(F16 + F19)) + 
     F22*(-F26 - 3*F30) + F21*(F26 + F30) + 3*(F24*F3 + F27*F5) + 
     F25*F5*(-6*Pair2 - 2*Pair4);

  Sub12853 = Opt3 - 2*(F11 + F9)*(2*(Pair1 + Pair2) + Pair4);

  Sub6529 = Opt3 + (F11 + F9)*(-2*Pair3 + Pair4);

  Sub13985 = Opt3 - 2*(F11 + F9)*(Pair3 + Pair4);

  Sub12449 = Sub12169 + 
     MT*((F20 + F26 + F29 + F30)*(F11 + F9)*
        (Pair1 + Pair2 + Pair3 + Pair4));

  Sub8540 = F37 + F39 + F11*(2*Pair2 - 4*Pair3 - 2*Pair4) + 
     F9*(2*Pair1 + 4*Pair2 - 4*(Pair3 + Pair4));

  Sub6991 = 2*F12*(F16 - 2*(F17 + F18) + F19) - 
     F20*(-5*F21 + 8*F22) - 2*F21*F29 - 8*F15*F7*(Pair1 + Pair2) + 
     4*F1*F13*(2*Pair3 + Pair4);

  Sub6811 = 2*F10*(F17 + F18 - 2*(F16 + F19)) + 
     (-8*F21 + 5*F22)*F26 - 2*F22*F30 - 8*F25*F5*(Pair1 + Pair2) + 
     4*F23*F3*(2*Pair3 + Pair4);

  Sub13307 = (F16 + F19)*(F26 + 2*(F29 + F30))*Pair4 + 
     Sub11767 + F20*((F16 + F19)*Pair4 + MT2*(F21 - F22)) + 
     MT2*(F21*(F26 - F29 - F30) + F22*(-F26 + F29 + F30));

  Sub6992 = 2*F10*(F16 - 2*(F17 + F18) + F19) - 
     (-5*F21 + 8*F22)*F26 - 2*F21*F30 - 8*F23*F3*(Pair1 + Pair2) + 
     4*F25*F5*(2*Pair3 + Pair4);

  Sub6810 = -2*F12*(F17 + F18 - 2*(F16 + F19)) - 
     F20*(-8*F21 + 5*F22) + 2*F22*F29 + 8*F1*F13*(Pair1 + Pair2) - 
     4*F15*F7*(2*Pair3 + Pair4);

  Sub5948 = 2*(F37 + F38) + F39 + F40 - 2*F11*Pair3 + 
     F9*(4*(Pair1 + Pair2) - 8*(Pair3 + Pair4));

  Sub11123 = 4*F11*(Pair1 + Pair2) + 
     F9*(-4*(Pair1 + Pair2) + 2*Pair4) - Sub11272;

  Sub12472 = F11*(F20 + F26 + F29 + F30)*Pair4 + 
     F43*F5*(Pair3 + 2*Pair4);

  Sub11120 = 4*F9*(Pair1 + Pair2) + 
     F11*(-4*(Pair1 + Pair2) + 2*Pair4) + Sub11270;

  Sub13160 = Opt3 + (F11 + F9)*(-2*Pair3 - 6*Pair4);

  Sub12810 = Opt3 + (F11 + F9)*(-4*Pair3 - 6*Pair4);

  Sub11761 = -(F29*F9*Pair4) - F30*F9*Pair4 + 
     (F1*F41 + F43*F5)*(Pair3 + Pair4) + 
     F11*(F30*Pair3 + F30*Pair4 + F29*(Pair3 + Pair4));

  Sub11114 = F22*F30 - 3*(F24*F3 + F21*F30) + 
     F5*(F27 - 4*F25*Pair3) + 
     2*F23*F3*(Pair1 + Pair2 + Pair3 + 2*Pair4) - 
     2*(F10*(F16 + F19) + F25*F5*Pair4);

  Sub8085 = F10*(F16 - F17 - F18 + F19) + F22*(-F26 - 2*F30) + 
     F21*(F26 + F30) + Sub11169;

  Sub6698 = (-F21 + F22)*(F20 + F29) + F13*F34 + F35*F41 + 
     2*F2*F52 + F7*(-F32 + 4*F15*(Pair3 + Pair4));

  Sub12385 = (2*F26 + 4*F29)*Pair2 - 6*F20*(Pair3 + Pair4) + 
     F10*S;

  Sub13049 = F1*F2*S + Sub13301;

  Sub12517 = -Sub10240 - Sub10791;

  Sub12515 = -Sub10244 - Sub10784;

  Sub12284 = Sub10683 + Sub11587;

  Sub12286 = -Sub10685 + Sub11591;

  Sub11089 = F12*(-F16 + F17 + F18 - F19) + F20*(-F21 + F22) + 
     (F21 - F22)*F29 + 2*(F1*Sub11087 + F7*Sub11088);

  Sub11166 = F12*(F16 - F17 - F18 + F19) + F20*(F21 - F22) + 
     (-F21 + F22)*F29 - 2*(F1*Sub11164 + F7*Sub11165);

  Sub11338 = F10*(F16 + F17 + F18 + F19) + F22*F26 + 
     F21*(-F26 + 2*F30) + F5*(-F27 + 2*F25*Pair3) - F3*Sub11337;

  Sub11687 = (F26 + F30)*F9*(Pair3 + Pair4) + 
     (Pair1 + Pair2)*Sub11686;

  Sub11690 = (F20 + F29)*F9*(Pair3 + Pair4) + 
     (Pair1 + Pair2)*Sub11689;

  Sub13153 = Sub13151 + Sub13152 + Sub2312;

  Sub13276 = (F10 + F12)*(-2*(F17 + F18) + 2*(F16 + F19)) + 
     7*F21*(F29 + F30) - 4*Sub13274 + 4*Sub13275;

  Sub13361 = 1/MW2*(-(MW2*(F21*Sub10474)) + 
       MT*((MB2 + MT2)*(F37 + F38 + F39 + F40) + 
          MT2*(-6*F11*Pair3 + 2*F9*Pair4)) + 
       MB2*(Sub13357 - 2*MT*Sub10466));

  Sub14192 = Sub14441 + F1*F13*Pair1*Sub152 + 
     Pair2*((2*(F16 + F17) - F18 - F19)*(F20 + F29) + 
        F1*F13*Sub152);

  Sub14189 = F26*(F19*Pair1 + 2*(F16 + F17)*Pair2) + 
     Pair2*(2*(F16 + F17)*F30 + F23*F3*Sub152) + 
     Pair1*(F19*F30 + F18*(F26 + F30) + F23*F3*Sub152);

  Sub14269 = (F18 + F19)*(F26 + F30)*(Pair1 - Pair2) + Sub14193
   ;

  Sub2458 = 1/MW2*((3*MB2*MT2 - 3*(MT2*MT2))*F22 + 
       F21*(MT2*(MT2 - MW2) + MB2*(-MT2 + Sub2321)) + 
       MT*((MB2 + MT2 - MW2)*(F37 + F38) + 2*MB2*(F39 + F40)));

  Sub2456 = 4*(F1*F14 + F21*(F29 + F30)) - 
     2*(F22*(F29 + F30) + F25*F5*Pair1) + 2*F5*Sub2455 + Sub2503;

  Sub12730 = (F20 + F26 + F29 + F30)*(F39 + F40) + 
     2*Pair4*Sub10685 - 2*Sub12729 - F10*F11*Sub265 - 
     F11*F12*Sub265 + (F3*F4 + F7*F8)*Sub265;

  Sub13936 = (F10 + F12)*(-F16 - F17 + F18 + F19) - 
     2*(F21 + F22)*(F20 + F26 + F29 + F30) - 3*Sub13935 + 
     (6*Pair1 + 4*Pair2)*Sub149 + 3*MT*Sub28;

  Sub2823 = F12*(2*F17 - 2*F18) + 
     F22*(F20 - F26 + F29 - F30) + 6*F25*F5*Pair1 - 
     2*(F13*Sub2821 + Sub2822);

  Sub2826 = F12*(2*F16 - 2*F19) + 
     F21*(F20 - F26 + F29 - F30) + 6*F23*F3*Pair1 - 
     2*(F7*Sub2824 + Sub2825);

  Sub3403 = 3*Sub196 + 5*Sub197 + 2*Sub198 - 
     2*(Pair1 + Pair2)*Sub3402 + MT*Sub3401;

  Sub3496 = (F11*(F10 + F12) - F3*F4 - F7*F8)*Sub265 + 
     Sub2667 + 2*Sub3495;

  Sub2636 = -2*Sub2635 + (F1*F2 + F3*F4 + F5*F6 + F7*F8)*Sub353
   ;

  Sub12137 = (F16 + F19)*
      ((F26 + F29 + F30)*Pair3 + F20*(Pair3 - Pair4) - F26*Pair4 - 
        F29*Pair4 - F30*Pair4) + Sub11766 + 
     F23*F3*(Pair1 + Pair2)*Sub353;

  Sub12202 = Sub13104 + F15*F7*(Pair1 + Pair2)*Sub1580 + 
     F23*F3*((Pair1 + Pair2)*Sub1580 + Pair4*Sub354);

  Sub12203 = -2*Sub12201 + F21*(-(F29*Sub354) - F30*Sub354) + 
     2*(Sub12202 + F15*F7*Pair4*Sub354);

  Sub6571 = F11*F30*(Pair3 - Pair4) + 
     (Pair1 + Pair2)*(F43*F5 + Sub4338) + 
     Pair4*(F11*(F26 + F30) + F3*F42 + Sub4339) + Sub4365;

  Sub6574 = F11*F29*(Pair3 - Pair4) + 
     (Pair1 + Pair2)*(F1*F41 + Sub4342) + 
     Pair4*(F11*(F20 + F29) + F44*F7 + Sub4343) + Sub4366;

  Sub4515 = -(F5*Sub4510) + F3*Sub4512 + 
     F9*(6*F30*Pair4 - Sub4513) + F11*(-2*F30*Pair4 + Sub4514);

  Sub4520 = F1*Sub4516 + F7*Sub4517 + 
     F9*(6*F29*Pair4 - Sub4518) + F11*(-2*F29*Pair4 + Sub4519);

  Sub12799 = (F29 + F30)*(F11 + F9) + Sub12774 + Sub12775 + 
     Sub12778 + Sub4868;

  Sub5366 = -(F21*(F20 + F26 + 3*(F29 + F30))) - 
     3*(F24*F3 + F7*(-F28 + 2*F15*Pair2)) + F1*F13*Pair4 - 
     2*Sub5365;

  Sub5808 = F12*(-F17 - F18 + 2*(F16 + F19)) - 2*F22*F29 + 
     F21*(-F20 + 3*F29) - F7*Sub5641 + F1*Sub5674;

  Sub5935 = F12*(F16 - 2*(F17 + F18) + F19) - 2*F22*F29 + 
     F21*(-F20 + 3*F29) + F1*Sub5674 - F7*Sub5934;

  Sub13456 = F1*F41*(Pair3 - 2*Pair4) + 
     F29*(F11*(-4*Pair3 - 2*Pair4) + F9*(2*Pair3 + Pair4)) + 
     Sub6004;

  Sub6077 = F26*(F37 + F38 - F39 - F40) + 
     F30*(-F37 - F38 + F39 + F40) + 2*(Pair1 + Pair2)*Sub6074 + 
     S*Sub6075 + (F3*F4 - F5*F6)*Sub6076;

  Sub6080 = F20*(F37 + F38 - F39 - F40) + 
     F29*(-F37 - F38 + F39 + F40) + (-(F1*F2) + F7*F8)*Sub6076 + 
     2*(Pair1 + Pair2)*Sub6078 + S*Sub6079;

  Sub6268 = F20*(5*F21 - 8*F22) - 2*F21*F29 - 
     8*F15*F7*(Pair1 + Pair2) + F1*F13*(8*Pair3 + 4*Pair4) + 
     2*F12*Sub6267;

  Sub6325 = F13*F34 + F23*F36 + 4*Pair4*Sub149 - Sub6319 - 
     2*Sub6324;

  Sub6465 = F45 - 2*(2*F20 + F29)*(Pair1 + Pair2) + 
     4*(F20 + F29)*Pair3 + 2*((F20 + F29)*Pair4 + F10*Sub6463) + 
     F12*Sub6464;

  Sub7213 = F20*(F21 - F22) + (3*F21 - F22)*F29 - 
     3*(F1*F14 + F28*F7) + 6*F15*F7*Pair2 + 2*Sub7212;

  Sub8655 = -4*F1*F13*Pair1 + 2*Sub6613 - Sub8582 + 
     4*Sub8654 + F12*(-4*F19 - 2*MT*(F11 + F9)) - 
     2*MT*(F10*(F11 + F9));

  Sub8712 = 6*F20*F22 + 2*F23*F36 - 
     8*(F25*F5 + F15*F7)*Pair1 - 4*F15*F7*Pair2 + 
     F13*(2*F34 - 4*F1*Pair3) - Sub8709;

  Sub8890 = 4*F12*F19 + F20*(F21 + 2*F22) + 
     (2*F21 + F22)*F26 + 2*Sub8888 - 4*Sub8889;

  Sub8935 = -3*F22*F30 - 2*(F31*F5 + F32*F7) + 
     F3*(2*F24 - 2*F23*Pair1) + 2*F1*F13*Pair4 + 6*Sub8934;

  Sub9031 = 6*F22*F30 - 4*F7*(F28 + F15*(2*Pair1 - 2*Pair3)) - 
     8*F25*F5*(Pair1 - Pair3) - Sub9024 + 2*Sub9030;

  Sub9138 = -14*(F27*F5 + F28*F7) + 4*F23*F3*Pair4 + Sub8977 + 
     2*Sub9136 - 4*Sub9137;

  Sub10019 = F5*(F47 + F6*(Sub10018 - 2*Sub9782)) + 
     F9*(-F46 + F10*(Sub9781 + Sub9782));

  Sub5061 = 1/SW2*((F12*F19 - F32*F7)*Sub3885 + 
       SW2*(8*F10*F18 - 8*F31*F5 + 2*Sub31 + 4*Sub34 - MT*Sub5060))
    ;

  Sub8989 = 1/SW2*(-(Sub13*Sub3885) + 
       SW2*(4*Sub11 - 8*Sub15 - 2*Sub9 + 
          MT*(4*Sub10 - 8*Sub2077 + Sub8988)));

  Sub1379 = 1/(SW2*SW2)*
     (SW2*SW2*(Sub1378*Sub881) + 
       Sub888*((-1 + 2*SW2)*(F12*F18) + 
          F13*((1 - 2*SW2)*F34 + MT*(-1 + 2*SW2)*F35) + 
          SW2*(2*F10*F18 - 2*F5*(F31 + MT*F6))));

  Sub176 = 1/SW2*(F10*(-(8*SW2*F18) + (3 - 8*SW2)*F19) + 
       F12*((2 - 8*SW2)*F18 + (5 - 8*SW2)*F19) + 
       (-2 + 8*SW2)*(F13*F34) + (-3 + 8*SW2)*(F23*F36) + 
       (-5 + 8*SW2)*(F32*F7) + SW2*(8*F31*F5 + MT*Sub175));

  Sub9623 = 1/SW2*(-Sub9622 + 
       F26*(-(8*(SW2*SW2)*F21) + (3 - 12*SW2)*SW2*F22) + 
       F23*(-(8*(SW2*SW2)*F36) + 2*SW2*Sub9620) + 
       SW2*(-2 + 4*SW2)*(F13*Sub9621));

  Sub7559 = 6*Pair3*Sub7555 + F26*(-Sub7558 + 8*SW2*F39) - 
     8*SW2*(F36*F42) + (3 - 4*SW2)*Sub7556 + (1 - 2*SW2)*Sub7557;

  Sub10460 = 12*F22*F30 - 12*F5*Sub10440 - 8*SW2*Sub10445 + 
     (3 - 4*SW2)*Sub10458 + (-2 + 4*SW2)*Sub10459 + 6*MT*Sub7540;

  Sub7587 = 2*F26*Sub7586 + 64*(SW2*SW2)*(F26*F39 - F36*F42) - 
     6*(3 - 8*SW2)*(Pair3*Sub7583) + Power(3 - 4*SW2,2)*Sub7584 - 
     Power(1 - 2*SW2,2)*Sub7585;

  Sub1387 = 1/MW2*Sub1379 + 2*Power(3 - 4*SW2,3)*Sub1382 + 
     128*(1 - 2*SW2)*SW2*Sub1383 - 256*(SW2*SW2)*Sub1384 + 
     32*MT*(F11*Sub1386);

  Sub255 = 1/CW2*(3*MT*SW2*Sub201 + 
       CW2*((8 - 32*SW2)*(F1*F14) + (-8 + 32*SW2)*(F22*F29) + 
          (12 - 32*SW2)*(F24*F3) + (-12 + 32*SW2)*(F21*F30) - 
          15*MT*Sub201 + (20 - 32*SW2)*Sub3));

  Sub4852 = 1/(MW2*(SW2*SW2))*
     ((-2 + 4*SW2)*(F15*F7*Pair3*Sub3994) + 
       SW2*(4*F23*F3*Pair3*Sub3994 + MT*MW2*(1 - 2*SW2)*(F1*F2)) + 
       MT*MW2*(2*(SW2*SW2)*Sub4842 + 
          (-1 + 2*SW2)*(CW2*(F1*F2) + SW2*Sub4849)));

  Sub10114 = 1/(CW2*MW2*(SW2*SW2))*
     (MB2*SW2*(-1 + 2*SW2)*(F21*F29) + 
       MW2*(Pair4*(4*(SW2*SW2)*(F23*F3) + 
            SW2*(-2 + 4*SW2)*(F15*F7))) + 
       CW2*(MB2*(1 - 2*SW2)*(F21*F29) + 
          MW2*((-2 + 4*SW2)*Sub10103 + 4*SW2*Sub10104)));

  Sub11031 = 1/(MW2*(SW2*SW2))*
     (MT*MT2*(CW2*(1 - 2*SW2) + SW2*(-1 + 2*SW2))*
        (F29*(F37 + F38)) + 
       MW2*(Pair3*(MT*(SW2*(-4 + 8*SW2)*(F1*F41) + 
               8*(SW2*SW2)*(F43*F5)) + 
            MT2*(-(8*(SW2*SW2)*(F23*F3)) + 
               (4 - 8*SW2)*SW2*(F15*F7)))));

  Sub173 = 1/(CW2*SW2)*
     (SW2*((F10 + F12)*(-3*F11 + 3*F9)) + 
       CW2*((F10 + F12)*(3*F11 - 3*F9) + 8*SW2*Sub167 + 
          (3 - 8*SW2)*Sub168 + (5 - 8*SW2)*Sub169 + 
          (-2 + 8*SW2)*Sub170));

  Sub256 = 1/(CW2*SW2)*
     (SW2*((2 - 8*SW2)*(F1*F14) + (-2 + 8*SW2)*(F22*F29) + 
          (3 - 8*SW2)*(F24*F3) + (-3 + 8*SW2)*(F21*F30) + 
          (5 - 8*SW2)*Sub3) + 
       CW2*(-Sub255 + (-2 + 8*SW2)*(F1*F14) + 
          (2 - 8*SW2)*(F22*F29) + (-3 + 8*SW2)*(F24*F3) + 
          (3 - 8*SW2)*(F21*F30) + (-5 + 8*SW2)*Sub3 + 
          8*SW2*(Sub154*Sub4)));

  Sub423 = 8*Sub421 + 64*(Sub15 + MT*Sub14) + 
     Power(-CW2 + SW2,2)/(CW2*CW2)*Sub420 + (3 - 4*SW2)*Sub422 + 
     (32*(1 - 2*SW2))/SW2*(Sub11 + MT*Sub10);

  Sub182 = -8*(F10*F18 - F31*F5)*Sub178 + 
     (2*Power(-CW2 + SW2,2))/(CW2*CW2*SW2)*Sub177 + 
     (1 - 2*SW2)*Sub179 + 8*MT*Sub180 + (-3 + 4*SW2)*Sub181;

  Sub6360 = F12*F17 + Sub6366;

  Sub4914 = F20*(F39 + F40) + F29*(-F37 - F38 + 2*F39 + 2*F40)
   ;

  Sub4916 = F26*(F39 + F40) + F30*(-F37 - F38 + 2*F39 + 2*F40)
   ;

  Sub13790 = F1*F14 + F22*(-F20 - F26 - 2*F29 - 2*F30) - F27*F5
   ;

  Sub5226 = F22*(-F26 - F30) - F27*F5 + Sub5545;

  Sub11486 = 3*F24*F3 - 2*F21*(F29 + F30) - 3*F28*F7 + Sub11869
   ;

  Sub11864 = 3*F24*F3 + F21*(-F29 - F30) - 3*F28*F7 + Sub11869
   ;

  Sub12579 = F21*(-F29 - F30) + Sub2476;

  Sub136 = Sub11543 + Sub147;

  Sub5221 = F1*F14 - F27*F5 - F28*F7 + Sub12784;

  Sub663 = (F10 + F12)*(F16 + F17) + Sub3467;

  Sub13407 = (F10 + F12)*(F16 - F17 - F18 + F19) + 
     F22*(-F29 - F30) + 3*(F24*F3 + F27*F5) - 3*(F1*F14 + F28*F7);

    

  Sub148 = Sub1272 + Sub22;

  Sub6534 = -5*(F3*F4 + F7*F8) + Sub2431;

  Sub733 = -(F7*F8) + F12*(F11 - F9) + Sub8;

  Sub13300 = -(F10*F9) + Sub12669;

  Sub2443 = (F10 + F12)*(2*F11 - F9) + Sub11866;

  Sub7339 = F3*F42 + F44*F7 + 
     2*(F1*F41 + F43*F5 + (F20 + F26)*F9);

  Sub13302 = -(F3*F42) - F43*F5 - F44*F7 + 
     F29*(2*F11 - 3*F9) - 3*F30*F9;

  Sub12668 = F1*F41 - Sub13320;

  Sub13379 = F11*F30 - F3*F42 - F44*F7 + Sub5107;

  Sub12940 = -2*F3*F42 + F43*F5 + 2*F30*F9 + Sub5425;

  Sub13298 = -Sub13337 + Sub4427;

  Sub13297 = -(F11*(F20 + F26 - 2*(F29 + F30))) + 
     (-2*(F20 + F26) + F29 + F30)*F9 + Sub4427;

  Sub11919 = (F10 + F12)*(2*F11 - F9) + Sub5179;

  Sub480 = Sub1542 + Sub278;

  Sub13447 = -3*(F10 + F12)*(F11 + F9) + Sub400;

  Sub11545 = -2*(F10 + F12)*(F11 + F9) + Sub400;

  Sub5668 = 3*(F10 + F12)*(F11 + F9) + Sub9732;

  Sub13965 = -2*(F25*F5 + F15*F7)*Pair1 + Sub147;

  Sub13982 = F12*F17 + Sub13981;

  Sub2641 = F12*(-2*F17 + 2*F18) - F20*F22 - F22*F29 + 
     F13*(-2*F34 + F1*(6*Pair1 - 2*Pair2));

  Sub1737 = F10*(-F16 + F17 + F18 - F19) - F24*F3 - F27*F5 - 
     2*F25*F5*Pair1 + F23*F3*(2*Pair1 + 2*Pair2);

  Sub2639 = F12*(2*F16 - 2*F19) + F21*(F20 + F29) + 
     F7*(2*F32 + F15*(-6*Pair1 + 2*Pair2));

  Sub3538 = 2*F25*F5*Pair2 + Sub919;

  Sub933 = (F29 + F30)*(Pair1 + Pair2) + Sub12561;

  Sub5063 = F27*F5 + F1*(-F14 + 2*F13*(Pair1 + Pair2)) - 
     Sub13107;

  Sub3864 = F23*F36 + F31*F5 + Sub2344 + Sub2346;

  Sub8151 = -(F33*F42) + Opt8;

  Sub7423 = F33*F42 + Opt8;

  Sub7424 = -(F35*F41) + Opt9;

  Sub8041 = F35*F41 + Opt9;

  Sub1630 = Sub1261 - Sub6336;

  Sub7427 = F21*(-F26 - F30) + F22*(F26 + F30) - F4*F51 + 
     F5*(F31 + F25*(-4*Pair1 - 2*Pair2)) + 
     F23*(-F36 + 2*F3*(Pair1 + Pair2));

  Sub909 = -(F12*(F16 + F17 + F18 + F19)) - F20*F21 - 
     F20*F22 + F28*F7 + 2*F15*F7*Pair1 + 
     F1*(-F14 + F13*(2*Pair1 + 2*Pair2));

  Sub918 = -(F27*F5) - F28*F7 - 2*F25*F5*Pair1 - 
     2*F15*F7*Pair1 + F1*(F14 + F13*(-2*Pair1 - 2*Pair2)) + 
     F3*(F24 + F23*(-2*Pair1 - 2*Pair2));

  Sub732 = (F10 + F12)*(F16 + F17) + 
     (F21 + F22)*(F20 + F26 + F29 + F30) + 
     F13*(F34 - 2*F1*(Pair1 + Pair2)) + 
     F7*(F32 - 2*F15*(Pair1 + Pair2)) + 
     F5*(F31 - 2*F25*(Pair1 + Pair2)) + 
     F23*(F36 - 2*F3*(Pair1 + Pair2));

  Sub9973 = F5*(F31 - 4*F25*Pair1) + 
     F7*(F32 - 4*(F28 + F15*Pair1) + 2*F15*Pair3);

  Sub5858 = Opt10 + (4*F11 - 4*F9)*Pair3;

  Sub5914 = -Sub12479 + Sub6899;

  Sub14534 = Opt10 + (F11 - F9)*Pair3;

  Sub14511 = Opt10 + (-2*F11 + 2*F9)*Pair3;

  Sub11398 = Opt10 + (-4*F11 + 4*F9)*Pair3;

  Sub11618 = Opt10 + (-6*F11 + 6*F9)*Pair3;

  Sub11399 = Opt10 + (-8*F11 + 8*F9)*Pair3;

  Sub11102 = (-4*F11 + 4*F9)*(Pair1 + Pair2) + Sub5867;

  Sub5936 = F10*(F16 - 2*(F17 + F18) + F19) + 
     F21*(-F26 + 3*F30) + 3*(F24*F3 + F27*F5) + 
     2*F23*F3*(-2*(Pair1 + Pair2) + Pair3) - 
     2*(F22*F30 + F25*F5*(3*Pair2 - Pair3 - 2*Pair4));

  Sub5809 = F10*(F17 + F18 - 2*(F16 + F19)) + 
     F21*(F26 - 3*F30) - 3*(F24*F3 + F27*F5) + 
     4*F23*F3*(Pair1 + Pair2) + 
     2*(F22*F30 + F25*F5*(3*Pair2 - Pair3 - 2*Pair4));

  Sub429 = 2*F15*F7*Pair3 - Sub5118;

  Sub12133 = (F26 + F29)*Pair1 + (F29 + F30)*Pair2 + 
     F20*(Pair2 + 2*Pair4);

  Sub13380 = F1*F41*(Pair1 + Pair2 + Pair3) + 
     F11*(F29*Pair4 + MT2*(F10 + F12));

  Sub7721 = F21*F26 + F23*F36 + 
     2*F3*(F24 + F23*(Pair1 + Pair2 + Pair4));

  Sub3807 = Sub3116 + Sub3164;

  Sub6853 = (2*F21 + F22)*F26 + 2*F23*F36 + 4*F25*F5*Pair4 + 
     Sub6602;

  Sub13033 = (F1*F41 + F3*F42 + F43*F5)*Pair4 + Sub12930;

  Sub9855 = F23*F36 + F7*(-2*F28 + F15*(16*Pair2 - 6*Pair4)) + 
     F25*F5*(16*Pair2 - 6*Pair4);

  Sub7801 = F12*(F16 + F19) + F21*(F20 - F29) + 
     F7*(-2*F28 + F15*(-4*Pair3 - Pair4));

  Sub6848 = F20*(F21 + 2*F22) + 2*F13*F34 + 4*F15*F7*Pair4 + 
     Sub6603;

  Sub11439 = F12*(F16 + F19) + F21*(F20 - F29) + 
     F7*(-2*F28 + F15*(-4*Pair1 + 4*Pair4));

  Sub11794 = Sub13102 + MT2*(F3*F4 + F7*F8);

  Sub7225 = Opt3 - 6*F9*(Pair3 + Pair4) + 
     F11*(2*Pair3 + 4*Pair4);

  Sub6533 = Opt3 - 6*F11*(Pair3 + Pair4) + 
     F9*(2*Pair3 + 4*Pair4);

  Sub11983 = Opt10 + (2*F11 - 2*F9)*Pair4;

  Sub13819 = F37 + F38 + F9*(-Pair1 - Pair2 - Pair4) + 
     F11*Pair4;

  Sub3438 = F9*(Pair3 + Pair4) + Sub13032;

  Sub6535 = (F20 + F26)*F9*Pair4 + Sub13161;

  Sub3620 = (F11*(F20 + F26 + F29 + F30) + (F29 + F30)*F9)*
     Pair4;

  Sub4586 = Opt3 + F9*
      (4*(Pair1 + Pair2) - 6*(Pair3 + Pair4)) + 
     F11*(-2*(Pair1 + Pair2) + 2*(Pair3 + Pair4));

  Sub5860 = Opt3 + F11*
      (4*(Pair1 + Pair2) - 6*(Pair3 + Pair4)) + 
     F9*(-2*(Pair1 + Pair2) + 2*(Pair3 + Pair4));

  Sub11897 = F7*(F44*Pair3 + F8*(MT2 + S)) + 
     F9*(F20*(Pair1 + Pair2) + MT2*F12);

  Sub13322 = F1*F41*Pair4 + F10*F9*S + Sub12830;

  Sub141 = ((F23*F3 + F25*F5 + F15*F7)*Pair1 + F23*F3*Pair2 + 
       F1*F13*(Pair1 + Pair2))*S;

  Sub12462 = (F43*F5 + (F29 + F30)*F9)*Pair3 + 
     F1*F41*(Pair3 + 2*Pair4) + 
     Pair4*(2*(F43*F5 + (F29 + F30)*F9) + Sub11042 + Sub11046) + 
     Sub11471;

  Sub11161 = F10*(-F16 + F17 + F18 - F19) + F22*(F26 - F30) + 
     F21*(-F26 + F30) - 4*F25*F5*Pair3 + 
     F23*F3*(4*Pair3 + 2*Pair4) - 2*Sub11160;

  Sub13074 = (F10 + F12)*(F16 - F17 - F18 + F19) + 
     (2*F21 - 2*F22)*(F20 + F26) + 
     (F23*F3 + F15*F7)*(-2*Pair3 - Pair4) + 2*Sub11468;

  Sub13362 = 1/MW2*(-(F29*Sub13358) - F30*Sub13358 + 
       MW2*(16*F15*F7*Pair3 + 16*F15*F7*Pair4 + 
          F23*F3*(12*Pair3 + 12*Pair4) + 2*Sub13354));

  Sub1461 = 2*(F21*(F29 + F30) + F28*F7) + 
     (F25*F5 - 5*F15*F7)*Pair3 + F1*(2*F14 + F13*Pair3) + 
     (-(F25*F5) + F15*F7)*(4*Pair1 - 4*Pair4) - 2*Sub1460;

  Sub12697 = Sub13104 + 
     (Pair1 + Pair2)*((F17 + F18)*(F20 + F26) + F1*F13*Sub1580) + 
     MT*((F20 + F26 + F29 + F30)*(F11 + F9)*
        (Pair1 + Pair2 + Pair3 + Pair4));

  Sub2253 = -4*F24*F3 + 5*F21*(F29 + F30) + 
     3*(F1*F14 + F5*(-F27 + 2*F25*Pair2)) - 
     2*(F22*(F29 + F30) + F15*F7*Pair3) + 2*F7*Sub2252;

  Sub5665 = 1/MW2*(-(MB2*
          (2*(F16 + F19)*Pair3 - F21*Sub2382)) + 
       MT2*(-2*(F17 + F18)*Pair3 + F22*Sub2382 + 
          (-MB2 + MT2)*(F21 - F22) + 2*MB2*(F21 + F22)) + 
       MT*((MB2 + MT2)*(F37 + F38) - 2*(2*MB2 + MT2)*(F11*Pair3)));

    

  Sub12650 = Sub12612 - F10*F11*Sub265 - F11*F12*Sub265 + 
     (F3*F4 + F7*F8)*Sub265;

  Sub2792 = Sub135 + 2*Sub2791;

  Sub14243 = Sub3467 - MT*Sub28;

  Sub3311 = 3*F10*F19 + F12*(2*F18 + 5*F19) - 2*F13*F34 - 
     3*F23*F36 - 5*F32*F7 + MT*Sub3310;

  Sub3506 = 2*F11*(F29 + F30)*Pair3 - 2*Sub3505 + 
     (F1*F2 + F3*F4 + F5*F6 + F7*F8)*Sub353;

  Sub12138 = F21*(-(F29*Sub265) - F30*Sub265) + 
     2*(Sub12136 + F15*F7*Pair4*Sub265) - 
     2*(Sub12137 + F15*F7*(Pair1 + Pair2)*Sub353);

  Sub13328 = F16*((F29 + F30)*(2*Pair3 - 2*Pair4) + 
        F20*(Pair3 + 3*Pair4)) + 
     F19*(-2*(F29 + F30)*Pair4 + F20*(Pair3 + 3*Pair4)) - 
     2*F23*F3*Pair4*Sub353 + 
     Pair3*(2*F19*(F29 + F30) + F23*F3*Sub353);

  Sub13005 = Sub13037 + Sub4194 + Sub4199;

  Sub13053 = F11*(F29 + F30)*(Pair3 - Pair4) + 
     (Pair1 + Pair2)*(Sub4338 + Sub4342) + 
     Pair4*(Sub4339 + Sub4343);

  Sub13026 = F29*(4*(Pair1 + Pair2) - 12*Pair4) - 
     4*F30*(Pair3 + Pair4) + F10*(-MB2 + MT2 + MW2 + Sub4771) + 
     (-MB2 + MT2 + MW2)*F12;

  Sub5447 = F26*(4*(Pair1 + Pair2) - 4*Pair3 - 12*Pair4) + 
     F30*(4*(Pair1 + Pair2) - 4*(Pair3 + Pair4)) + F10*Sub4771;

  Sub5452 = F20*(4*(Pair1 + Pair2) - 4*Pair3 - 12*Pair4) + 
     F29*(4*(Pair1 + Pair2) - 4*(Pair3 + Pair4)) + F12*Sub4771;

  Sub13184 = 1/MW2*(-(MT2*(F20*F22)) - MT2*(F22*F26) + 
       MW2*(F7*Sub11662) + MW2*(F3*Sub11665) + MT*MW2*Sub11866 + 
       MW2*(F21*Sub13183) - 2*MW2*Sub5007);

  Sub5817 = F20*(F37 + F38) - 
     4*(F29*(F39 + F40) + F1*F41*Pair4) - 
     2*(-(F1*F2) + F12*F9)*Sub318 + Sub353*Sub5814 + 4*Sub5815 + 
     2*Sub5816;

  Sub5822 = F26*(F37 + F38) - 
     4*(F30*(F39 + F40) + F43*F5*Pair4) - 
     2*(-(F5*F6) + F10*F9)*Sub318 + Sub353*Sub5819 + 4*Sub5820 + 
     2*Sub5821;

  Sub6163 = F12*(-4*F11 + 2*F9)*Sub353 - 
     2*(F20*(F37 + F38) + F1*F2*Sub6159) + 8*Sub6160 + 
     F29*(-F37 - F38 - 8*Sub6161) - 4*Sub6162;

  Sub6167 = F10*(-4*F11 + 2*F9)*Sub353 - 
     2*(F26*(F37 + F38) + F5*F6*Sub6159) + 
     F30*(-F37 - F38 - 8*Sub6161) + 8*Sub6165 - 4*Sub6166;

  Sub6518 = F22*F26 + F13*F34 + F23*F36 + 
     F3*(F24 - 2*F23*Pair1) + F1*(F14 - 2*F13*Pair3) - 2*Sub6517;

  Sub6823 = 2*F30*(F37 + F38) + 
     F26*(-2*(F37 + F38) - F11*Pair4) + 
     F5*(4*F43*Pair4 + F6*Sub4436) + 
     F10*(F9*Sub4434 + F11*Sub6821) - 4*Sub6822;

  Sub6825 = 2*F29*(F37 + F38) + 
     F20*(-2*(F37 + F38) - F11*Pair4) + 
     F1*(4*F41*Pair4 + F2*Sub4436) + 
     F12*(F9*Sub4434 + F11*Sub6821) - 4*Sub6824;

  Sub6852 = F10*(F16 + F17) + (F21 + F22)*(3*F26 - F30) - 
     F33*F42 - 2*F4*F51 + F23*(3*F36 - 4*F3*Pair3) - F5*Sub6851;

  Sub9140 = F22*F29 + F21*F30 + 6*F27*F5 + 
     F23*F3*(8*Pair2 - 4*Pair4) - 
     4*(F15*F7*Pair2 + F1*F13*Pair4) - 2*Sub9136;

  Sub9503 = F12*F19 + Sub9500 + MT*(F13*F35) + 
     F7*(-4*F28 - 5*F32 + 20*F15*Pair2 - 2*MT*F8);

  Sub456 = 1/SW2*((2 - 8*SW2)*Sub11 + (-5 + 8*SW2)*Sub13 + 
       MT*((2 - 8*SW2)*Sub10 + (-5 + 8*SW2)*Sub12 + 8*SW2*Sub14) + 
       SW2*(8*Sub15 + (3 - 8*SW2)*Sub455));

  Sub3853 = 1/(SW2*SW2)*
     ((3 + SW2*(-10 + 8*SW2))*Sub3817 + 8*(SW2*SW2)*Sub3847 + 
       MT2*((3 + SW2*(-14 + 16*SW2))*Sub1542 + 
          SW2*(-6 + 16*SW2)*Sub278) + 
       SW2*((-6 + 8*SW2)*Sub3816 + (-4 + 8*SW2)*Sub3850));

  Sub9608 = 1/SW2*((-3 + (10 - 8*SW2)*SW2)*Sub9591 + 
       MT*(8*(SW2*SW2)*(F5*F6) + 
          (3 + SW2*(-10 + 8*SW2))*(F7*F8)) + 
       SW2*((6*Pair1 - 6*Pair3)*Sub7757 + (3 - 4*SW2)*Sub9589 + 
          (2 - 4*SW2)*Sub9590));

  Sub9498 = 1/SW2*((-3 + (10 - 8*SW2)*SW2)*Sub9200 + 
       MT*((3 + SW2*(-10 + 8*SW2))*(F11*F12) + 
          8*(SW2*SW2)*(F10*F9)) + 
       SW2*(MT*(-4 + 8*SW2)*(F12*F9) + (6 - 8*SW2)*Sub9485 + 
          (4 - 8*SW2)*Sub9486));

  Sub1915 = 1/SW2*(F15*F7*
        ((-3 + (10 - 8*SW2)*SW2)*(Pair1 + Pair2) + 
          (3 + SW2*(-10 + 8*SW2))*Pair3 + (6 - 12*SW2)*Pair4) + 
       F25*F5*(SW2*SW2*(-8*(Pair1 + Pair2) + 8*Pair3) + 
          12*SW2*Pair4) + (-3 + 6*SW2)*(F1*F13*Pair4) + 
       SW2*(-6*F23*F3*Pair4 + (6 - 8*SW2)*Sub1894 + 
          (4 - 8*SW2)*Sub1895));

  Sub10403 = 1/SW2*((3 + SW2*(-18 + 24*SW2))*(F22*F29) + 
       (3 + SW2*(-10 + 8*SW2))*Sub10381 + 8*(SW2*SW2)*Sub10382 + 
       SW2*((4 - 8*SW2)*(F1*F14) + (6 - 8*SW2)*(F24*F3) + 
          (-12 + 24*SW2)*(F21*F30)));

  Sub2727 = -(24*SW2*(F10*(-F11 + F9)*Sub502)) + 
     Power(1 - 2*SW2,3)*(1/SW2*(-4*F13*F35*Sub152 + 4*MZ2*Sub10) + 
        1/(SW2*SW2)*(3*F12*(-F11 + F9)*Sub502 + 
           (3 - 4*SW2)*(-(F7*F8*Sub152) + MZ2*Sub12)));

  Sub8602 = 1/SW2*(SW2*
        (2*Sub8601 + MT2*(-1 + 2*SW2)*(F17*F29)) + 
       (-1 + 2*SW2)*(F29*(MT2*SW2*F18 + 
            Sub3991*(F16 + F19 + MT*F9))) + 
       MT2*(MT*(F11*(SW2*(-1 + 2*SW2)*F29 + 2*(SW2*SW2)*F30)) + 
          CW2*((1 - 2*SW2)*((F17 + F18)*F29) + 
             MT*(F11*((1 - 2*SW2)*F29 - 2*SW2*F30)))));

  Sub11579 = 1/SW2*(Sub3991*
        (MT*(-1 + 2*SW2)*(F11*F12) + (-2 + 4*SW2)*(F15*F7*Pair3))+
         2*(MT2*(SW2*SW2)*(F22*F26) + SW2*Sub11578) + 
       (-1 + 2*SW2)*(F20*(F21*Sub3991 + MT2*SW2*F22)) + 
       MT2*(Pair3*(SW2*(-2 + 4*SW2)*(F1*F13) + 
             4*(SW2*SW2)*(F25*F5)) + 
          MT*SW2*(-1 + 2*SW2)*(F12*F9) + 
          CW2*(-(2*SW2*(F22*F26)) + 
             Pair3*((2 - 4*SW2)*(F1*F13) - 4*SW2*(F25*F5)) + 
             (1 - 2*SW2)*(F20*F22 + MT*(F12*F9)))));

  Sub11736 = 1/SW2*(SW2*
        (2*Sub11735 + MT*MT2*(-1 + 2*SW2)*(F11*F12)) + 
       (-1 + 2*SW2)*(Sub3991*(Sub11720 + MT*(F12*F9))) + 
       MT2*(2*(SW2*SW2)*Sub11721 + SW2*(-1 + 2*SW2)*Sub11722 + 
          CW2*(-(2*SW2*Sub11721) + 
             (1 - 2*SW2)*(Sub11722 + MT*(F11*F12)))));

  Sub6149 = 1/(MW2*(SW2*SW2))*
     (Pair3*(MW2*(8 - 16*SW2)*SW2*(F15*F7) - 
          4*MT*(SW2*SW2)*(F30*F9)) + 
       SW2*SW2*(F11*(-(4*MT*(F30*Pair3)) - 2*MW2*Sub5926)) + 
       MW2*(SW2*(-1 + 2*SW2)*(F21*F29 + Sub6145) + 
          SW2*SW2*(F9*Sub5926 + 2*Sub6148)) + 
       CW2*(4*MT*SW2*(F30*(F11 + F9)*Pair3) + 
          MW2*((1 - 2*SW2)*(F21*F29) + (4 - 8*SW2)*(F15*F7*Pair3)))
       );

  Sub2500 = -2*(F21 + F22)*(F29 + F30) + Sub147;

  Sub145 = Sub11628 - Sub1463;

  Sub5230 = -Sub2431 + Sub2432;

  Sub2289 = -(F1*F41) - F43*F5 - F20*F9 - F26*F9 + Sub2313;

  Sub13319 = F11*(F20 + F26) - F1*F41 - 2*F3*F42 - F43*F5 - 
     2*F44*F7 + F20*F9 + F26*F9;

  Sub2703 = -(F3*F42) - F44*F7 - F29*F9 - F30*F9 + Sub12819;

  Sub13111 = F1*F41 - Sub13379;

  Sub931 = -(F1*F41) + Sub1459 + Sub5107;

  Sub11487 = F12*(F11 - F9) + Sub12942 - Sub5585;

  Sub924 = -Sub19 + Sub946;

  Sub616 = F1*F2 + F5*F6 + F10*(-F11 - F9) - F12*F9 - Sub12586
   ;

  Sub5165 = -(F11*F12) + 2*F1*F2 + 2*F3*F4 + 2*F5*F6 + 
     2*F7*F8 + F10*(-F11 - F9) - F12*F9;

  Sub9550 = F10*(F17 + F18 + 2*F19) + (-F21 + F22)*F26 + 
     F5*(-F27 - 2*F25*Pair1) - 2*F23*(F36 + F3*Pair2);

  Sub1613 = (-F21 + F22)*F26 + Sub1737;

  Sub8149 = F21*(-F26 - F30) + F22*(F26 + F30) - F4*F51 + 
     F5*(F31 - 2*F25*Pair2) + F23*(-F36 + 2*F3*(Pair1 + Pair2));

  Sub7169 = F23*F3*(-6*Pair1 - 2*Pair2) - 6*F15*F7*Pair2 + 
     Sub13935;

  Sub914 = (F10 + F12)*(F16 + F17 + F18 + F19) + Sub3538;

  Sub8229 = Opt23 + 2*F11*(F26 + F30)*Pair1 + Sub8367;

  Sub4080 = (F10 + F12)*(F16 + F17 + F18 + F19) + Sub918;

  Sub6847 = F12*F17 + F20*(2*F21 + F22) - F22*F29 + F13*F34 - 
     2*F2*F52 + F15*F7*(4*Pair1 - 4*Pair3);

  Sub13131 = -2*(F23*F3 + F15*F7)*Pair3 + Sub11869 + Sub2459;

  Sub6553 = MT2*((F10 + F12)*(F17 + F18) + F22*(F20 + F26) + 
       F25*F5*Pair3);

  Sub6846 = F10*F16 + 2*F22*F26 + F21*(F26 - F30) + F23*F36 - 
     2*F4*F51 + F25*F5*(4*Pair1 - 4*Pair3);

  Sub3785 = F15*F7*(Pair1 - Pair2 + Pair3) + F1*F13*Pair4 - 
     Sub213;

  Sub5783 = F22*(F29 + F30) + F31*F5 + F32*F7 - 
     2*(F1*F13*Pair4 + F3*(F24 + F23*Pair4));

  Sub3784 = F25*F5*(-Pair1 + Pair2 - Pair3) - F23*F3*Pair4 + 
     Sub211;

  Sub6699 = F21*(-F26 - F30) + F22*(F26 + F30) - F23*F36 - 
     F33*F42 + F31*F5 - 2*F4*F51 + F25*F5*(-4*Pair3 - 4*Pair4);

  Sub3786 = F23*F3*(-Pair1 - Pair2 - Pair3) - F25*F5*Pair4 + 
     Sub212;

  Sub5078 = 2*F25*F5*Pair4 + Sub5226;

  Sub5807 = F10*(F17 + F18) - F21*F26 - F27*F5 + 
     2*F23*F3*Pair3 + F25*F5*(-2*Pair1 + 2*Pair3 + 2*Pair4);

  Sub12383 = (F20 + F26)*F9*Pair1 + 
     F11*(F26*Pair1 + F20*(Pair1 + Pair2)) + F43*F5*(Pair3 + Pair4)
    ;

  Sub9632 = (F1*F41 + F43*F5)*(Pair3 + Pair4) + Sub5250;

  Sub7507 = F20*F21 + F15*F7*(-2*(Pair1 + Pair2) + 4*Pair4) + 
     Sub6603;

  Sub11173 = Opt3 + F9*
      (4*(Pair1 + Pair2) - 6*Pair3 - 10*Pair4) + 
     F11*(-2*(Pair1 + Pair2 + Pair3) + 2*Pair4);

  Sub11093 = F37 + F38 + F9*(-4*Pair3 - 10*Pair4) + 
     F11*(2*Pair3 + 6*Pair4) - Sub1261;

  Sub11090 = F39 + F40 + F11*(-4*Pair3 - 10*Pair4) + 
     F9*(2*Pair3 + 6*Pair4) - Sub6336;

  Sub11171 = Opt3 + F11*
      (4*(Pair1 + Pair2) - 6*Pair3 - 10*Pair4) + 
     F9*(-2*(Pair1 + Pair2 + Pair3) + 2*Pair4);

  Sub11496 = (F11*F30 + F3*F42 - F43*F5)*(Pair1 + Pair2) + 
     F9*(F26*(-Pair3 - Pair4) + 
        F30*(-Pair1 - Pair2 - Pair3 - Pair4));

  Sub10467 = F39 + F40 + (-F11 + 2*F9)*Pair3 + Sub10109;

  Sub12832 = (F29 + F30)*F9*Pair3 + 
     (F20 + F26)*(F37 + F38 + F9*(-Pair1 - Pair2 - Pair4)) + 
     Sub3477;

  Sub5717 = 4*F29*(Pair1 + Pair2) + 
     F20*(2*(Pair1 + Pair2) - 4*(Pair3 + Pair4)) + F12*S;

  Sub11903 = F11*F26*(Pair1 + Pair2) + 
     F30*F9*(Pair3 + Pair4) + F5*(F43*Pair3 + F6*(MT2 + S));

  Sub11341 = F12*(-F16 - F17 - F18 - F19) + F20*(-F21 + F22) + 
     F28*F7 - 2*(F22*F29 + F15*F7*Pair3) + F1*Sub11340;

  Sub11469 = (F10 + F12)*(F16 - F17 - F18 + F19) - 
     F15*F7*Pair3 + F23*F3*(-Pair3 - 2*Pair4) - 
     2*(F22*(F29 + F30) + F15*F7*Pair4) + 
     2*(F21*(F29 + F30) + Sub11468);

  Sub13015 = F43*F5*(Pair3 + 2*Pair4) + 
     F1*F41*(-Pair2 + Pair3 + 2*Pair4) + 
     (F29 + F30)*(F9*(Pair3 + Pair4) + 
        F11*(-Pair1 - Pair2 + Pair3 + Pair4)) + Pair2*Sub12193 + 
     Pair1*(-(F1*F41) + Sub12193);

  Sub10847 = (F20 + F29)*(F37 + F38) + 
     2*((Pair1 + Pair2)*Sub1033 + Pair4*Sub10846) + F1*F2*Sub265;

  Sub10851 = (F26 + F30)*(F37 + F38) + 
     2*((Pair1 + Pair2)*Sub1029 + Pair4*Sub10850) + F5*F6*Sub265;

  Sub10247 = (F26 + F30)*(F39 + F40 - Sub10246) + 
     F5*F6*(S - Sub265) + F3*F4*(-S + Sub265);

  Sub12291 = (F26 + F30)*(F39 + F40 - Sub10246) + 
     Sub19*(-S + Sub265);

  Sub2654 = (5*F21 - 2*F22)*(F20 + F26) + 
     3*(F5*(F27 + 2*F25*Pair1) + 
        F1*(-F14 + 2*F13*(Pair1 + Pair2))) - 
     4*(F7*(F28 + 2*F15*Pair1) + 
        F3*(-F24 + 2*F23*(Pair1 + Pair2))) + (F10 + F12)*Sub2653;

  Sub2666 = -2*(F20*F22 + F22*F26 + F28*F7) + 
     3*(-(F25*F5) + F15*F7)*Pair3 + (F23*F3 - 3*F25*F5)*Pair4 - 
     Pair1*Sub2663 - Pair2*Sub2664 + 
     2*(F12*(F16 - F17 - F18 + F19) + Sub2665);

  Sub2749 = 2*(2*F21 - F22)*(F20 + F26) + 
     4*(F5*(F27 + 2*F25*Pair1) + 
        F1*(-F14 + 2*F13*(Pair1 + Pair2))) - 
     3*(F7*(F28 + 2*F15*Pair1) + 
        F3*(-F24 + 2*F23*(Pair1 + Pair2))) + (F10 + F12)*Sub2748;

  Sub13794 = Sub135 + 3*Sub13793 + 4*Sub2791;

  Sub640 = Sub663 - MT*Sub28;

  Sub14150 = (F21 + F22)*(F20 + F26 + F29 + F30) + F23*F36 + 
     F31*F5 - 2*(F23*F3 + F25*F5)*(Pair1 + Pair2) + 
     F13*(F34 - 2*F1*(Pair1 + Pair2)) + 
     F7*(F32 - 2*F15*(Pair1 + Pair2)) - MT*Sub28;

  Sub13059 = (F11*(F26 + F30) - 2*F26*F9)*Pair3 + 
     F3*F42*(Pair3 - 2*Pair4) + 
     F30*(F11 - 2*F9)*(2*Pair3 + Pair4) + Sub4372;

  Sub2658 = 1/MW2*((F20 + F26)*
        ((-MB2 + MT2)*F21 + (3*MB2 - 3*MT2)*F22) + 
       MW2*(F7*(-2*F28 - 4*F15*(Pair1 + Pair2)) + 
          F3*(2*F24 - 4*F23*(Pair1 + Pair2)) - Sub2654 + MT*Sub480)
       );

  Sub4383 = -(F3*Sub4378) + 2*(Pair1 + Pair2)*Sub4379 + 
     F5*Sub4382 + F9*(-8*F30*Pair4 - 4*Sub4380 - F10*Sub505) + 
     F11*(6*F30*Pair4 + 2*Sub4381 + F10*Sub505);

  Sub2798 = MB2*(MT*(Sub2432*Sub265) + 
        MT2*(-Sub2792 + 2*(Sub2444 + Sub2794) - 2*Sub2795)) + 
     MT2*(MW2*(2*Sub2793 - 2*Sub2794 + 4*Sub2795) + 
        MT2*(Sub2793 - Sub2794 + 2*(Sub2795 + Sub2796))) + 
     MT*(Sub265*(-(2*MW2*Sub2432) - MT2*Sub508));

  Sub13318 = 2*(F10 + F12)*(F16 - F17 - F18 + F19) - 
     7*F21*(F20 + F26) - 4*F25*F5*Pair2 + 
     F3*(3*F24 - 4*F23*(Pair1 + Pair2)) + 4*Sub13317 - F7*Sub5423;

    

  Sub5678 = (3*F21 - 2*F22)*(F29 + F30) - 
     4*F3*(-F24 + F23*(Pair1 + Pair2)) + F1*Sub5674 + 
     2*(F12*(F16 - F17 - F18 + F19) + Sub5675) - 2*F7*Sub5676 - 
     F5*Sub5677;

  Sub11473 = 4*Sub11471 + 2*Sub11472 + 
     F3*(-4*F42*Pair4 + F4*Sub6159) + 
     F7*(-4*F44*Pair4 + F8*Sub6159) + Pair3*(Sub6743 - Sub6746);

  Sub9034 = F24*F3 + (-F27 + F31)*F5 + (-F28 + F32)*F7 + 
     2*Sub9032 - 2*Sub9033;

  Sub12290 = (F20 + F29)*(F39 + F40 - Sub10246) + 
     (S - Sub265)*Sub946;

  Sub1042 = 1/SW2*(F12*(2*SW2*F18 + (-3 + 5*SW2)*F19) + 
       SW2*(3*F10*F19 + F23*(-3*F36 + 3*MT*F33) + 
          F13*(-2*F34 + 2*MT*F35)) + (3 - 5*SW2)*(F7*(F32 + MT*F8))
       );

  Sub8089 = 1/(MW2*SW2)*
     (MB2*(2*(MB2 + MT2) - 2*MW2)*SW2*F21 + 
       MT2*(MB2*(-3 - 2*SW2) + MW2*(3 - 2*SW2))*F22 + 
       MT*(F9*(2*Pair3*Sub894 - 
             2*((Pair1 + Pair2)*Sub3937 + Pair4*Sub894)) + 
          (MB2 + MT2)*(3 - 2*SW2)*(F39 + F40) + 
          F11*(2*(Pair1 + Pair2)*Sub3937 + 
             MB2*(-6*Pair3 + 6*Pair4))));

  Sub5929 = 1/(SW2*SW2)*
     (SW2*(-1 + 2*SW2)*(F20*F21 + Sub5924) + 
       SW2*SW2*(-16*F23*F3*Pair4 - F11*Sub5926 + 
          2*(Sub5921 + F9*Sub5926) - 2*Sub5927 + 4*Sub5928) + 
       CW2*((1 - 2*SW2)*(F20*F21) - 8*SW2*(F23*F3*Pair4)));

  Sub15343 = Sub13368*Sub15341 + 
     MT*(Sub15342*(-(Sub13482*Sub37) + Sub13484*Sub39)) + 
     (Sub2902*Sub37 + Sub2901*Sub39)*pave127(dd002) + 
     (F20 + F26)*(Pair1 + Pair2)*Sub12749*pave127(dd122) + 
     Sub13732*pave127(dd123) + Sub13511*pave127(dd223) + 
     (F29 + F30)*((Pair1 + Pair2)*Sub12749*pave127(dd122) + 
        (Sub39*Sub4908 + Sub37*Sub4909)*pave127(dd233));

  Sub4325 = (F20 + F29)*(F37 + F38 - F39 - F40);

  Sub4328 = (F26 + F30)*(F37 + F38 - F39 - F40);

  Sub13110 = (F29 + F30)*(F37 + F38) + Sub12830;

  Sub2491 = F1*F14 + (F10 + F12)*(F17 + F18) - F27*F5 + Sub2476
   ;

  Sub11863 = 2*F1*F2 - 2*F12*F9 + Sub12586 + Sub4332;

  Sub12229 = -(F20*F9) - F26*F9 + Sub12668;

  Sub12024 = F1*F41 + (F20 + F26 + F29 + F30)*F9 - Sub12193;

  Sub13377 = (F20 + F26 + F29 + F30)*(F37 + F38) + 
     MT2*((F10 + F12)*F9);

  Sub2386 = F12*(-F16 - F17 + F18 + F19) + F20*(-F21 - F22) - 
     F21*F29 - F22*F29 - 2*F32*F7 + 4*F15*F7*Pair1 + 
     F13*(-2*F34 + 4*F1*Pair1);

  Sub9549 = F10*(F16 + F17 + 2*F18 + 3*F19) - 4*F23*F36 - 
     2*(F21*F26 + F5*(F27 + F25*Pair1)) + 
     F3*(F24 - 2*F23*(Pair1 + Pair2));

  Sub1705 = (F21 + F22)*F26 - 
     2*(F25*F5*Pair1 + F23*F3*(Pair1 + Pair2)) + Sub1063;

  Sub8083 = F12*(-F16 + F17 + F18 - F19) + F20*(-F21 + F22) - 
     F21*F29 + Sub4581;

  Sub2611 = Sub11543 + Sub3538;

  Sub9183 = F21*F29 + F22*F30 + (2*F1*F13 + 4*F15*F7)*Pair2 - 
     Sub405;

  Sub9630 = (F1*F41 + F3*F42)*(Pair1 + Pair2) + Sub13968;

  Sub1484 = Opt10 + (2*F11 - 2*F9)*(Pair1 + Pair2);

  Sub2226 = Opt10 - F9*Pair1 - F9*Pair2 + F11*(Pair1 + Pair2)
   ;

  Sub4087 = Sub14123 + Sub14124;

  Sub4148 = 2*(F25*F5 + F15*F7)*Pair1 + Sub5063;

  Sub2428 = Sub2594 + Sub2596;

  Sub7637 = (F21 + F22)*(F20 + F29) + F35*F41 + 
     F13*(F34 - 2*F1*(Pair1 + Pair2)) + 
     F7*(F32 - 2*F15*(Pair1 + Pair2));

  Sub2809 = (F10 + F12)*(F16 + F17 + F18 + F19) - F27*F5 - 
     F28*F7 - 2*F25*F5*Pair1 - 2*F15*F7*Pair1 + 
     F3*(F24 - 2*F23*Pair1) + 
     F1*(F14 + F13*(-2*Pair1 - 2*Pair2)) - 2*F23*F3*Pair2;

  Sub3530 = F21*(F20 + F26) + F5*(F27 + 2*F25*Pair1) + 
     F1*(-F14 + 2*F13*(Pair1 + Pair2)) - Sub11920;

  Sub2621 = F5*(F27 + 2*F25*Pair1) + 
     F1*(-F14 + 2*F13*(Pair1 + Pair2)) - Sub11492;

  Sub12389 = Sub12946 + Sub12951;

  Sub7931 = (F21 + F22)*(F26 + F30) - 
     2*(F23*F3 + F25*F5)*Pair3 + Sub1063;

  Sub5797 = F23*F36 + F13*(F34 - 2*F1*Pair3) - 
     2*(F25*F5*(Pair1 + Pair2) + F15*F7*(Pair1 + Pair2 + Pair3));

  Sub13381 = F29*F9*(Pair1 + Pair2) + F3*F42*Pair3 + 
     F1*F41*Pair4 + Sub12830;

  Sub6539 = 9*F21*(F29 + F30) + 
     F7*(-2*F28 + F15*(4*Pair2 + 2*Pair3 - 10*Pair4)) + 
     F3*(2*F24 - 10*F23*Pair4);

  Sub14692 = 2*(F1*F13 + F25*F5)*Pair3 + 
     F15*F7*(-2*Pair1 + 2*(Pair3 + Pair4)) - Sub1463;

  Sub7500 = F12*F16 + F20*(F21 + 2*F22) + 
     F13*(2*F34 - 4*F1*Pair3) + F7*(-F32 + 4*F15*Pair4) - Sub5208;

    

  Sub6763 = (4*F11 - 4*F9)*Pair4 + Sub5914;

  Sub14559 = (2*F11 - 2*F9)*Pair4 + Sub5914;

  Sub10786 = (2*F11 - 2*F9)*Pair4 + Sub14511;

  Sub11436 = (-F11 + F9)*Pair4 + Sub5914;

  Sub11261 = (-2*F11 + 2*F9)*Pair4 + Sub5914;

  Sub4639 = (-2*F11 + 2*F9)*Pair4 + Sub14511;

  Sub11450 = (-4*F11 + 4*F9)*Pair4 + Sub5914;

  Sub11260 = (-6*F11 + 6*F9)*Pair4 + Sub5914;

  Sub6279 = 8*(F37 + F38) - F39 - F40 - 16*F9*Pair1 + 
     F11*(2*Pair1 + 2*Pair2) + F9*(-16*Pair2 + 8*Pair3 + 8*Pair4);

    

  Sub6530 = Sub13161 + Sub13162;

  Sub13208 = (F29 + F30)*(F11 + F9)*Pair4 + Sub2601;

  Sub12759 = (F20 + F26 + F29 + F30)*F9*Pair4 + Sub2601;

  Sub5479 = Sub4581 + Sub4585;

  Sub5093 = F11*(F29 + F30)*(Pair1 + Pair2) + 
     (F1*F41 + F3*F42 + F43*F5 + F44*F7)*(Pair3 + 2*Pair4) + 
     Sub13188;

  Sub13132 = F1*(F14 + F13*(-2*Pair3 + 2*Pair4)) + 
     F5*(-F27 + F25*(-2*Pair3 + 2*(Pair2 + Pair4))) + Sub11920;

  Sub12982 = 4*F29*Pair1 + F26*(2*Pair1 - 4*Pair4) - 
     6*F30*Pair4 + F20*(2*Pair2 - 4*(Pair3 + Pair4)) + F10*S;

  Sub10248 = (F20 + F29)*(F39 + F40 - Sub10246) + 
     F1*F2*(S - Sub265) + F7*F8*(-S + Sub265);

  Sub2766 = -2*(F20*F22 + F22*F26 + F28*F7) + 
     (-4*F25*F5 - 3*F15*F7)*Pair4 + F1*(-2*F14 - F13*Sub1576) + 
     2*(F12*(F16 - F17 - F18 + F19) + Sub2762) - Pair1*Sub2763 - 
     Pair2*Sub2764 - 3*Sub2765;

  Sub13975 = (F18*F30 + F17*(F29 + F30))*
      (Pair1 + Pair2 + Pair4) + 
     F29*((F16 + F19)*Pair4 + F18*(Pair1 + Pair2 + Pair4)) + 
     Sub11766 + F1*F13*Pair4*Sub353;

  Sub11493 = F22*(-F29 - F30) + 
     F5*(3*F27 + F25*(2*Pair1 - 4*Pair2 + 4*Pair3)) - 2*Sub11492 + 
     F1*Sub5346;

  Sub5643 = F12*(-2*(F17 + F18) + 2*(F16 + F19)) + 
     (3*F21 - 2*F22)*(F29 + F30) + F5*(4*F27 - 6*F25*Pair2) + 
     F3*(3*F24 + F23*(-4*(Pair1 + Pair2) - 2*Pair3)) - 
     F7*Sub5641 + 2*Sub5642;

  Sub6527 = F12*(-2*(F17 + F18) + 2*(F16 + F19)) + 
     F20*(F21 - F22) + F22*(-F26 - F29 - F30) + 
     F21*(F26 + 3*(F29 + F30)) + 3*(F24*F3 + F27*F5) - 
     3*(F1*F14 + F28*F7) + 6*F15*F7*Pair2 + 2*Sub6526;

  Sub8578 = F10*(2*F16 + F17 - F18) + 
     F12*(F16 + 2*F17 - F19) + F20*(F21 + 2*F22) + 
     (2*F21 + F22)*F26 - 4*F23*F3*(Pair1 + Pair3) + 
     F7*(F28 - 2*F15*Sub7561) + 2*Sub8576 + F5*Sub8577;

  Sub10783 = 1/(CW2*MW2*SW2)*
     (CW2*(MW2*SW2*(8*Sub10779 - 4*Sub10780 - 
             2*(Sub10781 + Sub10782)) + 
          F29*((MT2*(F17 + F18) + MB2*(F16 + F19))*
              ((-1 + 2*SW2)*Pair3 + (1 - 2*SW2)*Pair4) + 
             MT*((MT2*F11 + MB2*F9)*
                ((-2 + 4*SW2)*Pair3 + (1 - 2*SW2)*Pair4)))) + 
       SW2*(F29*((MT2*(F17 + F18) + MB2*(F16 + F19))*
             ((1 - 2*SW2)*Pair3 + (-1 + 2*SW2)*Pair4) + 
            MT*((MT2*F11 + MB2*F9)*
               ((2 - 4*SW2)*Pair3 + (-1 + 2*SW2)*Pair4)))));

  Sub12976 = Sub13448 + Sub2791;

  Sub12699 = (F10 + F12)*(F16 + F17 + F18 + F19) - Sub403 + 
     Sub405;

  Sub543 = -2*(F1*F13 + F23*F3 + F25*F5 + F15*F7)*Pair1 + 
     Sub583;

  Sub14363 = F12*(F16 + F17 + 3*F18 + 3*F19) - 
     F20*(F21 + F22) - F21*F29 - F22*F29 - 2*F13*F34 - 2*F32*F7 + 
     4*F1*F13*Pair1 + 4*F15*F7*Pair1 + 2*MT*(F13*F35 - F7*F8);

  Sub9182 = -(F21*F29) - F22*F30 + F27*F5 + F28*F7 - 
     2*F23*F3*Pair2 + Sub405;

  Sub2445 = F21*(F20 + F26) - 
     2*(F15*F7*Pair1 + F23*F3*(Pair1 + Pair2)) + Sub2476;

  Sub4109 = (F17*(F20 + F26 + F29) + 
        F16*(F20 + F26 + F29 + F30))*Pair2 + MT2*(F12*(F16 + F17));

    

  Sub13359 = (F16 + F19)*F30*(Pair1 + Pair2) + Sub7053 + 
     MT2*(F15*F7*Pair1);

  Sub2989 = F10*(F16 + F17) + (F21 + F22)*(F26 + F30) + 
     F5*(F31 - 2*F25*(Pair1 + Pair2)) + 
     F23*(F36 - 2*F3*(Pair1 + Pair2));

  Sub14362 = -Sub13938 - Sub13940 + MT*(-2*F13*F35 + 2*F7*F8)
   ;

  Sub2986 = F12*(F16 + F17) + (F21 + F22)*(F20 + F29) + 
     F13*(F34 - 2*F1*(Pair1 + Pair2)) + 
     F7*(F32 - 2*F15*(Pair1 + Pair2));

  Sub14675 = -(F20*(F21 + F22)) - F21*F29 - F22*F29 - 
     3*F13*F34 - 3*F32*F7 + 4*F1*F13*Pair1 + 4*F15*F7*Pair1 + 
     2*F15*F7*Pair2 + 2*(F12*(F18 + F19) + F1*F13*Pair2);

  Sub14676 = (F21 + F22)*(F26 + F30) + 3*(F23*F36 + F31*F5) - 
     4*(F23*F3 + F25*F5)*Pair1 - 
     2*(F10*(F18 + F19) + (F23*F3 + F25*F5)*Pair2);

  Sub4074 = -(F27*F5) - F28*F7 - 2*F25*F5*Pair1 - 
     2*F15*F7*Pair1 + F3*(F24 - 2*F23*Pair1) + 
     F1*(F14 + F13*(-2*Pair1 - 2*Pair2)) - 2*F23*F3*Pair2 + 
     Sub11543;

  Sub5328 = F21*(-F20 - F26 + 2*F29 + 2*F30) + 
     (F23*F3 + F15*F7)*(2*Pair3 - 10*Pair4) + Sub5090;

  Sub13400 = 6*(F21 + F22)*F30 + F5*(-F27 + 2*F25*Pair2) + 
     F23*F3*(2*Pair3 - 8*Pair4) + Sub2459;

  Sub12689 = F22*(-F29 - F30) + F1*(F14 - 2*F13*Pair3) + 
     F5*(-F27 + F25*(-2*Pair1 + 2*Pair4)) + Sub11920;

  Sub11343 = F12*(F16 + F17 + F18 + F19) + F20*(-F21 + F22) + 
     2*F21*F29 + F1*(F14 + 2*F13*Pair3) + 
     F7*(-3*F28 + F15*(4*Pair2 - 2*(Pair1 + Pair4)));

  Sub2797 = -2*(F23*F3 + F15*F7)*Pair4 + Sub13131;

  Sub12906 = F20*(F21 - F22) + F22*(-F26 - F29 - F30) + 
     F21*(F26 + F29 + F30) + 
     (F1*F13 + F23*F3 + F25*F5 + F15*F7)*Pair4;

  Sub13269 = 1/MW2*((F20 + F26)*((MB2 + MW2)*F21 + MT2*F22) + 
       MW2*(2*(F23*F3 + F15*F7)*Pair4 - Sub11869 + 
          MT*(F11*(F10 + F12))));

  Sub4081 = (F21 + F22)*(F20 + F26) - F27*F5 - F28*F7 + 
     F1*(F14 - 2*F13*Pair3) + F3*(F24 - 2*F23*Pair3) + 
     F25*F5*(-2*Pair1 + 2*Pair4) + F7*(-2*F15*Pair1 + 2*F15*Pair4);

    

  Sub5019 = -6*F21*(F29 + F30) + 
     (F23*F3 + F15*F7)*(-4*Pair3 + 16*Pair4) + Sub2459;

  Sub2810 = -(F12*F17) + F10*(-F17 - F18) - F12*F18 + F27*F5 + 
     F25*F5*(-2*Pair2 + 2*Pair3 + 2*Pair4) + 
     F1*(-F14 + F13*(2*Pair3 + 2*Pair4));

  Sub12932 = 4*F30*Pair2 + (-4*F20 - 6*F29)*(Pair3 + Pair4) + 
     F26*(2*Pair2 - 4*(Pair3 + Pair4)) + F10*S;

  Sub12386 = -8*F29*Pair3 + F30*(4*Pair2 - 8*Pair4) - 
     6*F20*(Pair3 + Pair4) + F26*(2*Pair2 - 6*(Pair3 + Pair4)) + 
     F10*S;

  Sub12943 = F29*(4*Pair1 - 6*Pair3) + 
     F26*(2*Pair1 - 4*Pair3) - 6*F30*Pair3 + 
     F20*(2*Pair2 - 4*(Pair3 + Pair4)) + F12*S;

  Sub12974 = F25*F5*Pair4*S + Sub12389;

  Sub12558 = (F29 + F30)*F9*Pair3 + F43*F5*(Pair3 + Pair4) + 
     F11*Sub12557 + Sub13102;

  Sub13438 = F11*(F10 + F12)*(-2*MT2 + S) + 
     F3*(8*F42*Pair4 - F4*S) + F7*(8*F44*Pair4 - F8*S) - 
     4*(F20 + F26)*Sub13437 + 2*MT2*(F3*F4 + F7*F8);

  Sub14268 = (F26 + F30)*
      ((F18 + F19)*Pair1 + 2*(F16 + F17)*Pair2) + Sub14192;

  Sub12937 = (F17 + F18)*(F29 + F30)*(Pair3 + 2*Pair4) + 
     Sub11768 + F1*F13*Pair4*Sub1580 + 
     MT2*((F21 + F22)*(F20 + F26 + F29 + F30));

  Sub2439 = F20*(-F21 - F22) - F21*F29 - F22*F29 - 2*F32*F7 + 
     F1*F13*(6*Pair1 - 2*Pair2) + F7*(6*F15*Pair1 - 2*F15*Pair2) - 
     2*Sub2438;

  Sub12888 = (F17 + F18 + F19)*
      (F26*Pair3 + F20*(Pair3 + Pair4)) + 
     F16*(-3*(F29 + F30)*Pair4 + (F20 + F26)*(Pair3 + Pair4)) + 
     Pair4*((F17 + F18 + F19)*(F26 - 3*(F29 + F30)) + 
        F1*F13*Sub4669);

  Sub11921 = F22*(-F20 - F26 + F29 + F30) + 
     F5*(3*F27 + F25*(4*Pair3 + 2*Pair4)) - 2*Sub11920 + F1*Sub7147
    ;

  Sub9733 = F12*(F18 - 2*F19) + F10*(-2*F18 + F19) - F13*F34 - 
     F23*F36 + 6*F27*F5 - 4*F31*F5 + 6*F28*F7 - 4*F32*F7 + 
     MT*Sub9732;

  Sub3857 = 1/(SW2*SW2)*
     (8*(SW2*SW2)*Sub3856 + 
       MT2*(F1*((3 + SW2*(-10 + 8*SW2))*F14 + 
             MT*(3 + SW2*(-14 + 16*SW2))*F2) + 
          F21*((3 + SW2*(-10 + 8*SW2))*F29 + 
             SW2*(-6 + 8*SW2)*F30) + 
          F7*(MT*(3 + SW2*(-14 + 16*SW2))*F8 + 
             (4 - 8*SW2)*SW2*Sub316) + 
          SW2*((-4 + 8*SW2)*(F22*F29) + MT*(-6 + 16*SW2)*(F3*F4) + 
             F5*(MT*(-6 + 16*SW2)*F6 + (6 - 8*SW2)*Sub317))) + 
       MT*((3 + SW2*(-10 + 8*SW2))*Sub3827 + 
          SW2*((6 - 8*SW2)*Sub3826 + (4 - 8*SW2)*Sub3855)));

  Sub9724 = 1/SW2*(F1*F13*
        ((12 - 24*SW2)*Pair1 + (-12 + 24*SW2)*Pair4) + 
       (3 + SW2*(-10 + 8*SW2))*Sub9701 + 
       MT*((6 + SW2*(-20 + 16*SW2))*(F11*F12) + 
          F10*(SW2*(-12 + 16*SW2)*F11 + 16*(SW2*SW2)*F9)) + 
       SW2*(F23*F3*(24*Pair1 - 24*Pair4) + 
          MT*(-8 + 16*SW2)*(F12*F9) + (12 - 16*SW2)*Sub9699 + 
          (8 - 16*SW2)*Sub9700));

  Sub734 = -2*Sub723 - Sub733*Conjugate(dZfL1(3,3,3)) + 
     (-(F13*F35) + (F10 + F12)*(F11 - F9))*
      Conjugate(dZfR1(3,3,3)) + 
     F5*F6*(2*Conjugate(dZfR1(2,1,1)) + Conjugate(dZfR1(3,3,3)));

  Sub12576 = -2*F22*(F20 + F26 + F29 + F30) + Sub12579;

  Sub3637 = F10*(F16 - F17) - F22*F26 - F22*F30 + 
     F21*(F26 + F30) - F31*F5 + 
     F23*(F36 + F3*(-2*Pair1 - 2*Pair2)) + 
     F5*(2*F25*Pair1 + 2*F25*Pair2);

  Sub13215 = F21*(F20 + F26) - 
     4*(F23*F3 + F15*F7)*(Pair1 + Pair2) + Sub2476;

  Sub3414 = F20*(-F21 - F22) - F21*F29 - F22*F29 + 
     2*F1*F13*Pair2 + 2*F15*F7*Pair2 + Sub14502;

  Sub8941 = -(F27*F5) - F28*F7 + F1*(F14 - 2*F13*Pair1) + 
     F3*(F24 - 2*F23*Pair1) + F7*(-2*F15*Pair1 + 2*F15*Pair2) + 
     F5*(-2*F25*Pair1 + 2*F25*Pair2) + Sub11543;

  Sub3431 = F22*(-F26 - F30) - F31*F5 + Sub11 - Sub14316;

  Sub13345 = -(F12*F17) + F10*(-F17 - F18) - F12*F18 - 
     F20*F22 - F22*F26 + F27*F5 + F5*(4*F25*Pair1 + 4*F25*Pair2) + 
     F1*(-F14 + F13*(4*Pair1 + 4*Pair2));

  Sub3435 = F10*F16 + F21*F30 + F23*F36 + Sub13 + Sub8436;

  Sub490 = (F10 + F12)*(-F16 + F17 + F18 - F19) + 
     (-F21 + F22)*(F20 + F26) - F24*F3 - F27*F5 + F28*F7 + 
     2*F23*F3*Pair1 - 2*F25*F5*Pair1 + 2*F15*F7*Pair1 + 
     F1*(F14 + F13*(-2*Pair1 - 2*Pair2)) + 2*F23*F3*Pair2;

  Sub6133 = -(F22*F26) - 2*F24*F3 - F23*F36 + 4*F23*F3*Pair1 + 
     6*F15*F7*Pair1 + F13*(-F34 + F1*(4*Pair2 - 2*Pair3)) + 
     F15*F7*(6*Pair2 - 2*Pair3);

  Sub2574 = F1*F14 + (F10 + F12)*(-F16 + F17 + F18 - F19) + 
     (-F21 + F22)*(F20 + F26) - F24*F3 - F27*F5 + F28*F7 + 
     F25*F5*(-2*Pair1 + 2*Pair3) + F7*(2*F15*Pair1 - 2*F15*Pair3);

    

  Sub5327 = 2*F1*F14 + F15*F7*(-4*Pair1 + 4*Pair3) + 
     F5*(-2*F27 + F25*(-4*Pair1 - 2*Pair2 + 4*Pair3)) - Sub1463;

  Sub11345 = F10*(F16 + F17 + F18 + F19) + (F21 - F22)*F26 + 
     2*F22*F30 + F3*(F24 + 2*F23*Pair3) + 
     F5*(-3*F27 + F25*(4*Pair2 - 2*(Pair1 + Pair4)));

  Sub13000 = (F1*F41 + F3*F42 + F43*F5)*(Pair3 + Pair4) + 
     Sub2601;

  Sub12884 = (F1*F41 + F3*F42 + F43*F5)*(Pair1 + Pair2) + 
     Sub3478 + MT2*(F12*F9);

  Sub5096 = -2*F23*F3*Pair3 + F15*F7*(-2*Pair1 + 2*Pair4) - 
     Sub403 + Sub405;

  Sub12893 = -(F21*F29) - F28*F7 + 
     F15*F7*(2*Pair2 + 2*Pair4) + Sub405 - Sub7488;

  Sub4981 = -(F22*F29) - F22*F30 + F27*F5 + 2*F25*F5*Pair1 + 
     F1*(-F14 + F13*(2*Pair3 + 2*Pair4)) - Sub11492;

  Sub12933 = F11*(F26*Pair1 + F20*(Pair1 + Pair2)) + 
     (F26 + F29)*F9*(Pair3 + Pair4) + 
     F5*(F43*(Pair3 + Pair4) + F6*S);

  Sub12983 = F11*(F30*Pair4 + (F20 + F26)*(Pair3 + Pair4)) + 
     F7*(F44*Pair4 + F8*S) + Sub3477;

  Sub12682 = Sub10249 + Sub10252 + Sub10257 + Sub10260 + 
     F1*F13*Pair4*Sub265 + 
     MT*((F20 + F26 + F29 + F30)*(F11 + F9)*
        (Pair1 + Pair2 + Pair3 + Pair4));

  Sub12251 = (F10 + F12)*(F11 + F9)*S + F1*Sub12242 + 
     F3*Sub12243 + 2*(Pair2*Sub12244 + Sub12245) - 
     2*((F44*F7 - 3*(F20 + F30)*F9)*Pair3 + Pair4*Sub12246 + 
        Sub12248) + 6*Sub12250 + 3*(F5*F6 + F7*F8)*Sub505;

  Sub6891 = F12*(-F16 - F17 - F18 - F19) + F20*(-F21 - F22) - 
     F21*F29 - F22*F29 + F28*F7 + 
     F15*F7*(2*Pair1 + 2*Pair2 + 2*Pair3) + F1*Sub6890;

  Sub11868 = F22*(F29 + F30) + 
     F5*(3*F27 + F25*(-6*Pair2 + 2*Pair3 - 2*Pair4)) - Sub11920 + 
     F1*Sub7397;

  Sub8571 = F20*(4*F21 + 7*F22) + (7*F21 + 4*F22)*F26 + 
     6*(F13*F34 + F23*F36) + 2*(F27*F5 + F28*F7) - 
     8*(F25*F5*Sub7561 + F15*F7*Sub7561) + F10*Sub8567 - 
     F1*Sub8568 + F12*Sub8569 - F3*Sub8570 + 3*MT*Sub480;

  Sub284 = 1/(SW2*SW2)*
     (MT2*((-3 + (10 - 8*SW2)*SW2)*Sub23 + 8*(SW2*SW2)*Sub24 + 
          SW2*((4 - 8*SW2)*Sub21 + (6 - 8*SW2)*Sub244)) + 
       MT*(S*((3 + SW2*(-10 + 8*SW2))*(F1*F2) - 
             8*(SW2*SW2)*(F3*F4) + 
             F10*(8*(SW2*SW2)*F11 + (6 - 8*SW2)*SW2*F9) + 
             F12*(SW2*(-4 + 8*SW2)*F11 + 
                (-3 + (10 - 8*SW2)*SW2)*F9) + 
             SW2*((-6 + 8*SW2)*(F5*F6) + (4 - 8*SW2)*(F7*F8))) + 
          MT2*((-3 + 6*SW2)*Sub277 + 6*SW2*Sub278)));

  Sub4142 = F20*(-F21 - F22) + 
     (F21 + F22)*(-F26 - 2*(F29 + F30)) + Sub147;

  Sub14208 = (F17*(F26 + F29 + F30) + 
        F16*(F20 + F26 + F29 + F30))*Pair2 + Sub14123;

  Sub925 = -2*F15*F7*Pair1 + Sub11869 + Sub13107 + Sub2481;

  Sub706 = -2*(F25*F5 + F15*F7)*Pair2 + Sub4074;

  Sub13126 = -2*(F15*F7*Pair1 + F23*F3*Pair3) + 
     2*F15*F7*Pair4 + F25*F5*(-2*Pair1 + 2*Pair4) - Sub403 + Sub405
    ;

  Sub5782 = -4*F24*F3 - F21*F30 - F22*F30 - 3*F23*F36 - 
     F31*F5 - F32*F7 + F13*
      (-3*F34 + F1*(14*Pair1 + 6*Pair2 - 2*Pair3 - 2*Pair4));

  Sub4979 = F21*(F20 + F26 + F30) + F7*(-F28 - 2*F15*Pair3) + 
     F3*(F24 - 2*F23*(Pair3 + Pair4)) + Sub13248;

  Sub8524 = (F21 + F22)*(-F26 + 3*F30) + F33*F42 + 2*F4*F51 + 
     F5*(3*F31 - 4*F25*Pair4) + F23*(-F36 - 4*F3*Pair4) + Sub7105;

    

  Sub6850 = F12*(F16 + F17) - F21*F29 - F22*F29 + 
     3*(F20*(F21 + F22) + F13*F34) - F35*F41 - 2*F2*F52 - F32*F7 + 
     2*F15*F7*Pair1 - 4*F1*F13*Pair3 - 4*F15*F7*Pair3 + 
     4*F15*F7*Pair4;

  Sub8521 = F20*(F21 + F22) - F35*F41 - 2*F2*F52 - 
     3*(F21*F29 + F22*F29 + F32*F7) + 4*F15*F7*Pair4 + 
     F13*(F34 + 4*F1*Pair4) - Sub7103;

  Sub13050 = (F43*F5 + (F29 + F30)*F9)*Pair1 + 
     F11*(F29 + F30)*Pair3 + F43*F5*Pair4 + 
     F1*F41*(Pair1 + Pair2 + Pair3 + Pair4) + F10*F9*S;

  Sub11870 = F21*(-F20 - F26 + F29 + F30) + 
     F7*(3*F28 + F15*(4*Pair3 + 2*Pair4)) + 
     F3*(-3*F24 + F23*(4*Pair3 + 2*Pair4)) - 2*Sub11869;

  Sub12134 = F1*F41*(Pair1 + Pair2) + 
     (F11*(-F20 - F26 - F29 - F30) + 2*(F26 + F29 + F30)*F9)*
      Pair4 + Pair2*(-(F3*F42) + Sub12026) + 
     Pair1*(-(F3*F42) + Sub12132) + F9*Sub12133;

  Sub12194 = F9*(F20*Pair3 + (F29 + F30)*Pair4 + 
        F26*(Pair3 + Pair4)) + 
     (Pair1 + Pair2)*(F11*(F20 + F26 + F29 + F30) + F1*F41 - 
        Sub12193) + Sub12471;

  Sub13571 = (F10 + F12)*(F16 + F19) + 
     F21*(-F20 - F26 - 3*F29 - 3*F30) + F3*(2*F24 - 4*F23*Pair3) + 
     F7*(-2*F28 + F15*(-4*Pair1 + 4*Pair4)) + MT*Sub13498;

  Sub402 = F15*F7*(-2*Pair1 + 2*Pair3 + 2*Pair4) - Sub403 + 
     Sub405 - MT*Sub400;

  Sub8799 = F21*F29 + F22*F30 + 
     F7*(-F28 + 2*F32 + F15*(2*Pair2 - 4*Pair4)) + 
     F5*(-F27 + 2*F31 + F25*(2*Pair2 - 4*Pair4)) + MT*Sub400;

  Sub5177 = F22*(F20 + F26 - 2*(F29 + F30)) + 
     F5*(3*F27 + F25*(2*Pair3 + 12*Pair4)) - Sub11920 + F1*Sub5176;

    

  Sub5672 = (-7*F10 - 4*F12)*F16 + (-4*F10 - 7*F12)*F17 + 
     F20*(-4*F21 - 7*F22) + (-7*F21 - 4*F22)*F26 + 
     (2*F21 - F22)*F29 + (-F21 + 2*F22)*F30 - 
     7*(F13*F34 + F23*F36) - 
     4*(F25*F5 + F15*F7)*(-2*(Pair1 + Pair2) + 3*Pair4) + 
     2*(F3*Sub5670 + Sub5671) + MT*Sub5668;

  Sub12232 = (F26 + F29 + F30)*F37 + (F29 + F30)*F38 + 
     F26*(F38 - F39 - F40) + F20*(F37 + F38 - F39 - F40) - 
     Sub12830 - Sub19*Sub354 + Sub354*Sub946;

  Sub738 = 4*Sub736 - 2*Sub737 - 
     Sub197*Conjugate(dZfL1(3,3,3)) + 
     Sub196*(-Conjugate(dZfL1(3,3,3)) - 
        2*Conjugate(dZfR1(2,1,1))) + 
     (2*F1*F13*Pair2 - Sub195 - Sub198)*Conjugate(dZfR1(3,3,3)) + 
     F25*F5*(Pair1 + Pair2)*
      (4*Conjugate(dZfR1(2,1,1)) + 2*Conjugate(dZfR1(3,3,3))) + 
     2*(Sub735 + F1*F13*Pair1*Conjugate(dZfR1(3,3,3)));

  Sub11916 = 3*(F1*F14 + F24*F3) - 3*(F27*F5 + F28*F7) + 
     Sub13448 - Sub13793;

  Sub929 = Sub13793 - Sub4148;

  Sub6894 = -2*(F23*F3 + F25*F5)*(Pair1 + Pair2) + Sub7931;

  Sub3619 = F11*F30*Pair2 + F9*(F45 + F46 + F30*Pair3) + 
     Sub13301 + Sub3626;

  Sub6528 = (F10 + F12)*(-2*(F17 + F18) + 2*(F16 + F19)) + 
     F20*(F21 - F22) + F21*(F26 + F29 + F30) + 
     F22*(-F26 - 3*(F29 + F30)) + 3*(F24*F3 + F27*F5) - 
     3*(F1*F14 + F28*F7) + F25*F5*(-6*Pair2 - 2*Pair4);

  Sub5174 = F21*(-F20 - F26 + 2*F29 + 2*F30) + 
     F7*(-3*F28 + F15*(-2*Pair3 - 12*Pair4)) + 
     F3*(3*F24 + F23*(-2*Pair3 - 12*Pair4)) + Sub11869;

  Sub5233 = F21*(F20 + 6*(F29 + F30)) + 
     F7*(-F28 + F15*(2*(Pair2 + Pair3) - 8*Pair4)) + 
     F23*F3*(2*Pair3 - 8*Pair4) + Sub212;

  Sub1824 = (2*F11 - 2*F9)*(Pair1 + Pair2) + Sub4639;

  Sub12968 = (F29 + F30)*F9*Pair4 + 
     F11*(F29*Pair4 + F30*(Pair2 + Pair4)) + Sub12930 + Sub3626;

  Sub13986 = Sub3477 + Sub3627 + F11*(F30*Pair4 + MT2*F12) + 
     MT2*(F12*F9 + F10*(F11 + F9));

  Sub13249 = F21*(-F20 - F26 - 2*F30) + 
     (F23*F3 + F15*F7)*(2*(Pair1 + Pair2) + 3*(Pair3 + Pair4)) - 
     2*Sub13248;

  Sub13859 = 1/MW2*((F29 + F30)*
        (2*MT2*(F21 + F22) + MT*Sub5229) + 
       MW2*((F23*F3 + F15*F7)*
           (4*(Pair1 + Pair2) - 2*Pair3 - 4*Pair4) - Sub428 + 
          MT*Sub201));

  Sub12647 = F1*F14 - F28*F7 + Opt32 + Sub1063 - Sub13793;

  Sub13115 = Sub14122 + Sub5780 + 
     MT2*(F10*(F16 + F17 + F18 + F19) + F23*F3*Pair3);

  Sub401 = (F25*F5 + F15*F7)*(-2*Pair1 + 2*(Pair3 + Pair4)) + 
     Sub145;

  Sub5168 = (F25*F5 + F15*F7)*(-4*Pair1 + 4*Pair3 + 6*Pair4) + 
     Sub145;

  Sub12164 = (F26 + F29 + F30)*F37 + 
     (F29 + F30)*(F38 + F9*(2*Pair3 - 2*Pair4) + 
        F11*(-2*Pair3 + 2*Pair4)) + 
     F26*(F38 - F39 - F40 + 2*F9*Pair3 - 2*F9*Pair4 + 
        F11*(-2*Pair3 + 2*Pair4)) + 
     F20*(F37 + F38 - F39 - F40 + 2*F9*Pair3 - 2*F9*Pair4 + 
        F11*(-2*Pair3 + 2*Pair4)) - Sub12830 + 
     (F1*F2 - F3*F4 + F5*F6 - F7*F8)*Sub265;

  Sub12862 = (F17 + F18)*F26*(Pair1 + Pair2) + 
     F30*((F17 + F18)*(Pair3 - 2*Pair4) + 
        (F16 + F19)*(3*Pair3 - Pair4)) + 
     (F16 + F17 + F18 + F19)*F29*(Pair3 - 2*Pair4) + Sub11789 + 
     Sub13104 + F1*F13*Pair4*Sub265 + 
     F20*((F17 + F18)*(Pair1 + Pair2) + MT2*(F21 + F22)) + 
     MT2*((F21 + F22)*(F26 + F29 + F30));

  Sub5980 = -(F21*F30) - F22*F30 - 3*F23*F36 - F31*F5 - 
     F32*F7 + F3*(-4*F24 + F23*(2*Pair2 - 2*Pair3)) + 
     F7*(10*F15*Pair2 + 2*F15*Pair3) + 
     F13*(-3*F34 + F1*(10*Pair1 + 2*Pair2 - 2*Pair4));

  Sub4147 = (F10 + F12)*(F16 + F17 + F18 + F19) - F27*F5 - 
     F28*F7 + F1*(F14 - 2*F13*Pair3) + F3*(F24 - 2*F23*Pair3) + 
     F25*F5*(-2*Pair1 + 2*Pair4) + 
     F7*(-2*F15*Pair1 + 2*F15*Pair4) - Sub13793;

  Sub11787 = F11*F30*Pair4 + Sub13969 + Sub3477 + Sub3627 + 
     MT2*(F5*F6 + F7*F8);

  Sub13607 = 1/MW2*(-(MB2*MT*(F11*F12)) - 2*MW2*(F20*F21) - 
       7*MW2*(F24*F3) + F21*
        (-(2*MW2*F26) + 3*MW2*F29 + 3*MW2*F30) + 7*MW2*(F28*F7) + 
       F10*(-(MB2*MT*F11) - MB2*MT*F9) - MB2*MT*(F12*F9) + 
       MW2*(F15*F7*(4*Pair1 - 10*Pair2 + 6*Pair3)) + 
       MW2*(F23*F3*(4*Pair1 + 4*Pair2 + 6*Pair3)) - 
       4*MW2*Sub11869 + MT2*Sub13606 + 
       MB2*(-Sub13605 - MT*Sub201) + 
       MT*(-(MW2*Sub13604) + MT2*Sub201));

  Sub13697 = Sub12531 + Sub13104 + 
     (Pair1 + Pair2)*((F17 + F18)*(F20 + F26) + 
        (F1*F13 + F23*F3 + F25*F5 + F15*F7)*Sub1580) + 
     F1*F13*Pair4*Sub354;

  Sub8901 = F1*F14 + F24*F3 + F21*(2*F29 - F30) + 
     F22*(-F29 + 2*F30) + F7*
      (-4*F28 + 6*F32 + F15*(8*Pair2 - 12*Pair4)) + 
     F5*(-4*F27 + 6*F31 + F25*(8*Pair2 - 12*Pair4)) + 3*MT*Sub400;

    

  Sub8931 = -(F24*F3) + F22*(3*F29 + 5*F30) - F27*F5 - 
     F28*F7 + F7*(2*F32 + 2*F15*Pair1 + 
        F15*(-2*Pair2 - 6*Pair4)) + 
     F1*(-F14 + F13*(2*Pair1 - 2*Pair4)) + 
     F5*(2*F31 - 6*F25*Pair4) - Sub8927;

  Sub9745 = F12*F18 - F13*F34 - 3*F31*F5 - 3*F32*F7 - 
     4*F1*F13*Pair1 + F25*F5*(-24*Pair2 + 12*Pair3) + 
     F15*F7*(-24*Pair2 + 12*Pair3) + 
     F23*(-F36 + F3*(-4*Pair1 + 4*Pair4)) + Sub9741 - MT*(F5*F6) - 
     MT*(F7*F8);

  Sub5478 = (F10 + F12)*(F16 - F17 - F18 + F19) + 
     F21*(F29 + F30) + 3*(F24*F3 + F27*F5) + 
     (-2*F23*F3 + 2*F25*F5)*(Pair1 + Pair2) + 
     F1*(-3*F14 + 2*F13*(Pair1 + Pair2)) + 
     F7*(-3*F28 - 2*F15*(Pair1 + Pair2));

  Sub8756 = 2*F10*(F18 + F19) + F12*(-2*F17 + 2*(F18 + F19)) - 
     2*(F24*F3 + F23*F36 + F27*F5 + F28*F7) + 
     F13*(-2*F34 + 8*F1*Pair1) + 4*(F25*F5 + F15*F7)*Pair2 - 
     4*F23*F3*Pair4 + Sub8626;

  Sub14199 = 2*F12*F19 - 4*(F25*F5 + F15*F7)*Pair2 + 
     Sub13793 + Sub14281 + Sub2791;

  Sub3806 = (F10 + F12)*(F16 - F17) + F20*(F21 - F22) + 
     F22*(-F26 - F29 - F30) + F21*(F26 + F29 + F30) + 
     F13*(-F34 + 2*F1*(Pair1 + Pair2)) + 
     F7*(F32 - 2*F15*(Pair1 + Pair2)) + 
     F5*(-F31 + 2*F25*(Pair1 + Pair2)) + 
     F23*(F36 - 2*F3*(Pair1 + Pair2));

  Sub7338 = F12*(-F16 + F17 + F18 - F19) + F20*(-F21 + F22) + 
     F22*(F26 + 3*(F29 + F30)) - 2*F15*F7*Pair4 + Sub2034 - Sub6657
    ;

  Sub2486 = -Opt32 - 2*F25*F5*Pair2 + F7*(F28 - 2*F15*Pair2) + 
     2*F23*F3*Pair3 + 2*F25*F5*Pair3 + 2*F15*F7*Pair3 + 
     2*F23*F3*Pair4 + 2*F25*F5*Pair4 + 2*F15*F7*Pair4 + 
     F1*(-F14 + F13*(2*Pair3 + 2*Pair4)) - Sub1063;

  Sub12973 = (F18*F29 + F17*(F29 + F30))*(Pair1 + Pair2) + 
     F30*((F16 + F18 + F19)*(Pair1 + Pair2) + F22*S) + Sub7053;

  Sub3243 = (F10 + F12)*(F16 + F17) - 
     2*(F1*F13 + F23*F3 + F25*F5 + F15*F7)*(Pair1 + Pair2) + 
     Sub13793 + Sub13935 + Sub2791;

  Sub13071 = (F10 + F12)*(F16 + F17 + F18 + F19) - 
     3*(F27*F5 + F28*F7) + 
     (F25*F5 + F15*F7)*(6*Pair2 - 2*Pair3 + 2*Pair4) + 
     F3*(3*F24 + F23*(-2*Pair3 + 2*Pair4)) + F1*Sub13070 - 
     Sub13793 - MT*Sub480;

  Sub7337 = F12*(-F16 + F17 + F18 - F19) + F20*(-F21 + F22) + 
     F21*(-F29 - F30) + F22*(F26 + 2*F30) + 2*F25*F5*Pair2 + 
     Sub4581 - Sub6657;

  Sub12977 = -3*(F27*F5 + F28*F7) + 
     F3*(3*F24 + F23*(-2*(Pair1 + Pair2) - 4*Pair3)) + 
     (F25*F5 + F15*F7)*(-2*Pair1 + 4*Pair2 - 4*Pair3) + 
     2*Sub12976 + Sub13793 - F1*Sub5346 + MT*Sub400;

  Sub3242 = -(F10*F16) - F12*F16 + F20*(-F21 - F22) - 
     F22*F26 + F1*F13*(2*Pair1 + 2*Pair2) - Sub13793 - Sub13935 - 
     Sub14316 - Sub14321 - Sub8436;

  Sub5364 = F12*(-2*F16 - F17 - F18 - 2*F19) - 
     F10*(2*F16 + F17 + F18 + 2*F19) - 2*F20*F21 - F20*F22 - 
     2*F21*F26 - F22*F26 - 2*F21*F29 - F22*F29 - 2*F21*F30 - 
     F22*F30 + F27*F5 + 2*F28*F7 + Opt45 + 4*F25*F5*Pair3 + 
     4*F15*F7*Pair3 - F1*(F14 - 4*F13*Pair3) + 2*F15*F7*Pair4;

  Sub5613 = F10*(2*F16 + F17) + F12*(F16 + 2*F17) + 
     F20*(F21 + 2*F22) + (2*F21 + F22)*F26 - F21*F29 - F22*F30 + 
     2*F13*F34 + 2*F23*F36 - F31*F5 - F32*F7 - Opt45 - 
     4*F23*F3*Pair1 - 2*F25*F5*Pair1 - 2*F15*F7*Pair1 + 
     2*F1*(F14 + F13*(-2*Pair1 - 2*Pair3)) + 4*F25*F5*Pair4 + 
     4*F15*F7*Pair4;

  Sub5079 = -Opt32 + 2*F23*F3*Pair3 + 2*F25*F5*Pair3 + 
     F7*(F28 + 2*F15*Pair3) + 2*F23*F3*Pair4 + 
     F1*(-F14 + F13*(2*Pair3 + 2*Pair4)) - Sub1063 - Sub13793 - 
     Sub2791;

  Sub13949 = 3*(F13*F34 + F31*F5 + F32*F7) - 4*F1*F13*Pair1 + 
     F23*(3*F36 + F3*(-4*Pair1 - 2*Pair2)) + 
     (F25*F5 + F15*F7)*(-4*Pair1 - 2*Pair2) + Sub13793 - 
     2*Sub13948 + Sub2791 - 3*MT*Sub28;

  Sub13449 = -3*(F27*F5 + F28*F7) + 
     F3*(3*F24 + F23*(-6*Pair3 - 4*Pair4)) + 
     (F25*F5 + F15*F7)*(6*Pair2 - 6*Pair3 - 4*Pair4) - 
     F1*Sub11558 + 2*Sub13448 - Sub13793 + Sub2791 - MT*Sub13447;

  Sub6134 = (F21 + F22)*(-3*(F20 + F26) - 2*(F29 + F30)) - 
     3*(F13*F34 + F23*F36) - 2*(F31*F5 + F32*F7) + 
     F3*(-4*F24 + F23*(4*Pair2 - 2*Pair3)) + 
     F1*(-4*F14 + F13*(10*Pair1 + 4*Pair2 - 6*Pair4)) + 
     F15*F7*(14*Pair2 - 6*Pair4) - Sub5916;

  Sub6466 = -3*F12*F16 - 
     2*((F21 + F22)*(F20 + F26) + F24*F3 + F23*F36) + 
     6*F23*F3*Pair1 + F7*(F32 + 10*F15*(Pair1 + Pair2)) + 
     F5*(F31 + 10*F25*(Pair1 + Pair2)) + 
     F13*(-2*F34 + F1*(6*Pair1 - 4*Pair4)) + Sub13793 + Sub5916;

  Sub13436 = F12*(F17 + F18) + F10*(F16 + F17 + F18 + F19) - 
     2*(F21*F30 + F22*(F29 + F30)) + 
     F15*F7*(4*Pair2 - 2*(Pair1 + Pair3)) + 
     F3*(3*F24 - 2*F23*(Pair1 + Pair2 + Pair3)) + 
     F5*(-3*F27 + F25*(4*Pair2 - 2*(Pair1 + Pair3))) - 
     F1*Sub11386 + Sub5036 + MT*Sub13435;

  Sub5222 = Opt32 - 4*F23*F3*Pair3 + F1*(F14 - 4*F13*Pair3) + 
     F25*F5*(-4*Pair3 - 2*(Pair2 + Pair4)) + 
     F7*(-F28 + F15*(-4*Pair3 - 2*(Pair2 + Pair4))) + Sub1063 + 
     Sub13793 + Sub2791;

  Sub3494 = -Opt32 + F25*F5*Pair1 + 
     F25*F5*(-Pair2 + Pair3 + Pair4) + 
     F23*F3*(Pair1 + Pair2 + Pair3 + Pair4) + 
     F7*(F28 + F15*Pair1 + F15*(-Pair2 + Pair3 + Pair4)) - 
     Sub1063 - Sub2791 + F1*Sub3493;

  Sub12927 = (-2*F3*F42 - 2*F43*F5 - 2*F44*F7)*Pair3 + 
     F1*F41*(-2*Pair3 - 2*Pair4) + 
     F11*(-2*F29*Pair4 - 2*F30*Pair4) - 
     2*(F3*F42*Pair4 + F43*F5*Pair4 + F44*F7*Pair4 + 
        F29*F9*Pair4 + F30*F9*Pair4) + Sub13001 - Sub13110 - 
     F20*Sub9629 - F26*Sub9629;

  Sub13826 = (F20 + F26)*(-F37 - F38 - F39 - F40) + Opt52 + 
     (-2*(F1*F41 + F3*F42 + F43*F5 + F44*F7) + 2*F29*F9)*Pair3 - 
     2*(F1*F41 + F3*F42 + F43*F5 + F44*F7)*Pair4 + 
     2*(F29*F9*Pair4 + F11*F30*(Pair3 + Pair4)) + Sub13001 - 
     Sub13110;

  Sub13452 = -(F11*F12*S) - F12*F9*S + F10*(-(F11*S) - F9*S) + 
     Sub12927;

  Sub13333 = -(F11*F12*S) - F12*F9*S + F10*(-(F11*S) - F9*S) + 
     Sub13826;

  Sub10406 = (-4*F3*F42 - 4*F43*F5 - 4*F44*F7)*Pair1 + 
     (F3*F42 + F43*F5 + F44*F7)*(-4*Pair2 + 2*Pair3 + 2*Pair4) + 
     F1*F41*(-4*Pair1 - 4*Pair2 + 2*Pair3 + 2*Pair4) + 
     F11*(-2*F29*Pair4 - 2*F30*Pair4) - 
     2*(F29*F9*Pair4 + F30*F9*Pair4) + Sub13001 - Sub13110 - 
     F20*Sub9629 - F26*Sub9629;

  Sub12811 = (-2*F1*F41 - 2*F3*F42 - 2*F43*F5 - 2*F44*F7)*
      Pair3 - 2*(F1*F41*Pair4 + F3*F42*Pair4 + F43*F5*Pair4 + 
        F44*F7*Pair4) + (F29 + F30)*
      (6*F9*Pair1 + F9*(6*Pair2 + 2*Pair3 + 4*Pair4)) + 
     F11*(6*F30*Pair1 + F30*(6*Pair2 + 2*Pair3 + 4*Pair4) + 
        F29*(6*Pair1 + 6*Pair2 + 2*Pair3 + 4*Pair4)) - 
     F20*Sub12810 - F26*Sub12810 + Sub13001 - Sub13110;

  Sub8101 = -Sub5239;

  Sub4742 = -Sub4744;

  Sub1111 = -Sub1251;

  Sub1100 = -Sub1249;

  Sub12204 = -Sub12038;

  Sub11014 = -Sub4957;

  Sub10686 = -Sub11987;

  Sub11678 = -Sub13920;

  Sub14618 = -Sub14647;

  Sub4723 = -Sub3233;

  Sub1685 = -Sub1012;

  Sub1987 = -Sub11421;

  Sub361 = -Sub388;

  Sub334 = -Sub394;

  Sub1413 = -Sub2874;

  Sub8565 = -Sub8564;

  Sub12266 = -Sub2712;

  Sub2076 = -Sub4289;

  Sub4823 = -Sub6276;

  Sub4815 = -Sub6273;

  Sub1545 = -Sub278;

  Sub752 = -Sub3724;

  Sub1058 = -Sub225;

  Sub320 = -Sub4;

  Sub413 = -Sub1273;

  Sub1954 = -Sub1135;

  Sub14682 = -Sub1310;

  Sub12288 = -Sub12517;

  Sub12282 = -Sub12515;

  Sub12510 = -Sub12286;

  Abb5 = (Pair1 + Pair2)*(3*S - 5*S34);

  Abb37 = (Pair1 + Pair2)*(2*MT2 - S34);

  Abb146 = (Pair2 - Pair3)*(2*MT2 - S34);

  Abb48 = (Pair3 + Pair4)*(2*MT2 - S34);

  Abb36 = (Pair1 + Pair2)*(4*MT2 - S34);

  Abb4 = (Pair1 + Pair2)*(S - S34);

  Abb136 = Pair2*(-2*MT2 + S34);

  Abb39 = Pair4*(-2*MT2 + S34);

  Abb154 = Pair1*(-MT2 + S34);

  Abb29 = Pair2*(-S + S34);

  Abb72 = Pair3*(-S + S34);

  Abb14 = Pair4*(-S + S34);

  Abb119 = (Pair1 + Pair2)*(MT2 - T);

  Abb161 = (Pair3 + Pair4)*(MT2 - T);

  Abb130 = (Pair1 - Pair4)*(MT2 - S - T);

  Abb131 = Pair1*(-MT2 + S + T);

  Abb132 = Pair2*(-MT2 + S + T);

  Abb166 = (Pair1 + Pair2)*(MT2 - T14);

  Abb122 = (Pair3 + Pair4)*(MT2 - T14);

  Abb26 = (Pair1 + Pair2)*(2*MT2 - T - T14);

  Abb104 = (Pair1 + 2*Pair2)*(2*MT2 - T - T14);

  Abb106 = (Pair3 + Pair4)*(2*MT2 - T - T14);

  Abb24 = (Pair1 + Pair2)*(2*MT2 - S - T - T14);

  Abb107 = (Pair1 + Pair2)*(2*MT2 - 2*S34 - T - T14);

  Abb124 = Pair1*(-MT2 + T14);

  Abb125 = Pair2*(-MT2 + T14);

  Abb127 = Pair2*(-MT2 + S + T14);

  Abb96 = Pair1*(-2*MT2 + T + T14);

  Abb102 = Pair2*(-2*MT2 + T + T14);

  Abb113 = Pair2*(-2*MT2 - S + T + T14);

  Abb2 = Pair1*(-2*MT2 + S + T + T14);

  Abb23 = Pair2*(-2*MT2 + S + T + T14);

  Abb35 = Pair2*(-2*MT2 + 2*S34 + T + T14);

}
